### ISSUE TITLE
maven repo url

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1000]
Our poms still point to http://sdi.georchestra.org/maven/repository (eg https://github.com/georchestra/georchestra/blob/14.12/pom.xml#L374) but we have also setup http://build.georchestra.org/maven/repository/

**Comment by pmauduit** [comment]
https://github.com/pmauduit/georchestra/commit/34b399dc2ae8aa7e68cb11de5503ba55f8685c4f
