### ISSUE TITLE
GeoTools - bump to a newer version / Avoid the need to fork GT

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#1005]
For some reasons, we had to fork GeoTools to add / modify some features, I wonder if we could not move on a version closer to the official one.
- Specific XML parser: to avoid raising exceptions when schemas in the parsed XML documents point onto CAS-protected geoservers (Rennes-Metropole)
- MIF support (note: available via gt-ogr, maybe the plain java impl. is now useless)
- KML support (same remark)
- System.loadLibrary() in gt-ogr (? I cannot find the commits back in the logs)

Moving to an other version would require deep testing on the following modules (which are actually using the custom version):
- epsg-extensions (?)
- extractorapp
- mapfishapp

**Comment by pmauduit** [comment]
It seems that GeoTools was forked to address some specific issues:

- XML schemas checks should be avoided on closed platforms (Rennes-Metropole), because leading to 401 errors in GT code
- Custom "main" library (subdir geotools/library/main) ? (I could not find the diff with the vanilla version yet)
- Custom geotiff plugin
- "unsupported" module kml, mif and ogr (the main pom.xml in georchestra indicates that the module is no longer used though)

But analyzing the root pom, the geotools submodule does not seem to be used anymore: it is never declared as a module in any profile or in the main section, I'm am pretty sure that if we remove the submodule and launch a build, this won't break the build. (i cannot attest it would work at runtime)

**Comment by pmauduit** [comment]
> epsg-extensions (?)

The only EPSG code that is added with this epsg-extension module seems to be EPSG:27572 (in a provided epsg.properties. But it allows to define a custom EPSG file to be loaded using the CUSTOM_EPSG_FILE env variable, no idea if we still use it somewhere in production, to be checked.

**Comment by fvanderbiest** [comment]
To my knowledge, some SDIs use it to override geotools' buggy EPSG:27572, see eg http://osgeo-org.1560.x6.nabble.com/is-epsg-27572-wrong-in-geoserver-td3800161.html

**Comment by fvanderbiest** [comment]
@pmauduit : status for 16.12 ?

**Comment by pmauduit** [comment]
Not ready :(

**Comment by fvanderbiest** [comment]
#2676
