### ISSUE TITLE
addons init improvement

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1006]
In https://github.com/georchestra/georchestra/blob/15.06/mapfishapp/src/main/webapp/app/js/GEOR_tools.js#L303 it would be better to pass the GeoExt.MapPanel instance rather than the OpenLayers.Map instance.

**Comment by fvanderbiest** [comment]
There aren't many things to change since addons inherit from a base class.
https://github.com/georchestra/georchestra/pull/1092

Migration should be easy...

**Comment by landryb** [comment]
Yes please, this will be quite useful for addons that want to interact deeply with other ext components..

**Comment by fvanderbiest** [comment]
Done, I'm sure it will be useful to many existing and future addons !
