### ISSUE TITLE
mapfishapp - add the ability to style "local" vector layers

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#1008]
Mapfishapp gives the possibility to send user-provided geofiles (the "upload" feature) as zipped shapefile, gml, osm, kml, gpx .... Some other addons allows to fetch data as a "local" vector layer.

The idea would be to allow the use of the styling interface onto these layers, which would not need to save the SLD in database, just apply the generated style directly onto the vector objects, client-side.

**Comment by fvanderbiest** [comment]
Yep, that would be nice.

**Comment by pmauduit** [comment]
I'd have liked to have a PR to propose, but, well ... javascript / ExtJS ... ;-)
