### ISSUE TITLE
header - missing items

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1010]
Several items are currently missing from the header, eg : ldapadmin, analytics, extractorapp admin, etc

We also need to find a way to stack more items in the available space.

**Comment by fvanderbiest** [comment]
@tonio is currently having a look at this.

**Comment by landryb** [comment]
Ldapadmin was added in #1089 :)

**Comment by fvanderbiest** [comment]
Improved with https://github.com/georchestra/georchestra/commit/42ad3fbe45c9173275c174ec5e614faf8ada8f05

**Comment by landryb** [comment]
There's something wrong on sdi.georchestra.org - if you login, your 'account details' link is http://sdi.georchestra.org/ldapadminaccount/userdetails - there's a missing / and i dunno if it should be in the header index.jsp or in the ldapadminPublicContextPath.

I also got something wrong with the removal of the double // in front of ldapadmin (after merging those last commits/changes), if on my instance i'm in ldapadmin the 'account details' link is `http://fqdn/header/$%7BldapadminPublicContextPath%7D/account/userdetails`

Two issues - theres shouldnt be /header/ in the url (i think that was the reason for //ldapadmin ?) and there should be the value of ldapadminPublicContextPath but for some reason... nope. Consistency between variable name in module configs ? problem when using an index.jsp coming from a template ?

**Comment by fvanderbiest** [comment]
> There's something wrong on sdi.georchestra.org - if you login, your 'account details' link is http://sdi.georchestra.org/ldapadminaccount/userdetails - there's a missing / and i dunno if it should be in the header index.jsp or in the ldapadminPublicContextPath.

Yep, known issue, see https://github.com/georchestra/georchestra/issues/1096

> I also got something wrong with the removal of the double // in front of ldapadmin (after merging those last commits/changes), if on my instance i'm in ldapadmin the 'account details' link is http://fqdn/header/$%7BldapadminPublicContextPath%7D/account/userdetails

OK, please create another issue.

**Comment by fvanderbiest** [comment]
I think we can safely close this one.
