### ISSUE TITLE
mapfishapp - measurement tools improvements

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1011]
The current measurement tools should be replaced / improved in order to be able to :
 * handle N measurements at the same time
 * measure each segment
 * print the measures

Values should be displayed in m² / ha / km² or m / km.

**Comment by fvanderbiest** [comment]
Instead of replacing them, I propose the following:
 * make an addon with the current "simple" measure tools
 * make a new addon with the new "pro" measure tools

**Comment by fvanderbiest** [comment]
For the "pro" tools, since the measurements persist, we need a tool to delete a measurement.
Hence the idea of a dedicated toolbar with the following buttons: distance measurement, area measurement, delete measurement.

On toolbar closed, the addon is deactivated, and mesurements are removed.

**Comment by fphg** [comment]
Le 05/10/2015 14:34, François Van Der Biest a écrit :
> For the "pro" tools, since the measurements persist, we need a tool to
> delete a measurement.
> Hence the idea of a dedicated toolbar with the following buttons:
> distance measurement, area measurement, delete measurement.
> 
> On toolbar closed, the addon is deactivated, and mesurements are 
> removed.

Good idea. IMO the measurement result shall show up in that toolbar 
(345m, 5.34 km2).


-- 
Fabrice Phung

**Comment by fvanderbiest** [comment]
Done and available in 15.12 with https://github.com/georchestra/georchestra/blob/15.12/mapfishapp/src/main/webapp/app/addons/measurements/README.md
