### ISSUE TITLE
mapfishapp - querier - floating window

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1012]
Some users report that having the querier replace the layer manager is awkward.
Would you be in favor of displaying it in a floating window ?

**Comment by fphg** [comment]
thanks for asking.
querier needs more room, that's a fact.
main annoyance with floating windows is the dragbar being blocked out of the screen, impossible to drag back. If you can fix this, that should be ok.

**Comment by fvanderbiest** [comment]
> main annoyance with floating windows is the dragbar being blocked out of the screen

On an `Ext.Window`:
```
constrainHeader: true
```

**Comment by fvanderbiest** [comment]
Work is in progress in branch https://github.com/georchestra/georchestra/tree/FilterPanel_toolbar

**Comment by fvanderbiest** [comment]
Done & merged into 15.12 (sorry about that, new features should not land in stable releases)

**Comment by fvanderbiest** [comment]
Ping @MaelREBOUX & @catmorales: ready for a review on https://sdi.georchestra.org/mapfishapp/

**Comment by MaelREBOUX** [comment]
ok for me
