### ISSUE TITLE
mapfishapp - simplified metadata view

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1016]
When the user opens a layer's metadata sheet, he should stay within mapfishapp.

An Ext.Window should display a configurable list of metadata fields, eg:
 * title
 * abstract
 * lineage
 * dates (create / update)
 * point of contact
 * administrator

The user should also be able to open the full metadata (switching to GN)

**Comment by fvanderbiest** [comment]
I see an issue here...

Given the fact that WMC stores only one metadata url per layer, we have had to implement a "best metadata filter" (see  https://github.com/georchestra/georchestra/blob/15.06/mapfishapp/src/main/webapp/app/js/GEOR_util.js#L271-L296), which gets called before the context is serialized.

This means that, when both text/html and text/xml metadata links are provided by the OGC capabilities, the text/xml metadata link is lost on context creation.

Yet, for this feature, we need the text/xml metadata url !

**Comment by fvanderbiest** [comment]
An elegant solution would be to implement in GN a service which returns either the HTML or the XML version of the metadata depending on the ```accept``` header content. Not sure this fits into the bill though ...

**Comment by fvanderbiest** [comment]
Would be nice if @MaelREBOUX could tell us here what he expects for "administrator". 
Many thanks :-)

**Comment by fvanderbiest** [comment]
> This means that, when both text/html and text/xml metadata links are provided by the OGC capabilities, the text/xml metadata link is lost on context creation.

Or we could preferably store the text/xml version of the metadata url in the WMC instead of the text/html one, if we had a way to recover the link to the text/html version of the metadata given the text/xml one...

**Comment by landryb** [comment]
Don't remember how this is in GN2, but in GN3 you can call srv/fre/md.format.xml?xsl=xml_view&uuid={uuid} to have the xml view, and replace xml_view by full_view to have   a 'user-friendly' html view.

**Comment by MaelREBOUX** [comment]
> WMC stores only one metadata url per layer

I understand that this evolution (simple MD view in mapfishapp) impacts the case in wich a user restore a context he stored before. Because this context file stores only a text/html url yet we rather need an text/xml url.
Right ?

For me storing XML élements or XML url in the context sounds better.
Storing entire XML descriptives elements may be a bad idea : they could have evolved in the original MD catalog. No ?

@landryb 
http:///geonetwork3/srv/fre/md.format.xml?xsl=xml_view&uuid=9b470450-f62f-48ad-ad61-865a05ed006c  provides an HTML page showing XML code with HTML formatting. It is not reusable for me comparing to the true XML output : http://geonetwork3/srv/fre/xml.metadata.get?uuid=9b470450-f62f-48ad-ad61-865a05ed006c

**Comment by fvanderbiest** [comment]
> I understand that this evolution (simple MD view in mapfishapp) impacts the case in wich a user restore a context he stored before. Because this context file stores only a text/html url yet we rather need an text/xml url.
> Right ?

correct

> For me, storing XML url in the context sounds better.

To me too.
But, to my knowledge, we have no proper, portable way to recover the text/html version of the metadata given the text/xml one (even after parsing it).

**Comment by fvanderbiest** [comment]
@MaelREBOUX , you did not answer my question: what do you expect for "administrator" (an XPath would be perfect). Thanks

**Comment by MaelREBOUX** [comment]
I do not understand. Examples ? For wich concrete action ?

As written in the spec document, we need to show :
 - title : /gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:title/gco:CharacterString
 - abstract : /gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:abstract/gco:CharacterString
 - lineage : /gmd:MD_Metadata/gmd:dataQualityInfo/gmd:DQ_DataQuality/gmd:lineage/gmd:LI_Lineage/gmd:statement/gco:CharacterString
 - the revision date. If not existe the creation date : /gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:date/gmd:CI_Date/gmd:date/gco:Date + test /gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:date/gmd:CI_Date/gmd:dateType/gmd:CI_DateTypeCode  revision || creation
 - point of contact : contact : /gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:pointOfContact/gmd:CI_ResponsibleParty/gmd:organisationName/gco:CharacterString + /gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:pointOfContact/gmd:CI_ResponsibleParty/gmd:individualName/gco:CharacterString
 - point of contact : custodian : /gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:pointOfContact/gmd:CI_ResponsibleParty/gmd:organisationName/gco:CharacterString + /gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:pointOfContact/gmd:CI_ResponsibleParty/gmd:individualName/gco:CharacterString

**Comment by fvanderbiest** [comment]
> I do not understand. Examples ? For wich concrete action ?

Say you want to open the original metadata sheet in a new browser tab (same behavior as now) ...

**Comment by landryb** [comment]
> @landryb
> http:///geonetwork3/srv/fre/md.format.xml?xsl=xml_view&uuid=9b470450-f62f-48ad-ad61-865a05ed006c provides an HTML page showing XML code with HTML formatting. It is not reusable for me comparing to the true XML output : http://geonetwork3/srv/fre/xml.metadata.get?uuid=9b470450-f62f-48ad-ad61-865a05ed006c

What i meant was "as long as you have the uuid stored in the url pointing to the metadata in the WMC, you're fine"

Ie you can construct the url from the known pattern /srv/fre/md.format.xml?xsl=full_view&uuid={uuid} to display/embed the user-friendly view directly from geonetwork.. instead of creating yet another xsl formatter, displaying only the fields you want from the xml.

**Comment by fvanderbiest** [comment]
> What i meant was "as long as you have the uuid stored in the url pointing to the metadata in the WMC, you're fine"

Yes and no...
Yes for our own metadata, that we know are stored in GeoNetwork (though the URL construct will be different in the case of GN2 or GN3 !)
No for any other external layer/metadata for which the url scheme is most probably different.

**Comment by fvanderbiest** [comment]
We can probably also use our own extension to the WMC standard, see below the ```<geor:xmlMetadataUrl>``` tag.

```xml
    <Layer queryable="0" hidden="0">
      ...
      <MetadataURL>
        <OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="http://www.cgiar-csi.org/data/srtm-90m-digital-elevation-database-v4-1" />
      </MetadataURL>
      ...
      <Extension>
        <ol:maxExtent xmlns:ol="http://openlayers.org/context" minx="-20037508.3399999999" miny="-20037508.3399999999" maxx="20037508.3399999999" maxy="20037508.3399999999" />
        <ol:tileSize xmlns:ol="http://openlayers.org/context" width="512" height="512" />
        ...
        <geor:xmlMetadataUrl>http://www.cgiar-csi.org/data/srtm-90m-digital-elevation-database-v4-1.xml</geor:xmlMetadataUrl>
      </Extension>
      ...
```

In this case, the standard ```<MetadataURL>``` tag would always store the HTML version of the metadata, as currently. This would also ease migrations...

**Comment by MaelREBOUX** [comment]
As we said by phone : I vote for this Extension.

I think it should store either the XML and the HTML url.

**Comment by fvanderbiest** [comment]
Other possibility: when the user presses the "display metadata" menu in the layer's action menu, call [hydrateLayerRecord](https://github.com/georchestra/georchestra/blob/15.06/mapfishapp/src/main/webapp/app/js/GEOR_ows.js#L603-L622) on the (incomplete) layer record, to get the missing information.

I think this is my prefered one :-)

**Comment by fvanderbiest** [comment]
Done, merged into master, deployed to http://sdi.georchestra.org/mapfishapp/

**Comment by fvanderbiest** [comment]
https://twitter.com/georchestra/status/685814017579991040 for the announcement + screenshot

**Comment by fvanderbiest** [comment]
Reopening after comments from @MaelREBOUX :

 * on window resized, a scrollbar should appear
 * missing window maxHeight parameter

**Comment by fvanderbiest** [comment]
With https://github.com/georchestra/georchestra/commit/a4aef7b9866fdd08c338440c3a572980c12877f4, links to metadata appear as buttons (with a different icon if the link opens in the same tab or another one)

![capture du 2016-01-12 09 53 22](https://cloud.githubusercontent.com/assets/265319/12258912/7661e6ca-b912-11e5-95ca-4782ff78df23.png)

**Comment by fvanderbiest** [comment]
> Reopening after comments from @MaelREBOUX :

Should be addressed with ffdb974, already deployed to http://sdi.georchestra.org/mapfishapp/

**Comment by MaelREBOUX** [comment]
OK : we missed some precisions in the last specifications draft.

In our minds we must have the same behaviour on the "OGC" tab or on the "catalog" tab.
Originally, we designed / thought this functionality for the "catalog" tab because it is the most used by the end users. By far away.

At that point I know that it is so much simple to code that simplified view for the OGC tab because it searches into the capabilities of the WMS or WFS service.
For the catalog tab, it must ask to the catalog using the CSW protocol wich is much expensive in code.

So @fvanderbiest thank you to create a new issue for milestone 16.06 (or 16.12 ?!) in order to complete this request. Funding to discuss later.

**Comment by fvanderbiest** [comment]
See https://github.com/georchestra/georchestra/issues/1180
