### ISSUE TITLE
Atlas addon

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1017]
A new addon should be developed in mapfishapp in order to print atlases.
The server-side is expected to be a new, optional module in geOrchestra, based on [mapfish print v3](https://github.com/mapfish/mapfish-print).
Jobs should be queued, as for the extractorapp, and users should receive an email upon job completion.

**Comment by fvanderbiest** [comment]
### Workflow

The user has to choose:
 * a WMS layer (one backed by a WFS service) among those which are already loaded
 * whether to print a multipage PDF or several PDF files in a zip
 * legend or no legend
 * print template (A4 / A3 + landscape/portrait)
 * global title/subtitle **or** 3 fields from the layer to provide:
   * map title
   * map sub-title
   * filename prefix (if one PDF per item)

If not authenticated, he also has to provide an email.

**Comment by fvanderbiest** [comment]
We noticed that https://github.com/geoserver/geoserver/wiki/GSIP-95---GetLegendGraphics-BBOX-and-SRS-parameter would allow for a better, more concise legend. Unfortunately still "Under Discussion".

**Comment by Vampouille** [comment]
Here you can find Json example and specification for atlas app :
https://gist.github.com/Vampouille/1ceb047465047dd1f9fd

**Comment by fvanderbiest** [comment]
> Here you can find Json example and specification for atlas app

This looks good (except for the indents), thanks !

**Comment by fvanderbiest** [comment]
Merged into master (between 15.12 and 16.06) with https://github.com/georchestra/georchestra/pull/1421
