### ISSUE TITLE
geonetwork - mauvaise traduction

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1019]
Dans la gestion des droits sur une MD, le terme "publier" est erroné. 
Il correspond plutôt à la capacité à voir la fiche.

**Comment by landryb** [comment]
Plutot 'consulter' donc ? A priori ca serait cette clef: https://github.com/geonetwork/core-geonetwork/blob/develop/web-ui/src/main/resources/catalog/locales/fr-editor.json#L124 mais je ne suis pas sur que 'publish' ne soit pas utilisé ailleurs, et le nom de clef n'est peut-etre pas approprié... les traductions GN viennent de transifex (https://www.transifex.com/geonetwork/core-geonetwork/)

**Comment by fvanderbiest** [comment]
Florent, un avis sur ce point ? Merci.

**Comment by MaelREBOUX** [comment]
J'ai fait des modifications de traductions il y a qqs semaines. Elles devraient logiquement apparaître dans la version 3.0.3 et +.

cf https://github.com/geonetwork/core-geonetwork/pull/1265

**Comment by fvanderbiest** [comment]
Merci Mael.
