### ISSUE TITLE
travis: switch to container-based infrastructure

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1023]
See http://docs.travis-ci.com/user/migrating-from-legacy/ for more information

**Comment by pmauduit** [comment]
https://github.com/pmauduit/georchestra/commit/c8cd9f3de9a2b330ccbb116d4a794137932b5e2d

**Comment by pmauduit** [comment]
(FYI the gain is around ~1 or 2 minutes)

**Comment by fvanderbiest** [comment]
Thanks Pierre, this is now the default, with https://github.com/georchestra/georchestra/commit/a89d0b73f47f32bc88d5f3dd3089103fb1962afb and https://github.com/georchestra/georchestra.github.io/commit/fafe2a2cca8f105dbaefa85930cb57d2daf99e25

**Comment by pmauduit** [comment]
Please next time cherrypick ... ;-) so that it won't mess up my further rebases

**Comment by fvanderbiest** [comment]
Please next time create a separate branch so that it's easier to merge ;-)

**Comment by pmauduit** [comment]
> Please next time create a separate branch so that it's easier to merge ;-)

(It actually is in a separate branch, which is just ahead of 160+ commits ahead of master ...details ...). Cherry-picking in this case is imho the right way to do with git, instead of re-copying.

**Comment by fvanderbiest** [comment]
> It actually is in a separate branch, 

True, I meant in fact "a dedicated branch", as we are used to, when adding a new feature.

> which is just 160+ commits ahead of master

True again, we have to deal with this ASAP (but enjoy your holidays !).

> Cherry-picking in this case is imho the right way to do with git

Right, I was just lazy ...
