### ISSUE TITLE
[header] generated login url does not work with some frameworks 

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#1032]
Typically, GeoNetwork 3 won't work with the following routine:
https://github.com/georchestra/georchestra/blob/15.06/header/src/main/filtered-resources/WEB-INF/jsp/index.jsp#L230

because AngularJS is using anchors in the url, like

```
https://georchestra.mydomain.org/geonetwork/srv/eng/catalog.search#/home
```

Will generate the following login url:

```
https://georchestra.mydomain.org/geonetwork/srv/eng/catalog.search#/home?login
```

Instead of:

```
https://georchestra.mydomain.org/geonetwork/srv/eng/catalog.search?login#/home
```

@fvanderbiest any idea on how to update the JS routine ?

**Comment by fvanderbiest** [comment]
Yes, I'll have a look at it.
Thanks.

**Comment by fvanderbiest** [comment]
should be OK now.
