### ISSUE TITLE
doc - java.util.prefs.syncInterval for geonetwork and extractorapp

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1033]
In https://github.com/georchestra/georchestra/blob/15.06/doc/setup/tomcat.md, mention the `-Djava.util.prefs.syncInterval=86400` workaround for https://github.com/georchestra/georchestra/issues/871

**Comment by landryb** [comment]
Are you sure you want to document a hackish workaround ? I'd rather advise to point java.util.prefs.userRoot/java.util.prefs.systemRoot to a directory we know tomcat can write to, and in our case it could be ```/var/lib/tomcat-XXXX/``` , ```/var/lib/tomcat-XXXX/temp``` or ```/var/lib/tomcat-XXXX/conf``` even..

**Comment by landryb** [comment]
The "overriding java.util.prefs.PreferencesFactory with a DisabledPreferencesFactory" solution looks nice but it means adding some more code....

**Comment by fvanderbiest** [comment]
Right, let's add this ```DisabledPreferencesFactory``` to 15.12 for extractorapp and geonetwork if it makes sense for everyone.

**Comment by fvanderbiest** [comment]
https://github.com/georchestra/georchestra/commit/d3d75ec463d10f584e02fbf754d3f78469e8cf10 fixes the documentation in the mean time.

**Comment by landryb** [comment]
I'm not sure adding ```DisabledPreferencesFactory``` to geonetwork goes in the same direction as 'using a geonetwork as close as possible as upstream', or the fix should go upstream first :p The doc fix looks enough to me, maybe with a link/explanation why it is needed ?

**Comment by fvanderbiest** [comment]
> or the fix should go upstream first

+1

**Comment by fvanderbiest** [comment]
Bumping to 16.06 unless a PR is proposed before the release.
