### ISSUE TITLE
ldapadmin - hardcoded geoserver_privileged_user string

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1050]
`geoserver_privileged_user` is currently hardcoded in https://github.com/georchestra/georchestra/blob/15.06/ldapadmin/src/main/webapp/WEB-INF/spring/webmvc-config.xml#L79

We should use https://github.com/georchestra/template/blob/15.06/build_support/shared.maven.filters#L102 instead.

Thanks Landry for the good catch !

**Comment by landryb** [comment]
I'm a little bit lost with all the files replacement/templatization between filtered-resources and all, but isn't it only a matter of replacing 'geoserver_privileged_user' by '${protectedUser.uid1}' in webmvc-config.xml ? Afaict this file already contains a lot of 'templated' values inside ${} so i'm not sure if more is needed to properly replace this value.... which comes to ldapadmin 'context' from spring/ldapadmin.properties ?
