### ISSUE TITLE
[mapfishapp -> Gn3] WMC import is broken

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#1057]
In GN3.0.x, the entry point changed from

```
/geonetwork/srv/eng/wmc.import
```

To:

```
/geonetwork/srv/eng/map.import
```

It should be customizable mapfishapp-side (or else adapted GN-side in the geOrchestra fork ?).

**Comment by pmauduit** [comment]
After discussing with @fvanderbiest:

* [ ] Change entry point from wmc.import to map.import in Mapfishapp and GN2.x
* [ ] Rename parameters sent by Mapfishapp (from wmc_* to map_*)
* [ ] Adapt the GN2.x service to be compatible with the one in 3.0.x

**Comment by fvanderbiest** [comment]
Right, this can be done only on master, ie **not backported to 15.06**, since GN3 is due for 15.12 only.
Thanks !

**Comment by pmauduit** [comment]
Done. Need review on both PR (mainly the mapfishapp one, I'm pretty confident for the GN one), and would require runtime testing.
