### ISSUE TITLE
ogc-server-statistics logs requests to /proxy/ too

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1058]
ogc-server-statistics currently logs all requests going through the security proxy, including those targeting external servers (matching the /proxy/ endpoint, used to circumvent browser's "same origin policy").

These requests appear in analytics, but the view is very incomplete, since we lack the external server URL.

So, IMO, we have two choices:
 - [solution 1] either we drop support for requests going through /proxy/?url=
 - [solution 2] or we add support for the service endpoint

**Comment by fvanderbiest** [comment]
Voting for solution 1.

**Comment by pmauduit** [comment]
also :+1: for solution 1

**Comment by fphg** [comment]
+1 for 1
however requests still shall be file logged for security reasons

**Comment by pmauduit** [comment]
> however requests still shall be file logged for security reasons

Since they still will be intercepted by the frontend webserver, this would end up in the webserver logfiles logically, independantly of what is done by the Security-proxy afterwards.

**Comment by landryb** [comment]
While here, see also #1027 ?

**Comment by fvanderbiest** [comment]
> While here, see also #1027 ?

right.
