### ISSUE TITLE
mark clusterizable webapps as such

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#1066]
In the context of deploying as much as possible georchestra webapps in a clusterized tomcat environment, there's a requirement of adding <distributable/> to web.xml for each webapp (cf http://wiki.metawerx.net/wiki/Web.xml.Distributable and https://tomcat.apache.org/tomcat-8.0-doc/cluster-howto.html#Cluster_Basics) - afaict, this causes no ill-effect when running webapps in a non-clusterized tomcat environment, so would there be opposition to mark the known-working-as-clusterized webapps as such (and of course, i'll do a PR for this small change) ? so far, i've tested sec-proxy, cas, header & ldapadmin without fallout.

**Comment by fvanderbiest** [comment]
No objection from my side. Thanks !

**Comment by fvanderbiest** [comment]
Landry, do you plan more for this one on 15.12 ?

**Comment by landryb** [comment]
Nope, way more work will be required for geonetwork/geoserver, and i havent looked at the other webapps...
