### ISSUE TITLE
Addon - OSM editors

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1070]
The possibility to open the current viewport in any OSM editor should be ported to an addon (and removed from mapfishapp on master)

![capture du 2016-05-20 15 48 01](https://cloud.githubusercontent.com/assets/265319/15429711/73f1137a-1ea2-11e6-9515-e3d2f421a4b5.png)

**Comment by landryb** [comment]
Agreed, even if i fully support the 'edit in osm' feature, sadly it might confuse unexperienced users...

Having it as an addon might allow more flexibility too, like only enabling some items for particular configurations/usecases.
