### ISSUE TITLE
addon osm2geor : use stored geometries as spatial filter

### ISSUE THREAD

**Issue by fphg** [georchestra/georchestra#1074]
The querier let the user store a spatial condition in a buffer to reuse it for another query.
The object grid (south panel) also provide such a feature.

Idea : in an overpass query, use {{GEOMETRY}} as spatial filter statement, letting the user fetch OSM features intersecting a preselected geometry.

IMO any osm2geor request should feed the south panel without having to select the features one by one on the map : osm2geor should behave like a WFS query.

**Comment by fvanderbiest** [comment]
> use {{GEOMETRY}} as spatial filter statement

Taking advantage of http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#By_polygon_.28poly.29

**Comment by fvanderbiest** [comment]
> IMO any osm2geor request should feed the south panel without having to select the features one by one on the map : osm2geor should behave like a WFS query.

This is a different issue IMO.

**Comment by fvanderbiest** [comment]
Query by BBOX:
![capture du 2015-09-29 21 22 31](https://cloud.githubusercontent.com/assets/265319/10176308/35e21ea0-66f4-11e5-9e1f-02369fe8a0c5.png)

Query by stored GEOMETRY:
![capture du 2015-09-29 21 21 51](https://cloud.githubusercontent.com/assets/265319/10176317/45119b30-66f4-11e5-919a-df3d3b3d1aff.png)

Looks good, deployed to http://sdi.georchestra.org/mapfishapp/

**Comment by fphg** [comment]
nice ! thanks
