### ISSUE TITLE
improve the WPS add-on builder, and include it into the default tool list

### ISSUE THREAD

**Issue by stlejer-morvrini** [georchestra/georchestra#1082]
Improve and propose the WPS add-on builder (WAB) by default in the "tools" menu so that any one could link every possible WPS to an add-on and easily use WPSes from mapfishapp.
Imagine a way to make these add-ons persistent and sharable.

**Comment by fvanderbiest** [comment]
Can you include a link to the WPS addon builder source and eventually demo ? Thanks

**Comment by stlejer-morvrini** [comment]
Must be this one: https://github.com/BVService/addons/tree/master/wab
