### ISSUE TITLE
ldapadmin - no way of removing a field

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#1086]
Step to reproduce:

1. connect as a user who has a MOD_LDAPADMIN role
2. go to `/ldapadmin/privateui/`
3. edit a user, removing a field (its  phone number for example)
4. click "save"

=> The UI indicates that the user has been updated successfully, but this is not the case: reload the page, the field is back to its original value.

I think that in case of blanking a field, the LDAP operation is not strictly the same as the field update one. We have to add some logic to fully implement field removal.

**Comment by fvanderbiest** [comment]
Hmm, the fix was applied to master, but it should have been applied to 14.01 or 14.06.
Someone backports it ? Thanks :-)

**Comment by vdorut** [comment]
> 14.01 or 14.06.

Does not apply easily on 14.01 nor 14.06.

**Comment by fvanderbiest** [comment]
OK for 14.12 then !
