### ISSUE TITLE
header - incorrect link to ldapadmin user page

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1096]
Freshly tested on master, the link points to https://georchestra.mydomain.org/ldapadminaccount/userdetails instead of https://georchestra.mydomain.org/ldapadmin/account/userdetails

**Comment by landryb** [comment]
Because publicContextPath=/ldapadmin in  ldapadmin/src/deb/resources/etc/georchestra/ldapadmin/ldapadmin.properties ? missing trailing / ?
Interestingly it's  /ldapadmin/ in ldapadmin/src/deb/resources/etc/georchestra/ldapadmin/js/config.js ...

**Comment by pmauduit** [comment]
Following previous PR from @fvanderbiest (see #1088), it has been decided to exclude the CSS / JS files from the datadir (this removes 2 extra controllers java / spring side only meant to serve the 2 previous files).

**Comment by pmauduit** [comment]
@fvanderbiest can you retest ? I just commited a default configuration which should fix the issue (adding a trailing /)

**Comment by fvanderbiest** [comment]
Will live-test tomorrow @ cigalsace training ;-)

**Comment by landryb** [comment]
looking again, this should be fine after a default-redeploy (and maybe #1136) - contextpath defaults to /ldapadmin/ (https://github.com/georchestra/georchestra/blob/master/header/src/deb/resources/etc/georchestra/header/header.properties#L2 or https://github.com/georchestra/georchestra/blob/master/ldapadmin/src/deb/resources/etc/georchestra/ldapadmin/ldapadmin.properties#L2 still unsure which one is used) so the jsp shouldnt need to add a / - we could even remove the extra / added here https://github.com/georchestra/georchestra/blob/master/header/src/main/filtered-resources/WEB-INF/jsp/index.jsp#L347

**Comment by fvanderbiest** [comment]
Should be fixed with 3c43f3e and https://github.com/georchestra/datadir/commit/ec47bb2aa5a7ee37aa62c9cc9c9049640af72752

**Comment by fvanderbiest** [comment]
Deployed to sdi, looks good !
