### ISSUE TITLE
geonetwork 15.06 compilation failure

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1098]
[INFO] GeoNetwork opensource .............................. SUCCESS [ 30.993 s]
[INFO] Caching xslt module ................................ SUCCESS [02:31 min]
[INFO] Jeeves modules ..................................... FAILURE [27:35 min]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.10:check (check) on project jeeves: Execution check of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.10:check failed: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.10 or one of its dependencies could not be resolved: The following artifacts could not be resolved: com.puppycrawl.tools:checkstyle:jar:5.6, commons-beanutils:commons-beanutils-core:jar:1.8.3: Could not transfer artifact com.puppycrawl.tools:checkstyle:jar:5.6 from/to opengeo (http://repo.boundlessgeo.com/): Access denied to: http://repo.boundlessgeo.com/com/puppycrawl/tools/checkstyle/5.6/checkstyle-5.6.jar , ReasonPhrase:Forbidden. -> [Help 1]

**Comment by pmauduit** [comment]
I'm not the repo.boundlessgeo.com sysadmin ... ;-) Just kidding, could you please retry ? (supposing you are trying on master)

**Comment by fvanderbiest** [comment]
The issue was reported on stable 15.06 and might also affect older supported releases...

**Comment by pmauduit** [comment]
Yes but since I've everything locally, I cannot reproduce without removing my .m2 and redownloading the whole earth, my point was to let you test it out before I report it back on the other branches.

**Comment by fvanderbiest** [comment]
Tested on master with a clean cache: OK :-)

**Comment by pmauduit** [comment]
Ok, then I'll backport
