### ISSUE TITLE
Geowebcache Version

### ISSUE THREAD

**Issue by jusabatier** [georchestra/georchestra#1111]
I had a NullPointer Exception on some tiles/zoomlevel of an Ortho, I tried to just update my standalone GWC to latest version (1.8.0). And with the new version the error is solved. Maybe could be a good thing to update the GWC used in Georchestra to latest version ?

**Comment by pmauduit** [comment]
It should be as easy as to modify the following line:
https://github.com/georchestra/georchestra/blob/master/geowebcache-webapp/pom.xml#L16

But honestly I don't have the time to test it for now, do you mind giving it a try ?

**Comment by jusabatier** [comment]
Yes I'll try it :)
