### ISSUE TITLE
ldapadmin API should return json content-type

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#1115]
Right now the API sets content-type header to text/html when being called from the web ui, while it'd be more 'correct' for it to be 'application/json' .. since the actual value is json.

Also, in https://github.com/georchestra/georchestra/blob/master/ldapadmin/CLIENT_SERVER_INTERFACE.md#use-of-curl i dont really understand why the Content-Type header is set to text/xml since we POST json content...

**Comment by fvanderbiest** [comment]
agreed, +1

**Comment by pmauduit** [comment]
Reproduced:

```
$ curl -i 'http://sdi.georchestra.org/ldapadmin/private/users' ...

HTTP/1.1 200 OK
Date: Mon, 09 Nov 2015 13:28:37 GMT
Server: Apache-Coyote/1.1
Content-Type: text/html;charset=UTF-8
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 1889
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
```
Should be easily fixed using the `@Produces` annotation, see https://docs.oracle.com/cd/E19798-01/821-1841/gipxf/index.html ; (should also work on a method)

**Comment by pmauduit** [comment]
Tested into generated vm on current master ldapadmin package
