### ISSUE TITLE
ldapadmin - css not found

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1121]
http://sdi.georchestra.org/ldapadmin/privateui/css/main.css is 404, this breaks the flash message on user update

**Comment by pmauduit** [comment]
double slash vs simple slash:
https://georchestra.mydomain.org/ldapadmin/privateui/css/main.css OK
https://georchestra.mydomain.org/ldapadmin//privateui/css/main.css KO

Related to issue https://github.com/georchestra/georchestra/issues/1136

**Comment by fvanderbiest** [comment]
Should also be fixed with https://github.com/georchestra/georchestra/commit/84dd3ae038fec331bca479c0ab154a9b57fe5cea
