### ISSUE TITLE
travis: cache .m2 ?

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1126]
As per http://docs.travis-ci.com/user/caching/:

```
cache:
  directories:
    - $HOME/.m2
```

**Comment by pmauduit** [comment]
Possible, but can lead to some side-effects (old config template, ...). We have to make sure that the build will update the dependencies if necesary

**Comment by pmauduit** [comment]
I think it is better to start a new build from a completely clean .m2, so that we can be aware way faster that a dependency is no more available somewhere in a remote repository (even if we currently kindof cheat with the huge m2.tar hosted on build.georchestra.org ...)

To be closed, then ?

**Comment by fvanderbiest** [comment]
> To be closed, then ?

I'd like to give a try though.
As you say by yourself, we're already cheating it right now.

So, I'd say: 
 * sdi.geor.org/ci wipes its local repo before building, so that broken dependencies are quickly fixed
 * travis uses a local cache.
