### ISSUE TITLE
missing default config in cas.properties

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#1137]
cas top.jsp (coming from the default build template - https://github.com/georchestra/template/blob/master/cas-server-webapp/WEB-INF/view/jsp/default/ui/includes/top.jsp#L47) will try to read values from georchestra.datadir but two are missing from the example/default config (https://github.com/georchestra/georchestra/blob/master/cas-server-webapp/src/deb/resources/etc/georchestra/cas/cas.properties#L3) :

```
header.height=90
ldapadmin.contextpath=/ldapadmin/

```

While here, should https://github.com/georchestra/georchestra/blob/master/cas-server-webapp/src/main/filtered-resources/WEB-INF/cas.properties still be in the repo ? which one is used in which case ?

**Comment by pmauduit** [comment]
> While here, should https://github.com/georchestra/georchestra/blob/master/cas-server-webapp/src/main/filtered-resources/WEB-INF/cas.properties still be in the repo ? which one is used in which case ?

For people still willing to build (and who do not want to use the datadir feature for whatever reasons), I guess we have to keep it.

**Comment by fvanderbiest** [comment]
OK, should be fixed with https://github.com/georchestra/georchestra/commit/56d1b1263e1a119b47990e4769d989a0256a0339 and https://github.com/georchestra/datadir/blob/master/cas/cas.properties
