### ISSUE TITLE
Oracle integration

### ISSUE THREAD

**Issue by pierrejego** [georchestra/georchestra#1146]
Hello,
I'd like to add Oracle as possible database for geOrchestra. I have started to make modifications, it seems ok for mapfishapp and ldapadmin. I still have to find a good way of doing it for geonetwork.

The idea is to keep the same configuration as it's done now. No change in pom.xml for postgresql dependencies, only add oracle driver in tomcat bootstrap if needed.

Another Idea could be to use jdni, configure all connection in tomcat and refer to the jndi in applications. 

Regards

Pierre

**Comment by pmauduit** [comment]
Hi, as a first thought, you would need to activate the oracle jdbc module (which is deactivated by default because of licensing issues), see:

https://github.com/georchestra/geonetwork/blob/georchestra-15.06/pom.xml#L784-L790

Then configure your GN accordingly. It should be easier to configure in the coming version though: 

https://github.com/pmauduit/core-geonetwork/blob/georchestra-gn3-3.0.x/web/src/deb/resources/etc/georchestra/geonetwork/config/config-db-georchestra.xml

Anyway, it should be pretty similar for current version (just juggling with real conf files vs overrides ones)

Thanks for the investigations !

**Comment by pierrejego** [comment]
Hello, thank you for your explanation,

I will use GN3. And start installing it using your repo : https://github.com/georchestra/georchestra/issues/1120 

Regards

Pierre

**Comment by pierrejego** [comment]
For the moment I have detected only two modifications (more in configuration) needed to make mapfishapp and ldapadmin working with Oracle. (Cas, Security-proxy, Geonetwork are ok)

In mapfishapp it's mainly SQL request that are not compatible ( most of the time only because of ; at the end of the request) I have made all needed changes, there are working on Oracle I have to test them on postgresql.

In ldapadmin, it only because the attribute   private Date date of EmailEntry is called date, witch is a reserverd word for oracle, just rename it as emailEntryDate make it works.

I have put as well all mention of postgresql driver or hibernate postgresqlTemplate in properties files, but I am not sure how to do it correctly so it will work for datadir and configuration compile. 

I'd like to make a pull request for the end of the week, I hope it will help other than me :)

**Comment by fvanderbiest** [comment]
> I'd like to make a pull request for the end of the week, I hope it will help other than me :)

We appreciate it very much, thanks a lot :-)

**Comment by Vampouille** [comment]
Maybe you can change annotation here : 
https://github.com/georchestra/georchestra/blob/AddLogs/ldapadmin/src/main/java/org/georchestra/ldapadmin/model/EmailEntry.java#L25
with : `@Column(name = "email_date")`
I think same apply to AdminLogEntry :
https://github.com/georchestra/georchestra/blob/AddLogs/ldapadmin/src/main/java/org/georchestra/ldapadmin/model/AdminLogEntry.java#L23
with : `@Column(name = "log_date", updatable = false, nullable = false)`

**Comment by Vampouille** [comment]
Did take a look at analytics module ? There is entity with date field and a postgres array define here : 
https://github.com/georchestra/georchestra/blob/AddLogs/analytics/src/main/java/org/georchestra/analytics/model/Stats.java#L131

**Comment by pmauduit** [comment]
Once the PR #1141 will be merged, there will be an issue with some specific-postgres code:
https://github.com/georchestra/georchestra/pull/1141/files#diff-82dd661b3f7efba914aa790057735f4c

**Comment by pierrejego** [comment]
Health check from security proxy is not compatible Oracle as well. I will make correction to futher pull request.
I have never used analytics module for the moment. I think for the moment I won't try to make changes, I'll have a look after PR #1141
