### ISSUE TITLE
security-proxy - dead | still used code ?

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#1153]
I was looking at the generated cobertura coverage report on one of my branches, and was wondering what is the history / purpose behind the CheckHealth package of the security proxy. Is it used somewhere in production ? I refer to the following classes in the package healthcenter:

https://github.com/georchestra/georchestra/tree/15.06/security-proxy/src/main/java/org/georchestra/security/healthcenter

This induces extra processing at each requests if activated, see:
https://github.com/georchestra/georchestra/blob/15.06/security-proxy/src/main/java/org/georchestra/security/Proxy.java#L496

@fvanderbiest any idea ? From my PoV if the only purpose is to check the availability of postgresql, it is clearly behind the scope of the SP to do that, or it might be, but not each time a request is made.

**Comment by fvanderbiest** [comment]
> I was looking at the generated cobertura coverage report on one of my branches, and was wondering what is the history / purpose behind the CheckHealth package of the security proxy. 

PIGMA was complaining about their lack of opened connections on their DBMS

> Is it used somewhere in production ?

PIGMA IIRC

> From my PoV if the only purpose is to check the availability of postgresql, it is clearly behind the scope of the SP to do that, or it might be, but not each time a request is made.

+1, I think we should remove this code.
There are other, better, more appropriate, tools to do this kind of thing.

**Comment by pmauduit** [comment]
@fvanderbiest maybe @vdorut could try to remove the package ?

@vdorut: care to work on this ?

- [ ] Check what the code actually does
- [ ] Check in which project it is used
- [ ] See if it can be replaced by something more relevant (JMX ? Nagios probes for pure postgresql matters ...)

**Comment by fvanderbiest** [comment]
Done with the above PRs.
Needs a review...
