### ISSUE TITLE
[geonetwork] move log4j*xml files to ${georchestra.datadir}/geonetwork/log4j/

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#1154]
(Split out of https://github.com/georchestra/georchestra/issues/1120#issuecomment-164681408)

Would be nice to allow getting log4j.xml from ${georchestra.datadir} like other modules, possibly pushing this upstream. Dunno if that's possible via overrides, but GN3 has runtime-switching of loglevels (code partly at https://github.com/geonetwork/core-geonetwork/blob/develop/services/src/main/java/org/fao/geonet/services/config/LogUtils.java) like geoserver does, and this between all the WEB-INF/classes/log4j*xml files. Could be nice to keep this, only pointing the dir to ${georchestra.datadir}/geonetwork/log4j, but i'm not sure we can reuse the plumbing in georchestra-commons for this without invasive (and unmergeable upstream) changes.

**Comment by landryb** [comment]
Implementation in https://github.com/geonetwork/core-geonetwork/commit/eb6c5384b0dbdb2f459190fae59db9820f403ae0

**Comment by pmauduit** [comment]
Oooops was not the good remote to push onto ><

**Comment by pmauduit** [comment]
Hmm it seems to be ok actually, just github which is capable of retrieving any commits from the forks, and referencing them in the official repo. Misleading ...

**Comment by pmauduit** [comment]
done with https://github.com/georchestra/geonetwork/commit/2458b554949b005eba16b17bb051278bdea80893
