### ISSUE TITLE
geoserver 2.8.1 - need to settle which extra modules is necessary

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#1163]
This one is kind of related to https://github.com/georchestra/georchestra/issues/1135.

In `geoserver/geoserver-submodule/src/pom.xml`, several modules can be activated using maven profiles, then they can be added to the actual georchestra's geoserver webapp if they are also defined here:
https://github.com/georchestra/georchestra/blob/15.06/geoserver/webapp/pom.xml#L125

In addition, the profiles currently defined in the (`geoserver/webapp/`) pom.xml are not synchronized anymore with what is actually available geoserver-side.

This issue tend to address several different sub-problems:
- [ ] Cleanup the unecessary profiles (which are still useful ? which are out of date ?) ;
- [ ] Activate the ones we want to provide into geOrchestra by default (inspire ?) ;
- [ ] Add the optional ones ;

**Comment by landryb** [comment]
Fwiw, i'm not able to activate the ogr profile/extension. But i've been able to add profiles for http://docs.geoserver.org/latest/en/user/community/colormap/index.html, http://docs.geoserver.org/latest/en/user/community/geopkg/index.html and http://docs.geoserver.org/latest/en/user/extensions/importer/index.html

istyler seems broken, as dds, script and imagemap. sldService seems to require being called as 'gs-sldservice'..

Here's what i have locally: https://gist.github.com/landryb/565586f09e4a7ab8c5b1
And the full maven invocation
```
mvn clean package deb:package  --projects geoserver/webapp -Dgeoserver.war.excludes=WEB-INF/lib/*gwc*.jar -Dserver=craig-template -PdebianPackage -Papp-schema,authkey,charts,control-flow,css,csw,dxf,feature-aggregate,feature-pregeneralized,gdal,inspire,libjpeg-turbo,pyramid,spatialite,xslt,wps,importer,sldservice,colormap,geopkg
```

**Comment by fvanderbiest** [comment]
IMO, control-flow, pyramid, css, monitor, wcs20 should be activated by default in our builds.
For the others, I think it should be up to the plateform administrator.
