### ISSUE TITLE
[meta] validate java 8 support

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#1164]
Prompted by @pmauduit testing geonetwork 3 build with java 8, and this announce (http://osgeo-org.1560.x6.nabble.com/GeoServer-master-2-9-x-now-requires-Java-8-tt5242713.html) - at some point we'll have to start validating java 8.

**Comment by pmauduit** [comment]
The main part of the work is done by migrating to spring4, this should not be a big deal with "pure-georchestra" webapps, but I'm more strongly concerned by GeoNetwork: Some tests are still failing in our fork with Java7, and the try I did these last days shows that a considerable amount of work would have to be done to validate Java8 (repairing testsuite + changing some portions of code that do not react the same way with the new version).

**Comment by pmauduit** [comment]
Note: I'm already working with Java8 on my personal laptop and consider migrating soon on my Camptocamp dev environment.

**Comment by fvanderbiest** [comment]
I think this has to be tackled by the GN and GS communities before we have to worry about it.

**Comment by landryb** [comment]
> I think this has to be tackled by the GN and GS communities before we have to worry about it.

For GS it's already done since 2.9/master now requires java8 :)

**Comment by landryb** [comment]
https://github.com/geonetwork/core-geonetwork/pull/1394 for GN validation/testing with java8 (ie update to spring4)

**Comment by fvanderbiest** [comment]
I think this can be closed since all webapps run with java8 in our docker composition.
