### ISSUE TITLE
ldapadmin - TEMPORARY_USER

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1167]
https://github.com/georchestra/georchestra/blob/master/ldapadmin/src/main/java/org/georchestra/ldapadmin/ws/backoffice/groups/GroupsController.java#L58 introduces a virtual group named TEMPORARY_USER but:
 * it should not contain the underscore char because this introduces an unwanted hierarchy
 * when trying to remove it, a 404 is returned. Expected behavior : a user-readable message stating something like this: "this system group cannot be removed"

![capture du 2016-01-05 13 14 19](https://cloud.githubusercontent.com/assets/265319/12114957/9108216a-b3ae-11e5-824f-2cc566043c71.png)

**Comment by Vampouille** [comment]
This PR should fix this : 
https://github.com/georchestra/georchestra/pull/1168

**Comment by fvanderbiest** [comment]
In addition, one should not be able to affect a user to the TEMPORARY group:
![capture du 2016-01-06 17 11 32](https://cloud.githubusercontent.com/assets/265319/12147336/aa759f3e-b498-11e5-8b74-3f8e2f9c3f3a.png)

**Comment by Vampouille** [comment]
This should be fixed by #1172
