### ISSUE TITLE
geoserver build fails on CI

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1185]
using geoserver -Papp-schema,authkey,charts,control-flow,css,csw,dds,dxf,feature-aggregate,feature-pregeneralized,gdal,geoxacml,imagemap,inspire,istyler,libjpeg-turbo,mysql,ogr,pyramid,script,spatialite,wps,w3ds

with https://sdi.georchestra.org/ci/job/georchestra-sdi.georchestra.org/604/console
[INFO] Web 3D Service ..................................... FAILURE [  2.575 s]

**Comment by fvanderbiest** [comment]
Official extensions in branch ```2.8.1-georchestra```:
```
      <id>app-schema</id>
      <id>arcsde</id>
      <id>h2</id>
      <id>sqlserver</id>
      <id>oracle</id>
      <id>mysql</id>
      <id>db2</id>
      <id>imagemosaic-jdbc</id>
      <id>jp2k</id>
      <id>gdal</id>
      <id>feature-pregeneralized</id>
      <id>imagemap</id>
      <id>ogr</id>
      <id>excel</id>
      <id>charts</id>
      <id>geosearch</id>
      <id>control-flow</id>
      <id>wps</id>
      <id>querylayer</id>
      <id>teradata</id>
      <id>monitor</id>
      <id>security</id>
      <id>xslt</id>
      <id>inspire</id>
      <id>css</id>
      <id>csw</id>
      <id>dxf</id>
      <id>printing</id>
      <id>wcs2_0-eo</id>
      <id>libjpeg-turbo</id>
      <id>importer</id>
      <id>grib</id>
      <id>netcdf</id>
      <id>netcdf-out</id>
      <id>allExtensions</id>
      <id>release</id>
```

Community extensions in branch ```2.8.1-georchestra```:
```
      <id>proxy</id>
      <id>colormap</id>
      <id>rest</id>
      <id>sldService</id>
      <id>dds</id>
      <id>gpx</id>
      <id>dbconfig</id>
      <id>istyler</id>
      <id>webservice</id>
      <id>app-schema</id>
      <id>programming-guide</id>
      <id>communityRelease</id>
      <id>gss</id>
      <id>ftp</id>
      <id>spatialite</id>
      <id>sextante</id>
      <id>sfs</id>
      <id>feature-aggregate</id>
      <id>authkey</id>
      <id>jdbcconfig</id>
      <id>script</id>
      <id>pgraster</id>
      <id>w3ds</id>
      <id>wms-eo</id>
      <id>kml-old</id>
      <id>geopkg</id>
      <id>mbtiles</id>
      <id>wfs-notification</id>
      <id>geoserver-sync</id>
      <id>dyndimension</id>
      <id>rest-ext</id>
      <id>validation</id>
      <id>kmlppio</id>
      <id>wps-download</id>
      <id>solr</id>
      <id>rest-upload</id>
      <id>jms-cluster</id>
      <id>activemq</id>
      <id>geofence</id>
      <id>geofence-server</id>
      <id>hz-cluster</id>
      <id>geomesa</id>
      <id>gwc-distributed</id>
      <id>vectortiles</id>
      <id>gdal-translate</id>
      <id>gwc-s3</id>
```

**Comment by fvanderbiest** [comment]
OK, I think our CI should build GeoServer with:
 * app-schema,arcsde,h2,sqlserver,oracle,mysql,db2,imagemosaic-jdbc,jp2k,gdal,feature-pregeneralized,imagemap,ogr,excel,charts,geosearch,control-flow,wps,querylayer,teradata,monitor,security,xslt,inspire,css,csw,dxf,printing,wcs2_0-eo,libjpeg-turbo,importer,grib,netcdf,netcdf-out,app-schema,spatialite,jdbcconfig,pgraster,mbtiles,vectortiles,geofence,geofence-server
 * and the same with geofence,geofence-server

**Comment by fvanderbiest** [comment]
Trying a new build without GeoFence with https://sdi.georchestra.org/ci/job/georchestra-sdi.georchestra.org/605/

Finaly, we should also deploy the integrated GeoFence.

**Comment by fvanderbiest** [comment]
jdbcconfig in community fails to build, removing it
[INFO] GeoServer JDBC KV Catalog .......................... FAILURE [  4.926 s]

**Comment by fvanderbiest** [comment]
Importer fails ... https://sdi.georchestra.org/ci/job/georchestra-sdi.georchestra.org/606/console
[INFO] GeoServer Data Importer ............................ SUCCESS [  7.571 s]
[INFO] Importer Core Module ............................... FAILURE [  6.450 s]

**Comment by pmauduit** [comment]
You definitely should use the "-fae" maven option (fail-at-end). So that independant modules could be built even if one fails

**Comment by fvanderbiest** [comment]
More critical now:

[INFO] GeoServer Web Application .......................... FAILURE [  9.668 s]

[ERROR] Failed to execute goal on project gs-web-app: Could not resolve dependencies for project org.geoserver.web:gs-web-app:jar:2.8.1: The following artifacts could not be resolved: com.oracle:ojdbc7:jar:12.1.0.2, org.geoserver.community:gs-netcdf:jar:2.8.1, org.geoserver.community:gs-netcdf-out:jar:2.8.1, org.geoserver.extension:gs-pgraster:jar:2.8.1, org.geoserver.community:gs-grib:jar:2.8.1: Failure to find com.oracle:ojdbc7:jar:12.1.0.2 in https://repo.boundlessgeo.com/main/ was cached in the local repository, resolution will not be reattempted until the update interval of boundless has elapsed or updates are forced -> [Help 1]

**Comment by fvanderbiest** [comment]
OK, GeoServer 2.8.1 builds with -Papp-schema,arcsde,h2,sqlserver,mysql,db2,jp2k,gdal,feature-pregeneralized,imagemap,excel,charts,geosearch,control-flow,wps,querylayer,teradata,monitor,security,xslt,inspire,css,csw,dxf,wcs2_0-eo,libjpeg-turbo,app-schema,spatialite,mbtiles,vectortiles

**Comment by landryb** [comment]
Fwiw i'm using 
```
-Papp-schema,authkey,charts,control-flow,css,csw,dxf,feature-aggregate,feature-pregeneralized,gdal,inspire,libjpeg-turbo,pyramid,spatialite,xslt,wps,importer,sldservice,colormap,geopkg
```

i tried scripting extension but script-js requires gt 12, script-py requires gt 13-snapshot.

Related to #1163 ? :)

**Comment by fvanderbiest** [comment]
A naked 2.8.1 geoserver starts, but one compiled with app-schema,mysql,jp2k,gdal,geosearch,control-flow,wps,querylayer,monitor,security,xslt,inspire,css,csw,dxf,libjpeg-turbo,spatialite,mbtiles,vectortiles extensions fail to start with the following logs in catalina.out:
```
INFO: Starting Servlet Engine: Apache Tomcat/6.0.36
Jan 20, 2016 2:28:38 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive geoserver.war
Jan 20, 2016 2:28:38 PM org.apache.catalina.loader.WebappClassLoader validateJarFile
INFO: validateJarFile(/var/lib/georchestra/tomcat-03/webapps/geoserver/WEB-INF/lib/servlet-api-2.5.jar) - jar not loaded. See Servlet Spec 2.3, section 9.7.2. Offendin
g class: javax/servlet/Servlet.class
Jan 20, 2016 2:28:39 PM it.geosolutions.imageio.gdalframework.GDALUtilities loadGDAL
INFO: GDAL Native Library loaded (version: 1.9.0)
Jan 20, 2016 2:28:39 PM it.geosolutions.util.KakaduUtilities loadKakadu
WARNING: Failed to load the Kakadu native libs. This is not a problem unless you need to use the Kakadu plugin: it won't be enabled. java.lang.UnsatisfiedLinkError: no
 kdu_jni in java.library.path
Jan 20, 2016 2:28:39 PM it.geosolutions.imageio.plugins.turbojpeg.TurboJpegUtilities loadTurboJpeg
WARNING: Failed to load the TurboJpeg native libs. This is not a problem, but the TurboJpeg encoder won't be available: java.lang.UnsatisfiedLinkError: no turbojpeg in
 java.library.path
Jan 20, 2016 2:28:40 PM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'XStreamPersisterInitializer', but ApplicationContext is unset.
Jan 20, 2016 2:28:40 PM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
Jan 20, 2016 2:28:40 PM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'ExtensionProvider', but ApplicationContext is unset.
Jan 20, 2016 2:28:40 PM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
log4j:WARN File option not set for appender [geoserverlogfile].
log4j:WARN Are you using FileAppender instead of ConsoleAppender?
Jan 20, 2016 2:28:41 PM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'GeoServerSecurityProvider', but ApplicationContext is unset.
Jan 20, 2016 2:28:41 PM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
Jan 20, 2016 2:28:41 PM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'ExtensionProvider', but ApplicationContext is unset.
Jan 20, 2016 2:28:41 PM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
SLF4J: The requested version 1.6.99 by your slf4j binding is not compatible with [1.5.5, 1.5.6, 1.5.7, 1.5.8]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
Jan 20, 2016 2:28:51 PM org.apache.catalina.core.StandardContext start
SEVERE: Error listenerStart
Jan 20, 2016 2:28:51 PM org.apache.catalina.core.StandardContext start
SEVERE: Context [/geoserver] startup failed due to previous errors
Jan 20, 2016 2:28:51 PM org.geoserver.GeoserverInitStartupListener contextDestroyed
INFO: Beginning GeoServer cleanup sequence
```

**Comment by pmauduit** [comment]
Wrong log file, something is messed up between these 2 traces:

```
> Jan 20, 2016 2:28:39 PM it.geosolutions.imageio.plugins.turbojpeg.TurboJpegUtilities loadTurboJpeg
> WARNING: Failed to load the TurboJpeg native libs. This is not a problem, but the TurboJpeg encoder won't be available: java.lang.UnsatisfiedLinkError: no turbojpeg in
>  java.library.path
```

And

```
> Jan 20, 2016 2:28:40 PM org.geoserver.platform.GeoServerExtensions checkContext
> WARNING: Extension lookup 'XStreamPersisterInitializer', but ApplicationContext is unset.
```

**Comment by pmauduit** [comment]
Into `localhost.2016-01-20.log` instead:

```
Jan 20, 2016 2:34:53 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.geoserver.platform.GeoServerContextLoaderListener
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'geosearchLayerConfig' defined in URL [jar:file:/var/lib/georchestra/tomcat-03/webapps/geoserver/WEB-INF/lib/gs-geosearch-2.8.1.jar!/applicationContext.xml]: Initialization of bean failed; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Class' for property 'componentClass'; nested exception is java.lang.IllegalArgumentException: Cannot find class [org.geoserver.geosearch.web.GeoSearchLayerConfigPanel]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:527)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
[...]
Caused by: org.springframework.beans.TypeMismatchException: Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Class' for property 'componentClass'; nested exception is java.lang.IllegalArgumentException: Cannot find class [org.geoserver.geosearch.web.GeoSearchLayerConfigPanel]
[...]
Caused by: java.lang.IllegalArgumentException: Cannot find class [org.geoserver.geosearch.web.GeoSearchLayerConfigPanel]


```

**Comment by landryb** [comment]
I remember geosearch extension was badly breaking REST API in GS

**Comment by landryb** [comment]
Cf #616

**Comment by fvanderbiest** [comment]
GeoServer 2.8.1 builds and runs on sdi.georchestra.org with -Papp-schema,mysql,jp2k,gdal,control-flow,wps,querylayer,monitor,security,xslt,inspire,css,csw,dxf,libjpeg-turbo,spatialite,mbtiles,vectortiles

**Comment by fvanderbiest** [comment]
GeoServer 2.8.1 builds and runs on sdi.georchestra.org with -Papp-schema,arcsde,h2,sqlserver,mysql,db2,jp2k,gdal,feature-pregeneralized,imagemap,excel,charts,control-flow,wps,querylayer,teradata,monitor,security,xslt,inspire,css,csw,dxf,wcs2_0-eo,libjpeg-turbo,app-schema,spatialite,mbtiles,vectortiles

**Comment by fvanderbiest** [comment]
Diff with Landry's extensions: authkey,feature-aggregate,pyramid,importer,sldservice,colormap,geopkg

**Comment by fvanderbiest** [comment]
GeoServer 2.8.1 builds and runs on sdi.georchestra.org with -Papp-schema,arcsde,h2,sqlserver,mysql,db2,jp2k,gdal,feature-pregeneralized,imagemap,excel,charts,control-flow,wps,querylayer,teradata,monitor,security,xslt,inspire,css,csw,dxf,wcs2_0-eo,libjpeg-turbo,app-schema,spatialite,mbtiles,vectortiles,authkey,feature-aggregate,pyramid,sldservice,colormap,geopkg

**Comment by landryb** [comment]
I have a geoserver/webapp/pom.xml diff somewhere to add importer/colormap/geopkg profiles/extensions and fix sldservice naming - not sure it's relevant/needed.

**Comment by fvanderbiest** [comment]
Now trying to build and run GeoServer with integrated GeoFence

**Comment by fvanderbiest** [comment]
It builds and runs.
https://sdi.georchestra.org/geoserver/web/?wicket:bookmarkablePage=:org.geoserver.geofence.web.GeofencePage looks good but https://sdi.georchestra.org/geoserver/web/?wicket:bookmarkablePage=:org.geoserver.geofence.web.GeofenceServerPage crashes with
```
org.apache.wicket.WicketRuntimeException: Can't instantiate page using constructor public org.geoserver.geofence.web.GeofenceServerPage()
	at org.apache.wicket.session.DefaultPageFactory.createPage(DefaultPageFactory.java:212)
	at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:57)
Caused by: java.lang.NullPointerException
	at org.hibernate.impl.SessionFactoryImpl.getClassMetadata(SessionFactoryImpl.java:805)
	at com.googlecode.genericdao.search.hibernate.HibernateMetadataUtil.get(HibernateMetadataUtil.java:92)
	at com.googlecode.genericdao.dao.jpa.JPABaseDAO._all(JPABaseDAO.java:206)
	at com.googlecode.genericdao.dao.jpa.GenericDAOImpl.findAll(GenericDAOImpl.java:61)
	at org.geoserver.geofence.core.dao.impl.RuleDAOImpl.findAll(RuleDAOImpl.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy22.findAll(Unknown Source)
	at org.geoserver.geofence.services.RuleAdminServiceImpl.getAll(RuleAdminServiceImpl.java:193)
	at org.geoserver.geofence.web.GeofenceRulesModel.<init>(GeofenceRulesModel.java:79)
	at org.geoserver.geofence.web.GeofenceServerPage.<init>(GeofenceServerPage.java:59)
```

**Comment by fvanderbiest** [comment]
Here's what I did:
 * compile GeoServer with integrated geofence using jenkins on sdi.georchestra.org, with profiles -Ppyramid,inspire,wps,control-flow,geofence,geofence-server
 * create a geofence schema in the georchestra db on localhost:6432, populated with https://gist.github.com/fvanderbiest/fb0a7ee4c3971be4c2fa (a sensible adaptation of https://github.com/geoserver/geofence/blob/master/doc/setup/sql/001_setup_db.sql and https://github.com/geoserver/geofence/blob/master/doc/setup/sql/002_create_schema_postgres.sql for our setup)
 * set the georchestra.datadir variable to a folder with a fresh clone of https://github.com/georchestra/datadir (and checked tomcat is granted access to it)
 * set -DGEOSERVER_XSTREAM_WHITELIST=org.geoserver.geoserver.authentication.auth.GeoFenceAuthenticationProviderConfig to the tomcat hosting the geoserver webapp

The same error happens again.

**Comment by fvanderbiest** [comment]
I even started geoserver from a truely fresh minimal datadir (https://github.com/geoserver/geoserver/tree/2.8.x/data/minimal), with an added filter to interpret the security-proxy headers (file ```/security/filter/georchestra/config.xml``` registered in ```/security/config.xml``` as per https://gist.github.com/fvanderbiest/ad21ec926f0df1c50a78 )

... but with no better luck.

BTW, I see that geofence has created a ```geofence``` folder in this fresh geoserver data dir, with a ```geofence_db``` subfolder, hosting several ```.db``` files, the most important probably being geofence.data.db (400kB). I fear that geofence does not take into account the https://github.com/georchestra/datadir/blob/master/geofence/geofence.properties file for some reason.

**Comment by fvanderbiest** [comment]
Well, I think I should open another issue for this. It's not related to CI build anymore.
