### ISSUE TITLE
NPE with GeoFence 3 and GeoServer 2.8.1 on GeofenceServerPage

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1190]
The issue was originally described in https://github.com/georchestra/georchestra/issues/1185#issuecomment-173252341 but I'm porting it here.

Here's what I did:
 * compile GeoServer with integrated geofence using jenkins on sdi.georchestra.org, with profiles -Ppyramid,inspire,wps,control-flow,geofence,geofence-server
 * create a geofence schema in the georchestra db on localhost:6432, populated with https://gist.github.com/fvanderbiest/fb0a7ee4c3971be4c2fa (a sensible adaptation of https://github.com/geoserver/geofence/blob/master/doc/setup/sql/001_setup_db.sql and https://github.com/geoserver/geofence/blob/master/doc/setup/sql/002_create_schema_postgres.sql for our setup)
 * set the georchestra.datadir variable to a folder with a fresh clone of https://github.com/georchestra/datadir (and checked tomcat is granted access to it)
 * set -DGEOSERVER_XSTREAM_WHITELIST=org.geoserver.geoserver.authentication.auth.GeoFenceAuthenticationProviderConfig to the tomcat hosting the geoserver webapp

/geoserver/web/?wicket:bookmarkablePage=:org.geoserver.geofence.web.GeofenceServerPage crashes with
```
org.apache.wicket.WicketRuntimeException: Can't instantiate page using constructor public org.geoserver.geofence.web.GeofenceServerPage()
	at org.apache.wicket.session.DefaultPageFactory.createPage(DefaultPageFactory.java:212)
	at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:57)
...
Caused by: java.lang.NullPointerException
	at org.hibernate.impl.SessionFactoryImpl.getClassMetadata(SessionFactoryImpl.java:805)
	at com.googlecode.genericdao.search.hibernate.HibernateMetadataUtil.get(HibernateMetadataUtil.java:92)
	at com.googlecode.genericdao.dao.jpa.JPABaseDAO._all(JPABaseDAO.java:206)
	at com.googlecode.genericdao.dao.jpa.GenericDAOImpl.findAll(GenericDAOImpl.java:61)
	at org.geoserver.geofence.core.dao.impl.RuleDAOImpl.findAll(RuleDAOImpl.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy22.findAll(Unknown Source)
	at org.geoserver.geofence.services.RuleAdminServiceImpl.getAll(RuleAdminServiceImpl.java:193)
	at org.geoserver.geofence.web.GeofenceRulesModel.<init>(GeofenceRulesModel.java:79)
	at org.geoserver.geofence.web.GeofenceServerPage.<init>(GeofenceServerPage.java:59)
```

I even started geoserver from a truely fresh minimal datadir (https://github.com/geoserver/geoserver/tree/2.8.x/data/minimal), with an added filter to interpret the security-proxy headers (file ```/security/filter/georchestra/config.xml``` registered in ```/security/config.xml``` as per https://gist.github.com/fvanderbiest/ad21ec926f0df1c50a78 )

... but with no better luck.

BTW, I see that geofence has created a ```geofence``` folder in this fresh geoserver data dir, with a ```geofence_db``` subfolder, hosting several ```.db``` files, the most important probably being ```geofence.data.db``` (400kB). I fear that geofence does not take into account the https://github.com/georchestra/datadir/blob/master/geofence/geofence.properties file for some reason.

**Comment by fvanderbiest** [comment]
We may need to add -Dgeofence-ovr=file:/PATH/TO/OVR/FILE.properties, see  https://github.com/geoserver/geofence/wiki/GeoFence-configuration

**Comment by pmauduit** [comment]
I don't think so, because of the georchestra integration, it should use the ones from the georchestra datadir.

Anyway, the NPE seems related to a database access, which let me think that this is due to a db misconfiguration, I will check it more thoroughly:

```
    @Override
    public List<ShortRule> getAll() {
        List<Rule> found = ruleDAO.findAll();
        return convertToShortList(found);
    }
```

**Comment by pmauduit** [comment]
NPE actually related to misconfiguration (well, not exactly from our "fault" directly), a commit from my side already tried to address it:

https://github.com/georchestra/geoserver/blob/2.8.1-georchestra-work-geosolutions/src/community/geofence-server/src/main/resources/applicationContext.xml#L61

But ... geofence also activates extra dependencies for which we do not recompile the source (not sure if we should anyway):
 
https://github.com/geoserver/geofence/blob/master/src/services/core/persistence/src/main/resources/applicationContext-geofenceDatasource.xml#L51

Both jars ending in the actual war, we cannot predict which one will override before the other at the webapp instantiation ... Hence I propose to rename our georchestra datadir's file to find a way to respect both conventions.

**Comment by fvanderbiest** [comment]
> Hence I propose to rename our georchestra datadir's file to find a way to respect both conventions.

OK

**Comment by pmauduit** [comment]
Done with https://github.com/georchestra/datadir/commit/d3cc0064716c47594d8d47c1c20f634766432188 (docker-official branch from the datadir repository)

**Comment by pmauduit** [comment]
shall we consider a try with gs 2.8.2 instead of 2.8.1 ? http://blog.geoserver.org/2016/01/23/geoserver-2-8-2-released/?utm_source=twitterfeed&utm_medium=twitter

**Comment by fvanderbiest** [comment]
Might be worth it, yes.

**Comment by pmauduit** [comment]
Definitely too hard to merge between Niel's modifications and GeoSolution's ones. I'll keep a 2.8.2-georchestra branch for later retries, but I consider keeping 2.8.1 for now.

**Comment by fvanderbiest** [comment]
OK !

**Comment by pmauduit** [comment]
Related issue: https://github.com/georchestra/georchestra/issues/1135

**Comment by pmauduit** [comment]
Giving a second chance to get 2.8.2 working:

- PR geoserver/1335 merged into master, not 2.8.x
- PR geoserver/1348 merged into master, not 2.8.x
- PR geoserver/1352 merged into master, not 2.8.x

All other PR from GeoSolutions have been ported into 2.8.x and hence are available in 2.8.2 (geoserver/1380, geoserver/1379, geoserver/1378).

Merging by hand, by cherry-picking missing commits and fixing the conflicts, here is the current status:

```
1288c6e669a2f39c79d07679449cdd1d19319f8b OK
0dd0c020832c61a37136d137cadce30623dd19e2 OK
d015295305a6168ebf4b0cc7fbfb6bbba762956b
Deleted by us: CSWLayerConfig.java 
Deleted by them: AbstractLayerGroupPage.java <--- to be restored ?
Both modified: LayerGroupEditPageTest.java <--- ?

425e76e30395ac2288eee49546ba2bbbd06d946b OK
a99925979352b3ee3326c5b546336fcd36214ec9 OK
4ff5e0df45083b982e8212dfdc889fd59d0dbf4e OK
1f18dccf8642c2c2758eae62d3244ddd99ff08f7 OK
ffc165b90258886d0a97c22e327d016225605a9c OK
```

**Comment by pmauduit** [comment]
Work almost ready to be merged here: https://github.com/georchestra/geoserver/tree/2.8.2-georchestra

Utests: testsuite OK (almost, it sometimes fails for messing up resources not cleaned properly)
Runtime: TODO

**Comment by pmauduit** [comment]
Probable missing commit: bumping to a newer version of git maven plugin

**Comment by pmauduit** [comment]
Still some bugs with the layer groups management, since we are in between 2 versions (2.8.2 and 2.9.x). After a layergroup creation, the layer groups page crashes, and it requires a GS relaunch to have the interface working back.

**Comment by fvanderbiest** [comment]
Gosh, this is critical.
What can we do to address this issue ?

**Comment by pmauduit** [comment]
Move to 2.9 ? Asking niels for support ? I feel that I am close but I am pretty new to wicket / gs codebase ...

**Comment by fvanderbiest** [comment]
We'll stick to 2.8.x for 15.12

**Comment by pmauduit** [comment]
For the record, C2C subcontracted Niels to fix some geofence integration issues, he worked in his own branch (https://github.com/geoserver/geoserver/pull/1460) targetting master, but his commits were easily cherry-pickable in our fork.

To be  tested now.

**Comment by pmauduit** [comment]
> STILL TODO: change the submodule commit in the georchestra repository once fully tested.

Done with https://github.com/georchestra/georchestra/commit/0cf77caa96b0b96507d8c1520d63c25b3cb14277
