### ISSUE TITLE
extraction failure on public layers

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1192]
With 
```json
{
    "emails": ["me@provider.com"],
    "globalProperties": {
        "projection": "EPSG:4326",
        "resolution": 10,
        "rasterFormat": "geotiff",
        "vectorFormat": "shp",
        "bbox": {
            "srs": "EPSG:4326",
            "value": [-11.921241050119, 29.964200477327, 26.742243436754, 55.095465393795]
        }
    },
    "layers": [{
        "projection": null,
        "resolution": null,
        "format": null,
        "bbox": {
            "srs": "EPSG:4326",
            "value": [-10.617801218084, 37.327993172827, 14.623918225983, 57.836890221132]
        },
        "owsUrl": "https://sdi.georchestra.org/geoserver/wfs?",
        "owsType": "WFS",
        "layerName": "geor:menhirs"
    }]
}
```
being posted to https://sdi.georchestra.org/extractorapp/extractor/initiate (up-to-date proxy & extractorapp & geoserver master)

```
java.lang.RuntimeException: java.util.NoSuchElementException: Could not aquire feature:java.io.IOException: org.xml.sax.SAXException: Server returned HTTP response code: 401 for URL: https://sdi.georchestra.org/geoserver/wfs?service=WFS&version=1.0.0&request=DescribeFeatureType&typeName=geor%3Amenhirs
java.io.IOException: Server returned HTTP response code: 401 for URL: https://sdi.georchestra.org/geoserver/wfs?service=WFS&version=1.0.0&request=DescribeFeatureType&typeName=geor%3Amenhirs
	at org.georchestra.extractorapp.ws.extractor.WfsExtractor$1.exceptionOccurred(WfsExtractor.java:230)
	at org.geotools.data.DataUtilities.visit(DataUtilities.java:2804)
	at org.geotools.data.store.DataFeatureCollection.accepts(DataFeatureCollection.java:458)
	at org.georchestra.extractorapp.ws.extractor.FileFeatureWriter.generateFiles(FileFeatureWriter.java:73)
	at org.georchestra.extractorapp.ws.extractor.WfsExtractor.extract(WfsExtractor.java:257)
	at org.georchestra.extractorapp.ws.extractor.task.ExtractionTask.extractWfsLayer(ExtractionTask.java:394)
	at org.georchestra.extractorapp.ws.extractor.task.ExtractionTask.run(ExtractionTask.java:95)
```

**Comment by pmauduit** [comment]
We already encountered this issue earlier when working on extractorapp testsuite, it reveals that we are missing some integration tests.

Since it is related to geotools internals, tweaking the User-Agent might be more complicated than @Vampouille 's previous work. It should not be a big deal to solve if we have the sources of the WFS feature datastore, but I think we should definitely think of a geotools bump (to avoid using a custom unmaintained version in georchestra)

**Comment by Vampouille** [comment]
This PR : https://github.com/georchestra/georchestra/pull/1228 should fix extraction failure

**Comment by fvanderbiest** [comment]
Indeed

**Comment by fvanderbiest** [comment]
Testing this morning on sdi.georchestra.org, broken again :-(

**Comment by fvanderbiest** [comment]
Still an issue after https://github.com/georchestra/georchestra/issues/1267 has been merged.

https://github.com/fvanderbiest/extractorapp-testing reports no error for sdi.georchestra.org / ci:unprotectedVectorLayer but the folder contains only the bbox, not the data.

**Comment by pmauduit** [comment]
I just tried the layer and encountered no issue to extract, could you please retry ?

**Comment by fvanderbiest** [comment]
Indeed, there seems to be a specific issue when using extractrapp-testing.

**Comment by fvanderbiest** [comment]
Got it, the bbox was too tiny to include a single feature !
It's now fixed.

**Comment by pmauduit** [comment]
:)
