### ISSUE TITLE
mfapp - datadir regression on direct linking to WMC

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#1193]
In 15.06, contexts could be stored in the webapp, in contexts/ subdir. Hotlinking to a context was done with `/mapfishapp/?wmc=contexts/my.wmc`.

Since the move to datadir and the `/ws` service handling contexts, they can be stored in `datadir/mapfishapp/context/`, and direct linking is done via `/mapfishapp/?wmc=context/my.wmc` - would be nice to have backwards-compatible url-rewriting to support the previous url parameters, probably with a 302 redirect to `context/` removing the extra s.

Dunno if it has to be fixed serverside in https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/webapp/WEB-INF/urlrewrite.xml or in the client-side js parsing the wmc parameter (in https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/webapp/app/js/GEOR_mapinit.js#L523 ?).

**Comment by landryb** [comment]
Of course a rewrite rule can be done in the front reverse proxy but it's nicer if georchestra handles the migration by itself.

**Comment by landryb** [comment]
Adding a rule to `urlrewrite.xml` works:
```
    <rule>
        <from>^/contexts/(.*)$</from>
        <to type="forward" last="true">/ws/context/$1</to>
    </rule>
```
but:
  * dunno how that'd work for non-datadir mode - to me in non-datadir mode the /ws/contexts/ controller still reads contexts from the webapp dir ?
  * dunno if that should be a redirect to teach the client that contexts/ is deprecated ?

so, more testing needed :)

**Comment by pmauduit** [comment]
> to me in non-datadir mode the /ws/contexts/ controller still reads contexts from the webapp dir ?

yes, it resolves against the webapp directory:
https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/java/org/georchestra/mapfishapp/ws/ContextController.java#L142

So in both cases (non datadir, and datadir) it should now pass via the controller.


> dunno if that should be a redirect to teach the client that contexts/ is deprecated ?

Forward sounds good to me, no need to deprecate
