### ISSUE TITLE
header - admin link issue

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1200]
![capture du 2016-01-27 11 32 48](https://cloud.githubusercontent.com/assets/265319/12610763/b5e48a22-c4e9-11e5-9d12-dd1960d23ff7.png)

**Comment by landryb** [comment]
https://github.com/georchestra/georchestra/blob/master/header/src/main/filtered-resources/WEB-INF/jsp/index.jsp#L298 should match the admin key in https://github.com/georchestra/georchestra/blob/master/header/src/main/resources/_header/i18n/index_fr.properties - are the lang properties files properly installed ?

**Comment by fvanderbiest** [comment]
Not witnessed anymore, closing.

**Comment by fvanderbiest** [comment]
Reproduced for Rennes test deploy, with the `users` and `admin` links.
Would be good to know where this comes from and how to get rid of it...

![capture du 2016-03-25 14 07 54](https://cloud.githubusercontent.com/assets/265319/14044632/087078ba-f293-11e5-918b-fe8ca9768d9e.png)

**Comment by fvanderbiest** [comment]
Indeed, missing keys when deployed, yet they are in the sources ...

$ cat tomcat_base/webapps/header/WEB-INF/classes/_header/i18n/index_fr.properties 
### Translation file
go.home=retourner à l'accueil
logo=geOrchestra
catalogue=catalogue
viewer=visualiseur
extractor=extracteur
services=services
logout=déconnexion
login=connexion
actus=actus
fichiers=fichiers

**Comment by fvanderbiest** [comment]
FIxed, this is an issue with local files in the Rennes config profile.
