### ISSUE TITLE
copyright notice in every file

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1206]
We should add the copyright notice in every source file, eg:
```
# Copyright (C) 2009-2016 by XXX
#
# This file is part of geOrchestra.
#
# geOrchestra is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# geOrchestra is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# geOrchestra.  If not, see <http://www.gnu.org/licenses/>.
```

**Comment by landryb** [comment]
Quick poll - so far only `{analytics,catalogapp,extractorapp,mapfishapp}/src/main/webapp/app/js/GEOR*` have this section, im not even sure all of them have it, and it only mentions the GPL without specifying the version - the Copyright lines dont have the year.

**Comment by fvanderbiest** [comment]
Yes, we are currently missing several items.
In addition, the server-side code misses the copyright notice in every source file.

**Comment by fvanderbiest** [comment]
I think i'm done with it.

**Comment by landryb** [comment]
A full build with all your PRs merged into a master twig went fine here - but i really think you should commit your script to the repo :)

**Comment by fvanderbiest** [comment]
All done !
