### ISSUE TITLE
Get rid of moduleX/src/deb/resources

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1211]
As we said in https://github.com/georchestra/georchestra/pull/1178#issuecomment-171581789, we should get rid of moduleX/src/deb/resources but dynamically generate these resources during the debian package build cycle.

**Comment by pmauduit** [comment]
WIP: https://github.com/pmauduit/georchestra/tree/issue-1211

- [ ] analytics
- [ ] cas
- [ ] catalogapp
- [ ] downloadform
- [ ] extractorapp
- [ ] geonetwork
- [ ] geoserver
- [ ] geowebcache
- [ ] header
- [ ] ldapadmin
- [ ] mapfishapp
- [ ] security-proxy

**Comment by landryb** [comment]
Fwiw, i like this idea :) one less copy of every configurable file !

**Comment by pmauduit** [comment]
GN done in https://github.com/pmauduit/geonetwork/tree/georchestra-gn3-3.0.x-issue-1211
