### ISSUE TITLE
Geoserver - getcapabilities with layergroups fail when inspire extension is enabled

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#1232]
I have to retest, but when i tried to deploy 2.8.2 to production it failed to return me a getcapabilities with layergroups where 2.8.1 worked. Will add the full trace if i reproduce again, but the traceback pointed to one of niel's commits related to layergroups.

```
11:01 < gaston_ > ERROR [geoserver.ows] -
11:01 < gaston_ > java.lang.AbstractMethodError: org.geoserver.inspire.wms.WMSExtendedCapabilitiesProvider.overrideScaleDenominators(Lorg/geoserver/catalog/PublishedInfo;Lorg/geotools/util/NumberRange;)Lorg/geotools/util/NumberRange;
11:01 < gaston_ > ouch
11:01 < gaston_ > pas beau l'extension inspire dans gs 2.8.2...
11:04 < gaston_ > je pige pas j'ai pas coché les cases pour l'extended capabilities pourtant...
11:06 < gaston_ > ah ca a l'air un pbm lié a https://github.com/geoserver/geoserver/pull/1352
11:08 < gaston_ > un getcap wfs marche, un getcap wms est pété
```

Looked related to https://github.com/georchestra/geoserver/commit/48a3f73b8aff28c1aae213b07fee971be4535177

**Comment by fvanderbiest** [comment]
Works here https://sdi.georchestra.org/geoserver/ows?service=wms&version=1.3.0&request=GetCapabilities with layergroup dem:altitude

But no specific scale denominator was set here.

**Comment by landryb** [comment]
Pretty sure no scaledenom was set on the layergroup where i had issues, nor on the composing layers... which was the strange part.

**Comment by landryb** [comment]
Cant reproduce right now with gs 2.8.2 from debian packages, but again, dunno which extensions are enabled in this build.

**Comment by pmauduit** [comment]
> Cant reproduce right now with gs 2.8.2 from debian packages, but again, dunno which extensions are enabled in this build.

No extension is enabled to build the debian package on the CI.

**Comment by landryb** [comment]
Fully reproducible now, i just need to drop gs-inspire-2.8.2.jar in geoserver's WEB-INF/lib dir, and the exception is triggered. Is inspire extension enabled on sdi.georchestra.org ?

**Comment by fvanderbiest** [comment]
> Is inspire extension enabled on sdi.georchestra.org ?

nope

**Comment by fvanderbiest** [comment]
I could reproduce the exact same error with GeoServer 2.8.3 two days ago.

**Comment by fvanderbiest** [comment]
This is critical IMO but no time allocated for debugging => bumping

**Comment by fvanderbiest** [comment]
We fixed it by compiling the inspire extension with geoserver rather than dropping an incompatible jar in the libs folder. There's no issue here ;-)
