### ISSUE TITLE
[geonetwork3] use a separate database/hibernate_sequence not created

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#1235]
Trying to deploy a fresh georchestra instance with GN3, stumbling upon https://github.com/geonetwork/core-geonetwork/issues/1081 again. I think we may need to change the documentation to explain geonetwork needs its own separate database, or find how to tell geonetwork database config to use a distinct schema (and check if the hibernate sequence is created there...)

**Comment by landryb** [comment]
According to the interwebs, there are some solutions to set the schema, but that depends on the postgresql version.. eg http://stackoverflow.com/questions/4168689/is-it-possible-to-specify-schema-when-connecting-to-postgres-with-jdbc

http://www.bitsandpix.com/entry/postgresql-jdbc-url-to-connect-to-a-schema/ seems the 'best' option if it works.

**Comment by landryb** [comment]
Trying w/
```
postgres=# alter user geonetwork set search_path to 'geonetwork,public';

```
But that still doesnt explain why the sequence isnt created. I dont have it in the public schema either.

**Comment by landryb** [comment]
It's even worse with this, hbm2ddl doesnt know in which schema tables should be created.. :
```
ERROR [org.hibernate.tool.hbm2ddl.SchemaUpdate] - ERROR: no schema has been selected to create in
```

**Comment by landryb** [comment]
Same thing with adding ?currentSchema to jdbcURL in `webapps/geonetwork/WEB-INF/config-db/postgres.xml`
```
<constructor-arg value="jdbc:postgresql://${jdbc.host}:5432/${jdbc.database}?currentSchema=geonetwork"/>
```

At this point, i think we're better off changing the doc to tell the admin to setup/create a distinct database for geonetwork.

**Comment by landryb** [comment]
Of course, that works much better when using a distinct database. Just a heads up, since we use the postgis spatial index by default (which is still horribly broken by https://github.com/geonetwork/core-geonetwork/issues/1379) - one shouldnt forget to load postgis extension in this new database.

**Comment by pmauduit** [comment]
I tried from my side, and I have no trouble having a geonetwork user with its own schema: I don't have any hibernate sequence created in the public schema, everything goes in the expected schema, even the spatialindexes (if correctly configured in the datadir though, still in schema public for now as the default).

**Comment by landryb** [comment]
Is the hibernate_sequence created in the geonetwork schema ?

**Comment by pmauduit** [comment]
yes:

```
georchestra=# \ds geonetwork.
                     List of relations
   Schema   |         Name         |   Type   |   Owner    
------------+----------------------+----------+------------
 geonetwork | hibernate_sequence   | sequence | geonetwork
 geonetwork | spatialindex_fid_seq | sequence | geonetwork
(2 rows)

```

**Comment by fvanderbiest** [comment]
To close then ?

**Comment by landryb** [comment]
I have to retest a full deploy, but for me it was failing at some point. Maybe something in my playbook.

**Comment by MaelREBOUX** [comment]
Dont' know if it is linked but you can't have several postgresql sequences with the same name in the same database. Even if they are in differents schemas.
So : one DB per GeoNetwork. Mandatory.

See here :  http://osgeo-org.1560.x6.nabble.com/create-scripts-in-3-0-tt5205280.html#a5213599

**Comment by pmauduit** [comment]
Tested several different scenarios here, working fine with the current configuration modification: https://github.com/georchestra/datadir/pull/15

**Comment by landryb** [comment]
Works fine for me too on a clean deploy of GN3 with https://github.com/pmauduit/config/commit/92aceda8e09f61345eb8144922ad120d0615c87e applied to the georchestra datadir, the hibernate sequence is correctly created in the geonetwork schema.
```
georchestra=> \ds+ geonetwork.*
                                  List of relations
   Schema   |         Name         |   Type   |   Owner    |    Size    | Description
------------+----------------------+----------+------------+------------+-------------
 geonetwork | hibernate_sequence   | sequence | geonetwork | 8192 bytes |
 geonetwork | spatialindex_fid_seq | sequence | geonetwork | 8192 bytes |

```

**Comment by pmauduit** [comment]
:+1:
