### ISSUE TITLE
Missing partitions_stat.sql file

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1245]
The release notes mention a partitions_stat.sql file, but I could not find it.

**Comment by Vampouille** [comment]
This should be fixed by f7ae89750dd9116eea13ced921a9a9aeb825d6d3
`partitions_stat.sql` has been renamed to `update.sql`

**Comment by fvanderbiest** [comment]
OK, thanks !

**Comment by fvanderbiest** [comment]
Will rename update.sql to update_to_15.12.sql

**Comment by fvanderbiest** [comment]
fixed with https://github.com/georchestra/georchestra/commit/571a2bdc8e68c188bde8aa47255a7b93fb174860
