### ISSUE TITLE
gn3 - remove or hide instance logo

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1247]
It is redundant with the SDI logo in the geOrchestra header

![screenshot from 2016-02-13 12-05-25](https://cloud.githubusercontent.com/assets/265319/13027316/3d8c3fb6-d24a-11e5-952c-61759912db48.png)

**Comment by fvanderbiest** [comment]
... and it's broken by default :-(

**Comment by fvanderbiest** [comment]
It's easy to set it with /geonetwork/srv/fre/admin.console#/settings/logo but I do not see the use of having yet another logo... 

What do others think about it ?

**Comment by pmauduit** [comment]
Something fails at init process of gn, where it tries to copy the default logo into the datadir, should not be a big deal to fix, though.

**Comment by fvanderbiest** [comment]
removed with https://github.com/georchestra/geonetwork/pull/29

**Comment by landryb** [comment]
The instance logo has to be set anyway in the backend, because it's use when displaying catalog provenance for a metadata (local or harvested/remote)

**Comment by fvanderbiest** [comment]
Yes, people can still do it. It's just not displayed anymore in the top bar.
