### ISSUE TITLE
gn3 - expired session

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1248]
![screenshot from 2016-02-13 12-56-31](https://cloud.githubusercontent.com/assets/265319/13027456/46ea71f2-d251-11e5-8941-d58d81c83b6f.png)

... should not happen since the session is managed by our security-proxy

**Comment by pmauduit** [comment]
To be customized here:
https://github.com/georchestra/geonetwork/blob/georchestra-gn3-3.0.x/web/src/main/filters/prod.properties#L19

(time is in minutes in the file, GN seems to display it in seconds).

Even if the session is managed by the SP, there also is a session gn-side. The SP ensures the mapping between actual user and GN.

**Comment by fvanderbiest** [comment]
What should we put instead of 35 minutes ?
One day, as for the sec-proxy, or a bigger value ?

**Comment by Vampouille** [comment]
This PR should fixed session expiration issue on geonetwork : https://github.com/georchestra/geonetwork/pull/31

**Comment by Vampouille** [comment]
It's available in master : https://github.com/georchestra/georchestra/commit/66bb0eea7871c06fe01810bf0240610c3a9789b2

**Comment by fvanderbiest** [comment]
Thanks !
