### ISSUE TITLE
Geonetwork- Don't redirect to cas

### ISSUE THREAD

**Issue by vdorut** [georchestra/georchestra#1258]
https://sdi.georchestra.org/geonetwork/monitor redirect to this page when you are not login

![screenshot from 2016-02-17 11 29 55](https://cloud.githubusercontent.com/assets/9655282/13106862/cbe78194-d56a-11e5-97e7-3615c7eba2eb.png)

**Comment by fvanderbiest** [comment]
Same with GeoServer, indeed.
Instead they should reload the page with an added '?login' or '&login' string which is interpreted by the SP.

**Comment by pmauduit** [comment]
on geonetwork 3, adding this following snippet:

```
+
+  <!-- redirect to cas when need to be logged in -->
+  <bean id="authenticationEntryPoint"
+    class="jeeves.config.springutil.JeevesNodeAwareLoginUrlEntryPoint">
+    <constructor-arg index="0" value="/?login" />
+  </bean>
+
```

at the end of https://github.com/georchestra/datadir/blob/master/geonetwork/config/config-security-georchestra.xml should do the trick (rapidly tested, but would deserve more in-depth tests)

**Comment by pmauduit** [comment]
For geonetwork 2, who cares ... :) the login.form in the screenshot was still a jeeves service definition (see https://github.com/georchestra/geonetwork/blob/georchestra-15.06/web/src/main/webapp/WEB-INF/config.xml#L1015), I guess we should introduce a new class which fires a redirect or hack into the login-form.xsl stylesheet.

**Comment by fvanderbiest** [comment]
> on geonetwork 3, adding this following snippet
> at the end of https://github.com/georchestra/datadir/blob/master/geonetwork/config/config-security-georchestra.xml should do the trick (rapidly tested, but would deserve more in-depth tests)

Done on 18.06 with https://github.com/georchestra/geonetwork/pull/59 but with another approach.
@pmauduit your proposal, if relevant, was more elegant

**Comment by pmauduit** [comment]
So what is expected now on this issue ?

Trying with the default docker composition, it seems that both modifications are actually needed:

```
# hitting a non existent webservice on GN (missing /srv/eng/)
% curl -i 'http://localhost:8080/geonetwork/csw/?service=CSW&version=2.0.2&request=GetCapabilities'
HTTP/1.1 302 Found
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Thu, 01 Jan 1970 00:00:00 GMT
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Set-Cookie: JSESSIONID=node01x3nkshkpvo7nijcu6tzclmzo0.node0;Path=/
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.4.7.v20170914)
Location: http://localhost:8080/geonetwork/login.jsp;jsessionid=node0naluzjyiqw0f15cvhkeuhr2ai0.node0?node=srv
Content-Length: 0


```

**Comment by fvanderbiest** [comment]
> So what is expected now on this issue ?

Expected: accessing a protected page from geonetwork (eg /geonetwork/srv/fre/admin.console#/tools) redirects to the same url with `?login` smartly added (ie before the `#`char) so that the user is redirected to `/cas/login` then to the originally requested page on successful login.

Current behavior: 
/geonetwork/srv/fre/admin.console#/tools -> /geonetwork/login.jsp?node=srv&failure=true#/tools

**Comment by pmauduit** [comment]
With my modification, it is partially the correct behaviour: redirected onto cas, but after successful authentication, it finishes onto the main homepage of gn.

**Comment by fvanderbiest** [comment]
> With my modification

Can you push it to the datadir ? Thanks

**Comment by pmauduit** [comment]
By rethinking of it, I think we don't need the custom class from GeoNetwork `jeeves.config.springutil.JeevesNodeAwareLoginUrlEntryPoint`, but better off using the original class from Spring-security: `org.springframework.security.web.authentication.LoginUrlAuthenticationEntryPoint`, as we don't use the multinode system from GN.

**Comment by pmauduit** [comment]
Also works with the above class, tested on sandbox
