### ISSUE TITLE
docker ldap - mail & cn not indexed

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1259]
ldap_1              | 56c45b5b <= bdb_substring_candidates: (mail) not indexed
ldap_1              | 56c45b5c <= bdb_substring_candidates: (cn) not indexed

Funny because I thought we fixed that

**Comment by landryb** [comment]
Was https://github.com/georchestra/LDAP/pull/7 / #881

**Comment by landryb** [comment]
Should be indexed, according to https://github.com/georchestra/georchestra/blob/master/ldap/bootstrap.ldif#L10

**Comment by Vampouille** [comment]
With docker installation, `bootstrap.ldif` file is not used. Instead we use environment variables to configure admin account : https://hub.docker.com/r/dinkel/openldap/

Maybe we also need to check authorization and others things define in `bootstrap.ldif`

**Comment by fvanderbiest** [comment]
+1, thanks

**Comment by fvanderbiest** [comment]
We should have a look at https://github.com/dinkel/docker-openldap#prepopulate-with-data

**Comment by fvanderbiest** [comment]
Fixed with #1633
