### ISSUE TITLE
Date mismatch between debian:package and debian:publish target on jenkins

### ISSUE THREAD

**Issue by Vampouille** [georchestra/georchestra#1265]
When publishing deb package, jenkins tries to publish deb file with current date and time. It is not working when building at 13:05:59 and publishing at 13:06:02

**Comment by pmauduit** [comment]
We should find a file that is modified when the repository is updated, and set the following option in each debianPackage profile:

snapshotRevisionFile	deb.package.snapshotRevFile	When building snapshot packages, append the modification time of this file to the version number.	File	The default is to use the system time.

see http://debian-maven.sourceforge.net/usage.html.

**Comment by pmauduit** [comment]
Tried locally: it works well using:

```
+              <snapshotRevisionFile>${project.build.directory}</snapshotRevisionFile>
```

in the debianPackage configuration profile. PR to come ...

**Comment by pmauduit** [comment]
Should be solved now, closing.

**Comment by pmauduit** [comment]
It reappeared:

```
[WARNING] dpkg-deb: building package `georchestra-downloadform' in `/home/jenkins/jobs/georchestra-pipelines/jobs/georchestra-sandbox-pipeline/workspace/downloadform/target/georchestra-downloadform_16.12+201702031428+sandbox5-1_all.deb'.
[INFO] 
[INFO] --- debian-maven-plugin:1.0.6:deploy (default-cli) @ downloadform ---
[INFO] Skipping deployment of non-existent package: /home/jenkins/jobs/georchestra-pipelines/jobs/georchestra-sandbox-pipeline/workspace/downloadform/target/georchestra-downloadform_16.12+201702031515+sandbox5-1_all.deb
```

**Comment by pmauduit** [comment]
Seems fixed: It was missing a clean target (to remove & recreate target/), so the same date (modified date for target/ subdirectory) was used again and again.
