### ISSUE TITLE
header height in cas module is not 90px

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1273]

**Comment by pmauduit** [comment]
On which instance have you encountered the issue ? It looks kindof similar to https://github.com/georchestra/georchestra/issues/1234

**Comment by fvanderbiest** [comment]
> On which instance have you encountered the issue ?

On the ansible-generated vagrant box.

**Comment by fvanderbiest** [comment]
not witnessed anymore on docker master ...
