### ISSUE TITLE
analytics / ogc-server-stats - no logs are shown

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1279]
Analytics is empty, so either it is broken or the logger (ogc-server-statistics) is...

**Comment by pmauduit** [comment]
There are several problems:

- Logging on sdi.g.o seems broken since 2016-02-09 ; this is due to mismatch between slf4j and log4j libraries mixed together in the webapp.
- there actually is an issue with the db migration: if you look into tomcat-02's catalina.out:

```
[http-127.0.0.1-8280-5] ERROR org.georchestra.analytics - Caught exception while executing service: 
org.postgresql.util.PSQLException: ERREUR: droit refusé pour la relation ogc_services_log
```

**Comment by fvanderbiest** [comment]
Indeed, missing 
```
grant all on ogcstatistics.ogc_services_log to "www-data";
```

**Comment by fvanderbiest** [comment]
I'm handling the db migration, can you investigate the mismatch between slf4j and log4j libraries ?
Thanks @pmauduit

**Comment by Vampouille** [comment]
Maybe, we can change owner of georchestra database to `www-data`. This could simplify installation and allow webapp to update db schema.

**Comment by fvanderbiest** [comment]
Still an issue with sdi.geor.org: figures do not evolve when consuming local OGC services.

**Comment by Vampouille** [comment]
```
georchestra=> INSERT INTO ogcstatistics.ogc_services_log (user_name , date , service , layer , request , org , roles) VALUES ('anomymous', NOW(), 'WMS', 'test', 'getmap', '', NULL);
ERREUR:  droit refusé pour la séquence ogc_services_log_id_seq1
```
Il manque les droits de lecture sur la séquence

Il y a peut être aussi un soucis sur la séquence car il y a 2 séquences : 

* ogcstatistics.ogc_services_log_id_seq1 (last_value=1)
* ogcstatistics.ogc_services_log_id_seq (last_value=2890211)

La définition actuelle de la table utilise ogcstatistics.ogc_services_log_id_seq1 ce qui devrait générer des `id` en double

**Comment by Vampouille** [comment]
This second sequence is generated by upgrade procedure, so we need to modify new `ogc_services_log` to use old sequence and not create a new one.

**Comment by Vampouille** [comment]
```
ALTER TABLE ogcstatistics.ogc_services_log
   ALTER COLUMN id SET DEFAULT nextval('ogcstatistics.ogc_services_log_id_seq'::regclass);
```
This command should fix owner of sequence.

But user that insert records in ogcstatistics tables must be owner of `ogc_services_log` table in order to create child tables.
So we really need to change owner of database object because : 
* some webapp will try to create table based on spring annotation in java code
* ogcstatistics logging will try to create child table

**Comment by Vampouille** [comment]
This PR : https://github.com/georchestra/georchestra/pull/1287 should fix sequence used by new `ogc_services_log` table.
TODO : change owner

**Comment by Vampouille** [comment]
This new issue cover owner issues : https://github.com/georchestra/georchestra/issues/1288
