### ISSUE TITLE
All modules - reorganize the repositories / CI

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#1282]
Since the 15.12 has actually been released today, it is necessary to reorganize the way our auto-generated artifacts are managed:
- [x] Change the reprepro configuration on sdi.g.o
- [x] Change the yum repository configuration
- [x] Create a new job for generating 15.12 (stable) packages as well as docker images, (tagged 15.12)
- [x] Find a convenient way of keeping built artifacts in Jenkins (instead of using the workspace, which is not considered "stable" enough to serve files).

A little bit of the work has already been done for the reprepro configuration here: https://gist.github.com/pmauduit/5d0a694286bab6ce252f.

Since our debian packages have no hard "dependencies" on the system (we do not rely on glibc or whatever), we could use the distribution codename as a way to classify our deb packages, like master, 15.12 ... (see the previous gist).

For the YUM repository, I have no idea but it seems way more "manual" (copying rpm packages by hand in a shell script, launching the rpm repository manager on the directory, ...).

**Comment by landryb** [comment]
And i'll use it to point at branches in https://github.com/georchestra/ansible/blob/master/playbooks/georchestra.yml#L54 :)

**Comment by pmauduit** [comment]
Also noticed by @landryb on IRC: need to customize which branche from the datadir is checked out when compiling (depending on the version):

```
[INFO] Executing: /bin/sh -c cd /root/src/georchestra/cas-server-webapp/target/deb/etc/georchestra && git pull https://github.com/georchestra/datadir.git master
```

**Comment by pmauduit** [comment]
> need to customize which branche from the datadir is checked out when compiling (depending on the version):

Addressed with https://github.com/georchestra/georchestra/pull/1324 ; a 15.12 job which compiles the generic wars, deb + rpm packages, as well as the docker 15.12 images is on the go on the new build server provided by PauLLA.
