### ISSUE TITLE
Update the installation doc

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1284]
With the advent of the 15.12 release, https://github.com/georchestra/georchestra/blob/15.12/README.md should be reworked, putting the emphasis on generic artifacts rather than building from the sources ...

**Comment by catmorales** [comment]
We  have an error 404 on some wars.

**Comment by pmauduit** [comment]
The current build job on the official CI is far from perfect reguarding the generic war generation (it is ok with deb / rpm packages as they are saved elsewhere in the server's filesystem): if a build is currently running, there is no guarantee that the file will exist ; we are in the process to use a more stable solution to provide the generic wars (using a feature of Jenkins that will save the generated artifact in a safer place than the workspace, for instance).

See https://github.com/georchestra/georchestra/issues/1282 for more info about the coming work to be done

**Comment by fvanderbiest** [comment]
Done with main README revamped
