### ISSUE TITLE
docker images - missing required native libs + java bindings

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1285]
One can get inspiration from these older dockerfiles:
- https://github.com/georchestra/docker-ci/blob/master/geoserver/Dockerfile
- https://github.com/georchestra/docker-ci/blob/master/extractorapp/Dockerfile
- https://github.com/georchestra/docker-ci/blob/master/geowebcache/Dockerfile
- https://github.com/georchestra/docker-ci/blob/master/mapfishapp/Dockerfile

**Comment by pmauduit** [comment]
Related PR: https://github.com/georchestra/georchestra/pull/1338
