### ISSUE TITLE
GWC - unable to find GWC in version 1.8.0 on the maven repositories

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#1286]
Reported on IRC today:

```
[INFO] ------------------------------------------------------------------------
[INFO] Building geOrchestra GeoWebCache Web Application 15.12
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.geowebcache:gwc-web:jar:1.8.0 is missing, no dependency information available
```

`1.8.1` is available on boundlessgeo, but it might deserve a consolidation onto `build.georchestra.org` (even if I am not convinced by this method).

**Comment by fvanderbiest** [comment]
Should we update https://github.com/georchestra/georchestra/blob/15.12/geowebcache-webapp/pom.xml#L16 to 1.8.1 ?

**Comment by pmauduit** [comment]
@jusabatier is already trying this, it succeeds at compilation time, no idea how it behaves at runtime.
