### ISSUE TITLE
[mapfishapp] Correction de exemple l'adminCode1 dans la config de GEONAMES_FILTER

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#1290]
La recherche geonames vient subitement de tomber en panne chez nous... à cause de la fusion des régions :)

On utilisait jusqu'ici adminCode1: 98 pour l'Auvergne, qui a disparu des bases geonames au profit des nouvelles régions. Dans le commentaire de l'exemple (https://github.com/georchestra/georchestra/blob/15.12/mapfishapp/src/main/webapp/app/js/GEOR_config.js#L442) on propose 97 pour aquitaine ou A2 pour bretagne alors que maintenant selon le dump geonames ca serait plutot

```
FR.53	Brittany
FR.75	Aquitaine-Limousin-Poitou-Charentes
```

Je veux bien faire une PR pour fixer les commentaires, ou c'est plus simple de commit direct sur GEOR_config.js et sur GEOR_custom.js dans le repo datadir ?

**Comment by fvanderbiest** [comment]
Nice catch !
Tu peux commiter directement en mentionnant ce ticket, merci :-)

Attention, il faut prendre en compte 14.12, 15.06 et 15.12 actuellement, donc commit dans 14.12 et puis on mergera en cascade après.

**Comment by landryb** [comment]
Fixed in template/14.12, georchestra/14.12 and datadir/15.12.

**Comment by fvanderbiest** [comment]
Excellent, thanks again Landry.
Cascade merge OK.

**Comment by landryb** [comment]
No merge to datadir/master ?

**Comment by fvanderbiest** [comment]
Damn it ...

**Comment by fvanderbiest** [comment]
done
