### ISSUE TITLE
template submodule

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1292]
I'm considering removing the `config/configurations/template` submodule from the main repo, because it is a burden to maintain, and probably useless for most users

**Comment by pmauduit** [comment]
Ok, but the config.jar is still used as a dependency in most georchestra modules. Either:
- Provide the template one onto build.georchestra.org/maven
- Remove the config.jar build mechanism if dependency is not found ?

**Comment by fvanderbiest** [comment]
No, people wishing to build against the template config would be instructed to checkout `georchestra/template` in `config/configurations` manually...

**Comment by fvanderbiest** [comment]
Also I'd like to remove from the `template` config all files that are already provided by our datadir (eg: mapfishapp's GEOR_custom.js, contexts, addons, etc).

This means we would force people to work in "datadir" mode for 16.12.
The template repository would only allow for client-side file overrides.

Thoughts ?

**Comment by landryb** [comment]
Please kill non-datadir mode :)

**Comment by fvanderbiest** [comment]
> Also I'd like to remove from the template config all files that are already provided by our datadir (eg: mapfishapp's GEOR_custom.js, contexts, addons, etc).
> This means we would force people to work in "datadir" mode for 16.12.

Done with https://github.com/georchestra/template/pull/32 (to be reviewed though)

**Comment by landryb** [comment]
What's the template still useful for, besides customizing header ? (real question)
Could we just move header files to the datadir so that we can totally kill the build template ?

**Comment by fvanderbiest** [comment]
> customizing header ? (real question)

customizing the header could/should be done on the front server / rp IMO.

> What's the template still useful for ?

Nothing, just that it's not that easy to remove, so we're doing it piece by piece ;-)

**Comment by landryb** [comment]
> customizing the header could/should be done on the front server / rp IMO.

Erm... then why are we shipping a header webapp ?  and the header has some logic in it, and is behind the sec-proxy.. i dont really see how you can 'customize' the header outside of georchestra, if you want to retain the login integration.

**Comment by fvanderbiest** [comment]
> customizing the header

Sorry, I should have said "customizing the header image" ;-)
