### ISSUE TITLE
ldapadmin - login field is not used when creating a new user.

### ISSUE THREAD

**Issue by Vampouille** [georchestra/georchestra#1296]
Instead, login (uid ldap field) is computed from givenName and surname.
See: https://github.com/georchestra/georchestra/blob/15.12/ldapadmin/src/main/java/org/georchestra/ldapadmin/ws/backoffice/users/UsersController.java#L679

It happens when an administrator tries to create an account with the "New User" button.

**Comment by f-necas** [comment]
No more login field
