### ISSUE TITLE
mapfishapp - add ability to save keywords in WMC

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1305]
![capture du 2016-03-09 14 55 37](https://cloud.githubusercontent.com/assets/265319/13637321/0dae1e56-e607-11e5-8c10-c7b0ef5810b2.png)

Keywords are used server-side to provide context categorization, eg with https://github.com/georchestra/georchestra/blob/15.12/mapfishapp/src/main/java/org/georchestra/mapfishapp/ws/ContextController.java#L110-L151

**Comment by landryb** [comment]
Duplicate of #1166 ? :)

**Comment by fvanderbiest** [comment]
right, raising priority then ;-)

**Comment by fvanderbiest** [comment]
Contributions highly welcomed for this one :-)

**Comment by fvanderbiest** [comment]
was done ...

**Comment by landryb** [comment]
From git log -p, i suppose that was in 68e4b42364cd36a89f2b7f9d15b5fe1a28c67792 ?

**Comment by fvanderbiest** [comment]
Correct, thanks for the link !
(I was too lazy yesterday to look after it)
