### ISSUE TITLE
mapfishapp: better addons

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#132]
- handle more accurately interactions between activated tools
- preloading of an addon for a group of users, ~~or via GET parameters~~
- search in addon list
- group addons into submenus
- ~~possibility to insert the addon-generated component at a given place in the UI~~

**Comment by fvanderbiest** [comment]
Related PR for "possibility to insert the addon-generated component at a given place in the UI" is https://github.com/georchestra/georchestra/pull/894

**Comment by fvanderbiest** [comment]
Currently implementing "forced loading of addons via GET parameters" (thanks CIGALsace)

**Comment by fvanderbiest** [comment]
Example URL to load 2 addons: http://localhost:8287/mapfishapp/?addons=magnifier_0,annotation_0

**Comment by landryb** [comment]
Nice - how will it fit with the 'have addons depending on the profile or the user or the context' ? Still depending on OWSContext support ?

**Comment by fvanderbiest** [comment]
IMO, URL parameters override everything else.
For the rest, we'll see later ;-)
