### ISSUE TITLE
GeoServer 2.8.3

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1325]
Might be interesting to upgrade 15.12 to 2.8.3 since it contains nice fixes, see http://blog.geoserver.org/2016/03/23/geoserver-2-8-3-released/

**Comment by pmauduit** [comment]
Being resolved if the following PR is merged:
https://github.com/georchestra/georchestra/pull/1336

**Comment by Vampouille** [comment]
Work finished on #1336
