### ISSUE TITLE
mapfishapp - querying GN3 thesauri fails

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1333]
![capture du 2016-03-25 16 53 54](https://cloud.githubusercontent.com/assets/265319/14047786/31a35ace-f2aa-11e5-93bb-a99625903931.png)

When selecting a thesaurus from the list in mapfishapp, a request is made:

```
/geonetwork/srv/fre/xml.search.keywords?pNewSearch=true&pKeyword=*&pTypeSearch=1&pMode=consult&pThesauri=external.theme.geobretagne
```

... which fails on GN3 with 

```
org.jdom.IllegalAddException: Class java.lang.String is of unrecognized type and cannot be added
    org.jdom.ContentList.add(ContentList.java:142)
    org.jdom.ContentList.addAll(ContentList.java:292)
    org.jdom.ContentList.addAll(ContentList.java:262)
    org.jdom.Element.addContent(Element.java:825)
    org.fao.geonet.services.thesaurus.GetKeywords.exec(GetKeywords.java:153)
    org.fao.geonet.services.thesaurus.GetKeywords.deprecatedAPI(GetKeywords.java:89)
    sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:606)
```

**Comment by fvanderbiest** [comment]
@fgravin any idea ?

**Comment by fgravin** [comment]
Manifestement un problème avec la lib `jdom` ou bien un objet corrompu de notre côté.
Le paramètre `pThesauri` est converti par spring en `ArrayList<String>`, puis est ajouté en tant que `Collection` au noeud XML response.

Le code de l'ajout qui plante:
```java
        if (obj instanceof String) {  // String is OK to add as special case
            obj = new Text(obj.toString());  // wrap it as a Content
        } else {
            throw new IllegalAddException("Class " +
                         obj.getClass().getName() +
                         " is of unrecognized type and cannot be added");
        }

```
En gros `instanceof` ne détecte pas que c'est une String, mais `obj.getClass().getName()` oui.

- Essaie d'utiliser le service `/keywords` au lieu de `xml.search.keywords`
- Tente avec le paramètre `&_content_type=json`

Je ne reproduis pas, est-ce pareil avec un autre thésaurus (`external.place.regions`) ? 
Je ne pense pas que cela soit lié au thésaurus, mais sait-on jamais.

Pour la correction, on peut wrapper la String dans un TextElement si tu n'obtiens aucun service qui fonctionne.

**Comment by MaelREBOUX** [comment]
Je croyais avoir vu passer un message quelque part incitant à modifier / tester une autre url de service des thesaurus.
J'ai rêvé ou pas ?

**Comment by fvanderbiest** [comment]
> J'ai rêvé ou pas ?

I guess so.

**Comment by fvanderbiest** [comment]
As reported in thread https://groups.google.com/forum/#!topic/georchestra/e_2NL8_Z8xc the error shows up when using this thesaurus: [GeoBolivia.rdf.zip](https://github.com/georchestra/georchestra/files/653192/GeoBolivia.rdf.zip)

**Comment by MaelREBOUX** [comment]
None of "my" thesaurus work : https://github.com/MaelREBOUX/metadonnees/tree/master/thesaurus

**Comment by fvanderbiest** [comment]
Indeed witnessed on https://portail.sig.rennesmetropole.fr/mapfishapp/

**Comment by Vampouille** [comment]
Without `Mode=consult` parameter, it works, but I don't known if mapfishapp need thesaurus identifier and mode in response.

**Comment by fvanderbiest** [comment]
see https://github.com/georchestra/georchestra/blob/15.12/mapfishapp/src/main/webapp/app/js/GEOR_cswbrowser.js#L335

**Comment by Vampouille** [comment]
Fixed by https://github.com/georchestra/georchestra/pull/1654

**Comment by fvanderbiest** [comment]
Thanks Julien !
