### ISSUE TITLE
geoserver pom: useless code ?

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1342]
Not sure we need this anymore https://github.com/georchestra/georchestra/blob/15.12/geoserver/webapp/pom.xml#L1048-L1052

**Comment by pmauduit** [comment]
The following PR actually addresses this issue: https://github.com/georchestra/georchestra/pull/1338/files

**Comment by fvanderbiest** [comment]
hmm, ok, would have been better in a separate PR (or in a commit on 15.12 without PR)
