### ISSUE TITLE
mapfishapp - unable to reset WxS server selection

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#1349]
On the "add layer" window, once a WxS server from the selectlist has been chosen, there is no way to reset the window (so that one can be able to enter an URL by hand for example).

**Comment by fvanderbiest** [comment]
Which browser ? Works well with Chromium 49

**Comment by pmauduit** [comment]
```
Version 49.0.2623.87 built on Debian stretch/sid, running on Debian stretch/sid (64-bit)
```

**Comment by pmauduit** [comment]
Maybe because I was following this usecase:

1. add layer
2. select in wms "sdi.georchestra.org"
3. type in a dummy/non-existing service url like "example.com/wms" => the listing still describes the sdi.g.o one, I'd expect that the layer list would be cleared.

**Comment by fvanderbiest** [comment]
Well, there's a message indicating a wrong url was typed, I'm not sure this is a bug in fact.

**Comment by pmauduit** [comment]
With a correct one (replace by "http://example.com/wms" at step 3), the previous list is not cleared

**Comment by fvanderbiest** [comment]
OK, you get this
![capture du 2016-04-04 09 21 50](https://cloud.githubusercontent.com/assets/265319/14240631/b3ffc41e-fa46-11e5-9406-7a9089314074.png)
