### ISSUE TITLE
mapfishapp - resultspanel does not detect FTP protocol

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1356]
![capture du 2016-04-07 14 38 05](https://cloud.githubusercontent.com/assets/265319/14351221/5acc0684-fcce-11e5-9927-e312772bf122.png)

**Comment by landryb** [comment]
I had to craft the ```<a href>``` content in the attributes for http links too.. so yes, would be welcome :)

**Comment by fvanderbiest** [comment]
> I had to craft the <a href> content in the attributes for http links too

This is strange, because this code should have detected URLs: 
https://github.com/georchestra/georchestra/blob/15.12/mapfishapp/src/main/webapp/app/js/GEOR_ResultsPanel.js#L512-L519

Can you tell us more about what you had to do to make it work ?

**Comment by fvanderbiest** [comment]
This should do the job:
```diff
diff --git a/mapfishapp/src/main/webapp/app/js/GEOR_util.js b/mapfishapp/src/main/webapp/app/js/GEOR_util.js
index 132982e..5011c0e 100644
--- a/mapfishapp/src/main/webapp/app/js/GEOR_util.js
+++ b/mapfishapp/src/main/webapp/app/js/GEOR_util.js
@@ -660,9 +660,9 @@ GEOR.util = (function() {
          */
         isUrl: function(s, strict) {
             if (strict) {
-                return new RegExp(/^(http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?$/i).test(s);
+                return new RegExp(/^(http|https|ftp):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?$/i).test(s);
             }
-            return new RegExp(/^(http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/i).test(s);
+            return new RegExp(/^(http|https|ftp):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/i).test(s);
         },
 
         /**
```

**Comment by landryb** [comment]
> Can you tell us more about what you had to do to make it work ?

erm, dont really remember but at that time this was with mfapp 13.06.. some horrible hacks involving spatialite, shell scripts to generate the sql for the table like
```
                link="ftp://opendata.craig.fr/$file"
                echo "update $table set ftp=\"$link\", download=\"<a href='$link'>dalle $dalle</a>\" where location=\"$f\";" >> /tmp/$table.sql
```
so the `download` attribute contains the full html link content.
