### ISSUE TITLE
Mapfishapp - change default police for styler

### ISSUE THREAD

**Issue by catmorales** [georchestra/georchestra#1360]
Default police is tahoma. This one is subject to licence requirements  and not installed on servers.

**Comment by fvanderbiest** [comment]
Which one would you like by default ?

**Comment by fvanderbiest** [comment]
See https://github.com/georchestra/styler/blob/master/lib/Styler/widgets/form/FontComboBox.js#L8-L25

**Comment by fvanderbiest** [comment]
BTW, we could also add more choice to https://github.com/georchestra/styler/blob/master/lib/Styler/widgets/form/FontComboBox.js#L8-L19

**Comment by catmorales** [comment]
I think Verdana could be a good choice.

**Comment by fvanderbiest** [comment]
I'm lost ... https://en.wikipedia.org/wiki/Core_fonts_for_the_Web
