### ISSUE TITLE
[extractorapp] testsuite is broken

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#1373]
A server from bgdi / geocat is no longer alive, making the testsuite fail because some XML files are referencing a schema onto this dead server, see:

https://travis-ci.org/georchestra/georchestra/builds/129110552#L1860

We should remove the useless schema declarations:

```
http://tc-geocat0i.bgdi.admin.ch:80/geoserver/sf/wfs?
```

**Comment by fvanderbiest** [comment]
+1

**Comment by pmauduit** [comment]
Weird, only 15.06 seems affected. This might be fixed by the migration to `gt-wfs-ng`.
