### ISSUE TITLE
Jetty / docker: add Xms and Xmx parameters

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1382]
eg in https://github.com/georchestra/georchestra/blob/15.12/geoserver/webapp/src/docker/Dockerfile#L19

Every jetty instance should be capped with a Xmx

**Comment by Vampouille** [comment]
Here is a proposition of memory limit : 

* analytics : 512 Mo
* cas : 1 Go
* downloadform : 512 Mo
* extractorapp : 1 Go
* geoserver : 2 Go
* geowebcache : 1 Go
* header : 512 Mo
* ldapadmin : 1 Go
* mapfishapp : 1 Go
* security proxy : 1 Go
* geonetwork : en cours ...

**Comment by Vampouille** [comment]
Maybe geoserver need 8 Go of RAM

**Comment by pmauduit** [comment]
:+1: 

For the record, the current Xmx on PIGMA for geoserver is 28GB.

**Comment by landryb** [comment]
*khof*
```
$grep Xmx /etc/default/tomcat-geoserver
JAVA_OPTS="$JAVA_OPTS -Xmx2G"
```

Okay, maybe i should grant more.. i give 3G to geonetwork.

**Comment by Vampouille** [comment]
After testing with previous memory limit a docker compose up took around 8 Go.
PR on georchestra : https://github.com/georchestra/georchestra/pull/1398
PR on geonetwork : https://github.com/georchestra/geonetwork/pull/39
