### ISSUE TITLE
fermer/reouvrir la toolbar ne nettoie pas tout les outils -> requetes multiples pour l'infobulle

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#1385]
Si je ferme/reouvre la toolbar, l'outil d'interrogation/selection pour l'infobulle n'a pas l'air nettoyé/supprimé. Avec la console réseau, apres avoir ouvert/fermé 5 fois la toolbar, a chaque déclenchement du timeout j'ai 6 requetes WFS et 6 requetes getInfoBulle.... je ne sais pas si c'est lié, mais si je regarde la liste des controles dans l'objet map via ```GeoExt.MapPanel.guess().map``` j'ai 5 controles 'drawFeature' et 6 controles 'generiques'. Il y'a un truc qui cloche qqpart avec un controle de selection...

**Comment by fvanderbiest** [comment]
wrong repository ?

**Comment by landryb** [comment]
bien vu :)
