### ISSUE TITLE
LDAP master breaks ldapadmin legacy UI

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1391]
I fear this commit https://github.com/georchestra/georchestra/commit/f8fc41c27cd02f58c348e6a269f95de647d8b3c6 breaks our legacy UI (addition of the SV and MOD groups)

![screenshot from 2016-06-03 10-30-43](https://cloud.githubusercontent.com/assets/265319/15773279/6314fd58-2976-11e6-8a98-b721a6acc53b.png)

@tonio or @Vampouille, any idea ?

**Comment by Vampouille** [comment]
Maybe we need to fix #1299 ?

**Comment by fvanderbiest** [comment]
Right, this is a duplicate, you're right !
