### ISSUE TITLE
georchestra-generic-pkgs CI job fails

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1392]
[INFO] jsbuild/build.sh: 38: jsbuild/build.sh: /var/lib/jenkins/jobs/georchestra-generic-pkgs/workspace/catalogapp/jsbuild/env/bin/jsbuild: not found

https://sdi.georchestra.org/ci/job/georchestra-generic-pkgs/236/console

**Comment by pmauduit** [comment]
You renamed the jenkins job ... some paths are hardcoded in the build system, we will have to regenerate the jsbuild environments

**Comment by pmauduit** [comment]
Repaired (build unstable because of failing tests on GN), but the artifacts linked onto build.georchestra.org/wars/ are generated.

**Comment by fvanderbiest** [comment]
> You renamed the jenkins job

I knew this would have unexpected consequences ... sorry about that.
