### ISSUE TITLE
mapfishapp - server response includes a path

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1399]
https://sdi.georchestra.org/mapfishapp/ws/togeojson/ throws upon error `{"success":false, "error":"fileupload_error_ioError", "msg": "Failed reading /srv/georchestra/mapfishapp-data/geoFileUploadsCache/5929da26-399a-4adb-b7e3-fc2a84ef81e0/testGPX.gpx.  Unsuported format: gpx"}`

We should never disclose this kind of information.

**Comment by landryb** [comment]
String the dirname from the exceptions string building in https://github.com/georchestra/georchestra/blob/15.12/mapfishapp/src/main/java/org/georchestra/mapfishapp/ws/upload/UpLoadFileManagement.java#L395 ?

**Comment by fvanderbiest** [comment]
Strip it, yes.

**Comment by landryb** [comment]
There's another occurence of the same construct on line 395 for ProjectionException, might need the same fix ?
