### ISSUE TITLE
server-deploy fails to deploy the correct version of GeoNetwork

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#1402]
It still references the artifacts for the 15.12 (2.x) GN version:

```
        <dependency>
          <groupId>org.geonetwork-opensource</groupId>
          <artifactId>geonetwork-main</artifactId>
          <version>${project.version}</version>
          <type>war</type>
        </dependency>
```

2 things:

- To stay the closest to the GN 3.x upstream, we did not modify the root pom of the GN fork in geOrchestra. This causes me some concerns to modify the poms in GN.

- The "quick fix" for server-deploy would be:

```
        <dependency>
          <groupId>org.geonetwork-opensource</groupId>
          <artifactId>web-app</artifactId>
          <version>3.0.4-SNAPSHOT</version>
          <type>war</type>
        </dependency>
```

but we might have a more customized version for geOr (but see first point).

**Comment by fvanderbiest** [comment]
... but server-deploy should be removed from 16.12 ...
I think no one uses it anymore.
