### ISSUE TITLE
ldapadmin - ability to handle organizations

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1412]
This issue is about adding the ability to handle organizations as full-featured objects within ldapadmin:
- when a user registers himself, he must choose a **unique** org in a list, or fill a new one (as for [PPIGE](http://www.ppige-npdc.fr/portail/user/register) currently)
- orgs have their own fields, including name, address, geographic perimeter... The required ones should be configurable (in https://github.com/georchestra/datadir/blob/master/ldapadmin/ldapadmin.properties).
- new orgs should undergo a moderation process, as for new users
- ldapadmin should allow the admin to:
  - update organization fields (including the geographic perimeter)
  - update a user's organization

Edition of the geographic perimeter field should be configurable (either by the user or by the admin) through the use of a JS plugin/helper.

One can already imagine several plugin types:
- input plugins:
  - the user selects geographic entities by their name (eg: autocompletion on cities) 
  - the user selects geographic entities on a map
- output plugins:
  - the resulting string is a comma separated list of ids
  - the resulting string is a WKT

Our first implementation should only cover one case: the user selects geographic entities by their name and the resulting string is a comma separated list of ids.

**Comment by landryb** [comment]
Fwiw, i'm interested in this, since this is already how i'm managing my users in drupal - but the organisations are not in ldap yet...

**Comment by fvanderbiest** [comment]
An organization will be an instance of the `organization` objectClass (this is from core.schema).

A new Organizational Unit (OU) will be added to the default geOrchestra LDAP, as a parent to all organizations.

**Comment by fvanderbiest** [comment]
@pmauduit has had a brilliant idea related to this issue: what if we could map geoserver:
 * `users` to our LDAP's `ou=users` (as for now)
 * `groups` to our LDAP's `ou=orgs`
 * `roles` to our LDAP's `ou=groups`

This would be pretty disruptive, but would fit very well GeoServer's role system (see eg http://docs.geoserver.org/latest/en/user/security/usergrouprole/interaction.html)

**Comment by fvanderbiest** [comment]
We would get role inheritance for free ... since it is already implemented in geoserver.

**Comment by fvanderbiest** [comment]
> We would get role inheritance for free ... since it is already implemented in geoserver.

In fact not.
When geoserver gets roles from the request headers (as we do in geOrchestra), no role calculation takes place (role inheritance + roles from groups). This is explained in http://docs.geoserver.org/stable/en/user/security/usergrouprole/rolesource.html#using-an-http-header-attribute

**Comment by fvanderbiest** [comment]
So, if we want users to obtain roles from their group, we would have to implement it by ourselves at the security-proxy level (and the LDAP + console would need an overhaul in order to associate roles to orgs).

**Comment by fvanderbiest** [comment]
Closing this, since ldapadmin / console now handles orgs on master, ready for 16.12 !
