### ISSUE TITLE
[mapfishapp] allow to load addons with minified/debug versions

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#1420]
As mfapp allows for debug=1 in the URL to load separate js files, would be nice to be able to do the same for addons.

Implem ideas:
- in manifest.json, have different values for 'js' (for production) and 'debugjs' (for debug), listing different js files (minified version for js, full list for debugjs)
- in GEOR_tools.js, fetchAndLoadTools (https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/webapp/app/js/GEOR_tools.js#L197) have a different behaviour to populate the 'js' array, depending on the presence of debug in the viewer url ?

**Comment by fvanderbiest** [comment]
Your proposal sounds like a neat idea.

**Comment by landryb** [comment]
Tested working fine at runtime with cadastrapp.js built with georchestra/cadastrapp#235

**Comment by fvanderbiest** [comment]
OK, implemented with https://github.com/georchestra/georchestra/pull/1430

Now we might want to minify the addons we provide by default, when they load more than 1 file...

**Comment by jusabatier** [comment]
Is there a way to load the debug version for addons ?

Maybe with /mapfishapp?debug, but it was not working last time I tried on cadastrapp.js

**Comment by fvanderbiest** [comment]
> /mapfishapp?debug=true

It should work, yes.

**Comment by jusabatier** [comment]
Nope, with /mapfishapp?debug=true I still get the minified version of cadastrapp.js

Only the mapfishapp javascript files are the debug ones.

**Comment by landryb** [comment]
You have to list both versions (minified in the js array, and unminified in the debugjs array) in the manifest file:

```
        "js": [ "js/build/cadastrapp.js" ],
        "debugjs": [
        "js/printBordereauParcellaire.js",
        "js/printRelevePropriete.js",
                "js/selectFeature.js",
                "js/resultParcelle.js",
                "js/resultProprietaire.js",
                "js/searchUtils.js",
                "js/componentUtils.js",
                "js/searchParcelleByOwner.js",
                "js/searchParcelleByRef.js",
                "js/searchCoPropriete.js",
                "js/informationsRequest.js",
                "js/detailUniteFonciere.js",
                "js/habitationDetails.js",
                "js/detailUniteCadastrale.js",
                "js/infoBulle.js",
        "js/menu.js",
        "js/main.js",
        "js/cadastrappUtil.js",
                "js/external/fileUploadField.js"
    ],   
```

**Comment by jusabatier** [comment]
Yes I've both of them in my manifest.json, but as I havn't the last version of mfapp maybe I still not have the function. I test it on the craig viewer and it works fine.

**Comment by landryb** [comment]
You just need https://github.com/georchestra/georchestra/pull/1430/commits/014b0e7743efc08cbf0fb9a1fb0a926ed140102d
