### ISSUE TITLE
service 'image' must be a mapping not a string

### ISSUE THREAD

**Issue by MaxiReglisse** [georchestra/georchestra#1425]
i cannot execute "docker-compose up".

~/docker/georchestra$ docker-compose up
ERROR: In file './docker-compose.yml', service 'image' must be a mapping not a string.

~/docker/georchestra$ cat docker-compose.yml
database:
  image: georchestra/database
...

**Comment by MaxiReglisse** [comment]
the docker-compose version : 1.6.2, build 4d72027

**Comment by Vampouille** [comment]
Maybe indentation is missing before `image` ? Can you post entire yaml ?

**Comment by fvanderbiest** [comment]
https://github.com/docker/compose/blob/master/compose/config/validation.py#L92-L102

**Comment by fvanderbiest** [comment]
1.6.2 is a pretty old docker-compose version, https://github.com/docker/compose/releases 
Tell us if it's happening again with a newer version

**Comment by MaxiReglisse** [comment]
$ docker-compose -v
docker-compose version 1.8.0-rc1, build 9bf6bc6

same problem.  
georchestra/docker-compose.yml was obtained by copy/paste.

**Comment by MaxiReglisse** [comment]
$ colordiff docker-compose.yml.copypaste docker-compose.yml
151c151
< image: georchestra/downloadform:latest
---
>   image: georchestra/downloadform:latest
it is an indentation problem !

**Comment by MaxiReglisse** [comment]
151c151
 image: georchestra/downloadform:latest
   image: georchestra/downloadform:latest

**Comment by MaxiReglisse** [comment]
sorry, spaces are suppressed. you can not see.

**Comment by MaxiReglisse** [comment]
well, the problem is that you can not do a copy/paste from docker-compose.yml.
you must clic on "raw" and save the file.

**Comment by MaxiReglisse** [comment]
and every thing is ok now ! thanks.

**Comment by santosh9991** [comment]
I get the same error when use -f flag with docker-compose. I am new to docker. Can any one please help
docker-compose version 1.19
![image](https://user-images.githubusercontent.com/16803672/37115535-3cc17760-2200-11e8-97c7-05a37b14e02e.png)
Fig1: Error message and command used
![image](https://user-images.githubusercontent.com/16803672/37115657-9ec4c8ea-2200-11e8-8c54-cc6badbc6e41.png)
Fig2: Yaml file

**Comment by nhatlam97** [comment]
> Maybe indentation is missing before `image` ? Can you post entire yaml ?

ty
