### ISSUE TITLE
geonetwork : HTTP ERROR: 503

### ISSUE THREAD

**Issue by MaxiReglisse** [georchestra/georchestra#1426]
Problem accessing /geonetwork/. Reason: Service Unavailable
Powered by Jetty:// 9.3.8.v20160314

but geoserver, mapfishapp and extractorapp are OK !

**Comment by MaxiReglisse** [comment]
proxy_1         | 2016-07-08 08:23:34 statistics [INFO] testadmin|2016/07/08 08:23:34|http://geonetwork:8080/geonetwork/|geOrchestra|ROLE_SV_ADMIN,ROLE_MOD_EXTRACTORAPP,ROLE_ADMINISTRATOR,ROLE_MOD_LDAPADMIN,ROLE_MOD_ANALYTICS
proxy_1         | 2016-07-08 08:23:34 security [WARN] Error occurred. statuscode: 503, reason: Service Unavailable

**Comment by MaxiReglisse** [comment]
geonetwork_1    | 2016-07-08 09:49:49.726:INFO:geonetwork:main: No Spring WebApplicationInitializer types detected on classpath
geonetwork_1    | java.lang.IllegalArgumentException: The resource file /etc/georchestra/geonetwork/config/config-overrides-georchestra.xml is not a file and not a web resource.  Perhaps a leading / was forgotten?

**Comment by fvanderbiest** [comment]
Is it still an issue for you ?

**Comment by MaxiReglisse** [comment]
yes and no... it is worse today ! 
HTTP ERROR: 503 Problem accessing /. Reason: Service Unavailable on http://localhost:8080/
just before doing "docker-compose up", i cleaned every thing in docker.
and https://github.com/georchestra/docker-compose.yml does not exist anymore... :(

**Comment by fvanderbiest** [comment]
Did you give a try at https://github.com/georchestra/georchestra/blob/master/docs/docker.md ?

**Comment by MaxiReglisse** [comment]
oh i did not view this page before, and i tried it just now. every thing is ok now !!
and browsing is more fluid. thanks a lot !
