### ISSUE TITLE
docker - docker-entrypoint.sh not used anymore ?

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#1427]
Since the XMX / XMS env variable customization, we seem to have lost the use of the docker-entrypoint.sh script (at least on mapfishapp & extractorapp), see:

* https://github.com/georchestra/georchestra/blob/15.12/mapfishapp/src/docker/Dockerfile#L15
and
* https://github.com/georchestra/georchestra/blob/15.12/mapfishapp/src/docker/docker-entrypoint.sh

Am I missing something ?

**Comment by Vampouille** [comment]
Entrypoint is not defined, so it will use jetty one :
https://github.com/appropriate/docker-jetty/blob/c228052ac9459c1303601e90fd66a44d7be6b8ce/9.3-jre8/Dockerfile#L50
So `/docker-entrypoint.sh` is *still* use and https://github.com/georchestra/georchestra/blob/15.12/mapfishapp/src/docker/docker-entrypoint.d/00-adjust-perms will be executed.
