### ISSUE TITLE
ldapadmin master - org field not displayed

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1433]
/ldapadmin/account/userdetails shows "organisme" field label, but no field.
The field should be read-only

![capture du 2016-07-18 09 48 11](https://cloud.githubusercontent.com/assets/265319/16908536/c4428892-4ccc-11e6-9a82-26cc846d6c8b.png)

**Comment by Vampouille** [comment]
I think this user has no org, so it display an empty string. Maybe, we can display a dedicated i18n string like : 'non renseigné'

**Comment by fvanderbiest** [comment]
+1

Do we have the option to make it mandatory ?

**Comment by Vampouille** [comment]
No option as org field is not handle like other user attributes.

**Comment by fvanderbiest** [comment]
For PPIGE, having an org is mandatory for every user...
But for geOrchestra, we don't want to make the org field mandatory.

So we'll have to find a way to configure this...

**Comment by fvanderbiest** [comment]
@Vampouille I think you're done with this one ?

**Comment by Vampouille** [comment]
yes, it's done here :
https://github.com/georchestra/datadir/blob/master/ldapadmin/ldapadmin.properties#L7-L8

If you specify "org" then organizations is mandatory (create one or select one)
Then for organization creation, you can specify : 

* orgShortName
* orgAddress
* orgType

to make these field mandatory. organization name is always mandatory when you create an organization

**Comment by fvanderbiest** [comment]
Thanks Julien
