### ISSUE TITLE
ldapadmin fails travis CI on 15.12 and master

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1458]
https://travis-ci.org/georchestra/georchestra

[ERROR] 26 Aug 06:42:09 - error: Compiling of app/app.es6 failed. Couldn't find preset "/home/travis/build/georchestra/georchestra/ldapadmin/src/main/webapp/console/node_modules/babel-preset-es2016" relative to directory "app" ; Compiling of app/services/contexts.es6 failed.

**Comment by tonio** [comment]
@Vampouille fix it in https://github.com/georchestra/georchestra/tree/Improve_Org_display, see https://github.com/georchestra/georchestra/commit/75a86d01ead134cd066145abc916c42829e53396

**Comment by fvanderbiest** [comment]
on master branch: [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.27:npm (npm install) on project ldapadmin: Failed to run task: 'npm install --color=false' failed. (error code 1) -> [Help 1]

**Comment by fvanderbiest** [comment]
Seems fixed ... https://travis-ci.org/georchestra/georchestra/builds/160149358

**Comment by pmauduit** [comment]
> com.github.eirslett:frontend-maven-plugin:0.0.27

This is a pretty old version of the plugin by the way, the 1.0 is available since April 2016:
http://mvnrepository.com/artifact/com.github.eirslett/frontend-maven-plugin/1.0

I remember having to update recently, but I cannot remember where exactly in geOrchestra (and what for)

**Comment by fvanderbiest** [comment]
see also https://github.com/georchestra/georchestra/issues/1394
