### ISSUE TITLE
mapfishapp - referentials tab search don't follow width of the TOC

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/georchestra#1459]
On this screenshot you can see that the TOC has been enlarge for read the response to the search.
But both the combox of the referential and the response list do not optimize their size in dynamic.

It is unusable in our case.

![screenshot198](https://cloud.githubusercontent.com/assets/6370443/18006131/7190657e-6b9e-11e6-9f62-3fa1fdaa2b70.png)

**Comment by fvanderbiest** [comment]
RIght, and that should not be too difficult to fix, eg a resizable combo https://github.com/georchestra/georchestra/blob/15.12/mapfishapp/src/main/webapp/app/js/GEOR_LayerBrowser.js#L92

**Comment by fvanderbiest** [comment]
Fixed from 15.12 on.
