### ISSUE TITLE
mapfishapp - drawing tool + Print : vertex of a label is printed + font switch

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/georchestra#1460]
![screenshot199](https://cloud.githubusercontent.com/assets/6370443/18006353/70053594-6b9f-11e6-9c11-5be14c30d95e.png)

On this screencast one can see 2 labels.
On MPapp : we see only the labels.
On the PDF print : 2 circles appear. They are the base vertex of the label.

This should not happen.

Other thing : the font used on screen and in print is not the same. Result : label on PDF print is really bigger then those on screen in MPapp.

**Comment by jusabatier** [comment]
I already had the problem with the circles behind labels, I solved this with this PR : 
https://github.com/georchestra/georchestra/pull/1358
Wich also allow to save and load annotations.

**Comment by fvanderbiest** [comment]
> Other thing : the font used on screen and in print is not the same. Result : label on PDF print is really bigger then those on screen in MPapp.

That's another issue please.

> I already had the problem with the circles behind labels, I solved this with this PR

Hmm, a bugfix + a new feature in a PR...

Bugfix backported to 15.12 with https://github.com/georchestra/georchestra/commit/a09e09213ffdc7ebd6960d3d2196142849ce0f8e

Thanks Julien.

**Comment by fvanderbiest** [comment]
What's the status of this issue ?

**Comment by fvanderbiest** [comment]
Just tested ATM on 16.12, it's been fixed.

**Comment by MaelREBOUX** [comment]
tested here (mpaap master ?)

the point is always there but very small.
test with opacity = 0 maybe ?

![screenshot490](https://cloud.githubusercontent.com/assets/6370443/22115800/b29e5e34-de6e-11e6-9e12-54dde2b7e98a.png)

![screenshot491](https://cloud.githubusercontent.com/assets/6370443/22115851/da3ce0a0-de6e-11e6-94d3-9918638bb47c.png)
