### ISSUE TITLE
console - client should prevent system roles renaming & deletion

### ISSUE THREAD

**Issue by Vampouille** [georchestra/georchestra#1472]

**Comment by fvanderbiest** [comment]
You're right, we should prevent this, since it is required when `moderatedSignup=true` in https://github.com/georchestra/datadir/blob/15.12/ldapadmin/ldapadmin.properties#L4

**Comment by fvanderbiest** [comment]
Is it server-side protected ?

**Comment by Vampouille** [comment]
> Is it server-side protected ?

No

**Comment by fvanderbiest** [comment]
Euh https://github.com/georchestra/datadir/blob/master/ldapadmin/protectedgroups.properties#L2 ?

Ideally, the client-side app should also forbid protected groups renaming / deletion.

**Comment by fvanderbiest** [comment]
done
