### ISSUE TITLE
Upgrade master to GeoServer 2.9.3 or 2.10.0 ?

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1482]
As seen in http://blog.geoserver.org/2016/08/12/geoserver-2-8-5-released/ there are several security enhancements compared to 2.8.3. I'm not sure these are critical, but ...

This release includes several security enhancements and is a recommended upgrade for production systems:
Although we have not been able to reproduce from GeoServer, a remote execution vulnerability has been reported against both the Restlet  and the Apache Commons BeanUtils libraries we use. We have patched our use of these libraries as a preventative measure. We would like to thank Kevin Smith for doing the bulk of the work, and Andrea Aime for providing a patched BeanUtils library addressing these vulnerabilities.
Layer security restrictions in CHALLENGE mode were not being correctly applied by embedded GeoWebCache. Thanks to Nick Muerdter for his responsible report of this vulnerability and for submitting a fix (that included a unit test!)
Carl Schroedl reported a vulnerability at application startup when working with a data directory on a network file system, a new configuration option has been provided to check that the directory exists.  Thanks to Carl for following our responsible disclosure procedure, and to Ben Caradoc-Davies for implementing the new parameter.

**Comment by pmauduit** [comment]
> for providing a patched BeanUtils library

... Any reason for using a "patched" version ? why not using an (upstream) fixed version ?

**Comment by fvanderbiest** [comment]
More generally here, why are we still tied to GeoServer 2.8.3 when 2.10 is out ? 
IIRC, this is because of the geofence integration.

In my opinion, georchestra master should always target geoserver's latest stable release.

**Comment by fvanderbiest** [comment]
BTW there's something I don't understand: why are there so many differences between https://github.com/georchestra/geoserver/tree/2.8.3-georchestra and https://github.com/geoserver/geoserver/releases/tag/2.8.3 (using `meld` helps...)

**Comment by MaelREBOUX** [comment]
2.10 works well for me in VM for testing. Lots of things for better and efficient publishing process.

**Comment by fvanderbiest** [comment]
Yeah but not enough time for 16.12
Next release maybe ?

**Comment by MaelREBOUX** [comment]
:(

**Comment by fvanderbiest** [comment]
see #1655
