### ISSUE TITLE
viewer - spaces in context names

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1483]
The GEOR.config.CONTEXTS var is OK
```js
GEOR.config.CONTEXTS = [{
    "thumbnail": "context/image/PLU - Cadastre.png",
    "keywords": ["Aménagement - Cadastre - PLU - Urbanisme", "PLU - Cadastre"],
    "roles": [],
    "tip": "PLU - Cadastre",
    "label": "PLU - Cadastre",
    "wmc": "context/PLU - Cadastre.wmc"
}];
```
... but the `/mapfishapp/context/image` service is not able to return the image, eg:
https://www.ppige-npdc.fr/mapfishapp/context/image/PLU%20-%20Cadastre.png = HTTP 503

To be fixed from 15.12 on.

**Comment by Vampouille** [comment]
Should be fixed by this PR : https://github.com/georchestra/georchestra/pull/1486

**Comment by fvanderbiest** [comment]
Now we need to test if the fix is successful
