### ISSUE TITLE
SP - logging improvements (forgotten code in the georchestra-datadirization process)

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#1495]
There were some pieces of code forgotten between my own "georchestra-datadir" branch and the current one. I introduced a "apache-like common logging system" onto the security-proxy, that has not been ported to master / 15.12 and which could be of interest.

The main idea behind the forgotten feature is to be able to produce a logline for each queries made on the SP in a separate logger, that can actually be redirected onto whatever is supported by log4j (console for docker environments, network sockets for ELK stacks, file for regular logging ...).

If it is of interest, it should be easily ported back in a PR (~ 30 mins), or else, there is some dead code to remove (here: https://github.com/georchestra/georchestra/blob/15.12/security-proxy/src/main/java/org/georchestra/security/Proxy.java#L136).

**Comment by fvanderbiest** [comment]
I think it is of great interest for the 16.12 release !

**Comment by landryb** [comment]
If you're going to spend time into improving logging, why not looking into MDC (#1149)  :) ?

**Comment by fvanderbiest** [comment]
ping @pmauduit : status for 16.12 ?

**Comment by pmauduit** [comment]
We introduced a dependency to get closer to Logstash format, in addition Jetty offers some good metrics mechanisms (number of requests, mean time for each requests, ...). Instead of trying to imitate the apache-combined logs format using custom code, I'd prefer to go forward and use well-tested code / libraries.

**Comment by fvanderbiest** [comment]
OK, thanks.
