### ISSUE TITLE
hsperfdata_root folder written in containers tmp

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1507]
I suggest adding `-XX:-UsePerfData` to the JVM options.
http://stackoverflow.com/questions/76327/how-can-i-prevent-java-from-creating-hsperfdata-files

**Comment by fvanderbiest** [comment]
Also related to https://github.com/georchestra/georchestra/issues/1407

**Comment by fvanderbiest** [comment]
Fixed with https://github.com/georchestra/georchestra/commit/aafe31c688b09a993ada7d9e853116545223db45

**Comment by fvanderbiest** [comment]
Note that the hsperfdata_root folder exists in jetty base image.
-XX:-UsePerfData just prevents writes

**Comment by landryb** [comment]
Oh nice, can we also add this to the documentation for the non-docker case ? Those dirs always puzzled me.

**Comment by fvanderbiest** [comment]
Yep, feel free to PR :-)
