### ISSUE TITLE
mapfishapp - query on layer tools open 2 results tabs

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/georchestra#1510]
On a normal layer (ie : not an agregate) : selecting the all layers query tool or the specific layer tool.
Clic on an object in the map.
In the result table beyond the map : 2 tabs are shown :

The first with the human name of the layer. But it is empty.

![screenshot267](https://cloud.githubusercontent.com/assets/6370443/19263505/f18d9bf8-8f9c-11e6-920c-ea9fb202e8be.png)

The second with workspace:layer title and filled with the attributes

![screenshot266](https://cloud.githubusercontent.com/assets/6370443/19263507/f3e19062-8f9c-11e6-86e8-ba964789758b.png)

Same behavior on geobretagne 

Service : https://portail.sig.rennesmetropole.fr/geoserver/urba_fonc/ows?SERVICE=WMS&REQUEST=GetCapabilities
FeatureType : zppa
Protocole : WMS 1.3.0

https://portail.sig.rennesmetropole.fr/geoserver/urba_fonc/ows?SERVICE=WMS&LAYERS=zppa&QUERY_LAYERS=zppa&STYLES=&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&EXCEPTIONS=XML&BBOX=-202653.191145%2C6129513.950656%2C-198800.287188%2C6131711.515219&FEATURE_COUNT=1000&HEIGHT=920&WIDTH=1613&FORMAT=image%2Fpng&INFO_FORMAT=application%2Fvnd.ogc.gml&CRS=EPSG%3A3857&I=1507&J=373

Both happens with FireFox and Chrome

**Comment by MaelREBOUX** [comment]
maybe related issues : #670 and #950

**Comment by fvanderbiest** [comment]
True, that's the same as #670
There's no easy way here. Closing.

**Comment by MaelREBOUX** [comment]
Happens no more.
