### ISSUE TITLE
mapfishapp - show light metadata from a layer in the toc : replace \n by <br />

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/georchestra#1512]
In the abstract of the metadata one usually make return cartdrige (\n) to format a little the text.

The current windows which shows the light metadata in mapfishapp don't reuse the \n informations to format the HTML shown to the user.

Please replace ```\n``` by ```<br />```

![screenshot272](https://cloud.githubusercontent.com/assets/6370443/19309042/ea137f1e-9082-11e6-9437-6edbf11b5a05.png)

![screenshot271](https://cloud.githubusercontent.com/assets/6370443/19309049/efcf2782-9082-11e6-8259-4d5511816371.png)

**Comment by fvanderbiest** [comment]
Steps to reproduce:
 * https://portail.sig.rennesmetropole.fr/mapfishapp/map/b3cf3f5bb035be96362d4efcf23d5ce2
 * https://portail.sig.rennesmetropole.fr/geonetwork/srv/fre/catalog.search#/metadata/9b470450-f62f-48ad-ad61-865a05ed006c
