### ISSUE TITLE
Base Adresse Nationale

### ISSUE THREAD

**Issue by pierrejego** [georchestra/georchestra#1518]
Bonjour,
nous avons fait un addon utilisant l'api de la BAN
https://adresse.data.gouv.fr/api/

Cet addon permet de geocoder et d'utiliser l'autocomplétion de la BAN, un peu comme l'addon OpenLS.

Je fais une PR dans la foulée à merger si ça vous intéresse.

https://github.com/GFI-Informatique/georchestra/tree/BAN-Geocoder

Bonne soirée

Pierre et Gaetan

**Comment by landryb** [comment]
Nice!

**Comment by fvanderbiest** [comment]
Merci de la contribution !

**Comment by landryb** [comment]
Ticked closed without merging the PR ?

**Comment by fvanderbiest** [comment]
Issue was redundant with PR.
No need to create an issue each time you want to PR ;-)

**Comment by fvanderbiest** [comment]
PR needs more work to get merged BTW.

**Comment by fvanderbiest** [comment]
All done.

**Comment by fvanderbiest** [comment]
Oops, need more work: https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/webapp/app/addons/bangeocoder/README.md

**Comment by fvanderbiest** [comment]
@pierrejego can you submit a new PR improving the README.md you contributed ?
Many thanks.

**Comment by fvanderbiest** [comment]
Fixed with https://github.com/georchestra/georchestra/commit/1db11d5836c40655003af863aaf435a9f8347f80
