### ISSUE TITLE
Missing migration script for organizations

### ISSUE THREAD

**Issue by Vampouille** [georchestra/georchestra#1521]
With introduction of new organization based on ldap `organization` objects. Organization of users are not stored in `o` anymore. Instead, users are `memberOf` one `groupOfMembers` ldap object.
We need a script to migrate organizations in `o` attribut to `groupOfMembers` object.

**Comment by fvanderbiest** [comment]
This was done with https://github.com/georchestra/georchestra/pull/1523

Maybe we should create a `scripts` folder with one subfolder per release, to host these scripts.

**Comment by fvanderbiest** [comment]
Done with 12f4c68
