### ISSUE TITLE
[Mapfishapp] Cadre d'impression ne se déplace pas

### ISSUE THREAD

**Issue by jusabatier** [georchestra/georchestra#1532]
J'ai constaté que lorsque je viens d'ouvrir/actualiser mapfishapp et que j'ouvre le menu d'impression pour la première fois, il m'est impossible de déplacer la zone d'impression ou de faire une rotation (c'est la carte qui se déplace).

Est-ce que d'autres personnes ont ce souci ?

**Comment by fvanderbiest** [comment]
> Est-ce que d'autres personnes ont ce souci ?

Never seen that before...
Any error in the console ?

**Comment by jusabatier** [comment]
Non, aucune erreur ne remonte dans la console.

**Comment by jusabatier** [comment]
Je me demande si c'est pas encore un souci avec le chargement de mapfishapp qui semble avoir quelques soucis sur notre plateforme (icônes qui se promènent dans la barre et ce souci).

Mais impossible de savoir ce qui cause ce comportement...

**Comment by MaelREBOUX** [comment]
On a eu ça 2x / 3 en démo. Le cadre n'apparaissait pas. Peut-être à cause de la taille de l'écran ?
Quand il apparaissait : pas possible de le déplacer.

/!\ il faut bien cliquer sur la bordure noire. Malgré le curseur qui change de picto il n'est pas possible de cliquer à l'intérieur du rectangle pour le déplacer. uniquement en cliquant sur la bordure.


Et il y avait un bogue sur la fermeture de la fenêtre d'impression : un cadre blanc fantôme persistait. Impossible de l'enlever sans faire un rechargement total de la page.

**Comment by fvanderbiest** [comment]
Might be a problem with an addon having a vector layer positioned on top of the print vector layer.
Can you report available / loaded addons when this issue arises ?

**Comment by jusabatier** [comment]
Les addons ouverts lorsque ce bug arive et qui utilisent un layer sont : 

- Cadastrapp
- Outils de dessin
- Outils de mesure avancées

**Comment by fvanderbiest** [comment]
Then unregister all of them and try again.
If the bug does not appear, then try to add them one by one.

**Comment by MaelREBOUX** [comment]
rahh : je viens de faire différents tests : un coup ça passe un coup ça passe pas. C'est super bizarre.
j'ai testé avec 2 addons : cadastrapp et mesures avancées.

**Comment by jusabatier** [comment]
Apres quelques tests, cela semble lié à la couche cadastrapp qui est chargée par l'addon.

Cependant j'ai essayé de voir des logs de "GeoExt.MapPanel.guess().layers" et dans les deux cas (bug ou pas bug), l'ordre des layers est le même

**Comment by fvanderbiest** [comment]
> Apres quelques tests, cela semble lié à la couche cadastrapp qui est chargée par l'addon.

OK, closing the issue here, then.

**Comment by MaelREBOUX** [comment]
ici ça fonctionne mieux également.
