### ISSUE TITLE
Generic war from README - HTTP ERROR 404

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/georchestra#1536]
Hello, 
I  need to get mapfishapp.war and when i try to download mapfishapp.war[ from the documentation](http://build.georchestra.org/wars/) 
=>  i have [HTTP ERROR 404 page](https://build.georchestra.org/ci/job/georchestra-generic-pkgs/ws/mapfishapp/target/mapfishapp-template.war).

After trying all links i have 404 error for :
- cas-template.war
- mapfishapp-template.war
- geoserver-template.war
- geowebcache-template.war
- extractorapp-template.war
- catalogapp-template.war
- header-template.war
  -ldapadmin-template.war
- ROOT-template.war

**Comment by fvanderbiest** [comment]
I think the doc just needs an update ;-) ... the wars can be found here: https://build.georchestra.org/ci/job/georchestra-template/

**Comment by Gaetanbru** [comment]
thank you ! Can i close issue or you close this later ?

**Comment by fvanderbiest** [comment]
The page was updated.
Thanks for the report.

**Comment by Gaetanbru** [comment]
Hi, i think the site https://packages.georchestra.org is down - no response.

**Comment by Gaetanbru** [comment]
Thanks, wars are accessible again for 16.12 doc.
But link is broken (change)  to get wars from [15.12 doc.](https://demo.georchestra.org/wars/)

**Comment by fvanderbiest** [comment]
Can you submit a PR on 15.12 ? That would help a lot. Thanks.
