### ISSUE TITLE
SP - Problem with url decoded -> cadastrapp

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/georchestra#1537]
This issue to cross post with the problem found yesterday in cadastrapp :  https://github.com/georchestra/cadastrapp/issues/254

Bug caused by https://github.com/georchestra/georchestra/commit/079ee46620ba1bc1d3a8fa655308796c4f6a3a6b

**Comment by MaelREBOUX** [comment]
Tested here. Seems to be ok.
I close.

**Comment by landryb** [comment]
Tested with what ? #1538 ? Or the issue was a non-issue ?

**Comment by Vampouille** [comment]
#1538 fix this issue. There is also https://github.com/georchestra/georchestra/commit/079ee46620ba1bc1d3a8fa655308796c4f6a3a6b which fix some issues but adds another.
