### ISSUE TITLE
console - export users list

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/georchestra#1551]
The admin console should have a fonction wich allow to export a CSV file of all the users.
This file should contain all showed attributes in the console + groups with a separator like a pipe.

**Comment by fvanderbiest** [comment]
Yes, IIRC the service already exists in /ldapadmin/privateui/ but has not been ported to /ldapadmin/console

**Comment by fvanderbiest** [comment]
CSV export compatible with outlook 
also CardDAV

**Comment by fvanderbiest** [comment]
see #2674

**Comment by MaelREBOUX** [comment]
nice enhancement. need to test.
