### ISSUE TITLE
console - user - Organisation is not stored

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/georchestra#1556]
I want to set or change an organisation of users but after click on the save button -> nothing is stored

**Comment by Vampouille** [comment]
it seems that your openldap instance is not properly configured. `refint: true` is missing. See :
https://github.com/georchestra/georchestra/commit/15966855769e92c414b9951e59233eb28718edb2
and https://github.com/georchestra/georchestra/commit/534606e97186988ba2a672b729b2031e55256cfc

**Comment by MaelREBOUX** [comment]
ok thanks for the report
