### ISSUE TITLE
console - emails - table template : body set to 255 chars

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/georchestra#1557]
ldapadmin.email_template -> content character varying(255)

should be a text or long text attribute in order to paste HTML template in it.

**Comment by Vampouille** [comment]
Already done with : 

https://github.com/georchestra/georchestra/blob/master/ldapadmin/src/main/java/org/georchestra/ldapadmin/model/EmailTemplate.java#L42

Just drop this table and restart webapp.
