### ISSUE TITLE
proxy - nameserver 8.8.8.8 does not revolv private addresses

### ISSUE THREAD

**Issue by MaxiReglisse** [georchestra/georchestra#1564]
i have an error when i use private an IP address for my docker-georchestra server : 

    proxy_1         | 2016-11-23 08:31:18 security [ERROR] Unknown host: georchestra-docker.umrthema.univ-fcomte.fr

it seems that google nameserver 8.8.8.8 does not resolv private IP addresses.
172.20.74.124 <=> georchestra-docker.umrthema.univ-fcomte.fr

this can be corrected by adding a local DNS namesever, which is able to resolv private IP addresses :

    docker exec -it georchestra_proxy_1 bash
    echo "nameserver 194.57.91.200" >> /etc/resolv.conf

it would be be desirable for a public server to be added to the proxy container.

Thanks in advance.

Ernest.

**Comment by fvanderbiest** [comment]
What about running your security-proxy with `--add-host="georchestra-docker.umrthema.univ-fcomte.fr:172.20.74.124"` ?

**Comment by MaxiReglisse** [comment]
why not ? it can indeed be included in the docker-compose.yml file, like that.
    extra_hosts:
       - "georchestra-docker.umrthema.univ-fcomte.fr:172.20.74.124"
for me, it looks sufficient.
