### ISSUE TITLE
noninterative on postgresql Dockerfile

### ISSUE THREAD

**Issue by JPMenezes** [georchestra/georchestra#1577]
The postgresql Dockerfile has:
ENV DEBIAN_FRONTEND noninterative

Should be:
ENV DEBIAN_FRONTEND nonintera**c**tive

**Comment by fvanderbiest** [comment]
Nicely spotted, many thanks for the bug report !
Fixed with https://github.com/georchestra/georchestra/commit/f80587f7ab5d280a313ddb7e0ca9b55e92e0b56f
