### ISSUE TITLE
console - navigation by organisation don't lead to users of organisations

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/georchestra#1590]
When you navigate by organisation /ldapadmin/console/#/orgs/all you have the organisation list and, for each organisation the count of users attached to the organisation.

But at any time you have the list of the users of an organisation.

**Comment by tonio** [comment]
- In users list, add organizations filter (select)
 - in org list, count is a link to filtered user list
 - add batch action to set org to selected user.

**Comment by fvanderbiest** [comment]
superseded by #2080
