### ISSUE TITLE
ldapadmin - error 400 on create new account with IE 11 or out of date FireFox

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/georchestra#1596]
We have a serious problem : many of users that are customed to use IE 11.
After hav filled up the form on /ldapadmin/account/new and validate they obtain an error 400 page

```
HTTP Status 400 - Required String parameter 'orgCities' is not present
type Status report
message Required String parameter 'orgCities' is not present
description The request sent by the client was syntactically incorrect.
```

Users with an 'old' FireFox met this bug too. Many users have a FireFox 36 installed by default. The problem is that FireFox < to v 38 or 39 don't update automatically.

We should detect them and show a specific message.

**Comment by fvanderbiest** [comment]
@tonio & @Vampouille : what's happening here ?

**Comment by fvanderbiest** [comment]
We're giving #1644 a try before declaring this issue closed.

**Comment by fvanderbiest** [comment]
Looks like it's been fixed, eg https://www.ppige-npdc.fr/ldapadmin/account/new is OK in IE11

**Comment by MaelREBOUX** [comment]
Still in error here !

**Comment by fvanderbiest** [comment]
even https://www.ppige-npdc.fr/ldapadmin/account/new ?
which error, which browser ?

**Comment by MaelREBOUX** [comment]
Bingo : error 400 on PPIGE too !

**Comment by MaelREBOUX** [comment]
![screenshot531](https://cloud.githubusercontent.com/assets/6370443/22470844/cfb3089c-e7d0-11e6-90b6-95dd3ea38b3f.png)

**Comment by fvanderbiest** [comment]
I upgraded ppige to latest version, can you check again ?

**Comment by MaelREBOUX** [comment]
Test succesfull \o/

**Comment by MaelREBOUX** [comment]
still a console error at page load

![screenshot529](https://cloud.githubusercontent.com/assets/6370443/22471216/02955aac-e7d2-11e6-9f29-5ecb56194802.png)

and the suggestion list is not as responsive as the first test. to re-test by users ?

**Comment by fvanderbiest** [comment]
not ready for 16.12 despite hours of @tonio 's head-scratching, bumping ...

**Comment by fvanderbiest** [comment]
Testing again with #1661 additions ... (thanks @tonio )

**Comment by fvanderbiest** [comment]
Deployed on https://www.ppige-npdc.fr/ldapadmin/account/new and guess what ? 
It works on IE11 \o/
