### ISSUE TITLE
mapfishapp - docker - Failed to load the GDAL native libs

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1609]
On master:
```
mapfishapp_1    | Jan 19, 2017 9:10:05 PM it.geosolutions.imageio.gdalframework.GDALUtilities loadGDAL
mapfishapp_1    | WARNING: Failed to load the GDAL native libs. This is not a problem unless you need to use the GDAL plugins: they won't be enabled.
mapfishapp_1    | java.lang.UnsatisfiedLinkError: Native Library /usr/lib/jni/libgdaljni.so already loaded in another classloader
```

**Comment by fvanderbiest** [comment]
https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/docker/Dockerfile

See also https://groups.google.com/d/msg/georchestra-dev/o-fqtmy2XNw/aZAcqAui3OMJ

**Comment by pmauduit** [comment]
I cannot reproduce on the current mapfishapp:latest

**Comment by pmauduit** [comment]
Actually reproduced but needs an extra hit on the webapp (not the main entrypoint). The problem is similar to the one in #1628 and is due to the mapfishprint servlet, not the mapfishapp one.

**Comment by pmauduit** [comment]
In addition, the `gt-imageio-ext-gdal-9.2.jar` transitively needed by mapfish-print and present in the WEB-INF/lib of the webapp is incompatible with the native libraries present in /usr/lib:

```
java.lang.UnsatisfiedLinkError: org.gdal.gdal.gdalJNI.AllRegister()V
```

**Comment by pmauduit** [comment]
Funny, this also means that the classloading (at least in Jetty) is made for each servlets, not for each webapps. I could not manage to find any doc about this, and I guess it is sufficiently lowlevel to have an answer only by reading the jetty sources.

**Comment by pmauduit** [comment]
This does not harm the print, I'm still able to print as PDF, so the best we can do is to exclude the gdal libraries from the generated webapp to avoid the message.

**Comment by fvanderbiest** [comment]
> I'm still able to print as PDF

but are we able to also use mapfishapp features depending on gdal.jar ?

**Comment by pmauduit** [comment]
> but are we able to also use mapfishapp features depending on gdal.jar ?

yes, I just tested with loading an OSM file, and it works.

**Comment by fvanderbiest** [comment]
okay, bumping then :-)

**Comment by pmauduit** [comment]
Yes it could wait.

To complete a little bit the investigation: The current version of the dockerfile probably leads to have GDAL loaded in a "kindof" shared classloader:

https://github.com/georchestra/georchestra/blob/15.12/mapfishapp/src/docker/Dockerfile#L13

Since we have a hand on MFapp code, we probably did the necessary tasks to avoid a new `System.loadLibrary()` in the MFapp code (I cannot exactly remember), but that is another story for the mapfishprint jar.

**Comment by fvanderbiest** [comment]
See also https://github.com/jusabatier/georchestra-rancher/blob/master/mapfishapp/entrypoint.sh#L11-L12
