### ISSUE TITLE
geonetwork - error when getting appender named 'fileAppender

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1616]
docker master 

geonetwork_1    | 2017-01-17 12:46:49,741 ERROR [geonetwork] - Error when getting appender named 'fileAppender'. Check your log configuration file. No appender found.

**Comment by fvanderbiest** [comment]
This is strange since there is no fileAppender in https://github.com/georchestra/datadir/blob/docker-master/geonetwork/log4j/log4j.xml

**Comment by fvanderbiest** [comment]
fileAppender is mentionned in https://github.com/georchestra/geonetwork/blob/georchestra-gn3-master/web/src/main/webapp/WEB-INF/classes/log4j-dev.xml & 2 other files in the same dir.

**Comment by pmauduit** [comment]
Yes, there are some classes in GeoNetwork which allows to reconfigure log4j from the admin web interface. But you have to provide some default log4j files at webapp bootstrap. One option would be to remove the fileAppenders from the log4j configuration files you mentioned, but this will be actually valid for docker users, and not the recommended behaviour for people still using packages who still need to get their logs into a file.

I'm afraid there is no easy quickwin for this one. Anyway, this message is only concerning temporary log4j configuration files, before the other one from the datadir is used.

**Comment by fvanderbiest** [comment]
> I'm afraid there is no easy quickwin for this one.

OK, closing then :-)
Thanks !
