### ISSUE TITLE
geonetwork3 - uses deprecated ST_Force_2d while importing standards and templates

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1618]
Database (postgis 2.1 / pg 9.4) reports deprecation warning:

database_1      | WARNING:  ST_Force_2d signature was deprecated in 2.1.0. Please use ST_Force2D
database_1      | CONTEXT:  SQL function "st_force_2d" during startup
database_1      | WARNING:  ST_Force_2d signature was deprecated in 2.1.0. Please use ST_Force2D
database_1      | CONTEXT:  SQL function "st_force_2d" during startup

**Comment by aJClibre** [comment]
Does the v16.12 resolve this issue ?
Info : the same issue was open for mapserver : https://github.com/mapserver/mapserver/pull/4803

**Comment by fvanderbiest** [comment]
> Does the v16.12 resolve this issue ?

Not to my knowledge.

**Comment by f-necas** [comment]
GN3 not maintained anymore
