### ISSUE TITLE
Make sure CI pulls images before building

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1619]
```
$ find ./ -name Dockerfile -exec grep FROM {} \; | sort | uniq | cut -d ' ' -f 2

debian:jessie
dinkel/openldap
jetty:9.2-jre7
jetty:9.3-jre8
postgres:9.4
tianon/apache2
tomcat:8.0
```

Time also to clean dependencies ;-)

eg:
docker/smtp/webmail/Dockerfile:FROM tianon/apache2

**Comment by pmauduit** [comment]
We are currently building the following images in the CI:

* georchestra/database
* georchestra/ldap
* georchestra/ssh_data

These already do a docker pull before building as of #1620. For `tomcat:8.0`, I have no idea where it comes from ...

**Comment by fvanderbiest** [comment]
> For tomcat:8.0, I have no idea where it comes from ...

```
geonetwork/docker/Dockerfile:FROM tomcat:8.0
```

Let's leave this one alone ;-)

Thanks !

**Comment by fvanderbiest** [comment]
Err...
 * https://hub.docker.com/r/georchestra/ssh_data/tags/ is 4 months old
 * https://hub.docker.com/r/georchestra/ldap/tags/ is 14 days old
 * https://hub.docker.com/r/georchestra/database/tags/ too

**Comment by pmauduit** [comment]
build *pending* ;-)

**Comment by pmauduit** [comment]
Better now.
