### ISSUE TITLE
CI should build & push non-core docker images

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1620]
eg: 
 * `georchestra/database`
 * `georchestra/ldap`
 * `georchestra/ssh_data`

see https://github.com/georchestra/georchestra/blob/master/docker/README.md

**Comment by pmauduit** [comment]
for database and ldap, this is already the case: https://github.com/georchestra/ci-jenkinsfiles/blob/master/docker/Jenkinsfile#L65-L76

I'll add ssh_data

**Comment by pmauduit** [comment]
Done (there was a bug in the CI anyway for the 3 images, build currently running)

**Comment by pmauduit** [comment]
It works (anyway, this CI should be completely reworked ...)
