### ISSUE TITLE
CI should also build georchestra/atlas

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1621]
https://hub.docker.com/r/georchestra/georchestra_atlas/ is 404

It is currently commented out in docker-compose.yml (for memory usage reasons)

**Comment by pmauduit** [comment]
I'd name the docker repository `atlas` instead of `georchestra_atlas`, which is a more "camptocampish" convention, but +1 with this.

**Comment by fvanderbiest** [comment]
correct, https://hub.docker.com/r/georchestra/atlas/ :-)

**Comment by pmauduit** [comment]
and there you go: https://hub.docker.com/r/georchestra/atlas/tags/
