### ISSUE TITLE
geonetwork has no "wait for db" feature

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1623]
... which means that, following strictly https://github.com/georchestra/georchestra/blob/master/docs/docker.md leads to a 503 on http://localhost:8080/geonetwork/ the first time the composition is run, since the DB takes a long time to start (it is populated with test data by default currently)

**Comment by Vampouille** [comment]
We can also use https://github.com/vishnubob/wait-for-it

**Comment by Vampouille** [comment]
Should be fixed with : https://github.com/georchestra/geonetwork/pull/43

**Comment by Vampouille** [comment]
... and See https://github.com/georchestra/geonetwork/pull/44
