### ISSUE TITLE
mapfishapp failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1628]
mapfishapp_1    | SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
mapfishapp_1    | SLF4J: Defaulting to no-operation (NOP) logger implementation
mapfishapp_1    | SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by pmauduit** [comment]
https://github.com/georchestra/georchestra/pull/1649

**Comment by fvanderbiest** [comment]
thanks !
