### ISSUE TITLE
mapfishapp - homogeneize "context" to "map" in the UI interface

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/georchestra#1640]
https://github.com/georchestra/georchestra/tree/master/mapfishapp/src/main/webapp/app/js/GEOR_Lang

**Comment by MaelREBOUX** [comment]
work in progress : fr es de done but for ru...

Is it possible to make a PR from a local fork or it is mandatory to fork on github to make a PR ?

**Comment by fvanderbiest** [comment]
> Is it possible to make a PR from a local fork

This is indeed recommended.

**Comment by MaelREBOUX** [comment]
https://github.com/georchestra/georchestra/pull/1647

**Comment by MaelREBOUX** [comment]
local = only on my computer, not on github. It is no possible.
