### ISSUE TITLE
header - providing a custom logo without compiling

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1642]
We need a way to provide a custom logo without compiling the header webapp.
This is currently all that's left inside https://github.com/georchestra/template/tree/master.

Possibilities:
 * have `/header/img/logo.png` served by the frontend, not by the webapp
 * let the header webapp read the logo from its datadir, and serve it (suboptimal)
 * other ideas ?

**Comment by landryb** [comment]
> have /header/img/logo.png served by the frontend, not by the webapp

That's "clever" and as a sysadmin i like it, but that's too 'different' from other configurable parts of geOrchestra imo..

> let the header webapp read the logo from its datadir, and serve it (suboptimal)

I think that's what ppl deploying and configuring an instance would expect, even if it feels a bit awkward.

**Comment by fvanderbiest** [comment]
> I think that's what ppl deploying and configuring an instance would expect, even if it feels a bit awkward.

Right, I do agree.

**Comment by pmauduit** [comment]
> other ideas ?

An environment variable ? a java.properties ?

The question behind this: is it mandatory that the logo should be served by geOrchestra, or can it be hosted elsewhere ?

**Comment by fvanderbiest** [comment]
I like the idea of having a new `logoURL` property in https://github.com/georchestra/datadir/blob/master/header/header.properties with a default to `/header/img/logo.png` !

**Comment by pmauduit** [comment]
should it be compatible with non-datadir setups ?

**Comment by fvanderbiest** [comment]
The 16.12 release will require a datadir.

**Comment by fvanderbiest** [comment]
https://github.com/georchestra/datadir/commit/c5e7663191dd017665fe6f62bffeaa5d8274c949 adds a logo to the datadir in master branch.

Will also require to update the release notes.

**Comment by fvanderbiest** [comment]
> Will also require to update the release notes.

Done.
