### ISSUE TITLE
extractorapp - extraction stats seems to be stored in lat/lon instead of lon/lat

### ISSUE THREAD

**Issue by Vampouille** [georchestra/georchestra#1646]

**Comment by Vampouille** [comment]
This issue only apply to extractorapp docker images and is fixed by adding : `-Dorg.geotools.referencing.forceXY=true ` in Dockerfile

**Comment by Vampouille** [comment]
We also need to update old database records with : `ST_FlipCoordinates()` :

```sql
UPDATE extractorapp.extractor_layer_log SET bbox = ST_FlipCoordinates(bbox)
```

**Comment by fvanderbiest** [comment]
Done with #1653, thanks @Vampouille !
