### ISSUE TITLE
[Mapfishapp] Print error when load context

### ISSUE THREAD

**Issue by jusabatier** [georchestra/georchestra#1652]
I have an error when loading a context and trying to open print popup :

> Uncaught TypeError: Cannot read property 'getResolution' of null
>     at initialize.getViewPortPxFromLonLat (mapfishapp.js:718)
>     at initialize.move (mapfishapp.js:746)
>     at initialize.setFeature (mapfishapp.js:946)
>     at constructor.onPageChange (mapfishapp.js:971)
>     at h.Event.fire (ext-all.js:21)
>     at constructor.fireEvent (ext-all.js:21)
>     at constructor.updateFeature (mapfishapp.js:1197)
>     at constructor.fit (mapfishapp.js:1196)
>     at constructor.fitPage (mapfishapp.js:971)
>     at constructor.addPage (mapfishapp.js:964)

To reproduce, load a context directly after page loaded, and try to open the print popup.

**Comment by fvanderbiest** [comment]
Right, witnessed on master.
I could reproduce on https://www.ppige-npdc.fr/mapfishapp/ for instance.

**Comment by MaelREBOUX** [comment]
I could reproduce here too. @pierrejego has a patch but not a final solution.

**Comment by pierrejego** [comment]
Hello,
yes we had seen this bug before, but we were not sure it was coming from some modification we have made in WMC or if it was already existing

See https://github.com/GFI-Informatique/georchestra/commit/5448e89ce1be5b5414e7dd23ed8d9ed068e3ec7e  for workaround

**Comment by fvanderbiest** [comment]
Fixed with fbdff69
