### ISSUE TITLE
LDAP Not Ready waiting...

### ISSUE THREAD

**Issue by MaxiReglisse** [georchestra/georchestra#1656]
when i stop and restart docker-compose, there is no problem with data volumes: geochestra-docker stops and restarts, and so everything is OK.
but when i stop the composer, delete the ldap volume data, and restart the composer, then the ldap container does not restart, and one can see "LDAP Not Ready waiting..."

what happens in the ldap data volume ? just before stopping the composer, one can see data are owned by syslog:systemd-bus-proxy

[root@service-info12 ~]# ls -ltr /var/lib/docker/volumes/georchestra_ldap_data/_data/
total 1032
-rw-r--r-- 1 syslog systemd-bus-proxy             96 févr.  6 16:20 DB_CONFIG
-rw------- 1 syslog systemd-bus-proxy         8192 févr.  6 16:20 dn2id.bdb
-rw------- 1 syslog systemd-bus-proxy       65536 févr.  6 16:20 id2entry.bdb
-rw------- 1 syslog systemd-bus-proxy         8192 févr.  6 16:20 member.bdb
-rw------- 1 syslog systemd-bus-proxy         8192 févr.  6 16:20 uid.bdb
-rw------- 1 syslog systemd-bus-proxy         8192 févr.  6 16:20 mail.bdb
-rw------- 1 syslog systemd-bus-proxy       16384 févr.  6 16:20 cn.bdb
-rw------- 1 syslog systemd-bus-proxy         8192 févr.  6 16:20 objectClass.bdb
-rw------- 1 syslog systemd-bus-proxy 10485759 févr.  6 16:20 log.0000000001
-rw-r--r-- 1 syslog systemd-bus-proxy         2048 févr.  6 16:20 alock
-rw------- 1 syslog systemd-bus-proxy     286719 févr.  6 16:26 __db.003
-rw------- 1 syslog systemd-bus-proxy     147455 févr.  6 16:26 __db.002
-rw------- 1 syslog systemd-bus-proxy     589823 févr.  6 16:26 __db.001

but when one deletes the data volume, with the following command, then ownership changes.
`docker rm -f georchestra_ldap_1 && docker volume rm georchestra_ldap_data`

data are owned by root:root, and id2entry.bdb is not recreated.

[root@service-info12 ~]# ls -ltr /var/lib/docker/volumes/georchestra_ldap_data/_data/
total 600
-rw------- 1 syslog systemd-bus-proxy     8192 janv. 16 22:10 lock.mdb
-rw------- 1 syslog systemd-bus-proxy    65536 janv. 16 22:10 data.mdb
-rw------- 1 root   root              10485759 févr.  6 16:27 log.0000000001
-rw-r--r-- 1 root   root                          96 févr.  6 16:27 DB_CONFIG
-rw------- 1 root   root                    57343 févr.  6 16:27 __db.003
-rw------- 1 root   root                  147455 févr.  6 16:27 __db.002
-rw------- 1 root   root                  589823 févr.  6 16:27 __db.001
-rw-r--r-- 1 root   root                      2048 févr.  6 16:27 alock

is this a docker problem ? a docker-compose problem ? or a Dockerfile problem ?

Thanks in advance.

**Comment by fvanderbiest** [comment]
Which branch is it ? 15.12 or master ?
There's recently been work on master regarding LDAP indexes. Might be a regression.

**Comment by MaxiReglisse** [comment]
on master, of course, sir ! ;)

**Comment by fvanderbiest** [comment]
If you delete `georchestra_ldap_data` I recommend that you also delete `georchestra_ldap_config` at the same time, see https://github.com/georchestra/georchestra/blob/master/docker-compose.yml#L24-L34

**Comment by Vampouille** [comment]
I think something change in parent image

**Comment by MaxiReglisse** [comment]
you are right, François : one must remove both containers, data and config. Thanks !
