### ISSUE TITLE
CMD or start.sh

### ISSUE THREAD

**Issue by MaxiReglisse** [georchestra/georchestra#1658]
in the LDAP container, i would like to launch the cron and saslauthd  deamons just before the slapd daemon. for that, i replaced the CMD in the Dockerfile : 
>
CMD [ "slapd", "-d", "32768", "-u", "openldap", "-g", "openldap" ]
>
by
>
CMD ["/root/start.sh"]
>
where start.sh contains : 
>#!/bin/bash
echo "starting cron"
/etc/init.d/cron start
echo "starting saslauthd"
/etc/init.d/saslauthd start
echo "starting ldap"
slapd -d 32768 -u openldap -g openldap
>
I had no problem with that in docker-compose version 1, but it fails with version 2, WHEN i restart the composer ! note that it is ok at the first run.
The log then contains : 
>
5899f2fc @(#) $OpenLDAP: slapd  (Jan 16 2016 23:00:08) $
	root@chimera:/tmp/buildd/openldap-2.4.40+dfsg/debian/build/servers/slapd
5899f2fc hdb_db_open: database "dc=georchestra,dc=org" cannot be opened, err 13. Restore from backup!
5899f2fc bdb(dc=georchestra,dc=org): BDB1566 txn_checkpoint interface requires an environment configured for the transaction subsystem
5899f2fc bdb_db_close: database "dc=georchestra,dc=org": txn_checkpoint failed: Invalid argument (22).
5899f2fc backend_startup_one (type=hdb, suffix="dc=georchestra,dc=org"): bi_db_open failed! (13)
5899f2fc bdb_db_close: database "dc=georchestra,dc=org": alock_close failed
5899f2fc slapd stopped.
>
one may remark that in the docker file system, files ownerships are incorrect :  
>
[root@service-info12 ~]# ls -ltr /var/lib/docker/volumes/georchestra_ldap_data/_data/
total 10936
-rw-r--r-- 1 syslog systemd-bus-proxy       96 févr.  7 17:09 DB_CONFIG
-rw------- 1 syslog systemd-bus-proxy     8192 févr.  7 17:09 dn2id.bdb
-rw------- 1 syslog systemd-bus-proxy    65536 févr.  7 17:09 id2entry.bdb
-rw------- 1 root   root                147455 févr.  7 17:17 __db.002
-rw------- 1 root   root                589823 févr.  7 17:17 __db.001
-rw------- 1 root   root                114687 févr.  7 17:17 __db.003
-rw------- 1 syslog systemd-bus-proxy     8192 févr.  7 17:17 member.bdb
-rw------- 1 syslog systemd-bus-proxy     8192 févr.  7 17:17 uid.bdb
-rw------- 1 syslog systemd-bus-proxy     8192 févr.  7 17:17 mail.bdb
-rw------- 1 syslog systemd-bus-proxy    16384 févr.  7 17:17 cn.bdb
-rw------- 1 syslog systemd-bus-proxy     8192 févr.  7 17:17 objectClass.bdb
-rw------- 1 syslog systemd-bus-proxy 10485759 févr.  7 17:17 log.0000000001
-rw-r--r-- 1 syslog systemd-bus-proxy     4096 févr.  7 17:17 alock
>
if i change the ownerships, with the following command, everything restart !! but it is just a workaround...
>
chown -R syslog:systemd-bus-proxy /var/lib/docker/volumes/georchestra_ldap_data/_data/
>
any help would be appreciate.

**Comment by fvanderbiest** [comment]
> in the LDAP container, i would like to launch the cron and saslauthd deamons

Wrong option.
Only one process per container.

**Comment by MaxiReglisse** [comment]
ok for cron.
but for saslauthd, which works with slapd, i do not know if you can separate the two processes in different containers.

**Comment by fvanderbiest** [comment]
> ok for cron.

See https://hub.docker.com/r/blacklabelops/jobber/ for a replacement.

**Comment by MaxiReglisse** [comment]
my question remains : is it possible to replace 
CMD [ "slapd", "-d", "32768", "-u", "openldap", "-g", "openldap" ]
by
CMD ["/root/start.sh"]
with the following content for start.sh ?
#!/bin/bash
slapd -d 32768 -u openldap -g openldap

**Comment by fvanderbiest** [comment]
It should be the same yes.

**Comment by MaxiReglisse** [comment]
well, it should be, but it is not... from my experience. did you try it ?

**Comment by fvanderbiest** [comment]
> It should be the same yes.

In terms of process, it's not the same, you're right.
To replace the bash process with slapd, you should call `exec slapd -d 32768 -u openldap -g openldap` from your shell script.

**Comment by MaxiReglisse** [comment]
wonderful, François, it works and solve my problem. thanks a lot !!! 
notice that one can run multiple services in a single container with supervisor.
[multiple-entrypoints-in-docker](http://blog.kunicki.org/blog/2016/02/12/multiple-entrypoints-in-docker/)

**Comment by fvanderbiest** [comment]
> notice that one can run multiple services in a single container with supervisor.

this is awful ...
