### ISSUE TITLE
Outil de mesure avancé : erreur echelle

### ISSUE THREAD

**Issue by jusabatier** [georchestra/georchestra#1664]
Les mesures faites via l'outil de mesure avancé semble ne pas être justes : 

Suite à une impression au 1/1000, j'avais placé une mesure de 100m.
Celle-ci fait 14.3cm apres avoir été imprimée, elle devrait faire 10cm.

Visiblement le même problème que celui de la scalebar (https://github.com/georchestra/georchestra/issues/1084).

**Comment by fvanderbiest** [comment]
Yet it was correctly configured with the geodetic parameter ... 

https://github.com/georchestra/georchestra/blob/15.12/mapfishapp/src/main/webapp/app/addons/measurements/js/main.js#L39
