### ISSUE TITLE
mapfishapp - enhance gpx file load (layers management)

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/georchestra#1680]
The GPX file may contains several layers.
Some layers could be fullfilled, others not.

Actually the gpx file load function seems to read only the first layer. If it is empty -> an error occurs.
We should read the file and test all the layers to determine which are loadable.

Read : http://www.gdal.org/drv_gpx.html

**Comment by fvanderbiest** [comment]
GPX support has been removed

**Comment by MaelREBOUX** [comment]
> GPX support has been removed

This is a bad news. I think.
But maybe this function is not very used. Who knows ?
