### ISSUE TITLE
geonetwork - map groups onto orgs ?

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1682]
Currently, GN3 configuration maps "geonetwork groups" onto `EL_*` roles, but we have a better replacement in my opinion now that we have orgs stored in the LDAP.

Opinions ?

This would imply changing those two lines:
 * https://github.com/georchestra/datadir/blob/16.12/geonetwork/geonetwork.properties#L40
 * https://github.com/georchestra/datadir/blob/16.12/geonetwork/geonetwork.properties#L49

**Comment by landryb** [comment]
But then how do you deal with groups which aren't orgs ? think 'all admins', 'all editors', 'users allowed to access this set of metadata'...

**Comment by fvanderbiest** [comment]
You're right.
I'm wondering if we could mix `EL_*` roles and LDAP orgs into GN groups...

**Comment by fvanderbiest** [comment]
Not ready for 18.06, see https://github.com/georchestra/datadir/pull/62#issuecomment-361872784
We need #1887 before merging this.

**Comment by fvanderbiest** [comment]
https://github.com/georchestra/datadir/pull/62 merged
