### ISSUE TITLE
console - prevents creation of role EL_TEST

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1684]
... until one understands that creating role EL **before** is required.

The problem IMO is that the UI does not provide any actionable feedback ...

**Comment by fvanderbiest** [comment]
Maybe we should relax the requirement for a parent role.

**Comment by Vampouille** [comment]
> Maybe we should relax the requirement for a parent role.

or automatically create missing role on server or client side

**Comment by fvanderbiest** [comment]
> or automatically create missing role on server or client side

@tonio does not agree to hide this action

**Comment by fvanderbiest** [comment]
> Maybe we should relax the requirement for a parent role.

18.06 will not require roles to have parents.

**Comment by fvanderbiest** [comment]
deprecated by #1963
