### ISSUE TITLE
console - batch actions on users not implemented

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1688]
The older privateui allowed batch updates on users (delete, roles attribution, etc) but the new console does not allow that.

**Comment by fvanderbiest** [comment]
First implementation required by #1551 ?

**Comment by tonio** [comment]
Suggestion: to avoid inconsistency with role in user form, just add a widget to:
 - Add a role to selection
 - Remove a role from selection

Plus:
 - Delete selection
 - Export Selection

**Comment by fvanderbiest** [comment]
Fixed with https://github.com/georchestra/georchestra/pull/2652
