### ISSUE TITLE
console - does not allow login renaming

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1689]
https://github.com/georchestra/georchestra/commit/d8ce11ee101d08b87b11311f2992b50283af5c9c introduced the possibility to change a user login but this was not implemented in the console, only in privateui (which is now deprecated)

**Comment by landryb** [comment]
linked with #2104, yes please. Right now we want to enforce a login pattern policy, and if we cant we want at least to 'manually' apply this policy (renaming the user) before validating it.

**Comment by landryb** [comment]
Completes what was done in #1109 (backend part)
