### ISSUE TITLE
ldapadmin - remove privateui UI

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1690]
Should we wait at least that https://github.com/georchestra/georchestra/issues/1688 and https://github.com/georchestra/georchestra/issues/1689 are fixed before we delete the older privateui ?

**Comment by fvanderbiest** [comment]
We cannot maintain two UIs anymore.
As a result 17.12 will deprecate the older `privateui`.

**Comment by jusabatier** [comment]
Ok, but the big advantage of private UI is that it allow to assign multiple users to a ROLE at same time.

In the new console, we need to assign role to user one by one. I think this is a regression.

**Comment by fvanderbiest** [comment]
Agreed, but we have no choice here. It's too much of a burden.
