### ISSUE TITLE
mapfishapp - contexts in database / file system

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1692]
Mapfishapp currently leverages two types of WMC contexts: 
 * those from the datadir, manually provided by the administrator with a thumbnail
 * those from the database, automatically inserted on context/permalink generation

In order to ease the process of creating and sharing contexts across users, it would really be interesting to drop support for file-based WMC storage in <datadir>/mapfishapp/contexts, in favor of those coming from the database.

As a result, this UI should be improved in order to support "starred contexts" and thumbnail uploading:
![capture du 2017-03-23 14-07-07](https://cloud.githubusercontent.com/assets/265319/24249074/2649ca28-0fd2-11e7-9c21-1f659a45f34b.png)

If a context is starred by the user creating it, it would automatically be made available to all other users in the "load context" UI.

**Comment by landryb** [comment]
Please dont drop the file-based contexts, that's the only way to track them in git.

**Comment by fvanderbiest** [comment]
Should we favor users (and uses) or administrators ?

**Comment by landryb** [comment]
It's not a question of favoring one or the other, but i still think 'default' contexts provided by the admin should be trackable. If it makes the code flow more complicated, then drop it.,...
