### ISSUE TITLE
console - org perimeter should be optional

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1693]
It currently is mandatory, which is very annoying:

![capture du 2017-03-23 14-12-55](https://cloud.githubusercontent.com/assets/265319/24249271/eba291ce-0fd2-11e7-8c9f-b80167ddc665.png)

This was introduced for the PPIGE project.

**Comment by Vampouille** [comment]
Cannot reproduce, I can create an org without perimeter.

**Comment by Vampouille** [comment]
Here we need to make map display configurable with an option in ldapadmin.properties
