### ISSUE TITLE
[ldapadmin] Problem with sub roles in privateui

### ISSUE THREAD

**Issue by jusabatier** [georchestra/georchestra#1701]
I tried to add role on a group of users in 16.12 and when I want to deploy the sub role COMMUNE_*, the submenu still hidden in the role selection menu : 

![image](https://cloud.githubusercontent.com/assets/8310116/24445687/1506d5b0-146b-11e7-880b-b6f5066a476e.png)

But when looking in html code, the COMMUNE_* submenu exists, but it still not display when hover the italic COMMUNE entry. Probably a bug in the CSS.

**Comment by fvanderbiest** [comment]
Right, I could reproduce, indeed.

**Comment by fvanderbiest** [comment]
Closing, see #1690
