### ISSUE TITLE
geOrchestra on Docker bugs

### ISSUE THREAD

**Issue by gustavopalminha** [georchestra/georchestra#1710]
Hi.

After downloading and installing Xubuntu 16.04 LTS and following the doc at https://github.com/georchestra/georchestra/blob/16.12/docs/docker.md

When I'm about to do a "docker-compose pull" I get an error indicating it cant find the folder /etc/georchestra/postgresql folder.

I'm using docker-compose 1.12.0. I already tested running a "helloworld" container which worked ok.

Thanks

**Comment by fvanderbiest** [comment]
Thanks for the report, we'll have a look at your report asap.

**Comment by fvanderbiest** [comment]
Do you run `docker-compose pull` where you downloaded the docker-compose.yml files ?

**Comment by fvanderbiest** [comment]
Right:
```
$ docker-compose pull
ERROR: build path /tmp/postgresql either does not exist, is not accessible, or is not a valid URL.
```

**Comment by fvanderbiest** [comment]
This is a docker-compose issue / feature see https://github.com/docker/compose/issues/3513
Trying to find a workaround... 
In the mean time, remove the `build: ...` lines in the files your downloaded, and rerun `docker-compose pull`.

**Comment by fvanderbiest** [comment]
I updated the documentation:
https://github.com/georchestra/georchestra/commit/30ef44a68b3459b83a4a3390a1170299f9dd1971
