### ISSUE TITLE
Missing ${JAVA_OPTIONS} in 16.12 Dockerfile 

### ISSUE THREAD

**Issue by Vampouille** [georchestra/georchestra#1712]
JAVA_OPTIONS env var is not used in 16.12 Dockerfiles

**Comment by fvanderbiest** [comment]
How can it be ? Which webapp(s) ?

Geoserver is OK:
https://github.com/georchestra/georchestra/blob/16.12/geoserver/webapp/src/docker/Dockerfile#L34

**Comment by Vampouille** [comment]
> Which webapp(s) ?

This one :
https://github.com/georchestra/georchestra/blob/16.12/ldapadmin/src/docker/Dockerfile

**Comment by fvanderbiest** [comment]
Right, probably a merge issue ...
Good catch !

**Comment by fvanderbiest** [comment]
now fixed.
