### ISSUE TITLE
GN3 integration - login.jsp should redirect onto cas

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#1714]
See https://github.com/georchestra/geonetwork/blob/georchestra-gn3-16.12/core/src/main/java/org/fao/geonet/web/LocaleRedirects.java#L74-L82

**Comment by fvanderbiest** [comment]
How to reproduce: open https://www.geopicardie.fr/geonetwork/srv/fre/admin.console in private browser window => redirected to https://www.geopicardie.fr/geonetwork/srv/fre/catalog.signin?node=srv instead of https://www.geopicardie.fr/cas/login with a valid referer.

**Comment by fvanderbiest** [comment]
Done with https://github.com/georchestra/geonetwork/pull/58
