### ISSUE TITLE
Bad gateway: https://sdi-stable.georchestra.org/

### ISSUE THREAD

**Issue by gustavopalminha** [georchestra/georchestra#1716]
While following up https://github.com/georchestra/georchestra/blob/16.12/docs/build.md docs... we are redirected to https://sdi-stable.georchestra.org/ when reaching:
"Please have a look at our continuous integration. If it builds and yours doesn't, the error is probably on your side."

However its not available, the 502 error bad gateway by nginx error appears.

**Comment by fvanderbiest** [comment]
Right, the provided link in the documentation is incorrect, instead it should be https://packages.georchestra.org/bot/

**Comment by fvanderbiest** [comment]
Fixed with https://github.com/georchestra/georchestra/commit/dc1df26ca2d27a7c0720a9bffe7fbd619d39223c

**Comment by gustavopalminha** [comment]
https://packages.georchestra.org/bot/ returns 403 Forbidden by nginx.
I tried with a couple of web proxy sites and they all return this message. 
I'm sure it's not my connection.

**Comment by fvanderbiest** [comment]
Right, I forgot there was some firewall config restricting access to everyone.
CI is not public anymore => removing the line.

Do you need help building your modules ? Please join us on IRC https://kiwiirc.com/client/irc.freenode.net/georchestra

**Comment by fvanderbiest** [comment]
https://github.com/georchestra/georchestra/commit/4ea6fe39d4cae68af55b78ea301db3b4db9f9d2a

**Comment by landryb** [comment]
We can always make the buildbot public, it was more to avoid bruteforce access on the http auth used to 'control' the jobs...
