### ISSUE TITLE
xubuntu xenial: some packages are missing / obsolete

### ISSUE THREAD

**Issue by gustavopalminha** [georchestra/georchestra#1718]
While following up https://github.com/georchestra/georchestra/blob/16.12/docs/setup.md
some packages aren't available:
>> postgresql-9.4-postgis-2.1 should be changed for postgresql-9.5-postgis-2.2;
>> libgdal1h should be changed for libgdal1i;

**Comment by fvanderbiest** [comment]
Right, the install guide explicitly targets Debian Jessie.
