### ISSUE TITLE
deploy script update for 16.12

### ISSUE THREAD

**Issue by gustavopalminha** [georchestra/georchestra#1722]
While following up the "quick win approach" deployment https://github.com/georchestra/georchestra/blob/16.12/docs/deploy.md the bash script needs update because the war files name do not include the ${PROFILE} in its name.

..should be changed for:
```

VERSION=16.12

mkdir -p /tmp/georchestra
cd /tmp/georchestra
cp `find ~/.m2/repository/ -name "*-${VERSION}.war"` ./
cp ~/.m2/repository/org/geonetwork-opensource/web-app/3.0.4-SNAPSHOT/web-app-3.0.4-SNAPSHOT.war ./

mv security-proxy-${VERSION}.war ROOT.war
mv analytics-${VERSION}.war analytics.war
mv cas-server-webapp-${VERSION}.war cas.war
mv catalogapp-${VERSION}.war catalogapp.war
mv downloadform-${VERSION}.war downloadform.war
mv extractorapp-${VERSION}.war extractorapp.war
mv geoserver-webapp-${VERSION}.war geoserver.war
mv ldapadmin-${VERSION}.war ldapadmin.war
mv mapfishapp-${VERSION}.war mapfishapp.war
mv header-${VERSION}.war header.war
mv web-app-3.0.4-SNAPSHOT.war geonetwork.war

```

**Comment by gustavopalminha** [comment]
The symlink bash script net to the above should also be updated.

**Comment by fvanderbiest** [comment]
Thanks for the feedback on the doc, this is really appreciated.

**Comment by gustavopalminha** [comment]
The "Automating the deploy to remote hosts" "Initial Setup" has a link "..the one provided by the template configuration)." pointing nowhere. The ~/myprofile/DeployScript.groovy doesn't exist.

I think instead of "~/myprofile/DeployScript.groovy" it should be something like "~/myprofile/georchestra/config/configurations/georchestra/DeployScript.groovy"

**Comment by fvanderbiest** [comment]
This module was deprecated with #1854 
Closing.

**Comment by fvanderbiest** [comment]
Investigating the remaining ${PROFILE} issue

**Comment by fvanderbiest** [comment]
Fixed, thanks again for the report !
