### ISSUE TITLE
MapfishApp : interrogation d'un objet / bug affichage des données attributaires / 16.12

### ISSUE THREAD

**Issue by reve973** [georchestra/georchestra#1723]
Scénario : 
  + Ajouter une couche
  + Sélectionner l'onglet Serveur OGC
  + Sélectionner une donnée sur un serveur dont l'URL contient le **workspace** (exemple : https://catalogue.guyane-sig.fr/geoserver/administratif/wms)
  + Ajouter la couche (par exemple : chef_lieu représenté par du ponctuel)
  + Cliquer sur le "i" de la couche ajoutée et interroger un objet
  + Les données attributaires de l'objet sélectionné ne s'affiche pas dans le visualiseur. Par contre, la requête retourne les informations attributaires de l'objet sélectionné.

Le bug provient de l'affichage des données attributaires.

**Comment by fvanderbiest** [comment]
Should be fixed with https://github.com/georchestra/georchestra/pull/1731
