### ISSUE TITLE
MapfishApp - problème d'URL lors de l'accès à la fiche de métadonnées / 16.12

### ISSUE THREAD

**Issue by reve973** [georchestra/georchestra#1724]
Scénario :
- Créer une fiche de métadonnées 
- Ajouter une ressource shapefile
- Publier la ressource sur le serveur de données
- Accéder au visualiseur MapFishApp
- Ajouter la couche de donnée correspondant au shapefile précédemment ajouté
- Accéder à la fiche de métadonnées par le menu action > Afficher la métadonnées et sélectionner Plus
- Une nouvelle page s'ouvre avec l'URL suivante : _https://catalogue.guyane-sig.fr/geonetwork/srv/eng/home?uuid=56d5f0a3-ecff-4af9-ad01-5108f0ba4e1c_ et l'erreur suivante s'affiche _"message": "Service not found" , "class": "ServiceNotFoundEx"_ 

A noter, dans Georchestra 14.12, les URL d'accès aux métadonnées sont de la même forme _https://catalogue.guyane-sig.fr/geonetwork/srv/eng/home?uuid=XXXXXXX_ et provoque du coup les mêmes erreurs lors de la migration.

**Comment by landryb** [comment]
Dans Gn3, les urls d'accès 'unique' aux MD sont de la forme https://ids.craig.fr/geocat/srv/eng/catalog.search#/metadata/{uuid}, l'ancienne url de la forme /srv/{lang}/home?uuid={uuid} a disparu. Perso, je pensais avoir fait une regle de rewrite dans ma conf nginx en local pour gérer ca, mais on dirait que j'ai oublié..

Le problème vient du lien entre la couche geoserver et le lien vers la MD (le metadataURL) qui se fait quand on utilise la geopublication - il crée a la volée un lien avec "l'ancienne forme", cf https://github.com/georchestra/geonetwork/blob/ee0f3a5f7785874930c4848d97057f7db6435356/services/src/main/java/org/fao/geonet/services/publisher/GeoServerRest.java#L683 et https://github.com/georchestra/geonetwork/blob/ee0f3a5f7785874930c4848d97057f7db6435356/services/src/main/java/org/fao/geonet/services/publisher/GeoServerRest.java#L280 - c'est donc dans geonetwork qu'il faut corriger ca, car le meme code est toujours présent upstream dans 3.2.x (https://github.com/geonetwork/core-geonetwork/blob/3.2.x/services/src/main/java/org/fao/geonet/api/mapservers/GeoServerRest.java).

**Comment by reve973** [comment]
La règle de REWRITE semble la meilleur solution en l'état et simplifie la
migration.

J'avais également remarqué le champ METADATA_VIEW_BASE_URL dans le fichier
GEOR_custom.js. Quelqu'un sait à quoi sert cette variable qui semble en
lien avec la fiche de métadonnée ?

*    /***
*     * Constant: METADATA_VIEW_BASE_URL*
*     * The base URL to the "view metadata" service*
*     * Defaults to "/geonetwork/?uuid="*
*     */*
*    METADATA_VIEW_BASE_URL: "/geonetwork/?uuid=",*

**Comment by landryb** [comment]
https://github.com/georchestra/georchestra/search?utf8=%E2%9C%93&q=METADATA_VIEW_BASE_URL&type= -> il est utilisé par le viewer quand on a uniquement l'uuid d'une fiche 'locale' au catalogue, si je me souviens bien.

**Comment by reve973** [comment]
Pour la règle de translation, dans le fichier geonetwork.conf (apache2),
j'ai ajouté :

*RewriteEngine On*
*RewriteCond %{QUERY_STRING} uuid=(.*)$*
*RewriteRule ^/geonetwork/srv/(.*)/home
https://catalogue.guyane-sig.fr/geonetwork/srv/$1/catalog.search#/metadata/%1
[NE]*

Rémi

**Comment by landryb** [comment]
cf geonetwork/core-geonetwork#2970

**Comment by landryb** [comment]
Perso, j'ai *enfin* corrigé ca en local avec:
```
rewrite ^/geocat/srv/.*/home /geocat/?uuid=$arg_uuid redirect;
```
(ca ne prend pas en compte le cas ou ?uuid n'est pas set mais ca évite un if moche..)
