### ISSUE TITLE
postgresql docker image generation is broken

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#1727]
```
Step 10/10 : RUN cd / && patch -p 0 < docker-entrypoint.sh.patch
 ---> Running in b04ab86ffd3d
File docker-entrypoint.sh is not a regular file -- refusing to patch
1 out of 1 hunk ignored -- saving rejects to file docker-entrypoint.sh.rej
The command '/bin/sh -c cd / && patch -p 0 < docker-entrypoint.sh.patch' returned a non-zero code: 1
```

**Comment by pmauduit** [comment]
restricted link to the CI:
https://packages.georchestra.org/ci/job/georchestra-pipelines/job/docker-extra/1/console

**Comment by fvanderbiest** [comment]
Entrypoint script now resides in `/usr/local/bin`, see https://github.com/docker-library/postgres/blob/54053ad27ac099abff3d4964bf7460fb9c541d5d/9.4/Dockerfile#L64

**Comment by Vampouille** [comment]
We can replace docker entrypoint patch with a shell script that will remove content of some sql files if IGNORE_DATA is set. Something like : 

```
#!/bin/bash
if [ "$IGNORE_DATA" == "yes" ]; then
echo -n "" > /docker-entrypoint-initdb.d/*-data.sql
fi
```

**Comment by fvanderbiest** [comment]
Brilliant idea !
