### ISSUE TITLE
Mapfishapp - Styler error on logical filter (NOT)

### ISSUE THREAD

**Issue by Gaetanbru** [georchestra/georchestra#1730]
Hello,
When we create a new condition based on "NOT" logical filter, the rule is  well applied on map but we can't modify this rule again : 

![image](https://cloud.githubusercontent.com/assets/16317988/26487758/19b602d4-4201-11e7-8a4a-5c6e0d9ee39a.png)

Console error : _Uncaught TypeError: Cannot read property 'Filter' of undefined._

**Comment by Gaetanbru** [comment]
After reading the code, i found a syntax error in FilterBuilder.js : 
-  line 608 :    
   type = OpenLayers.Logical.Filter.AND;
- line  610 : 
      type = OpenLayers.Logical.Filter.OR;

"_OpenLayers.Logical_" method not exist.
This should be  "**_OpenLayers.Filter.Logical_**"

**Comment by fvanderbiest** [comment]
I cannot find any occurence of OpenLayers.Logical in the geoext repo.
Are you sure this is not in your fork ?

**Comment by Gaetanbru** [comment]
My screenshot comes from https://sdi-stable.georchestra.org/mapfishapp.
The file concerned Styler externals lib : [here](https://github.com/georchestra/styler/blob/eaf76b044f5124b13c9cd32dabc950ae10828df5/lib/Styler/widgets/FilterBuilder.js#L608).

**Comment by fvanderbiest** [comment]
Nice catch, thanks a lot.

**Comment by Gaetanbru** [comment]
You're welcome!

**Comment by fvanderbiest** [comment]
Fixed with https://github.com/georchestra/styler/pull/16 and in geOrchestra >= 15.12
