### ISSUE TITLE
Mapfishapp - GetCapabilities shall not send FORMAT=image/png

### ISSUE THREAD

**Issue by fphg** [georchestra/georchestra#1757]
Using following endpoint in the WMS panel : https://ogcie.iblsoft.com/observations?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities

Mapfishapp performs https://geobretagne.fr/proxy/?url=https%3A%2F%2Fogcie.iblsoft.com%2Fobservations%3FSERVICE%3DWMS%26VERSION%3D1.3.0%26REQUEST%3DGetCapabilities%26REQUEST%3DGetCapabilities%26SERVICE%3DWMS%26FORMAT%3Dimage%252Fpng

Answer is ```Unsupported GetCapabilities output format 'image/png'``` (```text/xml``` is the correct format)

Correct  : https://geobretagne.fr/proxy/?url=https%3A%2F%2Fogcie.iblsoft.com%2Fobservations%3FSERVICE%3DWMS%26VERSION%3D1.3.0%26REQUEST%3DGetCapabilities

Or : https://geobretagne.fr/proxy/?url=https%3A%2F%2Fogcie.iblsoft.com%2Fobservations%3FSERVICE%3DWMS%26VERSION%3D1.3.0%26REQUEST%3DGetCapabilities%26FORMAT%3Dtext%252Fxml

**Comment by fvanderbiest** [comment]
This is due to : https://github.com/georchestra/georchestra/blob/16.12/mapfishapp/src/main/webapp/app/js/GEOR_ows.js#L118

IIRC, this was required for some older mapserver instances.
It can probably be safely removed nowadays.

**Comment by fvanderbiest** [comment]
Removing it on master branch => should be fixed in v17.12
... or backported to 15.12 / 16.12 if considered safe (please test it)

**Comment by fvanderbiest** [comment]
backported to 16.12 with 3d8a4b8
