### ISSUE TITLE
docker-16.12 : Failed to execute goal on project cachingxslt

### ISSUE THREAD

**Issue by MaxiReglisse** [georchestra/georchestra#1784]
georchestra (16.12), i try to build with the "make docker-build" command but it fails. here are some errors : 
```
[INFO] GeoNetwork opensource .............................. SUCCESS [  0.787 s]
[INFO] Caching xslt module ................................ FAILURE [  0.171 s]
...
[ERROR] Failed to execute goal on project cachingxslt: Could not resolve dependencies for project org.geonetwork-opensource:cachingxslt:jar:2.9.0-SNAPSHOT: Failure to find net.sf.saxon:saxon:jar:9.1.0.8b-patch in http://download.osgeo.org/webdav/geotools/ was cached in the local repository
```

**Comment by MaxiReglisse** [comment]
same problem on the master branch:
[INFO] Building Caching xslt module 2.9.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for net.sf.saxon:saxon:jar:9.1.0.8b-patch is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] GeoNetwork opensource .............................. SUCCESS [  0.463 s]
[INFO] Caching xslt module ................................ FAILURE [  0.140 s]

**Comment by fvanderbiest** [comment]
Looks like a remote issue ?

**Comment by pmauduit** [comment]
The dependency does exist on our repository: https://packages.georchestra.org/maven/repository/net/sf/saxon/saxon/9.1.0.8b-patch/

But it might not be available in the local .m2 repository (not sure another geor webapp outside of GeoNetwork needs it explicitely, also the georchestra maven repository is probably not referenced in the pom.xml, but it should be provided by this one: https://github.com/geonetwork/core-maven-repo/tree/master/net/sf/saxon/saxon/9.1.0.8b-patch).
