### ISSUE TITLE
Docker - Georchestra administration Analytics

### ISSUE THREAD

**Issue by davinciagf** [georchestra/georchestra#1788]
In the administration interface, the analytics tabs isn't available.
Console : 

> GET  https://georchestra.spacebel.be/analytics/ws/app/js/GEOR_custom.js [HTTP/2.0 404 Not Found 42ms]

> ReferenceError: GEOR is not defined[Learn More]  Viewport.js:40:1

**Comment by Vampouille** [comment]
> 404 Not Found

should be fixed by #1792
