### ISSUE TITLE
anonymous extractions fail when downloadform is activated.

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1797]
https://github.com/georchestra/georchestra/blob/16.12/extractorapp/src/main/java/org/georchestra/extractorapp/ws/acceptance/CheckFormAcceptance.java#L46 
This fails for anonymous extractions, since one has to use `IS NULL` rather than `= NULL` in SQL, cc @pmauduit

**Comment by Vampouille** [comment]
Fixed by https://github.com/georchestra/georchestra/pull/1798

**Comment by fvanderbiest** [comment]
Cascade merged up to master
