### ISSUE TITLE
console - roles should be created capitalized

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1813]
... because (IIRC) the sec-proxy uppercases them to create the `sec-roles` header.

Witnessing this on geoserver layer security, all roles are capitalized.

**Comment by fvanderbiest** [comment]
... but GeoNetwork ldap sync does not capitalize ldap EL_* roles.
As a result, GN groups are currently using the same capitalization as their LDAP roles counterpart.

**Comment by fvanderbiest** [comment]
It's not the proxy, but GeoServer's LDAP role service which uppercases the roles, see http://docs.geoserver.org/stable/en/user/security/usergrouprole/roleservices.html#ldap-role-service

**Comment by fvanderbiest** [comment]
Client-side app should uppercase the role name with eg 
```html
<input type="text" style="text-transform:uppercase" />
```

... and the server-side controller should also uppercase the received string, since `text-transform` is purely visual.

**Comment by fvanderbiest** [comment]
We should also prevent accentuated chars !

**Comment by Vampouille** [comment]
> We should also prevent accentuated chars !

Which characters are allowed ? [A-Z_]+ ?

**Comment by fvanderbiest** [comment]
also numbers

**Comment by Vampouille** [comment]
> also numbers

ok so: [0-9A-Z_]+

**Comment by Vampouille** [comment]
Nothing about leading character ? must start with a letter or number ?

**Comment by fvanderbiest** [comment]
Ideally should start with a letter, true.

**Comment by Vampouille** [comment]
Should be fixed with https://github.com/georchestra/georchestra/pull/1925
