### ISSUE TITLE
geonetwork - bug on showing OnlineResources and child-parent resources on the default metadata view

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/georchestra#1820]
On geOrchestra 16.12 and so GeoNetwork 3.0.4 there is a bug that prevent the display of the linked resources and/or the parent or child metadada.

Put in another way : there is a différence between a standalone GN 3.0.4 and an geOrchestra GN 3.0.4 as you can see on the image below.

What I found :
- if the metadata has only some OnlineResources --> it is visible
- if OnlineResources + parent / child --> it is not visible

left : GN in geOrchestra       right : standalone GN

![screenshot039](https://user-images.githubusercontent.com/6370443/33177482-fffd2bd8-d062-11e7-9ac3-b59bf9569cb1.png)

**Comment by fvanderbiest** [comment]
Thanks for the report.
This is indeed a nasty issue.
