### ISSUE TITLE
console - detailed admin actions

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1823]
Give more detail about the actions performed by admin on a given user: which roles changed, were removed, added ...

![capture du 2017-12-01 11-55-31](https://user-images.githubusercontent.com/265319/33479749-8e336210-d68e-11e7-97fb-b68b4408c714.png)

**Comment by Vampouille** [comment]
We should provide a translation of such extended description.

**Comment by fvanderbiest** [comment]
@landryb Is it something you're working on with JDEV ? I'm not sure anymore...

**Comment by Gaetanbrl** [comment]
Yes @fvanderbiest, the work is in progress... see https://github.com/georchestra/georchestra/issues/2267

**Comment by fvanderbiest** [comment]
Closing this one then. Thanks !
