### ISSUE TITLE
console - expanding parent role may lead to broken UI if too many sub-roles

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1825]
![capture du 2017-12-01 12-07-12](https://user-images.githubusercontent.com/265319/33480131-2e1ea0d6-d690-11e7-800e-2d6cc99d603c.png)

**Comment by fvanderbiest** [comment]
@tonio what could be a better layout ? fixed page height ?

**Comment by tonio** [comment]
There's a search tool, maybe just add a max-height and a scroll…

**Comment by fvanderbiest** [comment]
18.06 will remove roles hierarchy, in favor of "favorite roles"

**Comment by fvanderbiest** [comment]
deprecated by #1963
