### ISSUE TITLE
console - description field should allow more text

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1826]
![capture du 2017-12-01 13-02-16](https://user-images.githubusercontent.com/265319/33482150-f67bb3dc-d697-11e7-9a15-488011b3d2a5.png)

**Comment by fvanderbiest** [comment]
... in the limit allowed by LDAP

**Comment by Vampouille** [comment]
> in the limit allowed by LDAP

yes, there is a limitation on LDAP side

**Comment by fvanderbiest** [comment]
Done
