### ISSUE TITLE
no pkill in ldap container

### ISSUE THREAD

**Issue by MaxiReglisse** [georchestra/georchestra#1835]
georchestra_ldap_1 container crashes at startup, with the following message : 

    /docker-entrypoint.d/00-populate: line 54: pkill: command not found
    Waiting for LDAP to stop...Waiting: OK
    run-parts: executing /docker-entrypoint.d/01-indexes
    LDAP indexed
    5a257144 @(#) $OpenLDAP: slapd  (Aug 10 2017 19:12:46) $
	Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>
    5a257144 daemon: bind(6) failed errno=98 (Address already in use)
    5a257144 hdb_db_open: database "dc=georchestra,dc=org": database already in use.
    5a257144 backend_startup_one (type=hdb, suffix="dc=georchestra,dc=org"): bi_db_open failed! (-1)
    5a257144 slapd stopped.

i don't no why this pkill command is missing... but if you add the package procps in Dockerfile, the problem is solved !

étonnant, non ?

**Comment by pmauduit** [comment]
> étonnant, non ?

the ldap docker image should derive from the official debian stretch one, where the `procps` package is no longer installed by default. I already figured out this when trying to launch `ps` in a running container.

The package can be easily added here: https://github.com/georchestra/georchestra/blob/16.12/ldap/Dockerfile#L8

**Comment by pmauduit** [comment]
We did basically the same PR ;-)

**Comment by MaxiReglisse** [comment]
cool !
