### ISSUE TITLE
geonetwork harvester logs are stored in geonetwork_datadir

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1850]
This does not sound like a good idea IMO to store them at the root of the `geonetwork_datadir` volume.
![capture du 2017-12-20 10-34-22](https://user-images.githubusercontent.com/265319/34200447-6b00a87e-e571-11e7-804f-b1181402cb63.png)

**Comment by pmauduit** [comment]
https://github.com/georchestra/geonetwork/blob/georchestra-gn3-16.12/harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java#L164

**Comment by landryb** [comment]
Logs in the datadir ? ew.

**Comment by pmauduit** [comment]
> Logs in the datadir ?

Why not ? Having the possibility to download the logs from the admin web UI is a nice feature, but sure it should be configureable.

**Comment by landryb** [comment]
Fwiw, toying with this, its easy to do in the log4j configuration by declaring a distinct appender for `geonetwork.harvester` class, specifying a subdir:
```
--- a/geonetwork/log4j/log4j.xml
+++ b/geonetwork/log4j/log4j.xml
@@ -1,6 +1,13 @@
 <?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">
 <log4j:configuration debug="false">
+    <appender name="harvestAppender" class="org.apache.log4j.FileAppender">
+        <param name="Threshold" value="ALL" />
+        <param name="File" value="/srv/log/tomcat/harvester/harvester.log" />
+        <layout class="org.apache.log4j.PatternLayout">
+            <param name="ConversionPattern" value="%d{ISO8601} %-5p [%c] - %m%n" />
+        </layout>
+    </appender>
     <appender name="fileAppender" class="org.apache.log4j.rolling.RollingFileAppender">
         <param name="Threshold" value="ALL" />
         <param name="File" value="/srv/log/tomcat/geonetwork.log" />
@@ -69,7 +76,7 @@
     </logger>
     <logger name="geonetwork.harvester" additivity="false">
         <level value="INFO" />
-        <appender-ref ref="fileAppender" />
+        <appender-ref ref="harvestAppender" />
     </logger>
     <logger name="geonetwork.lucene">
         <level value="WARN" />
```

which gives, after a webapp restart:
```
-rw-r--r-- 1 tomcat tomcat 0 Aug 29 15:13 /srv/log/tomcat/harvester/harvester_geonet_Clermont_Communaut__201808291513.log
-rw-r--r-- 1 tomcat tomcat 0 Aug 29 15:13 /srv/log/tomcat/harvester/harvester_geonet_Le_Puy_en_Velay_201808291513.log
-rw-r--r-- 1 tomcat tomcat 0 Aug 29 15:13 /srv/log/tomcat/harvester/harvester_ogcwxs_tiles_ign_201808291513.log
-rw-r--r-- 1 tomcat tomcat 0 Aug 29 15:13 /srv/log/tomcat/harvester/harvester.log
```

This way one can control the subdir where harvesting logs end up, instead of cluttering *where geonetwork.log is located*. Which is gross, since there's a distinct file per harvest instance/run...
```
$ls /srv/log/tomcat/harvester*log|wc -l
375
```

**Comment by fvanderbiest** [comment]
Landry, you're a genius ;-)

**Comment by severo** [comment]
See https://github.com/georchestra/datadir/pull/86

**Comment by severo** [comment]
Before closing -> https://github.com/georchestra/datadir/pull/86#issuecomment-450903417
