### ISSUE TITLE
Check geoserver 2.12 works with geofence

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1855]
Preliminary work (https://github.com/georchestra/georchestra/pull/1847#issuecomment-353376994) shows that this is not straightforward...

**Comment by pmauduit** [comment]
Seems working for me, just a glitch with calling `/geoserver/`, it redirects to geowebcache instead of the expected gs web interface ...

**Comment by pmauduit** [comment]
It would require a little bit of work to resolve the default redirect to gwc

**Comment by fvanderbiest** [comment]
On my setup, compiling with `make docker-build-geoserver-geofence` leads to a broken https://georchestra.mydomain.org/geoserver/web/wicket/bookmarkable/org.geoserver.geofence.web.GeofenceServerPage page with
```
Caused by: java.lang.NullPointerException
	at org.hibernate.impl.SessionFactoryImpl.getClassMetadata(SessionFactoryImpl.java:805)
	at com.googlecode.genericdao.search.hibernate.HibernateMetadataUtil.get(HibernateMetadataUtil.java:92)
	at com.googlecode.genericdao.dao.jpa.JPABaseDAO._all(JPABaseDAO.java:206)
	at com.googlecode.genericdao.dao.jpa.GenericDAOImpl.findAll(GenericDAOImpl.java:61)
	at org.geoserver.geofence.core.dao.impl.RuleDAOImpl.findAll(RuleDAOImpl.java:101)
```

**Comment by fvanderbiest** [comment]
Probably due to

geoserver_1                 | ERROR SchemaUpdate could not complete schema update org.hibernate.MappingException: No Dialect mapping for JDBC type: 2002
geoserver_1                 | 	at org.hibernate.dialect.TypeNames.get(TypeNames.java:78)
geoserver_1                 | 	at org.hibernate.dialect.TypeNames.get(TypeNames.java:103)
geoserver_1                 | 	at org.hibernate.dialect.Dialect.getTypeName(Dialect.java:249)
geoserver_1                 | 	at org.hibernate.mapping.Column.getSqlType(Column.java:208)
geoserver_1                 | 	at org.hibernate.mapping.Table.sqlCreateString(Table.java:418)

**Comment by fvanderbiest** [comment]
Setting `geofenceEntityManagerFactory.jpaPropertyMap[hibernate.hbm2ddl.auto]=update` in https://github.com/georchestra/datadir/blob/master/geoserver/geofence/geofence-datasource-ovr.properties does not help

**Comment by fvanderbiest** [comment]
Now https://github.com/georchestra/georchestra/blob/master/postgresql/08-geofence.sql misses the `GF_ADMINRULE` table:
```
geoserver_1                 | ERROR JDBCExceptionReporter Table GF_ADMINRULE not found; SQL statement:
geoserver_1                 | select adminrule0_.id as id6_, adminrule0_.grant_type as grant2_6_, adminrule0_.ip_high as ip3_6_, adminrule0_.ip_low as ip4_6_, adminrule0_.ip_size as ip5_6_, adminrule0_.instance_id as instance10_6_, adminrule0_.priority as priority6_, adminrule0_.rolename as rolename6_, adminrule0_.username as username6_, adminrule0_.workspace as workspace6_ from public.gf_adminrule adminrule0_ [42102-119]
```

**Comment by fvanderbiest** [comment]
The table is dynamically generated via https://github.com/geoserver/geofence/blob/f74fd0e0dae19294df220d5ccf6c9aacd9ad7264/src/services/core/model/src/main/java/org/geoserver/geofence/core/model/AdminRule.java#L42-L43

I'm wondering whether this https://github.com/georchestra/georchestra/blob/master/postgresql/08-geofence.sql file is still relevant at all : maybe we should let geofence manage its own tables.
ping @Vampouille

**Comment by fvanderbiest** [comment]
Missing 
-Dgeofence-ovr=file:/etc/georchestra/geoserver/geofence/geofence-datasource-ovr.properties option, hopefully fixed with 48dda74160656a2f8fdcdc8dc22817e388c64701

**Comment by fvanderbiest** [comment]
GeoFence schema update with 847046b, according to its internal tables definition

**Comment by fvanderbiest** [comment]
Now it works on master !
