### ISSUE TITLE
Update release notes with the sp-trust-sp feature

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1873]
See https://github.com/georchestra/georchestra/pull/1674

**Comment by Vampouille** [comment]
We also need to merge : https://github.com/georchestra/datadir/pull/54

**Comment by Vampouille** [comment]
A french version : 

### Description
Le security proxy est maintenant capable de 'truster' les requêtes issues d'un autre security proxy. C'est à dire que toutes les requêtes issue du premier security proxy seront forwardées tel quel au webapp applicative (geoserver, ldapadmin, ...) sans vérifier l'existence du compte utilisateur. Au niveau de la configuration du security proxy, une propriété 'trustedProxy' liste les adresses IP depuis lesquelles les requêtes seront 'trustées'. Par défaut, cette propriété vaut '127.0.0.1, localhost'. Attention il faut uniquement mettre des serveurs de confiance dans cette liste.

En pratique, sur le deuxième SP, les headers de sécurité :
* sec-username
* sec-email
* sec-orgs
* ... 
seront transmises à l'application cible sans vérification et cette requête sera ajoutée dans les logs avec les informations issues des headers même si le compte n'existe pas au niveau du deuxième SP.

```
Client --> SP(1) --> SP(2) --> ldapadmin
                        | 
                        |----> geoserver
                        |
                        -----> mapfishapp
```

### Mise en place

* Au niveau du SP(1) il faut modifier le fichier targets-mapping.properties afin de faire pointer les URL voulues vers le SP(2):

```properties
geoserver=http://sp2:8080/geoserver/
ldapadmin=http://sp2:8080/ldapadmin/
mapfishapp=http://sp2:8080/mapfishapp/
```

* Au niveau du SP(2), il faut ajouter l'adresse du SP(1) au niveau de la propriété 'trustedProxy'

La mise en place necessite un SP avec la fonctionnalité 'SP trust SP' uniquement au niveau du SP(2)

**Comment by fvanderbiest** [comment]
Translated with 57e92e3ff116fa40ccbd438c9ad186cda19aee26, thanks Julien !
