### ISSUE TITLE
SP/CAS - CAS behind the SP is broken

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#1889]
Encountered on master (17.12), on docker.georchestra.org test environment: it seems no longer possible to security-proxify CAS (i.e. having CAS behind the Security-Proxy). When trying to log into CAS, you will be redirected to the same login form over and over again.

This was working earlier, but now you will have to hit CAS directly to have geOrchestra working. I don't know if we want to fix this behaviour anyway.

**Comment by fvanderbiest** [comment]
Should impact our docker-composition since cas is proxied, cf https://github.com/georchestra/datadir/blob/a4619de56f0b2935a4a040bb3c3335696148c8ca/security-proxy/targets-mapping.properties#L4

**Comment by fvanderbiest** [comment]
> Should impact our docker-composition since cas is proxied

I can confirm this, our docker-composition needs to be updated, or this issue fixed...

**Comment by fvanderbiest** [comment]
> our docker-composition needs to be updated

Done with 08b33b760ca0167dffe48c738a5cba0fe409e6ee and https://github.com/georchestra/datadir/commit/7c9f6849899b441d3dc7a9830acc689f428f26bf
