### ISSUE TITLE
mapfishapp - jsbuild might fail to install jstools

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#1905]
Maybe other webapps impacted, see https://github.com/pypa/pip/issues/4817#issuecomment-345526042 for a workaround.

I cannot reproduce on my dev env, but Rennes-Metropole is impacted:

```
Cannot fetch index base URL 
http://pypi.python.org/simple/
[INFO]   Could not find any downloads that satisfy the requirement jstools==0.6
[INFO] No distributions at all found for jstools==0.6
[INFO] Storing complete log in /home/deploy/.pip/pip.log
[INFO] done.
```

**Comment by pmauduit** [comment]
tcpdump'ing trafic with pypi.python.org, we figure out that the packages are fetched using http which is no longer accepted by the remote server, forcing https in the pip install (see previous commit mentioned above) command fixes it.

**Comment by fvanderbiest** [comment]
IIRC there's also extractorapp/jsbuild/build.sh to fix...
