### ISSUE TITLE
gn3.4 submodule broken ref

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1907]
~/workspace/georchestra/georchestra (master *$%)$ git submodule update --init
fatal: la référence n'est pas un arbre : e6b64bdd49e2f2e8adb747e53683c39941c6cc2a
Impossible d'extraire 'e6b64bdd49e2f2e8adb747e53683c39941c6cc2a' dans le chemin de sous-module 'geonetwork'

**Comment by pmauduit** [comment]
Sorry, I forgot to push onto geonetwork. Done.
