### ISSUE TITLE
[Doc] Packages not available in Stretch

### ISSUE THREAD

**Issue by jusabatier** [georchestra/georchestra#1912]
I tried to setup a GS in stretch, and it seems like libjai-imageio-core-java package doesn't exists in stretch repositories.

**Comment by jusabatier** [comment]
Following this doc seems to work, but documentation need update for 17.12

http://docs.geoserver.org/stable/en/user/production/java.html#install-native-jai-and-imageio-extensions

**Comment by jusabatier** [comment]
Same problem for GDAL wich is now in version 2 : 

`apt-get install libgdal20 libgdal-java`

in https://github.com/georchestra/georchestra/blob/17.12/docs/setup/native_libs.md

**Comment by fvanderbiest** [comment]
You're right, thanks Julien !
Can you create a PR ?

**Comment by fvanderbiest** [comment]
But I'm not sure native jai is still required since jai-ext replaces it.

**Comment by jusabatier** [comment]
So we should just remove the JAI install part from the doc ?

**Comment by fvanderbiest** [comment]
yep

**Comment by jusabatier** [comment]
But in the geoserver doc, they say : "By default, GeoServer ships with the “pure java” version of JAI, but for better performance JAI and ImageIO are available as “java extensions” to be installed into your JDK/JRE."

And JAI/ImageIO availability still visible in Service state page of Geoserver 2.12

**Comment by fvanderbiest** [comment]
Yes, we should test the performance difference carefully eg using https://github.com/camptocamp/ms_perfs
Anyway, I don't like the idea of using files from http://data.opengeo.org/suite/jai/ rather than those provided by distribution packages.

**Comment by fvanderbiest** [comment]
Andrea provides a helpful response on https://gis.stackexchange.com/questions/255206/geoserver-which-library-for-boosting-raster-wms-output-generation regarding JAI / JAI-ext compared performances.

**Comment by groldan** [comment]
yup, takeaways:
- Native ImageIO is useless once you have libjpeg-turbo
- JaiExt has NODATA handling, slower than JAI, but we already are required to serve image mosaics which require proper NODATA handling in order to overlap without black artifacts, especially when reprojecting, so pay the price.

**Comment by groldan** [comment]
Also, if I'm not wrong, native JAI would only speed up reading rasters from disk, for which btw it's more important to have them properly optimized for fast consumption. My preference being getting rid of native jai and imageio, err on the side of correctness and simplicity, check back if there's a complain and a budget.

**Comment by fvanderbiest** [comment]
Thanks Gabriel !

**Comment by fvanderbiest** [comment]
Fixed with 1abc317cadfb71ec8d73d804037ae57d74b04302
