### ISSUE TITLE
[ci/packaging] differentiate debian package versions by default

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#1931]
As of now the Makefile `deb-build-*` targets don't set `-Ddeb.package.version` so packages end up always the same version number (ie georchestra-geoserver_17.12-1_all.deb) - whatever the commit you're building from in your current branch. That's not ideal to find regressions/etc - as the build should be deterministic (ie a given version of a package should match 'what version of the tree it has been built from)

An option is to set the build date (so that you know when you built) ie -Ddeb.package.version=${project.version}+201803132128 (that's what is done for 16.12 packages) but that's still not perfect as it doesnt give you the commit hash.. is there something in maven that allows you to get the sha of the current commit ? Or should the makefile target use git show to get the hash, and use that in the version ?

Either way, it would be nice to set deb.package.version in the Makefile to something meaningful *by default*. And while here, should the same sha/identifier be appended to the generic wars, or this information is already bundled somewhere inside the war ?

**Comment by landryb** [comment]
the git sha should be available via the git-commit-id-plugin maven plugin (which is already loaded by maven ?), but trying to set -Ddeb.package.revision to something on the commandline or adding <packageRevision>${git.commit.id.abbrev}</packageRevision> after https://github.com/georchestra/georchestra/blob/17.12/geoserver/webapp/pom.xml#L1048 doesnt override the default -1 revision.

I'm not sure how the git-commit-id-plugin is supposed to work, it seems only geonetwork has `git.properties` files:
```
./geonetwork/web/src/main/webResources/WEB-INF/classes/git.properties
./geonetwork/web/target/geonetwork/WEB-INF/classes/git.properties
./geonetwork/web/target/webapp/WEB-INF/classes/git.properties
```

**Comment by landryb** [comment]
Setting -Ddeb.package.revision on the command line to an arbitrary number or setting `<packageRevision>` in the debian-maven-plugin configuration seems to work, but trying to use values supposedly gathered from git-commit-id-plugin doesnt work. Is this plugin actually used in georchestra and we know it works ?

**Comment by landryb** [comment]
Okay, found it - setting `<prefix>` in the git-commit-id-plugin configuration uses it for properties names, so i need to set `<packageRevision>` to `${build.commit.id}` and voila:

```
georchestra-cas_17.12-f9030e264bb274516b54683352cbfb14ecdc1495_all.deb
```
Of course `${build.commit.id.abbrev}` is better :)

**Comment by landryb** [comment]
And finally with a bit more of maven magic (oh $DEITY) i also get the build date in the revision, this way we're sure it goes forward:
```
georchestra-cas_17.12-20180316-2054~f9030e2_all.deb
```
With this we know:
  * which branch we're on
  * when the package was built
  * from which toplevel/georchestra revision

@pmauduit @fvanderbiest does this look good ? I'll do a pr with that.

**Comment by landryb** [comment]
Cf #1936 and georchestra/geonetwork#63

**Comment by landryb** [comment]
problem to consider before merging: when building master, -SNAPSHOT is replaced by the date and thus there are two dates in the resulting name. We need to find a way to keep the version... @pierrejego any idea, as a maven wizard ?

**Comment by landryb** [comment]
Oh, and we need to find a way to put the version in the war name too, not only the deb package

**Comment by pierrejego** [comment]
One idea is to set <packageVersion> in debian with a new field as already done with <packageRevision>

This field coud be set in the ant-run part from debian with a condition on ${project.version}

**Comment by landryb** [comment]
ok got something that 'works' in all cases. The key was bumping the maven-antrun-plugin dependency to 1.7 as exportAntProperties only exists since this version.. and apparently the 1.6 dep in the child pom.xml was ignoring it even if you set it in the parent pom.

**Comment by pmauduit** [comment]
After merge of previous PR, we still need to update the GN submodule in master.

**Comment by landryb** [comment]
Building my PR on master results in the following packages:
```
$find . -path '*target*' -name '*.deb'
./atlas/target/georchestra-atlas_99.master-20180615-0752~e84b516_all.deb
./geowebcache-webapp/target/georchestra-geowebcache_99.master-20180615-0752~e84b516_all.deb
./header/target/georchestra-header_99.master-20180615-0752~e84b516_all.deb
./mapfishapp/target/georchestra-mapfishapp_99.master-20180615-0752~e84b516_all.deb
./extractorapp/target/georchestra-extractorapp_99.master-20180615-0752~e84b516_all.deb
./cas-server-webapp/target/georchestra-cas_99.master-20180615-0752~e84b516_all.deb
./analytics/target/georchestra-analytics_99.master-20180615-0752~e84b516_all.deb
./geoserver/webapp/target/georchestra-geoserver_99.master-20180615-0752~e84b516_all.deb
./security-proxy/target/georchestra-security-proxy_99.master-20180615-0752~e84b516_all.deb
./console/target/georchestra-console_99.master-20180615-0752~e84b516_all.deb
./geonetwork/web/target/georchestra-geonetwork3_3.4.1-0-20180615-0752~e84b516_all.deb

```

**Comment by landryb** [comment]
Now that everything is merged, buildbot processed the changes.. and reprepro (the part pushing the debian package to the debian repo) bails out because it strips the revision, and doesnt want to overwrite a package with the same version and a different checksum, *even if the revision differs*. *SIGH*
```
[WARNING] ERROR: '/home/buildslave/buildjob/build/cas-server-webapp/target/georchestra-cas_16.12-20180626-1832~7060d2b_all.deb' cannot be included as 'pool/main/g/georchestra-cas/georchestra-cas_16.12_all.deb'.
[WARNING] Already existing files can only be included again, if they are the same, but:
[WARNING] md5 expected: 43a537f89a908a85052167ce552a718e, got: 7049e0b3ced79597c0154b07616aa771
```
So, to achieve what we want for debian packages:
* having the git sha in the version so that one knows what commit he's running
* having updates working, which means a version number that goes forward

I think we need to: 
* give up on packageRevision as reprepro doesnt handle it (should have known, but oh well)
* set packageVersion to branch+builddate~sha

**Comment by landryb** [comment]
31fc62d generates the following packages:
```
analytics/target/georchestra-analytics_99.master.201806262006~87597cc-1_all.deb
atlas/target/georchestra-atlas_99.master.201806262006~87597cc-1_all.deb
cas-server-webapp/target/georchestra-cas_99.master.201806262006~87597cc-1_all.deb
console/target/georchestra-console_99.master.201806262006~87597cc-1_all.deb
extractorapp/target/georchestra-extractorapp_99.master.201806262006~87597cc-1_all.deb
geonetwork/web/target/georchestra-geonetwork3_3.4.1-0-1_all.deb
geoserver/webapp/target/georchestra-geoserver_99.master.201806262006~87597cc-1_all.deb
geowebcache-webapp/target/georchestra-geowebcache_99.master.201806262006~87597cc-1_all.deb
header/target/georchestra-header_99.master.201806262006~87597cc-1_all.deb
mapfishapp/target/georchestra-mapfishapp_99.master.201806262006~87597cc-1_all.deb
security-proxy/target/georchestra-security-proxy_99.master.201806262006~87597cc-1_all.deb
```

geonetwork still needs special treatment for some reason... i need to find a way to propagate the project.packageVersion from the parent pom.xml to geonetwork/pom.xml, or copy the way it is created there i guess.

**Comment by landryb** [comment]
Cf #2091 which gives:
```
$for f in */target/*.deb ; do dpkg --info $f |grep Vers; done
 Version: 99.master.201806262006~87597cc
 Version: 99.master.201806262006~87597cc
 Version: 99.master.201806262006~87597cc
 Version: 99.master.201806262006~87597cc
 Version: 99.master.201806262006~87597cc
 Version: 99.master.201806262006~87597cc
 Version: 99.master.201806262006~87597cc
 Version: 99.master.201806262006~87597cc
 Version: 99.master.201806262006~87597cc
```
in the master branch. Will do the same test for 17.12.

**Comment by landryb** [comment]
There's still a minor buglet: `project.packageVersion` is set only if the `package` phase is run, so if you only do `deb:package deb:deploy` after having done `package` in a previous mvn run the version wont be applied, but that can be fixed in a second time, and the buildbot/jenkins jobs now provide packages with meaningful versions. So closing this issue.
