### ISSUE TITLE
[ci/packaging] Differentiate geoserver with and without geofence

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#1932]
Right now in https://github.com/georchestra/georchestra/blob/17.12/Makefile#L71 there's an alternative to build geoserver with or without geofence, but that difference is explicitely shown nowhere in the resulting wars/packages.

Would it be possible to suffix this in the war/package name so that both can be provided by a CI without having to make a choice between one or the other ? ie maybe georchestra-geoserver & georchestra-geoserver-geofence (& geoserver/geoserver-geofence for the war)

Up to the ppl deploying to choose the one he/she wants and name it accordingly when dropping the war in tomcat, but at least the choice is provided to the user.

**Comment by pmauduit** [comment]
> but that difference is explicitely shown nowhere in the resulting wars/packages.

First, your war package should contain some `*geofence*` jars in `WEB-INF/libs`. You can test it with `jar tf mywebapp.war` or simplier `unzip -t`.

For the version suffix, you can try passing `-Ddeb.package.version=17.12~geofence` to your maven command (see http://debian-maven.sourceforge.net/usage.html)

**Comment by landryb** [comment]
> For the version suffix, you can try passing -Ddeb.package.version=17.12~geofence to your maven command (see http://debian-maven.sourceforge.net/usage.html)

I'm not sure that would solve the problem as i'm not sure a repository can provide different versions of the same package name..

**Comment by pmauduit** [comment]
`-Ddeb.package.name=geoserver-geofence` then ?

**Comment by landryb** [comment]
Ah, so there's an option in the maven debian plugin.. will try it, but then i think the two packages will need to have a conflict marked as the war names will stay the same, unless there's another maven option to change the war name.

Ultimately this should get commited to the Makefile so that the CI picks it up :)

**Comment by landryb** [comment]
Ah - think i found one way. In https://github.com/georchestra/georchestra/blob/17.12/Makefile#L90 - only the `debianPackage` profile is passed to maven, while if i use `-PdebianPackage,geofence` then the resulting debian package is correctly set to `georchestra-geoserver-geofence`.

Now to figure out how to differentiate the war name...

**Comment by landryb** [comment]
Okay, i have something that works but is a bit of a hack imo:
```
diff --git a/Makefile b/Makefile
index e6ad2651b..72906ae4d 100644
--- a/Makefile
+++ b/Makefile
@@ -89,7 +89,7 @@ deb-build-geoserver: war-build-geoserver

 deb-build-geoserver-geofence: war-build-geoserver-geofence
        cd geoserver; \
-       ../mvn clean package deb:package -PdebianPackage --pl webapp
+       ../mvn clean package deb:package -PdebianPackage,geofence -Dserver=geofence-generic --pl webapp

 deb-build-georchestra: war-build-georchestra build-deps deb-build-geoserver
        ./mvn package deb:package -pl atlas,cas-server-webapp,security-proxy,header,mapfishapp,extractorapp,analytics,geoserver/webapp,ldapadmin,geonetwork/web,geowebcache-webapp -PdebianPackage -DskipTests
diff --git a/geoserver/webapp/pom.xml b/geoserver/webapp/pom.xml
index dec8ddbd4..cb74f3527 100644
--- a/geoserver/webapp/pom.xml
+++ b/geoserver/webapp/pom.xml
@@ -975,8 +975,10 @@
     </profile>
     <profile>
       <id>debianPackage</id>
+      <properties>
+       <server>generic</server>
+      </properties>
       <build>
-        <finalName>geoserver-generic</finalName>
         <plugins>
           <plugin>
             <groupId>org.apache.maven.plugins</groupId>
```
With that, `make deb-build-geoserver` produces a war named `geoserver-generic.war` packaged in a debian package named `georchestra-geoserver`, and `make deb-build-geoserver-geofence` produces a war named `geoserver-geofence-generic.war` packaged in a debian package named `georchestra-geoserver-geofence`.

On top of that i think `war-build-geoserver-geofence` target should be amended to also set the correct war name.. or since this target only does 'mvn clean install' it doesnt generate a war at all, and is badly named ?

@pmauduit what's your opinion on this way of doing things ?

**Comment by pmauduit** [comment]
> @pmauduit what's your opinion on this way of doing things ?

as said on IRC, the -Dserver is normally to select the correct config.jar based on the suffix, that is pretty weird it works this way, but maybe because config.jar is not a dependency on geoserver anymore (since we want to remove it).
I would instead parameterize the package name so that you can override it using its own dedicated variable

**Comment by landryb** [comment]
So having a new property 'warSuffix' defaulting to the value of server ?
