### ISSUE TITLE
Console - Missing test data and ORGADMIN role

### ISSUE THREAD

**Issue by Vampouille** [georchestra/georchestra#1986]
Test data for delegation need to be updated:
* Replace "testadmin" with no admin user
* Create another org 
* Use existing org

**Comment by fvanderbiest** [comment]
Not sure I understand correctly if your issue was fixed with #1987

**Comment by Vampouille** [comment]
> Not sure I understand correctly if your issue was fixed with #1987

Yes #1987 fix this issue !
