### ISSUE TITLE
Login and logout in CAS

### ISSUE THREAD

**Issue by mpintogeo** [georchestra/georchestra#1991]
Hi, I am working in GeoBolivia and I had some problems when I want to login and logout.
First, when I login, I had 404 error using https://georchestra.mydomain.com/j_spring_cas_security_check url. I had to change to https://georchestra.mydomain.com/login/cas and It worked. Then when I was logged, I want to logout but the https://georchestra.mydomain.org/j_spring_security_logout url gives 404 error.
What changes do I have to do?

**Comment by Vampouille** [comment]
Hello, you also need to change your logout URL. First, configure security-proxy by editing `security-proxy.properties`, take a look at : 
https://github.com/georchestra/datadir/blob/master/security-proxy/security-proxy.properties#L10
Then, on header, logout URL should be `/logout`

**Comment by mpintogeo** [comment]
Hello @Vampouille, I have configured security-proxy and forcing in url "/logout" works well. But the button "logout" has "https://georchestra.mydomain.org/j_spring_security_logout" url and It gives 404 error.

**Comment by pmauduit** [comment]
You will have to update your header webapp, because of this commit: https://github.com/georchestra/georchestra/commit/2989d8c0a49219a5343faf1c0c03dca828ae99ba

**Comment by mpintogeo** [comment]
@pmauduit Thanks for help, Im using docker and I cannot find these files, how can I update in docker?

**Comment by fvanderbiest** [comment]
> I cannot find these files

You mean the [datadir](https://github.com/georchestra/datadir/) ?
Well it depends on your setup (have a look at your `docker-compose.yml` file): it could be located in a local volume (FS mount) or a named volume.

> how can I update in docker?

`docker-compose pull` should be enough.
Reminder: using docker images from the `master` branch is dangerous !

**Comment by mpintogeo** [comment]
@fvanderbiest Thanks for help, so which branch is recommended?

**Comment by mpintogeo** [comment]
@fvanderbiest 
docker-compose pull should be enough.  works thanks for help, but which branch recommend for docker?

**Comment by fvanderbiest** [comment]
> which branch recommend for docker?

The stable one, 17.12.
But then you have to [build the containers by yourself](https://github.com/georchestra/georchestra/blob/17.12/docker/README.md) since a policy forbids us to provide stable docker images.
