### ISSUE TITLE
Geoserver - update to 2.13.0 tag

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#1993]
A quick test was made here:
https://github.com/georchestra/georchestra/tree/gs-2.13.0

Almost no problem (tested with GeoFence), but on GGE instance, it seems that an issue with the datadir causes the REST endpoint (layers.xml) failing. Also I had to deactivate 2 tests related to GeoFence, and the cache invalidation feature in the UI is broken.

**Comment by fvanderbiest** [comment]
Related PR is #1995

**Comment by fvanderbiest** [comment]
Merged
