### ISSUE TITLE
console - empty error flash message displayed during app load

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2004]
![capture du 2018-04-19 10-41-21](https://user-images.githubusercontent.com/265319/38980936-6b8bdb46-43be-11e8-8576-e34e73f8109c.png)

Where does this come from ?
Can it be removed ?

**Comment by tonio** [comment]
This may happen with an incomplete composition (ie. missing analytics).
PR to come with a better error message.

**Comment by fvanderbiest** [comment]
Indeed. Thanks

**Comment by fvanderbiest** [comment]
fixed with #2058, thanks !
