### ISSUE TITLE
console - two orgs fields on /console/account/new

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2010]
![capture du 2018-04-19 15-08-04](https://user-images.githubusercontent.com/265319/38993302-83b35dd2-43e3-11e8-867b-d1782c899831.png)

Probably a merge issue after captcha v2.
Might be an issue to fix from 16.12 on...

**Comment by Vampouille** [comment]
Should be fixed by #2016

**Comment by Vampouille** [comment]
Merged into 17.12 and master
