### ISSUE TITLE
SP - messes accentuated chars

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2018]
Searching "émissions" yields 2 results:
![capture du 2018-04-25 15-18-48](https://user-images.githubusercontent.com/265319/39248315-0560eaa4-489c-11e8-89f6-4c1ee3771981.png)
But the word "émissions" is not found in both MD !

Searching "emissions" yields 3 valid results:
![capture du 2018-04-25 15-18-33](https://user-images.githubusercontent.com/265319/39248318-08451736-489c-11e8-8ae5-12dca1558fa1.png)

**Comment by fvanderbiest** [comment]
![capture du 2018-05-03 09-12-08](https://user-images.githubusercontent.com/265319/39563841-1347cd92-4eb2-11e8-937a-4ba7c888abf7.png)

**Comment by fvanderbiest** [comment]
Matching metadata for "émissions" is 
[export-full-1525331878788.zip](https://github.com/georchestra/georchestra/files/1969910/export-full-1525331878788.zip) (in which only "mission" can be found, not "émissions")

**Comment by fvanderbiest** [comment]
The SP is the culprit : it messes accentuated chars !
Witnessed on master. Might impact 17.12 as well.

**Comment by fvanderbiest** [comment]
Same issue as #2020

**Comment by landryb** [comment]
LANG encoding in the env affecting the way the SP rewrites/deals with urls ?
