### ISSUE TITLE
console - broken graph

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2021]
![capture du 2018-04-25 16-23-10](https://user-images.githubusercontent.com/265319/39252022-ff9aa00c-48a4-11e8-95b1-16cb037b4010.png)
 on master branch /console/manager/#!/analytics/all
going back from the csv export tab ...

**Comment by Vampouille** [comment]
> on master branch /console/manager/#!/analytics/all
> going back from the csv export tab ...

@fvanderbiest Can you add details about this issue ?

**Comment by fvanderbiest** [comment]
> Can you add details about this issue ?

Tested on Chromium 65.0.3325.181 (Build officiel) Built on Ubuntu , running on Ubuntu 16.04 (64 bits)

**Comment by fvanderbiest** [comment]
Not witnessed anymore.
