### ISSUE TITLE
geoserver - rollback upgrade to 2.13.0

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2035]
... breaks too many things with existing datadirs (REST service, layer list, UI accents), probably mostly due to isolated workspaces (http://blog.geoserver.org/2018/03/20/geoserver-2-13-0-released/)

Use 2.12.3 instead (maintenance release)

**Comment by zchicago** [comment]
let's go for the 2.13 and make sure everything works with this new version

**Comment by fvanderbiest** [comment]
Related error message was 
```
Caused by: java.lang.IllegalArgumentException: Could not find a security wrapper for class class com.sun.proxy.$Proxy97, cannot secure the object at org.geoserver.security.decorators.SecuredObjects.secure(SecuredObjects.java:65)
```

Closing this issue then.

**Comment by fvanderbiest** [comment]
For the reference, UI accents have been fixed by our own @yjacolin with https://github.com/geoserver/geoserver/pull/2810 on 2.13.1
