### ISSUE TITLE
Error building docker images

### ISSUE THREAD

**Issue by mpintogeo** [georchestra/georchestra#2036]
Hi everybody,
I  want to use geOrchestra 17.12 with docker and I clone recursively https://github.com/georchestra/georchestra.git and `make docker-build` in the new folder but It gives me errors:

`[WARNING] Some problems were encountered while building the effective model for org.geonetwork-opensource:cachingxslt:jar:2.9.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ org.geonetwork-opensource:geonetwork:2.9.0-SNAPSHOT`

Showing me error in geonetwork/pom.xml, line 121, column 15, geonetwork/pom.xml, line 136, column 15.

`[ERROR] Failed to execute goal on project cachingxslt: Could not resolve dependencies for project org.geonetwork-opensource:cachingxslt:jar:2.9.0-SNAPSHOT`

`[WARNING] The requested profile "docker" could not be activated because it does not exist.
[ERROR] No plugin found for prefix 'docker' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories`

I dont know what is going wrong.

**Comment by fvanderbiest** [comment]
I'm sorry, I could not reproduce on a local setup.
Please try again.
