### ISSUE TITLE
Javascript error with ldapadmin console

### ISSUE THREAD

**Issue by jusabatier** [georchestra/georchestra#2039]
I tried to use the 17.12 ldapadmin generic war provided here : 
https://packages.georchestra.org/bot/wars/17.12/

But when going to /ldapadmin/console, I get the following error in the browser console : 

> TypeError: t is undefined -> libraries.js:3:28805
> ReferenceError: angular is not defined -> app.js:1:2036

And the console isn't loading. Nothing more in the log files on server.

**Comment by fvanderbiest** [comment]
Probably related to #2037

**Comment by fvanderbiest** [comment]
Is it fixed now ?

**Comment by jusabatier** [comment]
Yes with a git pull and compilation from 17.12 branch it's fixed.
