### ISSUE TITLE
[ldapadmin] wrong urls in mails

### ISSUE THREAD

**Issue by fphg** [georchestra/georchestra#2040]
tested on geobretagne using ldapadmin 17.12

urls in the messages sent by ldapadmin are badly forged.

https://internalmachine:8080/ldapadmin/xz instead of https://hostname.tld/ldapadmin/xz

this happens on geobretagne.fr, dunno if other instances are affected.

We tried the tomcat options -DproxyName=geobretagne.fr -Dscheme=https without success

tomcats are cascaded behind a HAProxy ( loadbalancing and fault tolerance) then nginx (reverse proxy).

**Comment by fphg** [comment]
https://internalmachine:8080/ldapadmin/xz instead of https://hostname.tld/ldapadmin/xz

this happens on geobretagne.fr, dunno if other instances are affected.

We tried the tomcat options -DproxyName=geobretagne.fr -Dscheme=https without success

**Comment by fvanderbiest** [comment]
Did you check https://github.com/georchestra/georchestra/blob/17.12/docs/setup/tomcat.md#configure-connector ?

**Comment by fphg** [comment]
yes, using proxyName and scheme

**Comment by fvanderbiest** [comment]
So your ldapadmin tomcat connector looks like this ?
```
<Connector port="8280" protocol="HTTP/1.1" 
               connectionTimeout="20000" 
               URIEncoding="UTF-8"
               proxyName="hostname.tld"
               proxyPort="443"
               scheme="https"
               redirectPort="8443" />
```

**Comment by fphg** [comment]
No, I'm using -DproxyName -DproxyPort n JAVA_OPTS. Is it a mistake ?

**Comment by fvanderbiest** [comment]
Yes, you should change your connector settings instead to tell your app what is its public URL.

IIRC -DproxyName -DproxyPort is used when your app has to make requests to the external world going through a proxy.

**Comment by fphg** [comment]
solved ! many thanks
I used proxyName, proxyPort and scheme according to the documentation
