### ISSUE TITLE
ogc-server-statistics - logging WCS 2.0.1 requests fails to persist coverageid

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2049]
![capture du 2018-05-23 15-55-12](https://user-images.githubusercontent.com/265319/40428929-b4b8bff2-5ea1-11e8-8c85-c20f7d33a57a.png)

The `CoverageId` parameter should be persisted as "layername" for the WCS `GetCoverage` and `DescribeCoverage` requests.

The above screenshot shows there's also an issue logging the WMS layername for `GetLegendGraphic` requests

**Comment by fvanderbiest** [comment]
For the record, these queries have been performed using https://github.com/fvanderbiest/inspire-qos-check/blob/master/inspire-qos-check

**Comment by fvanderbiest** [comment]
see also #2076

**Comment by cmangeat** [comment]
In analysis...

**Comment by fvanderbiest** [comment]
Should be fixed on 18.06 with  #2137
