### ISSUE TITLE
geoserver - activate every maven profiles ?

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#2051]
Currently, the Makefile provided at the project's root proposes to build a GeoServer with a lot of profiles activated by default:

https://github.com/georchestra/georchestra/blob/17.12/Makefile#L67

Why not activating these profiles by default ? This would allow generated artifacts (deb packages, wars, docker images) to be basically the same ... And could simplify the previous makefile.

On the other hand, we might want to keep the possibility to activate some plugins or not (webapp size smaller, some modules might be useless for some usecases, ...).

**Comment by fvanderbiest** [comment]
> Why not activating these profiles by default ?

Because we want to keep the possibility to build a clean geoserver package without any extension ?

**Comment by pmauduit** [comment]
ok, so that is voluntary
