### ISSUE TITLE
proxy - /header does not get redirected to /header/

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2057]
I remember there was some code in the proxy to redirect to a selected list of well-known locations, eg /mapfishapp/ /geonetwork/ ... but I cannot find it again.
@pmauduit missing `header` in the list ?

witnessed on master

**Comment by pmauduit** [comment]
> I remember there was some code in the proxy to redirect to a selected list of well-known locations, eg /mapfishapp/ /geonetwork/ ... but I cannot find it again.

it was urlrewrite, but we removed it. I think it would be more relevant to have this on the frontend webserver

**Comment by pmauduit** [comment]
https://github.com/georchestra/georchestra/blob/17.12/security-proxy/src/main/webapp/WEB-INF/urlrewrite.xml#L46-L49

**Comment by fvanderbiest** [comment]
> I think it would be more relevant to have this on the frontend webserver

okay.
