### ISSUE TITLE
Do we still need local maven binaries ?

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2060]
```
$ ./mvn --version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T18:29:23+01:00)
Maven home: /home/fvanderbiest/workspace/georchestra/georchestra/build-tools/maven
Java version: 1.8.0_171, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.13.0-39-generic", arch: "amd64", family: "unix"
```

**Comment by pmauduit** [comment]
From my point of view, this has nothing to do in the georchestra codebase

**Comment by pmauduit** [comment]
On the other hand, it is used in the Makefile

**Comment by pmauduit** [comment]
the projects based on gradle usually use a "gradle wrapper" (gradlew). A similar concept seems to exist also with maven: http://www.baeldung.com/maven-wrapper ; maybe more relevant than our shell scripts in the repository.

**Comment by fvanderbiest** [comment]
Okay, thanks for the pointers Pierre !
Moving this to core maintenance issues.

**Comment by landryb** [comment]
Data point: stretch has maven 3.3.9, and i'm running a make deb-build-georchestra with it (ie removed the ./ ../ from Makefile) - seems master builds fine wit it.

**Comment by fvanderbiest** [comment]
Thanks Landry, I'll submit a PR to clean this in a moment.
