### ISSUE TITLE
factorize instanceName & language in default.properties

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2068]
https://github.com/georchestra/datadir/blob/17.12/security-proxy/security-proxy.properties#L49
https://github.com/georchestra/datadir/blob/17.12/mapfishapp/mapfishapp.properties#L2
https://github.com/georchestra/datadir/blob/17.12/ldapadmin/ldapadmin.properties#L4
https://github.com/georchestra/datadir/blob/17.12/geowebcache/geowebcache.properties#L4
https://github.com/georchestra/datadir/blob/17.12/cas/cas.properties#L3
https://github.com/georchestra/datadir/blob/17.12/analytics/analytics.properties#L6

on master branch ...

**Comment by pmauduit** [comment]
Looks like recursive resolutions of properties file is not possible, currently the default docker composition is ending with the following trace at SP bootstrap:

```
proxy_1         | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.filterChains': Cannot resolve reference to bean 'org.springframework.security.web.DefaultSecurityFilterChain#0' while setting bean property 'sourceList' with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.web.DefaultSecurityFilterChain#0': Cannot create inner bean '(inner bean)#41d426b5' of type [org.springframework.security.web.authentication.logout.LogoutFilter] while setting constructor argument with key [3]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#41d426b5': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.web.authentication.logout.LogoutFilter]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: ${publicUrl}/cas/logout?fromgeorchestra isn't a valid redirect URL
```

One workaround though, is to launch the SP container with `JAVA_OPTIONS` env variable set at least to `-DpublicUrl=http://blah/`.

**Comment by fvanderbiest** [comment]
> One workaround though, is to launch the SP container with JAVA_OPTIONS env variable set at least to -DpublicUrl=http://blah/.

I like it a lot !
Though I would prefer a dedicated env var for the docker case. 

extractorapp, console, cas and atlas also use ${publicUrl}

**Comment by pmauduit** [comment]
> I like it a lot !

My concern is that is a very docker-oriented approach ... And the `default.properties` file is then useless.

**Comment by fvanderbiest** [comment]
How could this work when @Vampouille first worked on it ?

**Comment by pmauduit** [comment]
Good question, I asked him and he was pretty sure his implementation was working, fact is it does not with the current default docker compo.

**Comment by severo** [comment]
Remaining occurrences of `georchestra.mydomain.org` to examine:

- https://github.com/georchestra/georchestra/blob/master/security-proxy/src/main/java/org/georchestra/security/Proxy.java#L157
- https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/webapp/WEB-INF/ws-servlet.xml#L52

**Comment by severo** [comment]
Occurrences of `instance.name`:

- https://github.com/georchestra/georchestra/blob/master/geowebcache-webapp/src/main/java/org/geowebcache/GeorchestraGeoWebCacheDispatcher.java#L55, https://github.com/georchestra/georchestra/blob/master/geowebcache-webapp/src/main/java/org/geowebcache/GeorchestraGeoWebCacheDispatcher.java#L93L113, https://github.com/georchestra/georchestra/blob/master/geowebcache-webapp/src/main/resources/geowebcache.properties#L3
- https://github.com/georchestra/georchestra/blob/master/cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/default/ui/includes/top-noheader.jsp#L39L50, https://github.com/georchestra/georchestra/blob/master/cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/default/ui/includes/top.jsp#L38L56

**Comment by severo** [comment]
Occurrences of the `language` property (note that it's assumed that "language" can be composed of various language codes, separated by commas, like: "en,fr" - maybe the variable should be `languages`, not `language`):

- https://github.com/georchestra/georchestra/blob/master/extractorapp/src/main/java/org/georchestra/extractorapp/ws/AbstractEmailFactory.java#L72L73
- https://github.com/georchestra/georchestra/blob/master/header/src/main/webapp/WEB-INF/jsp/index.jsp#L49
- https://github.com/georchestra/georchestra/blob/master/analytics/src/main/webapp/WEB-INF/jsp/index.jsp#L45
- https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/webapp/WEB-INF/jsp/index.jsp#L49

Found occurrences that should use the `language` property and do not (the list might be incomplete):

- https://github.com/georchestra/georchestra/blob/master/extractorapp/src/main/webapp/WEB-INF/ws-servlet.xml#L60

Found occurrences of `lang` GET parameter:

- https://github.com/georchestra/georchestra/blob/master/header/src/main/webapp/WEB-INF/jsp/index.jsp#L72
- https://github.com/georchestra/georchestra/blob/master/analytics/src/main/webapp/WEB-INF/jsp/index.jsp#L62
- https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/webapp/WEB-INF/jsp/index.jsp#L69

Found occurrences of using the `accept-header` HTTP header for the language (and Spring `LocaleResolver` for customized strategies):

- https://github.com/georchestra/georchestra/blob/master/header/src/main/webapp/WEB-INF/jsp/index.jsp#L68 (see the [Spring doc](https://docs.spring.io/spring/docs/3.1.0.RELEASE/javadoc-api/org/springframework/web/servlet/support/RequestContextUtils.html#getLocale(javax.servlet.http.HttpServletRequest)))
- https://github.com/georchestra/georchestra/blob/master/analytics/src/main/webapp/WEB-INF/jsp/index.jsp#L61
- https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/webapp/WEB-INF/jsp/index.jsp#L68
