### ISSUE TITLE
mapfishapp - disable by default the legend and the mini map

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/georchestra#2087]
We are operating a 16.12 geOrchestra.

We meet a problem with the print module wich, in certain cases hang up.
It happens on a particular map-contex with many (30 to 45) layers. Somes have complicated / rich SLD styles.
If a user let all the option ticked (mini map, scale, date, legend) it crashed.

So **we would want to have choosen by default only date and scale.**
Furthermore we think that :
- it is better for environnemental issue to not have by default 2 pages in the PDF file
- in the web use it is less important than in desktop use

Please share your comments below.

![screenshot214](https://user-images.githubusercontent.com/6370443/41663534-f5b5b7d6-74a3-11e8-8731-4a8ffb2565f1.png)

**Comment by fvanderbiest** [comment]
I do agree, since the minimap is not so useful, and the legend is ... complicated.

**Comment by fvanderbiest** [comment]
People seem to approve.
Done with 255be68 on 16.12

**Comment by fphg** [comment]
+1

**Comment by MaelREBOUX** [comment]
\o/
