### ISSUE TITLE
jetty - disable directory listing

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2088]
With https://github.com/georchestra/datadir/pull/79 merged, accessing `/geonetwork/srv/fre/admin.console#/tools` without being logged in results in being redirected to `/cas/login` then to `/geonetwork/;jsessionid=nodexxxxxx.node0` which displays this directory listing:
![capture du 2018-06-22 13-54-47](https://user-images.githubusercontent.com/265319/41775345-db3d0d56-7623-11e8-9c12-8e8c18d9ef46.png)

**Comment by fvanderbiest** [comment]
Should we modify each webapp's web.xml with the following ?
```xml
<context-param>
    <param-name>org.eclipse.jetty.servlet.Default.dirAllowed</param-name>
    <param-value>false</param-value>
</context-param>
```

**Comment by fvanderbiest** [comment]
Related issues (jsessionid in url) : #1953 & #878

**Comment by pmauduit** [comment]
> Should we modify each webapp's web.xml with the following ?

it's Jetty-specific :-/ (but should not harm the other servlet containers anyway)

**Comment by pmauduit** [comment]
I guess it is the expected behaviour after preventing the directory listing
