### ISSUE TITLE
Provide a way to disable captcha

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2098]
I know theres #693 but in the meantime, for dev purposes or privacy reasons i dont want to use the evil google captcha.

In georchestra/ansible@ab8d5d6d i did a quick workaround to fake the captcha response, but having a way to disable it in the config would be better..

here are the places where the google bits could be abstracted:
  *  console/src/main/webapp/WEB-INF/views/validation.jsp#L90
  * console/src/main/webapp/WEB-INF/views/createAccountForm.jsp#L41
  * and the iframe in console/src/main/webapp/WEB-INF/tags/recaptcha.tag

Less google in our lifes..

**Comment by fvanderbiest** [comment]
Related issue is #693

**Comment by landryb** [comment]
Cf #2239

**Comment by fvanderbiest** [comment]
You can thank DT ;-)
