### ISSUE TITLE
console: allow to remove an area from the bullet list

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2099]
when editing an org area, the bullet list on the right is static and updated based on selections on the map/via the autocomplete.

to remove an area, the user/admin needs to:
* click a selected area (but he needs to know where is area is on the map)
* redo the autocomplete by name and click on the tick item on the left of the name (that one was not super obvious :)

would it be possible to have a red cross instead of a bullet list so that one can uncheck/remove areas based on their name ?

**Comment by fvanderbiest** [comment]
Done on master for 18.12

**Comment by landryb** [comment]
Tested on firefox, works as expected. Thanks !

**Comment by fvanderbiest** [comment]
That was fast :-)
