### ISSUE TITLE
console: import/export org area as csv

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2100]
would be nice to be able to export/import the code list as csv (or geojson since we have the geometry available ? but then the file is huge) so that one can *replace* the area by uploading a csv.

we have cases where every year, an admin has to compare a list of 300 insee codes (what's in the db/ldap, what's the new list) , with 90 to add and 20 to remove....

**Comment by landryb** [comment]
> Indeed.
> Can you iterate on your requirements for uploading / downloading this CSV ? (mostly: who, where, what...)
On the coverage page, a link would export the current codelist as csv (eventually with a heading, but the codes are not always inseeCodes..) - cadastrapp has that kind of feature for parcel exports. This should be available to anyone (i'm not sure it makes sense to keep that information secret, but right now the org pages arent available to users anyway)

On the same page an upload form/button with 'replace codelist' would allow to send a similarly formed csv (potentially removing the heading, if it's not a number ?), available for an ORGADMIN or a SUPERUSER, and per #2101 eventually available for a member user, but with a validation step.

Uploading the codelist would *replace* the current codelist, which is simpler than trying to mix/match/add existing vs new.

**Comment by fvanderbiest** [comment]
IIUC, you mean a dumb CSV (actually without comma) like this one:
```csv
code
75001
75002
...
```

**Comment by landryb** [comment]
Yes, no point in having more than this, we just need a codelist. Eventually with area names but only for informational purposes, as uploading the codelist should only care about the codes/keys.
