### ISSUE TITLE
console: should regular users have access to it ?

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2103]
Right now on master the `testuser` user without specific rights (ie only USER, not ORGADMIN) has access to the 'administration->utilisateurs' link and can see the console tabs (dashboard/users/orgs/roles/stats/logs (but not messages ?)). The users/orgs/roles tabs show no value. 

I get it that it makes total sense for user with ORGADMIN rights, but should this tab be accessible to regular users ? If so, shouldnt they only see dashboard/stats or their own roles/org as readonly fields (related to #2101)?

What is more worrying is that on the 'users' tab, the 'create new user' button is active, and allows a regular user to think he can create a user. Saving the 'new user' details triggers a POST on console/private/users which is 302 redrected to a GET on /cas/login?service=https://fqdn/login/cas but the UI doesnt seem to handle it, and no new user seems created in the LDAP.

**Comment by fvanderbiest** [comment]
You're completely right, this is not expected.
If it can be reproduced, it's a blocker for 18.06

**Comment by fvanderbiest** [comment]
Nope, not expected at all with https://github.com/georchestra/datadir/blob/master/security-proxy/security-mappings.xml#L13
What's your configuration ?

**Comment by landryb** [comment]
On a demo install, i login as `testuser`, in the header i have 'administration' and 'users' links, clicking on users leads to `/console/manager/#!/home`

i've doublechecked the apache vomit and readded the RewriteRule/RewriteCond from console.conf (from https://github.com/georchestra/georchestra/blob/master/docs/setup/apache.md) that were missing, but that doesnt fix this issue.

security-mappings.xml match what's in git:
```
$grep console/manager /etc/georchestra/security-proxy/security-mappings.xml 
  <intercept-url pattern="/console/manager/public/.*" access="IS_AUTHENTICATED_ANONYMOUSLY" />
  <intercept-url pattern="/console/manager/.*" access="ROLE_SUPERUSER,ROLE_ORGADMIN" />
```

**Comment by landryb** [comment]
Something is fishy somewhere as in the sec-proxy log it seems testuser has ORGADMIN ?
```
2018-07-02 15:08:27 statistics [INFO] testuser|2018/07/02 15:08:27|http://localhost:8280/console/manager/|Project Steering Committee|ROLE_ORGADMIN,ROLE_USER
```
in the LDAP, that's the case (ie testuser is memberOf cn=ORGADMIN) but if i go check on the web UI only 'USER' is checked.

```
ou=roles,~ > cat cn=ORGADMIN
member: uid=testuser,ou=users,dc=georchestra,dc=org

ou=users,~ > cat uid=testuser memberOf
memberOf: cn=ORGADMIN,ou=roles,dc=georchestra,dc=org
```

so it seems the web UI is lying to me, as it doesnt list ORGADMIN in the roles ?

![capture d ecran_2018-07-02_15-12-55](https://user-images.githubusercontent.com/3421760/42166179-7ee1497a-7e0a-11e8-9746-7861d2b0a724.png)

**Comment by fvanderbiest** [comment]
OKay, there's an issue with this commit:
https://github.com/georchestra/georchestra/commit/7e62e6844880e959ded546da6bb1f66ffa495c22

**Comment by fvanderbiest** [comment]
> so it seems the web UI is lying to me, as it doesnt list ORGADMIN in the roles ?

It's not lying, it's masking it ;-)

**Comment by landryb** [comment]
Note that i have no delegation set 'Pas de délégation de gestion définie pour cet utilisateur', and the user is in the PSC org. The fact that `testuser` has ORGADMIN comes from https://github.com/georchestra/georchestra/blob/master/ldap/georchestra.ldif#L175 but then it's confusing, as an admin has no way of knowing testuser has the ORGADMIN role.

a newly created user doesnt exhibit this issue, ie he only sees *his* account details and has no administration links, and /console/manager/#!/home is denied as expected.

**Comment by landryb** [comment]
maybe time to add a testdelegatedadmin user to the example data ? :)

**Comment by landryb** [comment]
Ah, and i didnt see the delegation for those two users as i didnt integrate postgresql/05-console-data.sql in the psql role of the ansible playbook. grr.

**Comment by landryb** [comment]
and now i remember i didnt play this sql script because https://github.com/georchestra/georchestra/blob/master/postgresql/05-console-data.sql#L45 is non-docker hostile... :)

**Comment by landryb** [comment]
Tested that `testuser` can indeed create an user (without password) in the PSC org and assign him the GN_REVIEWER or GN_EDITOR roles.

**Comment by fvanderbiest** [comment]
> https://github.com/georchestra/georchestra/blob/master/postgresql/05-console-data.sql#L45 is non-docker hostile... :)

Right, separate issue #2111

**Comment by fvanderbiest** [comment]
> maybe time to add a testdelegatedadmin user to the example data ? :)

Yes, with #2112
