### ISSUE TITLE
geoserver dockerfile - do not specify GC to use

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2120]
http://docs.geoserver.org/stable/en/user/production/container.html#optimize-your-jvm shows that choosing a GC depends on many assumptions. Our images should not be opinionated on the GC choice.

https://github.com/georchestra/georchestra/blob/8b4681b79c5c6b69859a9fb3448cc41a90ce5ce3/geoserver/webapp/src/docker/Dockerfile#L41

![capture du 2018-07-06 15-36-33](https://user-images.githubusercontent.com/265319/42381883-c844cb2a-8132-11e8-83a5-a7208b691148.png)

**Comment by fvanderbiest** [comment]
Users will still have the choice to tweak this parameter via the `JAVA_OPTIONS` env var https://github.com/georchestra/georchestra/blob/8b4681b79c5c6b69859a9fb3448cc41a90ce5ce3/geoserver/webapp/src/docker/Dockerfile#L43

**Comment by pmauduit** [comment]
Parallel GC is the default one until Java8 included ; it switched to G1GC in newer versions (Java9, 10, 11 ...)

**Comment by fvanderbiest** [comment]
True, this change lets people use G1GC with jdk8.
