### ISSUE TITLE
fix properties loading order/conflicts

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2123]
Generalisation of #2114, which applies potentially to the following files:
```
$git grep -l property-placeholder
analytics/src/main/webapp/WEB-INF/ws-servlet.xml
atlas/src/main/resources/camel/atlas_app.xml
cas-server-webapp/src/main/webapp/WEB-INF/spring-configuration/propertyFileConfigurer.xml
console/src/main/resources/META-INF/spring/applicationContext.xml
console/src/main/webapp/WEB-INF/spring/webmvc-config.xml
geowebcache-webapp/src/main/webapp/WEB-INF/geowebcache-servlet.xml
security-proxy/src/main/filtered-resources/WEB-INF/proxy-servlet.xml
security-proxy/src/main/webapp/WEB-INF/applicationContext-security.xml
security-proxy/src/test/resources/applicationContext-test.xml
```
in geonetwork submodule (some might be from/apply to georchestra, some not..):
```
core/src/main/resources/config-spring-geonetwork.xml
messaging/src/main/resources/config-spring-geonetwork-parent.xml
web/src/main/webResources/WEB-INF/config-db/defaultJdbcDataSource.xml
web/src/main/webResources/WEB-INF/config-db/postgis-alternate-datasource.xml
web/src/main/webResources/WEB-INF/config-db/postgres-postgis.xml
web/src/main/webResources/WEB-INF/config-spring-geonetwork.xml
web/src/main/webapp/WEB-INF/config-security/config-security.xml
workers/wfsfeature-harvester/src/main/resources/config-spring-geonetwork.xml
```
(none found in geoserver submodule)

When there are several `property-placeholder` entries in a file, the values they read might overwrite each other. On top of this, we want the following priority:
* `default.properties` (which has the lower weight/is overriden by values set in other files)
* `$webapp/WEB-INF/foo.properties` (which will disappear with the removal of config.jar in #1417)
* `${georchestra.datadir}/foo/foo.properties` which has the highest priority

**Comment by landryb** [comment]
And the occurences of `ctx:property-placeholder` found in `${georchestra.datadir}/geonetwork/config`

**Comment by landryb** [comment]
I think #2114 is not correctly fixed for some properties, because with 18.06 and the following config:
```
default.properties:publicUrl=https://ids.dev.craig.fr
security-proxy/security-proxy.properties:public.host=${publicUrl}
```
when i try to use the openls addon on mfapp, i get a 403, because the proxy sends the request to the ign server with a wrong referer:
```
headers [DEBUG] http-outgoing-0 >> Referer: ${publicUrl}
```

This of course works if i set `public.host=https://ids.dev.craig.fr` in `security-proxy.properties` but that defeats the purpose of using variables to set common values in a single spot..

My guess is that the code in https://github.com/georchestra/georchestra/blob/18.06/security-proxy/src/main/java/org/georchestra/security/HeadersManagementStrategy.java#L84 gets the raw property value, and not the one resolved by the multiple properties inclusion.. or the placeholders are taken into account only for the xml config files, and not for java code ?

**Comment by severo** [comment]
> I think #2114 is not correctly fixed for some properties, because with 18.06 and the following config:
> 
> ```
> default.properties:publicUrl=https://ids.dev.craig.fr
> security-proxy/security-proxy.properties:public.host=${publicUrl}
> ```
> 
> when i try to use the openls addon on mfapp, i get a 403, because the proxy sends the request to the ign server with a wrong referer:
> 
> ```
> headers [DEBUG] http-outgoing-0 >> Referer: ${publicUrl}
> ```
> 
> This of course works if i set `public.host=https://ids.dev.craig.fr` in `security-proxy.properties` but that defeats the purpose of using variables to set common values in a single spot..
> 
> My guess is that the code in https://github.com/georchestra/georchestra/blob/18.06/security-proxy/src/main/java/org/georchestra/security/HeadersManagementStrategy.java#L84 gets the raw property value, and not the one resolved by the multiple properties inclusion.. or the placeholders are taken into account only for the xml config files, and not for java code ?

I understand that it's not feasible: you cannot use placeholders in the properties files. Please confirm @pmauduit or @fvanderbiest.

**Comment by severo** [comment]
Note that we have to take care also of all the occurrences of `PropertyPlaceholderConfigurer`, `PropertyOverrideConfigurer` (maybe) and `PropertySourcesPlaceholderConfigurer` (the latter is not present in the code).

**Comment by severo** [comment]
Something is not clear to me: do we want to load the `file:${georchestra.datadir}/default.properties` file in servlets that currently aren't loading it?

As it's not clear to me, and as it might break current configurations (eg if a property is set in the `default.properties` file but currently ignored because the file is not loaded, changing the behavior could replace the value of the property and break things) -> I prefer not to add this file when it is not loaded, and wait for a decision from yourselves.

**Comment by severo** [comment]
> - `default.properties` (which has the lower weight/is overriden by values set in other files)
> - `$webapp/WEB-INF/foo.properties` (which will disappear with the removal of config.jar in #1417)
> - `${georchestra.datadir}/foo/foo.properties` which has the highest priority

If I understand correctly the moves in https://github.com/georchestra/georchestra/pull/1966/files, the idea is to have a file `$foo_webapp/WEB-INF/foo.properties` in every module, that will be the default set of options. Then, `${georchestra.datadir}/default.properties` and `${georchestra.datadir}/foo/foo.properties` would override the properties.

Therefore, the correct order should be:

- `$foo_webapp/WEB-INF/foo.properties` (which has the lower weight/is overriden by values set in other files)
- `${georchestra.datadir}/default.properties` 
- `${georchestra.datadir}/foo/foo.properties` which has the highest priority

Note that not all the modules have the `$foo_webapp/WEB-INF/foo.properties`, as it is a work in progress (#1417)
