### ISSUE TITLE
console - user sees details of his org

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2125]
@landryb said elsewhere: "Would there be a way for a user to see the details of his org (ie coverage, member list, etc...) ? right now he only sees the org name.

**Comment by fvanderbiest** [comment]
Would that be OK, to show a "more information about this Org" link next to the Org name displayed in the `/console/account/userdetails` page ?
This new console page would be read-only, and access would be restricted to users of this Org.

Can you iterate on the above "(ie coverage, member list, etc...)". Thanks.

**Comment by fvanderbiest** [comment]
Oops, I did not see there's already #2101

**Comment by fvanderbiest** [comment]
> Would that be OK, to show a "more information about this Org" link next to the Org name displayed

Or a 2-column display: 
 * left column as currently with user-centric fields
 * right column with org-related informations + map

**Comment by landryb** [comment]
Isn't it simpler to have org name a link that reuses the actual 'org details' page, but making the fields displays as readonly instead of entries/textfields ?

Otherwise yes it's less clicks for the user to see his personal info *and* his org details on the same page. It's just that if you add more fields to an org page, you need to remember to add them too on the user page...

**Comment by fvanderbiest** [comment]
Okay, will discuss this with @tonio during implementation

**Comment by bchartier** [comment]
> Org-related informations must include readonly list of org members

Not sure that all org members would appreciate to see that their names appear in the description of the organisation (see General Data Protection Regulation).

**Comment by landryb** [comment]
afaik, console is not available to anonymous users...

**Comment by fvanderbiest** [comment]
> Would it be only visible to authenticated users?

Yes

**Comment by fvanderbiest** [comment]
Just to make it clear, we're speaking of the /console/account/userdetails page

**Comment by bchartier** [comment]
> Just to make it clear, we're speaking of the /console/account/userdetails page

Thank you. I was affraid that this kind of information could be visible in the user account creation form.

**Comment by fvanderbiest** [comment]
Implemented with #2172 

Smallish issue found & reported with #2229 
Possible improvement with #2230
