### ISSUE TITLE
console - org perimeter batch selection - Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2126]
![capture du 2018-07-12 15-34-38](https://user-images.githubusercontent.com/265319/42636435-1c288154-85e9-11e8-9238-49b6a62c2c7e.png)

In the above screenshot, I first selected "Moselle" (displayed in blue), then I selected "Bas rhin".

Expected : bas-rhin areas replacing moselle areas
Got : bas-rhin still displayed and moselle areas disappearing + JS error "Cannot read property 'forEach' of undefined"

**Comment by landryb** [comment]
UI-wise, i would have expected both dept to be selected... anyway, here in firefox, no such error message in the console. Using `99.master.201807111441~403d14f`

**Comment by fvanderbiest** [comment]
Fixed on master with #2143 => should be backported to 16.12 and later branches as well

**Comment by fvanderbiest** [comment]
backported to 18.06 only due to limitations
