### ISSUE TITLE
using gwc embedded in geoserver fails to seed

### ISSUE THREAD

**Issue by catmorales** [georchestra/georchestra#2141]
**Describe the bug**
GWC Seed Form returns a page with "Chunk [] is not a valid entry" message error when seeding a layer..

**geOrchestra version or branch**

 master 

**To Reproduce**
1. Go to 'https://public-test.sig.rennesmetropole.fr/geoserver/gwc/rest/seed/raster:ortho2014'
2. Click on submit (levels 0 to 10)'
3. See error : "Chunk [] is not a valid entry"

referenced bug https://osgeo-org.atlassian.net/browse/GEOS-8474
solution is update geoserver 
 I  used generic war on master branch.

**Comment by fvanderbiest** [comment]
To be fixed on 18.06 (GeoGrandEst also affected)

**Comment by fvanderbiest** [comment]
WIP with #2208

**Comment by fvanderbiest** [comment]
GeoServer updated to 2.12.5 on 18.06 and master fixes the issue
