### ISSUE TITLE
console - add ability to define Org referents

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2147]
These Org referents should be able to update their Org fields.
Only SUPERUSER members should be able to define which users are Org referents

**Comment by fvanderbiest** [comment]
There's a discussion here about whether Org referents differ from Org admins (which are able to manage users, limited to a collection of roles in a collection of Orgs).

**Comment by landryb** [comment]
Allowing a referent to directly modify its org coverage would be a no-go for us .. since we deliver/share data based on this information, which might have licence terms/etc not allowing full coverage availabilty... that's why we had #2101 for the referent to *request changes* to the org, and a superuser to validate them.

**Comment by fvanderbiest** [comment]
OK, let's say that a referent cannot update his Org's perimeter.

**Comment by fvanderbiest** [comment]
So, to sum it up: users with a delegation (to manage roles in one or several Org) will also be allowed to modify all Org fields, except areas.
They will not be allowed to delete the Org, nor to modify its users (at least for now).

**Comment by landryb** [comment]
i would also exclude org type. So far, we base some sharing decisions on the org type.. (ie some dataset shouldnt be available to certain types of orgs, some dataset should only be available to a subset of org types...)

I dont plan to use delegation so far...  but if i would, this would be a blocker (like area)

**Comment by fvanderbiest** [comment]
> i would also exclude org type.

Makes sense indeed.
Other comments ?

**Comment by fvanderbiest** [comment]
> There's a discussion here about whether Org referents differ from Org admins

The geo2france project is strongly opposed to having them merged into a single "feature".
Makes sense to me.

New proposal: on a console Org page, ability to define 0 to N referents, which are able to update their Org, except for the type & area fields.

**Comment by fvanderbiest** [comment]
Better: on `/console/manager/#!/users/xxxx/delegations` add a checkbox, "allow org info modification"

**Comment by fvanderbiest** [comment]
> Better: on `/console/manager/#!/users/xxxx/delegations` add a checkbox, "allow org info modification"

Which would imply potentially empty roles list in delegation ... which might be weird, or difficult to implement....

**Comment by fvanderbiest** [comment]
New proposal regarding the UI, hopefully the last one here ;-)
 * on page `/console/manager/#!/org/xxx/users` : for each member, a new button allows to switch user state from "org referent" to "regular user", back and forth. 
 * on this same page `/console/manager/#!/org/xxx/users` a text is added to explain what a referent is and what it allows.
 * on page `/console/manager/#!/users/yyy/infos` a flag/tag/text shows whether the user is referent or not.

As a consequence, we'll need to implement:
 * a new service in the console, to toggle a user's "referent" state. This service will be restricted to users having the `SUPERUSER` role (via the datadir's `security-proxy/security-mappings.xml`)
 * a new database table to store this information (no LDAP involved here)

A referent should be able to edit in place 6 of his Org's fields, on the `/console/account/userdetails` page : org name, org short name, org adress, org logo, org description, org url

**Comment by landryb** [comment]
> org name, org short name, org adress, org logo, org description, org url

I'm not sure it's wise to allow end users to change _org short name_, since it's the "internal" name used for LDAP objects. Usually, it's cleaned up/improved by org admins so that it's consistent over a full DIT......

(yes, i use it as a key in lots of places: cadastrapp group ids, nextcloud group ids..)

**Comment by fvanderbiest** [comment]
Above proposal was considered over-complicated by the team here !

We decided to go for a `REFERENT` role that a `SUPERUSER` may grant to any user, allowing him to update his (and only his) organisation's fields, restricted to: org name, org adress, org logo, org description, org url.

**Comment by landryb** [comment]
looks good to me too, as long as org short name cant be modified by a referent that's fine  :)

thanks !

**Comment by fvanderbiest** [comment]
I consider this nearly done (it's merged) but there are still minor issues we're dealing with.
One thing is missing: documentation !
