### ISSUE TITLE
GDPR compliance - let the user manage personal data

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2148]
Managing here means:
 * being able to permanently delete his account
 * being able to download personal data as an archive

Which data should be downloadable here ?
 * of course, information from the inetOrgPerson LDAP instance, as a LDIF/CSV/Contact file
 * `* from mapfishapp.geodocs where username=xx` as a collection of CSV, KML, SLD, WMC, GML, WKT files in a single directory, named `created_at` _ `file_hash` _ `access_count`.`standard`
 * `* from ogc_services_log where user_name=xx` as a single CSV file
 * `* from extractorapp.extractor_log left join extractorapp.extractor_layer_log on .... where user_name=xx` as a single CSV file
 * an xml export of all metadata owned by the user, from `geonetwork.metadata`
 
What happens when the user deletes his account ?
 * the user account is being removed from LDAP, which also means Roles, Orgs, Delegations are updated accordingly.
 * `UPDATE mapfishapp.geodocs SET username = 'ghost' WHERE username = 'xxx'`
 * `UPDATE ogcstatistics.ogc_services_log SET user_name = 'ghost' WHERE user_name=xxx`
 * `UPDATE extractorapp.extractor_log SET username = 'ghost' WHERE username=xxx`
 * `UPDATE geonetwork.users SET name = 'ghost', surname='ghost', username= 'ghost' WHERE username=xxx`

The `/console/account/userdetails` page looks like the perfect place to integrate this.

**Comment by fvanderbiest** [comment]
The `/console/account/userdetails` page looks like the perfect place to integrate this.

**Comment by fvanderbiest** [comment]
Which personal data should be downloadable here ?
 * of course, information from the inetOrgPerson LDAP instance + Org Name
 * `* from mapfishapp.geodocs where username=xx`
 * `* from ogc_services_log where user_name=xx`
 * `* from extractorapp.extractor_log left join extractorapp.extractor_layer_log on .... where user_name=xx`

**Comment by landryb** [comment]
Right now if you delete a user from LDAP, its metadata in geonetwork stays there (and the corresponding entry in the `users` table too), you get the nagging in the logs (that nobody reads):
```
ERROR [geonetwork.ldap] - Cannot delete user 'robert.bidochon' who is owner of 2 metadata record(s).
```

Once you've transferred the ownership to another user (or deleted the metadata) then the user entry is really deleted from geonetwork database.

**Comment by fvanderbiest** [comment]
> Does it also apply to metadata and layers created by the user ? I'm not sure this is considered as personal information.

Let's say it does not.

**Comment by groldan** [comment]
Note to self: see https://github.com/georchestra/georchestra/tree/org-fields

**Comment by fvanderbiest** [comment]
@bchartier @fphg @landryb and others - do we really want permalinks to disappear ?

**Comment by fphg** [comment]
Good point, even the user itself may not want that.

I'd say that he must acknowledge the deletion, and if it's not possible permalinks are preserved.

⁣Fabrice Phung​


-------- Original Message --------

**Comment by fvanderbiest** [comment]
Thinking about it twice, I'm really not sure contexts should be considered as personal data.
We should probably keep contexts and SLDs from the geodocs table.

**Comment by bchartier** [comment]
Explanation for what we should consider as personal data from CNIL in french:
https://www.cnil.fr/fr/definition/donnee-personnelle
https://www.cnil.fr/fr/cnil-direct/question/492

**Comment by fvanderbiest** [comment]
Thanks for the feedback Benjamin. 
If I understand correctly, it seems like the job here is less than expected, since only the information from the LDAP (essentially `inetOrgPerson` fields) is to be considered for downloading / deletion.

Does everyone share the same understanding here ?

**Comment by bchartier** [comment]
If some kind of user names, user ids, ips... are stored somewhere else than in the ldap database they should also be considered for downloading/deletion in my understanding.

**Comment by fvanderbiest** [comment]
OK, but the content may be preserved...

Let's take https://github.com/georchestra/georchestra/blob/18.06/postgresql/020-mapfishapp.sql as an example. Entries from `mapfishapp.geodocs` (permalinks, sld, etc) created by the user can be preserved, as long as username is replaced with another string.
To put it differently: `UPDATE mapfishapp.geodocs set username = 'ghost' where username = 'fvanderbiest';` would be enough to comply with GDPR regarding personal data deletion.

**Comment by fvanderbiest** [comment]
Same thing for `ogc_services_log` and `extractorapp.extractor_log.
This makes more sense to me than simply deleting this information, which is useful for analytics.

**Comment by groldan** [comment]
FYI work is being conducted at this branch: https://github.com/groldan/georchestra/commits/feature/GDPR_compliance

**Comment by groldan** [comment]
#2613 has been merged as agreed on today's standup meeting. Awaiting for UI integration and/or feedback before closing this issue.
