### ISSUE TITLE
[console] users with same name but different uid missing from user list

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2157]
Extracted from https://github.com/georchestra/georchestra/pull/2154#issuecomment-419444816

It seems users with homonyms are hidden/missed by the console backend. At first i noticed it from group membership numbers being off, but now that i've tested creating a user with `nom=user` & `prénom=test` (the generated uid being `tuser`, but it has the same `sn`/`givenName` as the `testuser` account) it's not shown in the userlist, while it's present in the ldap:
```
# tuser, users, georchestra.org
dn: uid=tuser,ou=users,dc=georchestra,dc=org
uid: tuser
employeeNumber: 9
mail: blah@foo.com
givenName: test
sn: user
cn: test user
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: inetOrgPerson
objectClass: shadowAccount
```

`/console/private/users` doesnt list it (ie there's `uid=testuser` but not `uid=tuser` in the JSON), although i can browse to `/console/manager/#!/users/tuser/infos` and edit its infos.

I thought `uid` was supposed to be the key for users uniqueness, but it seems it's not the case.. i'm puzzled now.

**Comment by fvanderbiest** [comment]
Fixed with #2194 on 18.06

**Comment by landryb** [comment]
I'm puzzled by 417d60c and the other commits working on this.. how can you have a real user in the ldap not having an email ? I thought so far it was a requirement..

**Comment by fvanderbiest** [comment]
OKay, #2199 created to keep track of it.
