### ISSUE TITLE
[console] only show users from selected branches

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2158]
Extracted from https://github.com/georchestra/georchestra/issues/2108#issuecomment-418358202

It seems `AccountDaoImpl` uses a broad ldap filter on `objectClass=person` under `baseDN` which returns all such objects across all branches, which it should only return users from `userSearchBaseDN` branch (and the branch for pending users once #2108 is implemented)

There might be other branches in the LDAP with valid `objectClass=person` entries georchestra has no business dealing with..

**Comment by fvanderbiest** [comment]
Fixed on master for 18.12
