### ISSUE TITLE
Missing homepage.url in cas.properties

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2161]
Fallout from georchestra/datadir@85608423, `homepage.url` isnt defined anymore in `cas.properties`, and this breaks the redirection upon login from https://github.com/georchestra/georchestra/blob/18.06/config/defaults/cas-server-webapp/WEB-INF/view/jsp/default/ui/casGenericSuccess.jsp#L32 as `sharedHomepageUrl` comes from https://github.com/georchestra/georchestra/blob/18.06/config/defaults/cas-server-webapp/WEB-INF/view/jsp/default/ui/includes/top-noheader.jsp#L46

**Comment by landryb** [comment]
@fvanderbiest : fixed by #2181 ?

**Comment by fvanderbiest** [comment]
Yes ;-)

**Comment by landryb** [comment]
Thanks then :)
