### ISSUE TITLE
console has a hidden dependency on analytics

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2170]
Dunno if it should be mentioned in the console/README.md, but by default there's a dependency on the analytics webapp, as console homepage queries `analytics/ws/distinctUsers` & `analytics/ws/combinedRequests.json`, and the analytics tab queries `analytics/ws/layersUsage.json` & `analytics/ws/layersExtraction.json`

Should there be a way to make it optional ? So far, the interdependencies between webapps were clearly listed, or possibly optional..

**Comment by landryb** [comment]
I think there's also a hidden dep on mfapp, as it queries the (hardcoded, of course) `/mapfishapp/ws/contexts` service in https://github.com/georchestra/georchestra/blob/18.06/console/src/main/webapp/manager/app/app.es6#L73 to display the user default context.

**Comment by landryb** [comment]
And it gets even better... if you have analytics installed, then the 404 on `analytics/ws/layersExtraction.json` becomes a 500, as analytics reaches for an `extractorapp` schema in the database.. so analytics has a hidden dep on extractorapp. 😿

**Comment by fvanderbiest** [comment]
You've put your finger on an issue we're aware of. 
Our goal for 18.12 was to merge analytics into console.

The dependency on mapfishapp and extractorapp should indeed be optional.

**Comment by landryb** [comment]
yeah i've loaded the analytics UI for the first time this morning, and seeing all those extjs small files hits in the accesslog while the page was loading i had some kind of *back to the future* feeling :)

**Comment by fvanderbiest** [comment]
@f-necas is taking care of it

**Comment by f-necas** [comment]
https://github.com/georchestra/georchestra/pull/4080
