### ISSUE TITLE
SP & GWC - hardcoded headerURL and headerHeight

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2173]
https://github.com/georchestra/georchestra/blob/4b68ca7347f57112becf12508dcb89466b57feb1/config/defaults/security-proxy/header.jsp#L6 does not take into account vars from https://github.com/camptocamp/georchestra-grandest-configuration/blob/docker-18.06/default.properties

**Comment by landryb** [comment]
Are you sure this header.jsp is used ? in which cases ?

**Comment by fvanderbiest** [comment]
http://ids.craig.fr/ksqckqqskv ;-)

**Comment by landryb** [comment]
Ok, i see the point now :)

And yeah, i'm aware of the https/http mixup. It's always been awkward, and i'm planning to switch to https in the upcoming upgrade.

**Comment by severo** [comment]
Ocurrences of "@...@" I found (with `ag "@[\.a-zA-Z0-9_-]+@"`):

- https://github.com/georchestra/georchestra/blob/master/cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/default/ui/includes/top-noheader.jsp#L39L40
- https://github.com/georchestra/georchestra/blob/master/cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/default/ui/includes/top.jsp#L38L42
- https://github.com/georchestra/georchestra/blob/master/geowebcache-webapp/src/main/java/org/geowebcache/GeorchestraGeoWebCacheDispatcher.java
- https://github.com/georchestra/georchestra/blob/18.06/mapfishapp/README.md

**Comment by severo** [comment]
Occurrences of "90px":

- https://github.com/georchestra/georchestra/blob/18.06/console/src/main/webapp/manager/app/styles/app.less#L27
- https://github.com/georchestra/georchestra/blob/18.06/cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/default/ui/includes/top.jsp#L40
- https://github.com/georchestra/georchestra/blob/18.06/extractorapp/src/main/webapp/admin/index.html#L16
- https://github.com/georchestra/georchestra/blob/18.06/config/defaults/security-proxy/header.jsp#L6 (o https://github.com/georchestra/georchestra/blob/master/security-proxy/src/main/webapp/header.jsp#L6 on master)

**Comment by severo** [comment]
Occurrences of "/header" or "header/" (`ag -s "/header|header/"`):

- https://github.com/georchestra/georchestra/blob/master/analytics/src/main/webapp/WEB-INF/jsp/index.jsp#L38

- https://github.com/georchestra/georchestra/blob/master/cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/default/ui/includes/top.jsp#41

- https://github.com/georchestra/georchestra/blob/master/console/src/main/webapp/WEB-INF/views/header.jsp#L8
- https://github.com/georchestra/georchestra/blob/master/console/src/main/webapp/manager/app/assets/index.html#L17

- https://github.com/georchestra/georchestra/blob/master/extractorapp/src/main/webapp/admin/index.html#16

- https://github.com/georchestra/georchestra/blob/master/geowebcache-webapp/src/main/java/org/geowebcache/GeorchestraGeoWebCacheDispatcher.java#L70

- https://github.com/georchestra/georchestra/blob/master/header/pom.xml#87

- https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/webapp/WEB-INF/jsp/header.jsp#L12

- https://github.com/georchestra/georchestra/blob/master/security-proxy/src/main/java/org/georchestra/security/Proxy.java#382
- https://github.com/georchestra/georchestra/blob/master/security-proxy/src/main/webapp/WEB-INF/proxy-servlet.xml#25
- https://github.com/georchestra/georchestra/blob/master/security-proxy/src/main/webapp/header.jsp#L6

**Comment by severo** [comment]
I think we have to work on master, not 18.06, because of the work to remove dependency to config.jar (see #1417).

**Comment by fvanderbiest** [comment]
Agreed.

**Comment by severo** [comment]
Remaining occurrences of `header.height`:

- https://github.com/georchestra/georchestra/blob/master/geowebcache-webapp/src/main/java/org/geowebcache/GeorchestraGeoWebCacheDispatcher.java#L70, https://github.com/georchestra/georchestra/blob/master/geowebcache-webapp/src/main/java/org/geowebcache/GeorchestraGeoWebCacheDispatcher.java#L93L113, https://github.com/georchestra/georchestra/blob/master/geowebcache-webapp/src/main/resources/geowebcache.properties#L4

**Comment by severo** [comment]
Remaining occurrences of `georchestra.mydomain.org` to examine:

- https://github.com/georchestra/georchestra/blob/master/security-proxy/src/main/java/org/georchestra/security/Proxy.java#L157
- https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/webapp/WEB-INF/ws-servlet.xml#L52

**Comment by severo** [comment]
OK. I don't know how to fix the last ones, so I open dedicated issues: #2422 and #2423.
Pending PR before closing: #2420, #2421
