### ISSUE TITLE
[mapfishapp] failure to query IGN geoportail WFS

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2177]
geoportail WFS has this in its getCapabilities:
```
<FeatureType>
<Name>BDTOPO_BDD_WLD_WGS84G:transport_cable</Name><Title>BDTOPO_BDD_WLD_WGS84G:transport_cable.title</Title><Abstract>
```
For some reason (i guess geoserver namespaces special handling ?) when adding a layer from such service, mapfishapp strips the first part of the layer name when doing DFT:
```
url=https://wxs.ign.fr/1wexxrf38g4k60sfffkgyotp/geoportail/wfs/?REQUEST=DescribeFeatureType&TYPENAME=transport_cable&VERSION=1.0.0&SERVICE=WFS
```
which results in the following reply from the server:
```
<ServiceException code="InvalidParameterValue" locator="typeName">
      Could not find type name transport_cable
</ServiceException>
```
Readding the 'namespace/prefix' fixes it, but i cant really understand the code in https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/webapp/app/js/GEOR_ows.js#L720 that does the split on ':', nor if it's specific to geoserver, but it breaks certain WFS such as IGN...

**Comment by fvanderbiest** [comment]
Need to test if we can remove this layername split with newest geoserver versions
