### ISSUE TITLE
GeoNetwork - upgrade to 3.4.4

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2198]
From https://github.com/georchestra/geonetwork/pull/91#issuecomment-427892096:
"the 3.4.x branch is now quite stable and we're about to do the 3.4.4 release (hopefully the last)"

**Comment by landryb** [comment]
For the adventurous ppl who would want to eventually work on this ( not me ! ), what's the workflow ?

* Merge upstream/3.4.x in georchestra-3.4-master ?
* Rebase georchestra-3.4-master commits on top of upstream/3.4.x ?

**Comment by fvanderbiest** [comment]
I would opt for the latest one, rebasing commits on top of upstream/3.4.x but I'm not the expert here.
ping @pmauduit @cmangeat 
And 3.6.0 is now stable ...
