### ISSUE TITLE
Console - API should prevent creation of users without email

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2199]
As reported in https://github.com/georchestra/georchestra/issues/2157#issuecomment-427872452

More generally, the same constraints on fields should be applied on the client side and server side.

**Comment by fvanderbiest** [comment]
Did you check @f-necas ?
A bit of explanation would be interesting before closing. Thanks

**Comment by f-necas** [comment]
Yes I tried it and the `mail` attribute is requested (as others which are mandatory in UI)
