### ISSUE TITLE
All modules - more resilient db and ldap connections pools

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2201]
This is WIP with eg #2200 but I feel the need to file this issue so that our apps are able to recover gracefully from failing ldap or db connections.

**Comment by groldan** [comment]
Covered by issue #2414, PR #2436 as long as JDBC connections go. Not sure how the ldap connection pools are handled, need to do some research.

**Comment by groldan** [comment]
Closing, fixed by #2436
