### ISSUE TITLE
GeoServer - docker image missing geofence.dir ?

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2203]
Our geoserver docker image CMD already mentions `-Dgeofence-ovr=file:/etc/georchestra/geoserver/geofence/geofence-datasource-ovr.properties` but it might also miss `-Dgeofence.dir=/etc/georchestra/geoserver/geofence`

To be confirmed.

**Comment by fvanderbiest** [comment]
Maybe @groldan can have a look ?
Here's the dockerfile: https://github.com/georchestra/georchestra/blob/18.06/geoserver/webapp/src/docker/Dockerfile
And the config dir: https://github.com/georchestra/datadir/tree/18.06/geoserver/geofence

**Comment by groldan** [comment]
@fvanderbiest  @pmauduit ok, made some digging around. It looks like the `geofence.dir` never existed in geoserver's geofence source code, just the `geofence-ovr` property file, which the [documentation](https://github.com/geoserver/geofence/wiki/GeoFence-configuration) mentions as valid for both the embedded and standalone versions.

As for georchestra/geofence, I don't think we're using it anymore (last commit being from 2015)?.

**Comment by fvanderbiest** [comment]
Thanks for the investigation Gabriel !
@pmauduit do you remember why we introduced `geofence.dir` in eg https://github.com/camptocamp/georchestra-grandest-configuration/blob/jenkins/geoserver/Dockerfile#L62 ?

**Comment by fvanderbiest** [comment]
> As for georchestra/geofence, I don't think we're using it anymore (last commit being from 2015)?.

Yes.
Then maybe we should remove it.

**Comment by fvanderbiest** [comment]
https://github.com/georchestra/geofence archived
