### ISSUE TITLE
CAS - Relicates of config.jar in the JSP files 

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#2210]
**Bug description**

We can find some traces of the shared config here:
https://github.com/georchestra/georchestra/blob/master/cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/default/ui/includes/top.jsp#L38-L42

**geOrchestra version or branch**

since 18.06, also present on master currently

**Expected behavior**

We should get rid of these shared.* variables previously defined in the old config.jar process. Maybe the concerned variables should end in the default.properties.

**Comment by fvanderbiest** [comment]
linked with #1417

**Comment by fvanderbiest** [comment]
Yes, we should fix all this on master branch.

**Comment by severo** [comment]
Only four PR (#2366, #2367, #2368, #2369) to merge, and we can close the issue!
