### ISSUE TITLE
{publicUrl} not substituted in extractor-email-ack-template.tpl

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2224]
Witnessed on 18.06
https://github.com/georchestra/datadir/blob/docker-18.06/extractorapp/templates/extractor-email-ack-template.tpl

**Comment by severo** [comment]
It's not a bug, it's a feature:

> By default, the ack mail template does not support string substitution, but the second email template does

https://github.com/georchestra/georchestra/blame/18.06/extractorapp/README.md#L101

:)

**Comment by severo** [comment]
See also the docs I wrote to install the environment: https://github.com/severo/some_docs_on_georchestra/blob/master/use_docker_images_for_a_branch.md
