### ISSUE TITLE
epsg-extension - Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2231]
mvn -P-all,mapfishapp install fails on "Custom Extensions to EPSG authority factory" 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project epsg-extension: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]

```
$ mvn --version
Apache Maven 3.5.2
Maven home: /usr/share/maven
Java version: 1.8.0_181, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-36-generic", arch: "amd64", family: "unix"
```

**Comment by fvanderbiest** [comment]
-DskipTests is a workaround but I'm surprised...

**Comment by pmauduit** [comment]
Note that you will have to skip tests everywhere, the debian bug pointed above proposes to add an option to the maven-surefire-plugin (`<useSystemClassLoader>false</useSystemClassLoader>`)

**Comment by landryb** [comment]
Issue still present as of now, and annoying, as it breaks the buildbot ci using stretch - since it uses the Makefile for epsg-extensions, and the Makefile doesnt set -DskipTests. I had to downgrade jdk...

**Comment by groldan** [comment]
Superseded by #2600, should be closed as won't fix
