### ISSUE TITLE
mapfishapp - give a feedback hint to the user when they change the selected tools

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2246]
**Describe the bug**

When selecting/deselecting a tool in mapfishapp, the user has no clear feedback that the operation has been completed successfully, and as the different tools create icons/menus entries/tabs in different places of the interface, it might be hard to understand that the operation (adding/removing a tool) has been successful.

**geOrchestra version or branch**

master

**To Reproduce**

1. go to /mapfishapp/
2. click on "herramientas" / "Manejar las herramientas" (sorry for using Spanish, see #2245)
3. Select other tools
4. Click on "xxx heramientas"
5. See nothing happening

**Expected behavior**

A notification that the tool or tools have added or removed of the interface

**Comment by fvanderbiest** [comment]
There should be a notification ... it's handled here: https://github.com/georchestra/georchestra/blob/b2b0a9c9bd4148ef06bf736d8814b6994fe0bc89/mapfishapp/src/main/webapp/app/js/GEOR_tools.js#L166-L169

Not sure it still works.

**Comment by fvanderbiest** [comment]
Fixed with 468922385
