### ISSUE TITLE
doc - documentation for build is outdated

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2249]
**Describe the bug**

At https://github.com/georchestra/georchestra/blob/master/docs/build.md#install-your-configuration, it is said that:

> By default, cloning the geOrchestra repository will also fetch the template configuration in ~/georchestra/config/configurations/template

It is not true. But I still don't understand enough how the configuration works to fix it.

**geOrchestra version or branch**

master

**Comment by severo** [comment]
Note that https://github.com/georchestra/georchestra/blob/master/docs/config.md seems outdated too:

> Contrary to other projects such as GeoServer, we do not provide generic WARs.
> First thing to note is that you end up in the stable branch (15.12) matching the latest stable geOrchestra version (also 15.12).

Should this doc file disappear entirely?

**Comment by fvanderbiest** [comment]
On master, this is someting I'm currently working on, with #1417 
Documentation should also be part of it, true.

**Comment by fvanderbiest** [comment]
Fixed with https://github.com/georchestra/georchestra/pull/2345/commits/c0f65cdf6a7901e99c62d384bca7f57fab8c61b3
