### ISSUE TITLE
Question: what to do with the security warnings

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2256]
There are two sources of security warnings that are currently not empty:
- https://github.com/georchestra/georchestra/network/alerts
- npm, during the compilation (see https://docs.npmjs.com/auditing-package-dependencies-for-security-vulnerabilities)

What is the plan to fix (or ignore?) these warnings?

**Comment by fvanderbiest** [comment]
Dupe of #2211 
Camptocamp will tackle these issues in the coming days / weeks.
