### ISSUE TITLE
Question - how to best manage frontend exceptions

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2260]
Yesterday in a PR (#2259) on a mapfishapp addon, I took care of a possible Javascript exception, but the question is: what to do with this exception?
Following how it's done in the rest of the file, I added an `alert(...)`, but:
- it will annoy the user
- they maybe will contact the maintainer of the platform
- the maintainer of the platform maybe will fill an issue or fix its configuration.

How could we improve this, and get feedback on the possible errors?

Do you think that https://github.com/getsentry/sentry/ or https://errbit.com/docs/master/ could be a solution, be it for the geOrchestra project or for every instance?

**Comment by fvanderbiest** [comment]
Several platforms currently use Sentry for backend error collection.
There's no plan for more ATM.
