### ISSUE TITLE
console - fix the README

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2262]
**Describe the bug**

The https://github.com/georchestra/georchestra/blob/master/console/README.md file is very outdated (title is "ldapadmin", the text seems to be a specification of the work to do more than a doc, eg. "These pages should be light (no need to ship ExtJS).", the test instructions include a reference to the config directory...)

Note that the work is surely related to #1417, but I created the issue in case we forgot to update this file. 

**geOrchestra version or branch**

master

**Comment by fvanderbiest** [comment]
Dupe of #359, you're right there's something to be done here !

**Comment by severo** [comment]
Ups, sure
