### ISSUE TITLE
console - send a mail at the user when it's account creation has been validated

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2264]
When the `moderatedSignup` variable is set to `true` in the console module configuration (see the [templates documentation](https://github.com/georchestra/datadir/blob/18.06/console/templates/README.md)), a new user has to wait for a validation by an administration of the platform, before their account became enabled. They [receive an email](https://github.com/georchestra/datadir/blob/18.06/console/templates/account-creation-in-progress-template.txt) with the following message: "Your request for a new account will be processed very soon."

But there is no mail sent when the account is effectively validated (or when the account creation is rejected). I think we should send one.

Branch: master

**Comment by fvanderbiest** [comment]
Indeed, it's the platform administrator responsibility to write this email ATM (it's easy, replying is enough).
IMO this makes sense (rather than sending an automatic email), because it allows the admin to have an iteraction with the newcomer, for instance saying "based on what I know from the role you're playing / the org you belong, I granted you the rights to ...".
An automatic email would not provide the new user with these informations.

**Comment by severo** [comment]
OK, I understand.

I have the feeling, though, that sending an automatic mail does no damage, as it does not impede the administrator to send a customized mail, and helps in the case the administrator does not send nothing. Moreover, it seems to me that receiving a notification for every "important" interaction with an online system gives a sense of reliability: you know that you will always receive a notification when something important occurs.

**Comment by landryb** [comment]
I have to agree with @severo here. Yes, having an automated mail when you validate an account would be nice, and it would be better to 'template' it based on the given roles and the rights it gives (ie not only replacing values in the template like we can do now, but being able to do jstl/jinja-like templates) - that's what we actually do with drupal.

Having an email sent when you reject a new account is more problematic, as you might not want the other party to know you've rejected it, and what if its a spambot ? captchas are not always the reliable to prevent them.

**Comment by fvanderbiest** [comment]
Makes sense, OK.
Technically, this means we'll also need to add a "save" button on the user's modify roles page (I mean eg `/console/manager/#!/users/fvanderbiest/roles`) so that we have a single 'bulk' change rather than a batch of atomic role changes.

**Comment by fvanderbiest** [comment]
See #2601
