### ISSUE TITLE
[console] log relevant information in admin log

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2267]
The information logged right now in the `admin_log` table is ... scarce. For an admin, you know that _at some moment, an account did 'something' (a value in a list of 5 possibilites) to another account_. Fine, that's better than nothing, but that's ... not much.

To be actually useful, this could be improved (as part of #2108? #2148?) by logging actual meaningful details:

- SYSTEM_ROLE_CHANGE/OTHER_ROLE_CHANGE => was the role added ? removed ? **which** role ?
- ACCOUNT_MODERATION  only tracks the pending->validated state. How about tracking when an account was deleted ?
- EMAIL_SENT => what email ? from a template, which template ? since the emails are logged, maybe even linking to the actual mail content in the console ?
- LDAP_ATTRIBUTE_CHANGE => **which** attribute(s) ? what was the previous values, the new values ?

on top of this, possibly interesting events to log:
- role creation/removal
- (pending)org creation/validation/removal
- org attribute change, most importantly: **area**. I need to know when someone adds/removes a given area to an org to trigger changes on other apps. short name change is also an interesting event, since it is an ldap group rename, which can have consequences on other apps using the ldap.. same for the org type change, if you have other things depending on this information.

**Comment by fvanderbiest** [comment]
I do agree with everything you said here.

**Comment by Gaetanbrl** [comment]
> LDAP_ATTRIBUTE_CHANGE => which attribute(s) ? what was the previous values, the new values ?

We could add "old_value" and "new_value" entry to contains old/new informations separates by a coma (or whatever you want) : ```attributes1: value, attribute2: value```

![image](https://user-images.githubusercontent.com/16317988/62278741-f4d8ba80-b448-11e9-8a5b-e4de7d5ff0d8.png)

**Comment by landryb** [comment]
if only the changed attributes are listed then that would be fine for me.

beware of all the possible corner cases:
* in the same event, multiple distinct attributes can change (ie admin changes attr X and Y then hits save)
* a multivalued attribute (ie description/area, or member) gets a new value
* a multivalued attribute loses a value
* an attribute which was previously missing is added
* an attribute which was present is removed

**Comment by Gaetanbrl** [comment]
> if only the changed attributes are listed then that would be fine for me.

So, only one field will be added to list attributes instead of 2 fields "old" / "new".

>beware of all the possible corner cases:

You need to distinguish this possible cases in the logs table ?

**Comment by landryb** [comment]
> > if only the changed attributes are listed then that would be fine for me.
> 
> So, only one field will be added to list attributes instead of 2 fields "old" / "new".

you still need to display the old & new values to be able to correlate them :)

> > beware of all the possible corner cases:
> 
> You need to distinguish this possible cases in the logs table ?

no but they need to be handled / tested ;)

**Comment by RemiDesgrange** [comment]
maybe instead of old_value and new_value as text and comma separated stuff we could simply store everything in json. Or if you're old school doing EAV.

**Comment by Gaetanbrl** [comment]
Yes, values was already display as JSON since we display emails infos inside logs.

**Comment by landryb** [comment]
Work in progress is [here](jdev-org/georchestra/tree/issue-2267)

**Comment by RemiDesgrange** [comment]
broken link

**Comment by landryb** [comment]
Meh. fixed..

**Comment by landryb** [comment]
we had a lenghty discussion with @Gaetanbrl yesterday to list all the possible actions/cases, and the way they will be displayed in the UI (and accessed/filtered). The issue will be updated with the result of that discussion shortly.

**Comment by Gaetanbrl** [comment]
Further to our discussion with @Landry we expect to :

1. Add more type for admin logs (AdminlogType) visible in the "Action" column :
EMAIL_SENT
ORG_ATRIBUTE_CHANGE
USER_ATTRIBUTE_CHANGE
PENDING_USER_VALID or PENDING_USER_REFUSE
PENDING_ORG_VALID or PENDING_ORG_REFUSE
SYSTEM_ROLE_ADD, SYSTEM_ROLE_DEL
OTHER_ROLE_ADD, OTHER_ROLE_DEL
ROLE_ADD, ROLE_DEL
ORG_MODERATION_ADD, ORG_MODERATION_DEL
USER_MODERATION_ADD, USER_MODERATION_DEL

2. For each action visible in the "Action" column, we expect to get a short info about changed attribute (see picture).
	
3. Each action could be clickable (if necessary) to get more informations about the modification, inspired from the email interaction (click to open in a view like user's email UI).

4. If more than one attribute is changed (for one user or org), we get one log per changed value (see picture for jdupuis).

5. Elements in "Target" column are clickable, in order to directly access to the role, org, user view.

6. Action filter display in a list (with input to search in values) : 
Attributes name, all created roles value, admin logs type

![image](https://user-images.githubusercontent.com/16317988/64331681-86e95b00-cfd3-11e9-8507-75fb7ef6cee7.png)

Do you agree with this approach ?

**Comment by fvanderbiest** [comment]
Thanks for the proposal !

If we go for `EMAIL_SENT` I would rename the others into :
```
ORG_ATTRIBUTE_CHANGED
USER_ATTRIBUTE_CHANGED
PENDING_USER_ACCEPTED or PENDING_USER_REFUSED
PENDING_ORG_ACCEPTED or PENDING_ORG_REFUSED
SYSTEM_ROLE_ADDED, SYSTEM_ROLE_DELETED 
OTHER_ROLE_ADDED, OTHER_ROLE_DELETED
ROLE_ADDED, ROLE_DELETED
ORG_MODERATION_ADDED, ORG_MODERATION_DELETED
USER_MODERATION_ADDED, USER_MODERATION_DELETED
```

I don't understand you distinction between SYSTEM_ROLE / OTHER_ROLE / ROLE in the following:
```
SYSTEM_ROLE_ADDED, SYSTEM_ROLE_DELETED 
OTHER_ROLE_ADDED, OTHER_ROLE_DELETED
ROLE_ADDED, ROLE_DELETED
```
Roles are categorized either as `SYSTEM` or `OTHER`.

In addition, what is the meaning of:
```
ORG_MODERATION_ADDED, ORG_MODERATION_DELETED
USER_MODERATION_ADDED, USER_MODERATION_DELETED
```

**Comment by fvanderbiest** [comment]
While we're at it, I think that these action keys should not be displayed as such to admin users.
Instead, a nice & short sentence should appear, eg `PENDING_USER_ACCEPTED` should be replaced with `User account accepted`.

**Comment by landryb** [comment]
> In addition, what is the meaning of:
> 
> ```
> ORG_MODERATION_ADDED, ORG_MODERATION_DELETED
> USER_MODERATION_ADDED, USER_MODERATION_DELETED
> ```

I think those are for the cases when a user requests an account (USER_MODERATION_ADDED), eventually creating a new pending org (ORG_MODERATION_ADDED), and if the admin decides to refuse them then the pending acct/org is deleted and triggers the USER/ORG_MODERATION_DELETED events.

maybe ORG_MODERATION_DELETED is the same as PENDING_ORG_REFUSED, and USER_MODERATION_ADDED should be PENDING_USER_WAITING (same thing for org?)

**Comment by landryb** [comment]
> I don't understand your distinction between SYSTEM_ROLE / OTHER_ROLE / ROLE in the following:
> 
> ```
> SYSTEM_ROLE_ADDED, SYSTEM_ROLE_DELETED 

A system role was added/removed on an user (as, technically, in the ldap, the member is added *on the role object* so the role itself is modified)

> OTHER_ROLE_ADDED, OTHER_ROLE_DELETED

A georchestrarole was added/removed on an user

> ROLE_ADDED, ROLE_DELETED

A role was created/removed

> Roles are categorized either as `SYSTEM` or `OTHER`.

**Comment by fvanderbiest** [comment]
OK, for clarity please consider then : 
`ROLE_CREATED, ROLE_DELETED` 
`OTHER_ROLE_ADDED, OTHER_ROLE_REMOVED`
`SYSTEM_ROLE_ADDED, SYSTEM_ROLE_REMOVED`

**Comment by Gaetanbrl** [comment]
>maybe ORG_MODERATION_DELETED is the same as PENDING_ORG_REFUSED, and USER_MODERATION_ADDED should be PENDING_USER_WAITING (same thing for org?)

Currently, we have only _ACCOUNT_MODERATION_ . So, i could identify 4 situation : 
- user create account >> PENDING_USER_ADDED
- org is create >> PENDING_ORG_ADDED
- admin create manually user (example : to create test user) >> USER_MODERATION_ADD
- admin create manually org (example : to create test org) >> ORG_MODERATION_ADD  
- pending user is accepted  or refused>> PENDING_USER_ACCEPTED or _REFUSED
- pending ORG is accepted  or refused>> PENDING_ORG_ACCEPTED or _REFUSED

Create org, user, role manually are very usefull to test or directly create something (ex : you need to prepare account for a demo or something else fastly). In this case, user is not in PENDING and direclty create.

**Comment by Gaetanbrl** [comment]
Yes @landryb  for SYSTEM and OTHER role.

**Comment by Gaetanbrl** [comment]
I propose this template to get more logs details on click @landryb  : 
![image](https://user-images.githubusercontent.com/16317988/65413227-4706de00-ddf1-11e9-9742-703b74d012d6.png)

**Comment by landryb** [comment]
looks great ! maybe display the time in addition of the date ? 'ancienne valeur' + 'nouvelle valeur' ?

**Comment by Gaetanbrl** [comment]
> looks great ! maybe display the time in addition of the date ?

Indeed, if you need this information we can display the time.

> 'ancienne valeur' + 'nouvelle valeur' ?

What do you mean ?

**Comment by landryb** [comment]
for the strings, 'ancienne' & 'nouvelle' only is a bit obscure ..

**Comment by Gaetanbrl** [comment]
Do you prefer a sentence like `Replace Foo by Bar`  ?
If Foo or Bar is empty, we could display `Set Foo` or `Clear foo`.

**Comment by landryb** [comment]
Definitely more user friendly  :)

**Comment by Gaetanbrl** [comment]
@landryb this look good for you so ? 
![image](https://user-images.githubusercontent.com/16317988/65497125-f7401980-deb9-11e9-8915-73cac529a938.png)

**Comment by landryb** [comment]
great :)

**Comment by landryb** [comment]
@fvanderbiest with @Gaetanbrl we were wondering what to do with existing records in the db, ie should we keep the old values for the AdminLogType enum to display the old log records, or should we drop them/ignore them and have a clean start with our new layout ?

I was in favor of keeping them to avoid breaking compatibility (and i dunno how other SDI rely on those infos), but from my understanding you dont mind dropping them from the display ? they will still be in the database anyway....

**Comment by landryb** [comment]
testing lots of different usecases, when an org is renamed (ie `shortName` is modified, say from 'c2c' to 'c2c2' ) the logged target is wrong and thus the link target too - ie `name` is used, the link target is `Camptocamp` while it should be the new value of `shortName`.
```
 290 | testadmin | 2019-09-27 11:17:36.558 | Camptocamp         |    8 | {"new":"C2C2","field":"shortName","old":"C2C","type":"Attribute was changed for an org"}
 291 | testadmin | 2019-09-27 11:17:41.536 | Camptocamp         |    8 | {"new":"C2C","field":"shortName","old":"C2C2","type":"Attribute was changed for an org"}
```
Modifying an org description feels wrong as the value of the address is logged as previous value:
```
 289 | testadmin | 2019-09-27 11:17:30.981 | c2c                |    8 | {"new":"Camptocamp SAS France","field":"description","old":"18 Rue du lac Saint André, 73000 Chambéry","type":"Attribute was changed for an org"}
```

**Comment by fvanderbiest** [comment]
> testing lots of different usecases, when an org is renamed (ie `shortName` is modified, say from 'c2c' to 'c2c2' ) the logged target is wrong and thus the link target too - ie `name` is used, the link target is `Camptocamp` while it should be the new value of `shortName`.

The PR should include unit tests.

**Comment by fvanderbiest** [comment]
> we were wondering what to do with existing records in the db, ie should we keep the old values for the AdminLogType enum to display the old log records, or should we drop them/ignore them and have a clean start with our new layout ?

I'd rather start from a fresh base, since we all agree that previous logs were nearly unusable.

**Comment by Gaetanbrl** [comment]
@landryb thanks. Reproduce and fix.

**Comment by landryb** [comment]
@fvanderbiest can you be a little more specific on which unit tests should be done ?

**Comment by landryb** [comment]
On the console homepage (`/console/manager/#!/home`) the link targets for the adminlog target are always pointing at `console/manager/users/<uid>/infos` while it should point at `console/manager/org/<orgid>/infos` when the target is an org..

**Comment by landryb** [comment]
Tried creating a pending account via `/console/account/new`, was created in ldap but no admin log ?

**Comment by landryb** [comment]
On a sidenote, PENDING_ORG_CREATED event is correctly logged when a pending user creates his org when registering.

**Comment by Gaetanbrl** [comment]
>was created in ldap but no admin log ?

I get and see this log when i try to reproduce this case. What is your branch ?

![image](https://user-images.githubusercontent.com/16317988/66555468-03c9a080-eb4f-11e9-8749-36c638de9848.png)

**Comment by landryb** [comment]
i dont understand why PENDING_USER_CREATED wasnt logged, as there's code (`account.setPending(this.moderatedSignup)`) that ensures the new account is pending (`moderatedSignup` defaults to true) so `account.isPending()` test should succeed. Will do more testing.

**Comment by landryb** [comment]
Disregard, it was a  local problem, for some reason memberOf overlay was missing at some point when i recreated my DIT, so the search for SUPERUSER members in https://github.com/georchestra/georchestra/blob/master/console/src/main/java/org/georchestra/console/ws/newaccount/NewAccountFormController.java#L279 yielded nothing, and that caused a `Caused by: javax.mail.SendFailedException: No recipient addresses` exception on https://github.com/georchestra/georchestra/blob/master/console/src/main/java/org/georchestra/console/ws/newaccount/NewAccountFormController.java#L297, thus the line logging PENDING_USER_CREATED wasnt reached.

**Comment by landryb** [comment]
When EMAIL_SENT is logged, and viewing the corresponding event details, only the sender, date and email content is shown - is it possible to also show the recipient ? I know this info is available on the 'all logs' page but still could be useful.. just a minor detail.

**Comment by landryb** [comment]
EMAIL_RECOVERY_SENT doesnt work and is probably a copy-paste, as https://github.com/jdev-org/georchestra/blob/issue-2267-pr/console/src/main/java/org/georchestra/console/ws/passwordrecovery/PasswordRecoveryFormController.java#L188 doesnt make sense to me - why trying to get the content of `sec-username`, as at that point if the user itself isnt connected and wants to get his passwd sent he .. wont be connected ?

Imo this only takes care of the 'administrator sends the reset pwd link to user' case, not the 'user clicked on the forgot password link' on the cas login page.

So i think the `if (admin != null)` check should be removed so that both cases are handled, and while here remove the bogus `// log role deleted` comment :)

**Comment by landryb** [comment]
In https://github.com/jdev-org/georchestra/blob/issue-2267-pr/console/src/main/java/org/georchestra/console/ws/backoffice/orgs/OrgsController.java#L500 would be nice to have some consistency on the first parameter to `createLog` calls, sometimes it's `orgId`, sometimes `json.optString(Org.JSON_SHORT_NAME)`, and in my testing that lead to some cases where target wasnt clickable while it could (for example with `ORG_ATTRIBUTE_CHANGED (cities) ` - i think only this case is bogus but i didnt test all cases_

**Comment by Gaetanbrl** [comment]
> So i think the if (admin != null) check should be removed

It's maybe better to keep this test and create an other `else` case, to create a log without `sec-username` if not.

**Comment by landryb** [comment]
would work too for me, dunno what would be displayed if the log entry was stored with null for username.

**Comment by landryb** [comment]
As mentioned privately, 255 for the `changed` field in `admin_log` table feels a bit tight, as json tends to be a bit verbose, and lots of things end up logged.. email body, potentially large list of removed/added insee codes, etc... a laaaarger fieldsize would imo be a better fit, and once its been in a release it might not be easy to change it later on.

**Comment by landryb** [comment]
Another usecase not handled/logged - an user can modify a subset of his own attributes (when logged in) on `console/account/userdetails` - the new values are correctly persisted in the ldap but no USER_ATTRIBUTE_CHANGED event is logged

**Comment by landryb** [comment]
for the  'user modifies his attrs' case i think an event should be logged in the `edit` method in console/src/main/java/org/georchestra/console/ws/edituserdetails/EditUserDetailsFormController.java

**Comment by Gaetanbrl** [comment]
> for the 'user modifies his attrs' case i think an event should be logged in the edit

You forget to /editorgdetails/EditOrgDetailsFormController.java  to log Org modification from user details 😏.

**Comment by Gaetanbrl** [comment]
> for the 'user modifies his attrs' case

@landryb work is done in `dev` branch according to log modifications about org / user.

**Comment by Gaetanbrl** [comment]
> a laaaarger fieldsize would imo be a better fit

Indeed, it could be better if possible.

**Comment by Gaetanbrl** [comment]
>would be nice to have some consistency [...]
> first parameter to createLog calls, sometimes it's orgId, sometimes json.optString(Org.JSON_SHORT_NAME)

You'r right.
> for example with ORG_ATTRIBUTE_CHANGED (cities)

Weird, but works on dev.
I will update PR branch soon with refacto, Test U and apply some fix (according to test explained here ).

**Comment by landryb** [comment]
> > a laaaarger fieldsize would imo be a better fit
> 
> Indeed, it could be better if possible.

Well, what in the hibernate  goop says that `private String` maps to `varchar(255)` and how can one tell it to map to `text` ?

Looking a bit on the interwebs, it seems adding `@Column(columnDefinition = "TEXT")` above https://github.com/georchestra/georchestra/commit/15f7b894fcacffd73154c817b1ce50c995480592#diff-d01214e5dd9f76b65a774b1b1d12d0f4R46 should achieve that

**Comment by landryb** [comment]
`text`/`longvarchar` allows for 32k strings which gives us some room imo :)

**Comment by landryb** [comment]
`clob`/`blob` might be a better fit but i'm not java/hibernate expert.. @cmangeat ? @fvanderbiest ?

**Comment by landryb** [comment]
Now that we have a nice UI in logs, can we also get the action details (clickable to view the event) on the console homepage ? Right now i have `USER_ATTRIBUTE_CHANGED` (not clickable) for an event, while on the logs page i have (for the same event) `USER_ATTRIBUTE_CHANGED (org) ` which allows to see the event details.

**Comment by Gaetanbrl** [comment]
> can we also get the action details (clickable to view the event) on the console homepage

@landryb, you can now click get the action details from the console home page.

**Comment by landryb** [comment]
woot! kudos @Gaetanbrl ;)
