### ISSUE TITLE
[console] ldap spam on org attribute change

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2270]
Pretty sure that's a fallout of #2174 fixing #2107, right now just when changing a single attr value (say, org address, or coverage) the ldap directory sees 6 large changes:
```
Nov 22 16:52:26 demo slapd[15919]: conn=2562 op=1 MODRDN dn="cn=Conseil régional d'Alsace,ou=orgs,dc=georchestra,dc=org"
Nov 22 16:52:26 demo slapd[15919]: conn=2563 op=2 DEL dn="cn=Conseil régional d'Alsace,ou=orgs,dc=georchestra,dc=org"
Nov 22 16:52:26 demo slapd[15919]: conn=2563 op=3 ADD dn="cn=Conseil régional d'Alsace,ou=orgs,dc=georchestra,dc=org"
Nov 22 16:52:26 demo slapd[15919]: conn=2564 op=1 MODRDN dn="o=Conseil régional d'Alsace,ou=orgs,dc=georchestra,dc=org"
Nov 22 16:52:26 demo slapd[15919]: conn=2565 op=2 DEL dn="o=Conseil régional d'Alsace,ou=orgs,dc=georchestra,dc=org"
Nov 22 16:52:26 demo slapd[15919]: conn=2565 op=3 ADD dn="o=Conseil régional d'Alsace,ou=orgs,dc=georchestra,dc=org"
```
It's as if the two entries were completely recreated from scratch, while the backend was supposed to only change a single attribute value in the LDAP..

Will revert to a webapp before #2174 to check.

**Comment by landryb** [comment]
Reverting to `99.master.201809191639~b2ba8eb` doesnt show the MODRDN upon just changing a single attr value, but the DEL/ADD were already there:
```
Nov 22 17:04:17 demo slapd[15919]: conn=2569 op=2 DEL dn="cn=Conseil régional d'Alsace,ou=orgs,dc=georchestra,dc=org"
Nov 22 17:04:17 demo slapd[15919]: conn=2569 op=3 ADD dn="cn=Conseil régional d'Alsace,ou=orgs,dc=georchestra,dc=org"
Nov 22 17:04:17 demo slapd[15919]: conn=2570 op=2 DEL dn="o=Conseil régional d'Alsace,ou=orgs,dc=georchestra,dc=org"
Nov 22 17:04:17 demo slapd[15919]: conn=2570 op=3 ADD dn="o=Conseil régional d'Alsace,ou=orgs,dc=georchestra,dc=org"
```
can we do something smarter than the huge hammer of removing/recreating everything from what java thinks it knows about ldap content ?

**Comment by landryb** [comment]
As an example, setting the title attr on a user does the right thing:
```
Nov 22 17:09:15 demo slapd[15919]: conn=2588 op=1 MOD dn="uid=testadmin,ou=users,dc=georchestra,dc=org"
Nov 22 17:09:15 demo slapd[15919]: conn=2588 op=1 MOD attr=title
```

**Comment by landryb** [comment]
Reupdated to `99.master.201811131441~b67926c` for more testing: Removing a member from an org (from the user page) does the right thing:
```
Nov 23 08:31:10 demo slapd[15919]: conn=2619 op=1 MOD dn="cn=Project Steering Committee Bluh Foo,ou=orgs,dc=georchestra,dc=org"
Nov 23 08:31:10 demo slapd[15919]: conn=2619 op=1 MOD attr=member
```
Readding a member to an org on the user page also does the right thing:
```
Nov 23 08:38:57 demo slapd[15919]: conn=2643 op=1 MOD dn="cn=Project Steering Committee Bluh Foo,ou=orgs,dc=georchestra,dc=org"
Nov 23 08:38:57 demo slapd[15919]: conn=2643 op=1 MOD attr=member
```

On a sidenote, trying to add or remove a member from the `/console/manager/#!/org/Conseil régional d'Alsace/users` (implemented in #2154) now triggers a 500 on the `PUT https://<url>/console/private/users` call (i'm pretty sure i had successfully tested this one though..):
```
org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'PUT' not supported
```

**Comment by landryb** [comment]
Adding/removing a user to a role (be it from the role page or the user page) does the right thing, ie only modifiers the `member` attribute of the `ou=roles` object.

**Comment by landryb** [comment]
Dunno if this is related to the issue (or to #2277) but at some point i'm pretty sure the org ldap objects were named after the short org name (stored in the `ou` attribute of the `cn` object ?) ie, i had o=PSC & cn=PSC, o=C2C & cn=C2C, and now it seems those objects are named after the full name (ie `dn: o=Project Steering Committee Bluh Foo,ou=orgs`, `dn: cn=Project Steering Committee Bluh Foo,ou=orgs`). I'm not sure this change was intentional, but i'm sure in 18.06 the ldap scheme used the previous hierarchy.

This of course impacts the urls called by the console, now `/manager/#!/org/Conseil régional d'Alsace/infos` and previously `/manager/#!/org/CRA/infos` which is harmless for the console webappitself, but could be confusing for 3rd party apps trying to use the private json API: calling `/console/private/orgs/Project%20Steering%20Committee%20Bluh%20Foo` is harder thant `/console/private/orgs/PSC`

**Comment by landryb** [comment]
Ie i'd expect naming to follow what's still in https://github.com/georchestra/georchestra/blob/master/ldap/georchestra.ldif#L219

Dunno what manipulations have been done in the console to change the objects names, but something went wrong at some point....

**Comment by landryb** [comment]
Looked at bit more at the commit, especially https://github.com/georchestra/georchestra/pull/2174/commits/9746cac0d8d74e5b68aba0a548807d5084609d2f#diff-c293194c45071b4aa302edf0a82d602d ->
  * now a `rename()` is done on the `LdapTemplate` object at each `update()` call, whether or not the actual DN changed or not. Not very fine-grained..
  * the `rebind()` operation is also gross, per https://docs.spring.io/spring-ldap/docs/current/reference/#updating it 'works' but that's mostly a "trash everything and replace" while it'd be much cleaner to use `modifyAttributes()` like explained on https://docs.spring.io/spring-ldap/docs/current/reference/#adding-and-updating-data-using-dircontextadapter - that would allow a much better transaction model against the ldap (and allow me to properly detect changes in LDAP in what i'm building right now).

As for the move from short names to full names, i haven't figured out yet where it comes from.

**Comment by landryb** [comment]
> As for the move from short names to full names, i haven't figured out yet where it comes from.

I think it's related to https://github.com/georchestra/georchestra/commit/9746cac0d8d74e5b68aba0a548807d5084609d2f#diff-64866de091337b8c3df5683c59092996 which uses JSON_NAME as source for the id, while previously it would use JSON_SHORT_NAME (by default ? i dont see another code change related to this... and id seems built from JSON_NAME)

**Comment by cmangeat** [comment]
> Looked at bit more at the commit, especially [9746cac#diff-c293194c45071b4aa302edf0a82d602d](https://github.com/georchestra/georchestra/commit/9746cac0d8d74e5b68aba0a548807d5084609d2f#diff-c293194c45071b4aa302edf0a82d602d) ->
> 
> * now a `rename()` is done on the `LdapTemplate` object at each `update()` call, whether or not the actual DN changed or not. Not very fine-grained..
> * the `rebind()` operation is also gross, per https://docs.spring.io/spring-ldap/docs/current/reference/#updating it 'works' but that's mostly a "trash everything and replace" while it'd be much cleaner to use `modifyAttributes()` like explained on https://docs.spring.io/spring-ldap/docs/current/reference/#adding-and-updating-data-using-dircontextadapter - that would allow a much better transaction model against the ldap (and allow me to properly detect changes in LDAP in what i'm building right now).
> 
> As for the move from short names to full names, i haven't figured out yet where it comes from.

**Comment by cmangeat** [comment]
i am not sure that modifyAttributes() is smart enough to perform rebind(). I remember having seen records with key not corresponding to attribute when testing, that is to said still registred with old attribute value.

Concerning transaction model, the big trouble in my opinion is beetween ldap, sql database and end user  sent mail, sql database and ldap transaction should be rollbacked when mail cannont be sent, and ldap transaction when db failure.

**Comment by cmangeat** [comment]
I a am a little bit disappointed for org name and id, you are right.

**Comment by landryb** [comment]
> i am not sure that modifyAttributes() is smart enough to perform rebind().

modifyAttribute() does the right thing here in my testing, but if you have a more specific testcase that failed i can try it.

> I a am a little bit disappointed for org name and id, you are right.

the PR fixes it. your call on how to handle the migration..

**Comment by cmangeat** [comment]
Sorry for the noise, mismatch at my side between rename and rebind.

What do you mean by "handle the migration.." ?

**Comment by landryb** [comment]
Well i think in production directories since there's a mismatch between the ldif (where it shows its should be short name) and what the console actually does (use the long name, and since some releases ?), it might need renaming/migration for 18.12 (ie rename all org objects to actually use/match the short name ?) otherwise the console might not be able to access those objects.

Someone running a 18.06 instance and managing accounts/orgs with the console should look at how the ldap objects are named in their directories...

**Comment by landryb** [comment]
since #2287 was merged, should this issue be closed, or stay open until someone figures out what is needed to handle the ldap objects renaming needed for the 18.06 -> 18.12 migration ?

**Comment by fvanderbiest** [comment]
o/
having a look asap

**Comment by fvanderbiest** [comment]
Here's a diff of the LDAP between 18.06 and master: 
```diff
diff --git a/ldap/georchestra.ldif b/ldap/georchestra.ldif
index d02b8f3d2..25ee747c9 100644
--- a/ldap/georchestra.ldif
+++ b/ldap/georchestra.ldif
@@ -4,6 +4,12 @@ objectClass: organizationalUnit
 objectClass: top
 ou: users
 
+# pendingusers, georchestra.org
+dn: ou=pendingusers,dc=georchestra,dc=org
+objectClass: organizationalUnit
+objectClass: top
+ou: pendingusers
+
 # testuser, users, georchestra.org
 dn: uid=testuser,ou=users,dc=georchestra,dc=org
 objectClass: organizationalPerson
@@ -17,7 +23,6 @@ givenName: Test
 sn: USER
 l: SRID=4326;POLYGON((-5.76043921875 48.698689609375,-2.02508765625 50.104939609375,2.45733421875 51.423298984375,7.51104515625 47.644002109375,6.23663109375 45.842244296875,7.29131859375 42.853963046875,3.59991234375 41.975056796875,-2.55243140625 43.601033359375,-5.76043921875 48.698689609375))
 description: USER
-employeeNumber: 1
 userPassword:: e1NIQX1SY1Z4b1ZiZHp2UVRVYWNUdk4zdVc2ZnBWR0E9
 cn: testuser
 
@@ -32,7 +37,6 @@ uid: testreviewer
 givenName: Test
 sn: REVIEWER
 description: Reviewer
-employeeNumber: 2
 userPassword:: e1NIQX1Nb3IzdXZ5cnpISWpHK0crSEcvblhxZW8reWc9
 mail: psc+testreviewer@georchestra.org
 cn: testreviewer
@@ -48,7 +52,6 @@ uid: testeditor
 givenName: Test
 sn: EDITOR
 description: editor
-employeeNumber: 3
 userPassword:: e1NIQX1mVTFvSmdzV0FEZ1ZtTHBHeHBxdFBVa2RiekU9
 mail: psc+testeditor@georchestra.org
 cn: testeditor
@@ -64,7 +67,6 @@ uid: testadmin
 givenName: Test
 sn: ADMIN
 description: Admin user
-employeeNumber: 4
 userPassword:: e1NIQX1kREU1SkEvMkVpVTRGMFFObUt5eXpuazUrN1E9
 mail: psc+testadmin@georchestra.org
 cn: testadmin
@@ -80,12 +82,11 @@ objectClass: top
 mail: psc+geoserver_privileged_user@georchestra.org
 uid: geoserver_privileged_user
 cn: geoserver_privileged_user
-employeeNumber: 5
 description: Do not modify.  This is a required user for extractorapp, geofence, mapfishapp...
 userPassword:: e1NIQX1XMlY4d2UrOFdNanpma28rMUtZVDFZcWZFVDQ9
 
 # testpendinguser, users, georchestra.org
-dn: uid=testpendinguser,ou=users,dc=georchestra,dc=org
+dn: uid=testpendinguser,ou=pendingusers,dc=georchestra,dc=org
 objectClass: inetOrgPerson
 objectClass: organizationalPerson
 objectClass: person
@@ -95,7 +96,6 @@ uid: testpendinguser
 givenName: Test
 sn: PENDINGUSER
 description: User pending admin validation
-employeeNumber: 6
 userPassword:: e1NIQX16cnJXRCtmbnc2QjZGVDRpcFVYMzh0d1VxRHM9
 mail: psc+testpendinguser@georchestra.org
 cn: testpendinguser
@@ -111,7 +111,6 @@ uid: testdelegatedadmin
 givenName: Test
 sn: DELEGATEDADMIN
 description: User with admin delegation
-employeeNumber: 7
 userPassword:: e1NIQX02OGRFejBlb25BYkdjVm1aWkFoQVVDYmo3bTQ9
 mail: psc+testdelegatedadmin@georchestra.org
 cn: testdelegatedadmin
@@ -127,27 +126,15 @@ dn: cn=ADMINISTRATOR,ou=roles,dc=georchestra,dc=org
 objectClass: top
 objectClass: groupOfMembers
 cn: ADMINISTRATOR
-ou: 1
 description: This group grants admin access to GeoServer
 member: uid=geoserver_privileged_user,ou=users,dc=georchestra,dc=org
 member: uid=testadmin,ou=users,dc=georchestra,dc=org
 
-
-# PENDING, roles, georchestra.org
-dn: cn=PENDING,ou=roles,dc=georchestra,dc=org
-objectClass: top
-objectClass: groupOfMembers
-cn: PENDING
-ou: 2
-description: This group does not grant any right inside the SDI. Users in this group are requesting a fully fledged account.
-member: uid=testpendinguser,ou=users,dc=georchestra,dc=org
-
 # SUPERUSER, roles, georchestra.org
 dn: cn=SUPERUSER,ou=roles,dc=georchestra,dc=org
 objectClass: top
 objectClass: groupOfMembers
 cn: SUPERUSER
-ou: 10
 description: This group grants access to the LDAPadmin private User Interface
 member: uid=testadmin,ou=users,dc=georchestra,dc=org
 
@@ -156,7 +143,6 @@ dn: cn=EXTRACTORAPP,ou=roles,dc=georchestra,dc=org
 objectClass: top
 objectClass: groupOfMembers
 cn: EXTRACTORAPP
-ou: 11
 description: This group grants access to the Extractorapp application
 member: uid=testadmin,ou=users,dc=georchestra,dc=org
 
@@ -166,7 +152,6 @@ dn: cn=GN_ADMIN,ou=roles,dc=georchestra,dc=org
 objectClass: top
 objectClass: groupOfMembers
 cn: GN_ADMIN
-ou: 20
 description: This group grants admin access to GeoNetwork
 member: uid=testadmin,ou=users,dc=georchestra,dc=org
 
@@ -175,7 +160,6 @@ dn: cn=GN_EDITOR,ou=roles,dc=georchestra,dc=org
 objectClass: top
 objectClass: groupOfMembers
 cn: GN_EDITOR
-ou: 21
 description: This group grants edit rights in GeoNetwork
 member: uid=testeditor,ou=users,dc=georchestra,dc=org
 
@@ -184,7 +168,6 @@ dn: cn=GN_REVIEWER,ou=roles,dc=georchestra,dc=org
 objectClass: top
 objectClass: groupOfMembers
 cn: GN_REVIEWER
-ou: 22
 description: This group grants reviewer (publish) rights in GeoNetwork
 member: uid=testreviewer,ou=users,dc=georchestra,dc=org
 
@@ -193,7 +176,6 @@ dn: cn=USER,ou=roles,dc=georchestra,dc=org
 objectClass: top
 objectClass: groupOfMembers
 cn: USER
-ou: 23
 description: This group grants basic, authenticated access to the whole SDI
 member: uid=testuser,ou=users,dc=georchestra,dc=org
 member: uid=testeditor,ou=users,dc=georchestra,dc=org
@@ -206,7 +188,6 @@ dn: cn=ORGADMIN,ou=roles,dc=georchestra,dc=org
 objectClass: top
 objectClass: groupOfMembers
 cn: ORGADMIN
-ou: 24
 description: This role is automatically granted to all users holding an admin delegation
 member: uid=testdelegatedadmin,ou=users,dc=georchestra,dc=org
 
@@ -216,18 +197,24 @@ objectClass: organizationalUnit
 objectClass: top
 ou: orgs
 
+# orgs, georchestra.org
+dn: ou=pendingorgs,dc=georchestra,dc=org
+objectClass: organizationalUnit
+objectClass: top
+ou: pendingorgs
+
+
 dn: o=psc,ou=orgs,dc=georchestra,dc=org
 objectClass: organization
 objectClass: top
 o: psc
-businessCategory: ASSOCIATION
+businessCategory: Association
 postalAddress: 127 rue georchestra, 73590 Chamblille
 
 dn: cn=psc,ou=orgs,dc=georchestra,dc=org
 objectClass: groupOfMembers
 objectClass: top
 cn: psc
-businessCategory: REGISTERED
 description: 4184,684,9849,7987,797898,5797,579,97,49,797,97
 member: uid=testadmin,ou=users,dc=georchestra,dc=org
 member: uid=testuser,ou=users,dc=georchestra,dc=org
@@ -240,14 +227,13 @@ dn: o=c2c,ou=orgs,dc=georchestra,dc=org
 objectClass: organization
 objectClass: top
 o: c2c
-businessCategory: COMPANY
+businessCategory: Company
 postalAddress: 18 Rue du lac Saint André, 73000 Chambéry
 
 dn: cn=c2c,ou=orgs,dc=georchestra,dc=org
 objectClass: groupOfMembers
 objectClass: top
 cn: c2c
-businessCategory: REGISTERED
 description: 4184
 member: uid=testeditor,ou=users,dc=georchestra,dc=org
 o: Camptocamp
@@ -258,34 +244,32 @@ dn: o=cra,ou=orgs,dc=georchestra,dc=org
 objectClass: organization
 objectClass: top
 o: cra
-businessCategory: COMPANY
+businessCategory: Company
 postalAddress: Rue Jean Wenger - Valentin, 67000 Strasbourg
 
 dn: cn=cra,ou=orgs,dc=georchestra,dc=org
 objectClass: groupOfMembers
 objectClass: top
 cn: cra
-businessCategory: REGISTERED
 description: 4184
 member: uid=testreviewer,ou=users,dc=georchestra,dc=org
 o: Conseil régional d'Alsace
 ou: CRA
 seeAlso: o=cra,ou=orgs,dc=georchestra,dc=org
 
-dn: o=pendingorg,ou=orgs,dc=georchestra,dc=org
+dn: o=pendingorg,ou=pendingorgs,dc=georchestra,dc=org
 objectClass: organization
 objectClass: top
 o: pendingorg
-businessCategory: COMPANY
+businessCategory: Company
 postalAddress: Null island
 
-dn: cn=pendingorg,ou=orgs,dc=georchestra,dc=org
+dn: cn=pendingorg,ou=pendingorgs,dc=georchestra,dc=org
 objectClass: groupOfMembers
 objectClass: top
 cn: pendingorg
-businessCategory: PENDING
 description: 59107
-member: uid=testpendinguser,ou=users,dc=georchestra,dc=org
+member: uid=testpendinguser,ou=pendingusers,dc=georchestra,dc=org
 o: Fictive org pending admin validation
 ou: PENDINGORG
 seeAlso: o=pendingorg,ou=orgs,dc=georchestra,dc=org
```
There's indeed a small LDAP migration to consider.

**Comment by landryb** [comment]
I'm afraid that's only the tip of the iceberg. To me the real potential for trouble is production directories which have used the console to manage the DIT for the past years:
* their orgs in the ldap are named after the 'long' name (since that's how the code was addressing orgs when persisting objs)
* suddenly with 18.12, the console will try to address the orgs with their short name, which wont match what's present in the DIT.

So unless i missed something ( i hope so !), i'm afraid all production directories will have to rename all existing orgs from `cn/o=longname` to `cn/o=shortname` - and of course move orgs with `businessCategory=PENDING` to `ou=pendingorgs` & users with the `cn=PENDING` role to `ou=pendingusers` ..

**Comment by fvanderbiest** [comment]
> i'm afraid all production directories will have to rename all existing orgs from `cn/o=longname` to `cn/o=shortname`

I tested with a 18.06 DIT (production geograndest) on 18.12 and the console ran smoothly, provided the missing `ou` are added.

> and of course move orgs with businessCategory=PENDING to ou=pendingorgs & users with the cn=PENDING role to ou=pendingusers

I was hoping we could assume these categories are usually (or should be) empty before doing the migration.

**Comment by landryb** [comment]
> > i'm afraid all production directories will have to rename all existing orgs from `cn/o=longname` to `cn/o=shortname`
> 
> I tested with a 18.06 DIT (production geograndest) on 18.12 and the console ran smoothly, provided the missing `ou` are added.

so the objects aren't named `cn/o=longname` in this DIT ?

**Comment by fvanderbiest** [comment]
Nope, eg:
```
dn: o=ca-epinal,ou=orgs,dc=georchestra,dc=org
objectClass: top
objectClass: organization
o: ca-epinal
businessCategory: EPCI

dn: cn=ca-epinal,ou=orgs,dc=georchestra,dc=org
objectClass: top
objectClass: groupOfMembers
cn: ca-epinal
businessCategory: REGISTERED
member: uid=[...]
o:: Q29tbXVuYXV0w6kgZCdBZ2dsb23DqXJhdGlvbiBkJ0VwaW5hbA==
ou: CA-EPINAL
seeAlso: o=ca-epinal,ou=orgs,dc=georchestra,dc=org
```
