### ISSUE TITLE
extractorapp - mention the mapfishapp addon in the README

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2275]
**Describe the bug**

In https://github.com/georchestra/georchestra/blob/18.06/extractorapp/README.md, at least mention the existence of the [mapfishapp addon](https://github.com/georchestra/georchestra/blob/18.06/mapfishapp/src/main/webapp/app/addons/extractor/README.md), and better if we explain how it works for the user (how to extract a layer) and for the administrator (how to enable the feature, how to migrate from the former dedicated web interface).

**geOrchestra version or branch**

18.06

**To Reproduce**

See https://github.com/georchestra/georchestra/blob/18.06/mapfishapp/src/main/webapp/app/addons/extractor/README.md , https://github.com/georchestra/georchestra/blob/18.06/extractorapp/README.md and https://github.com/georchestra/georchestra/blob/18.06/RELEASE_NOTES.md.

**Comment by fvanderbiest** [comment]
Agreed !

**Comment by severo** [comment]
See:
- #2398
-
