### ISSUE TITLE
[console] improve/fix user export as csv/vcf

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2278]
Somewhat of a hidden feature it seems, one can export a list of uids as VCF/CSV with https://github.com/georchestra/georchestra/blob/master/console/src/main/java/org/georchestra/console/ws/backoffice/users/UsersExport.java#L76 . Except i struggled a bit to make it work, as the code declares it's a POST, but fails if you just use POST with json data:
```
curl -v -H "Content-Type: application/json" -X POST -d '{"users":["testadmin"]}' -u testadmin:testadmin https://georchestra.dev.craig.fr/console/private/users.csv

GlobalExceptionHandler [ERROR] org.springframework.web.bind.MissingServletRequestParameterException: Required String parameter 'users' is not present
```

i figured out one needs to pass the users arg urlencoded as a GET queryParam to make it work but still specify it's a POST (while the arg is not taken from the postdata), which is somewhat awkward:
```
curl -XPOST -v -H "Content-Type: application/json" -d '{"users":["testadmin"]}' -u testadmin:testadmin https://georchestra.dev.craig.fr/console/private/users.csv?users

org.json.JSONException: A JSONArray text must start with '[' at character 0
```
the version that works:
```
curl -H "Content-Type: application/json" -XPOST -u testadmin:testadmin https://georchestra.dev.craig.fr/console/private/users.csv?users=%5Btestadmin%5D
```
can the code be fixed so that it properly takes the params from the POST data ? otherwise the query should be declared as GET..

On top of this, two ideas:
  * adding a link from the user page on the console allowing to export the given user as CSV/VCF (i suppose that was one of the original intents of the given code ?)
  * if no param is given, export the complete list...

And, while at it, could be nice to have the same for the orgs.. but that's probably ways more code :)

**Comment by landryb** [comment]
@fvanderbiest @tonio: API-related, should the call be a GET or a POST ? To me it seems more natural to use a GET, unless the intent is to send a huge list of usernames in the queryparams, where in that case POST makes sense..

Or have GET take no params and export the complete list, and POST only taking usernames as param ?

**Comment by Gaetanbrl** [comment]
Is this two link good for you ? 

![image](https://user-images.githubusercontent.com/16317988/61796086-04427d00-ae25-11e9-97ba-f8a830b82e52.png)

**Comment by fvanderbiest** [comment]
Please note that we already have this issue in our Geo2France backlog, and we're ready to have multiselection working, with export to CSV/VCF from selection...

**Comment by Gaetanbrl** [comment]
> we're **ready** to have multiselection working, with export to CSV/VCF

Thank you for the note @fvanderbiest. So, the PR is coming soon ?

**Comment by fvanderbiest** [comment]
Yes, you can already have a look at #2652 for multiple selection
Export is coming next week, well I guess so @tonio

**Comment by landryb** [comment]
having the issue in the backlog is something (there are many issues that are rotting in backlogs here and there), commenting here to say work has started (and in which direction) is another ;) I have no details about what geo2france wants here....

We can still work on the org csv export anyway.

**Comment by Gaetanbrl** [comment]
> Export is coming next week, well I guess so @tonio

I'd already worked in this part before your note...  So, i will create a pull request that you can close or approve.

**Comment by fvanderbiest** [comment]
@RemiDesgrange For 19.06/19.09 (geo2france-related) would you mind crafting us a nicer API for the CSV/VCF export (in close link with @tonio who's working on the client side) ? That would be awesome. Thanks !

**Comment by landryb** [comment]
If you're at it, please add support for exporting orgs/roles ;)

**Comment by landryb** [comment]
@RemiDesgrange is the org export planned in what geo2france wants ? or should i ask @Gaetanbrl to do it, taking the risk of having conflicts with pending work ?

**Comment by fvanderbiest** [comment]
Not planned, indeed.

**Comment by landryb** [comment]
ok @fvanderbiest @RemiDesgrange would be nice to know when/if you plan to work on the API for the CSV/VCF export *for users only* so that we know with @Gaetanbrl when/if we can work on the role/org export on top. To see if it can make 19.09..

**Comment by fvanderbiest** [comment]
I think we're done with it, see #2670, #2675 & #2681

**Comment by landryb** [comment]
Those 3 PR are merged so the work is finished ?

**Comment by landryb** [comment]
sorry, i misread your comment, disregard mine - so that means @Gaetanbrl can work on the org/role export, thanks !

**Comment by landryb** [comment]
Tested working fine on current master, guess we need to open a distinct issue with @Gaetanbrl to have the org/role export now that this issue is closed ? The logic to select a subset of entries was only applied to users, so i guess we'll only export all orgs/roles as csv.

**Comment by Gaetanbrl** [comment]
@landryb i think we could open a new issue for org/role export.
