### ISSUE TITLE
Update the maven plugins

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2284]
**Describe the bug**

For example, in https://github.com/georchestra/georchestra/blob/18.06/analytics/pom.xml#L247, we depend on jetty-maven-plugin in its version [9.2.11.v20150529](https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-maven-plugin/9.2.11.v20150529) of May of 2015. This branch is no more maintained (EOL) by the Jetty project: https://www.eclipse.org/jetty/previousversions.html.

**geOrchestra version or branch**

master

**Expected behavior**

- Identify the unmaintained versions of maven plugins and update them, taking care of potential compatibility issues.
- Ideally, have a routine to periodically do this update job, maybe having some automatic tests that launch alerts when a plugin becomes obsolete.

**Comment by pmauduit** [comment]
We already do have a dependency analyzer, but it probably won't scan the plugins used in maven, only the maven dependencies used in the actual artifact. You can fire the dependency check using the following:

```
$ mvn dependency-check:check
```
This will generate an html report into `target/` as well as printing out stuff on stdout during build. This targets mainly the security issues that each dependencies provides.

There is also another tool of interest which only checks the updates available:

```
$ mvn versions:display-dependency-updates
```

Which will produce on MFapp the following output:

```
[INFO] The following dependencies in Dependencies have newer versions:
[INFO]   commons-dbcp:commons-dbcp ............................... 1.2.2 -> 1.4
[INFO]   commons-fileupload:commons-fileupload ................. 1.3.1 -> 1.3.3
[INFO]   commons-io:commons-io ..................................... 1.4 -> 2.6
[INFO]   javax.servlet:servlet-api ......................... 2.4 -> 3.0-alpha-1
[INFO]   junit:junit ...................................... 4.11 -> 4.13-beta-1
[INFO]   log4j:apache-log4j-extras .............................. 1.1 -> 1.2.17
[INFO]   org.geotools:gt-epsg-hsql ................................ 9.2 -> 20.1
[INFO]   org.geotools:gt-geojson .................................. 9.2 -> 20.1
[INFO]   org.geotools:gt-imageio-ext-gdal ......................... 9.2 -> 20.1
[INFO]   org.geotools:gt-main ..................................... 9.2 -> 20.1
[INFO]   org.geotools:gt-mif ....................................... 9.2 -> 9.5
[INFO]   org.geotools:gt-ogr-core ................................. 9.2 -> 19.1
[INFO]   org.geotools:gt-ogr-jni .................................. 9.2 -> 19.1
[INFO]   org.geotools:gt-shapefile ................................ 9.2 -> 20.1
[INFO]   org.geotools:gt-wfs-ng ................................... 9.2 -> 20.1
[INFO]   org.geotools.xsd:gt-xsd-kml .............................. 9.2 -> 20.1
[INFO]   org.json:json ................................... 20080701 -> 20180813
[INFO]   org.mapfish.print:print-lib .............. 2.1.1-georchestra -> 3.16.2
[INFO]   org.mockito:mockito-all .......................... 1.9.5 -> 2.0.2-beta
[INFO]   org.slf4j:slf4j-simple .......................... 1.7.5 -> 1.8.0-beta2
[INFO]   org.springframework:spring-mock ....................... 2.0.3 -> 2.0.8
[INFO]   org.springframework:spring-webmvc ..... 3.1.0.RELEASE -> 5.1.3.RELEASE
[INFO]   org.tuckey:urlrewritefilter ........................... 3.0.4 -> 4.0.4
[INFO]   postgresql:postgresql ............... 9.1-901.jdbc4 -> 9.4-1210.jdbc42
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

```

**Comment by severo** [comment]
OK, excellent. How do you want to manage these regular updates?

**Comment by severo** [comment]
And would it be possible to launch the same type of tools for the plugins?

**Comment by pmauduit** [comment]
> How do you want to manage these regular updates?

No idea, I think this has to be done manually because if some conventions change in the libraries (package renaming), this has to be fixed by hand in our code, obviously. For example, I tried a naive update and got a lot of issues related to classes refactored in geotools.

> And would it be possible to launch the same type of tools for the plugins?

That is less critical than the dependencies used at runtime I think. No idea either

**Comment by severo** [comment]
OK, maybe treat this with https://github.com/georchestra/georchestra/issues/2256 and https://github.com/georchestra/georchestra/issues/2211

**Comment by fvanderbiest** [comment]
Yes, #2211 is the main issue here.

**Comment by RemiDesgrange** [comment]
@fvanderbiest what do you want me to do ? we are already taking take of updates via dependabot ?

**Comment by fvanderbiest** [comment]
right
