### ISSUE TITLE
Remove version numbers to Spring schemas

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2291]
It seems recommended not to specify the version number of the Spring XSD schemas: https://stackoverflow.com/a/20900801/7351594

Note that Spring 5 removed the version numbers ([What's new in Spring framework 5](https://dzone.com/articles/whats-new-in-spring-framework-5)).

To find all the cases using [ag](https://github.com/ggreer/the_silver_searcher) (that you should also do :+1:):

```bash
ag spring.*[0-9].xsd
```

**Comment by severo** [comment]
See #2426

**Comment by groldan** [comment]
@severo, so if the version numbers were removed in Spring 5, it means we should first upgrade all apps to Spring 5 as of #1329 I guess?

**Comment by severo** [comment]
I understand from https://stackoverflow.com/questions/20894695/spring-configuration-xml-schema-with-or-without-version/20900801#20900801 that it's not a requirement, and that Spring 5 only enforce a best practice.
But my only reference is that SO answer, so I cannot give much more arguments. I let you define if going on with that PR, or discard it.

**Comment by groldan** [comment]
Fixed by #2426
