### ISSUE TITLE
console - remove useless code?

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2294]
I think [this line](https://github.com/georchestra/georchestra/blob/master/console/src/main/resources/META-INF/spring/applicationContext.xml#L10) (and maybe the [applicationContext.xml](https://github.com/georchestra/georchestra/blob/master/console/src/main/resources/META-INF/spring/applicationContext.xml) file) is useless and could be removed, since there are no `META-INF/spring/` directories in all the geOrchestra project, except this one, and therefore no properties files to load from them.

https://github.com/georchestra/georchestra/blob/master/console/src/main/resources/META-INF/spring/applicationContext.xml#L10

Note that this file [comes from the initial commits](https://github.com/georchestra/georchestra/blame/master/console/src/main/resources/META-INF/spring/applicationContext.xml#L10) and has never been updated (apart from a change in the name of the module, that does not affect the functionnalities).

**Comment by fvanderbiest** [comment]
Agreed.
Please proceed on master.

**Comment by severo** [comment]
See #2425
