### ISSUE TITLE
console - typo in the placeholder name

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2296]
**Describe the bug**

In the properties files ([1](https://github.com/georchestra/georchestra/blob/18.06/console/src/main/webapp/WEB-INF/spring/protectedroles.properties#L2), [2](https://github.com/georchestra/datadir/blob/18.06/console/protectedroles.properties#L2)), we set the `protectedRolesList` placeholder, whereas [in the code](https://github.com/georchestra/georchestra/blob/18.06/console/src/main/webapp/WEB-INF/spring/webmvc-config.xml#L125) we look for the `protectedRoleList` placeholder (without `s`).

**geOrchestra version or branch**

18.06

**Comment by severo** [comment]
No more a problem in 18.12 since 62561b2c0b.

**Comment by fvanderbiest** [comment]
Yes, please fix it :-)

**Comment by severo** [comment]
Sure, it was only in case we were waiting for this before releasing <strike>19.03</strike> 18.12
