### ISSUE TITLE
Take into account default.properties in all the webapps

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2299]
See https://github.com/georchestra/georchestra/issues/2123#issuecomment-442622628

> Something is not clear to me: do we want to load the file:${georchestra.datadir}/default.properties file in servlets that aren't currently loading it?
>
> As it's not clear to me, and as it might break current configurations (eg if a property is set in the default.properties file but currently ignored because the file is not loaded, changing the behavior could replace the value of the property and break things), I prefer not to add this file when it is not loaded, and wait for your comments on this point.

 and https://github.com/georchestra/georchestra/pull/2082.

**Comment by severo** [comment]
Note that some modules apply an additional layer of default values, when using the placeholder ([console](https://github.com/georchestra/georchestra/blob/18.06/console/src/main/webapp/WEB-INF/spring/webmvc-config.xml#L125)):

```xml
  <bean class="org.georchestra.console.ws.backoffice.roles.RoleProtected">
    <property name="listOfprotectedRoles">
      <description>Comma separated list of one or more protected Roles</description>
        <!-- Roles are defined as a comma separated list of Roles name and can be override in data dir with "protectedRoleList" key-->
      <value>${protectedRoleList:ADMINISTRATOR,USER,GN_.*,MOD_.*}</value>
    </property>
  </bean>
```

Should we remove this "hardcoded" default values and only take into account the `default.properties` file?

**Comment by severo** [comment]
Also note (well, more a note to myself) that the modules that use the commons module to load their properties files always load the datadir `default.properties` file (see [GeorchestraConfiguration.java](https://github.com/georchestra/georchestra/blob/18.06/commons/src/main/java/org/georchestra/commons/configuration/GeorchestraConfiguration.java#L76))

**Comment by severo** [comment]
See #2419

**Comment by fvanderbiest** [comment]
I think we can close this one @severo ?

**Comment by severo** [comment]
Yes
