### ISSUE TITLE
datadir - cadastrapp config out of sync

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2303]
https://github.com/georchestra/datadir/blob/18.06/cadastrapp/cadastrapp.properties compared to https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/resources/cadastrapp.properties ...

**Comment by MaelREBOUX** [comment]
Better use a release version ?

**Comment by fvanderbiest** [comment]
I will remove cadastrapp config from the datadir, since it is a burden to maintain, and belongs to a different repo.

**Comment by fvanderbiest** [comment]
Done with https://github.com/georchestra/datadir/commit/b9476518a2c538e30e3456e40c8420904de26de9

**Comment by fvanderbiest** [comment]
Cadastrapp users will have to maintain it in their own datadir.
