### ISSUE TITLE
console - dégélation

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2313]
![capture du 2018-12-05 09-11-46](https://user-images.githubusercontent.com/265319/49499452-5f136e00-f86e-11e8-8a06-95ed3772bc5e.png)

C'était le moment WTF de la formation ;-)

**Comment by landryb** [comment]
joli :)

**Comment by fvanderbiest** [comment]
Sûr que c'est un Easter Egg de @tonio !

**Comment by tonio** [comment]
o/
