### ISSUE TITLE
viewer extractor addon - remove email validation

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2331]
I think the current email verification made by ExtJS does not help (see [ExtJS doc](https://docs.sencha.com/extjs/2.3.0/source/VTypes.html#Ext-form-VTypes-method-email)). The regexp is

```regexp
/^(\w+)([-+.][\w]+)*@(\w[-\w]*\.){1,5}([A-Za-z]){2,4}$/
```

That means that a valid gTLD like .amsterdam for example would be marked as incorrect. The regexp is nearly the same in the last version of ExtJS. 

A good reference (as always with @bortzmeyer): https://www.bortzmeyer.org/arreter-d-interdire-des-adresses-legales.html

**Comment by bortzmeyer** [comment]
Indeed:

1. Email addresses cannot be parsed by pure POSIX regexps (they depend on too much context)
2. The size limitation on TLD is quite stupid. Longer TLD exist for many years
3. Either you read the standard (RFC 5322) or, better, you do not try these useless validations.

**Comment by fvanderbiest** [comment]
Thank you guys for your attention to details :-)
