### ISSUE TITLE
[console] document API with swagger

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2340]
I think the REST world settled on swagger, so at some point for proper self-documentation the console should be converted to use it like geonetwork did ... instead of having to write out-of-band documentation.

**Comment by fvanderbiest** [comment]
I'd like to find resources to push this for 20.06

**Comment by landryb** [comment]
i just wrote some python code to interact with geonetwork API, and having it online on `/geonetwork/doc/api/` was *definitely* helpful :)

**Comment by RemiDesgrange** [comment]
I'll try to make something automatic ;-) Spring have a package for that
