### ISSUE TITLE
proxy - remove services monitoring?

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2342]
Currently, the security proxy provides a basic page for monitoring the status of some modules:
- code: https://github.com/georchestra/georchestra/blob/18.06/security-proxy/src/main/java/org/georchestra/security/ServicesMonitoring.java
- demo: https://sdi-stable.georchestra.org/services_monitoring

As monitoring is complex, it could be better to:

- clearly document which are the endpoints to test for each module
- use an external and dedicated monitoring system to test these endpoints
- or, alternatively, provide a basic monitoring module, separated from the security-proxy (see https://github.com/georchestra/georchestra/issues/948)

**Comment by fvanderbiest** [comment]
As discussed earlier, completely agree with this.

**Comment by severo** [comment]
See #2424
