### ISSUE TITLE
viewer - GeoExt i18n files extended to "fr" instead of correct language

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2355]
See https://github.com/georchestra/georchestra/blob/6482f4fdaa2bf874c73ef20529556339fc4a1023/mapfishapp/src/main/webapp/app/js/GEOR_Lang/es.js#L533

It should be `es`, not `fr`.

The same applies for all the files of the https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/webapp/app/js/GEOR_Lang/ directory.

**Comment by fvanderbiest** [comment]
Good catch !
