### ISSUE TITLE
viewer - allow to configure maxUploadSize and MaxInMemorySize

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2358]
<strike>See

https://github.com/georchestra/georchestra/blob/6482f4fdaa2bf874c73ef20529556339fc4a1023/mapfishapp/src/main/webapp/WEB-INF/ws-servlet.xml#L45

It should use

https://github.com/georchestra/datadir/blob/d093d795aa7d824a72acb749750f67fcedc28418/mapfishapp/mapfishapp.properties#L6

instead.</strike>

**Comment by severo** [comment]
See also https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/webapp/WEB-INF/ws-servlet.xml#L37L40. It seems that we could move these values to the datadir, with default values.

**Comment by severo** [comment]
For the first comment, it's only the default value.
For the second comment -> the temporary directory is the default value. The other are hardcoded.

**Comment by severo** [comment]
For https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/webapp/WEB-INF/ws-servlet.xml#L38L40, I don't see the point (see https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/java/org/georchestra/mapfishapp/ws/UpLoadGeoFileController.java#L433-L444) because the important parameter to be able to configure is https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/webapp/WEB-INF/ws-servlet.xml#L27.
The other ones only launch an error, saying the file is too large, but after having it downloaded, which is pointless and misleading.

So, I think:
- we have to remove https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/webapp/WEB-INF/ws-servlet.xml#L38L40 and https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/java/org/georchestra/mapfishapp/ws/UpLoadGeoFileController.java#L433-L444
- we must find a way to configure https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/webapp/WEB-INF/ws-servlet.xml#L27 from the datadir (and https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/webapp/WEB-INF/ws-servlet.xml#L31).

**Comment by fvanderbiest** [comment]
Agreed, we have customers hitting this issue.

**Comment by fvanderbiest** [comment]
I assigned @severo but if @groldan wants to give it a try too ...

**Comment by landryb** [comment]
Also needs to be configured in the webserver/reverse proxies too :)

**Comment by fvanderbiest** [comment]
Indeed, should be mentioned in the documentation !

**Comment by severo** [comment]
> I assigned @severo but if @groldan wants to give it a try too ...

I will be working on it

**Comment by severo** [comment]
I stop working on it, because it's better to decide on #2379 before working on parameterizing two new properties.

**Comment by severo** [comment]
See #2417, https://github.com/georchestra/datadir/pull/115.

**Comment by severo** [comment]
Remains:

- [ ] evaluate if 8MB is the correct default value for the maximum file size

I would prefer if somebody took the issue for that particular point, as the choice of the default values (in both [ws-servlet.xml](https://github.com/georchestra/georchestra/blob/f1752787ead9bbaf7f751f92cbdfc6905254d56d/mapfishapp/src/main/webapp/WEB-INF/ws-servlet.xml) and [mapfishapp.properties](https://github.com/georchestra/datadir/blob/82b0e78a85abdcfa2fe0f27014ac52f53981f476/mapfishapp/mapfishapp.properties)) should be based on the experience from the geOrchestra instances.

**Comment by fvanderbiest** [comment]
@severo can you also add a bit of documentation regarding apache / nginx configurations for upload limits ? Thanks !

**Comment by severo** [comment]
OK

**Comment by severo** [comment]
It proposed https://github.com/georchestra/datadir/pull/124. I think that's the only doc we are "sure" the administrator will read.

**Comment by fvanderbiest** [comment]
Agreed. Thanks !

**Comment by fvanderbiest** [comment]
There's also https://github.com/georchestra/georchestra/blob/18.12/docs/setup/apache.md

**Comment by severo** [comment]
https://github.com/georchestra/datadir/pull/124 is replaced by https://github.com/georchestra/datadir/pull/125

**Comment by severo** [comment]
See #2467

**Comment by fvanderbiest** [comment]
Thanks !
