### ISSUE TITLE
header - move file

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2362]
I think that https://github.com/georchestra/georchestra/blob/master/header/src/main/webapp/js/header.js is not needed anymore.

**Comment by fvanderbiest** [comment]
Yes and no...
Yes because it's not loaded in the common use case.
No because people loading a remote page inside the header iframe might need it so that header links load in the main frame.

It could be moved in a documentation file.

**Comment by severo** [comment]
OK. You're right, maybe it could be located in another directory.

**Comment by fvanderbiest** [comment]
See 2414a102ef0614f6c4f8b9b4f26664362fb07e5f & 36076f8fa1269ad9b249368c4bac9248c150cf10
