### ISSUE TITLE
viewer - give more details in error message

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2365]
When the viewer receives an invalid POST request, if the problem comes from the name of the layer (missing, or not in the list of layers returned by GetCapabilities), we could return an error message slightly larger in order the user to understand they could fix the problem on their side (typically fixing a metadata in GeoNetwork - it's the main use case for the POST requests in mapfishapp).

Maybe we could also manage the case when the name is missing, and load all the layers listed by GetCapabilities, instead of returning an error... I don't know if it would be a better way to manage or not, what do you think?

**Comment by fvanderbiest** [comment]
Currently displaying https://github.com/georchestra/georchestra/blob/4d8fb574c6183875ca0466faac07877b4d12a8dd/mapfishapp/src/main/webapp/app/js/GEOR_Lang/fr.js#L286-L287

If name is missing, yes, we could probably use the same code (factorized) as https://github.com/georchestra/georchestra/blob/4d8fb574c6183875ca0466faac07877b4d12a8dd/mapfishapp/src/main/webapp/app/js/GEOR_mapinit.js#L210-L311 to display a list of layers offered by the service.
