### ISSUE TITLE
mapfishapp - pass the language property instead of hardcoded value?

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2376]
See https://github.com/georchestra/georchestra/blob/1ce4183b822a73f4f2c3d9065f069a53e7b1574d/mapfishapp/src/main/webapp/app/js/GEOR_address.js#L56

**Comment by severo** [comment]
@fvanderbiest: as I don't know the GeoExt library very well, I wonder if there was a special reason for setting `lang` to `fr` instead of passing the `GEOR.config.lang` parameter. Please give me your opinion.

The same occurs in https://github.com/georchestra/georchestra/blob/1ce4183b822a73f4f2c3d9065f069a53e7b1574d/mapfishapp/src/main/webapp/app/js/GEOR_config.js#L474.

**Comment by fvanderbiest** [comment]
GEOR.config.RECENTER_ON_ADDRESSES is false by default & never used (very old stuff !).
As a result this file is useless and should be removed.

**Comment by severo** [comment]
And `GEONAMES_FILTERS` ?

**Comment by fvanderbiest** [comment]
Nope, this one is useful.

**Comment by severo** [comment]
OK, sorry, there is no problem there, the `fr` value is the default one that should be overridden by the properties file, it's no hardcoded.
(maybe we should only be coherent between "fr" and "en" for the default language - I will propose to change it to "en").
