### ISSUE TITLE
maven - official wars are generated with a "-null" suffix

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#2391]
After the config.jar removal, we probably need to adapt the way the official war packages are generated:
https://packages.georchestra.org/wars-master/

**Comment by severo** [comment]
See https://github.com/georchestra/geonetwork/pull/108 and later https://github.com/georchestra/georchestra/pull/2416 that depend on it.

**Comment by landryb** [comment]
As long as you dont break the versioning done for the debian pkgs in #1931, it was painful to get it right :)

**Comment by severo** [comment]
> As long as you dont break the versioning done for the debian pkgs in #1931, it was painful to get it right :)

OK, it seems it was a long story. Let @pmauduit or @fvanderbiest give their opinion.

**Comment by severo** [comment]
> what about adding the `<server>` property to the root pom instead of to each one

I didn't do it because the modules can be built by their own, from inside the directory. But we can change.

> and set the default value to `${project.version}`, so you get `atlas-18.12-SNAPTHOT` or `atlas-18.12` as appropriate for a snapshot or release version.

As said before, let listen to other opinions. To me, it would be OK.
