### ISSUE TITLE
console - too many threads waiting for available db connection

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2395]
See attached [console-jstack.txt](https://github.com/georchestra/georchestra/files/2782715/console-jstack.txt)

@cmangeat was wondering if setting `checkoutTimeout` in c3po datasource could help avoid the trouble. https://www.mchange.com/projects/c3p0/#checkoutTimeout but maybe the issue is somewhere else.

**Comment by cmangeat** [comment]
checkoutTimeout is in my opinion important because on a general way one should never block on an infinite timeout.

**Comment by groldan** [comment]
Covered by issue #2414, PR #2436.

**Comment by groldan** [comment]
Closing, fixed by #2436
