### ISSUE TITLE
Extractorapp - remove hardcoded headerUrl and headerHeight

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2423]
The header URL and height are hardcoded in:

https://github.com/georchestra/georchestra/blob/f0fd2e8d05c79fefb7d6a1b34c8b00f90911e13f/extractorapp/src/main/webapp/admin/index.html#L16

They should obtain the properties from the datadir (from [default.properties](https://github.com/georchestra/datadir/blob/master/default.properties), that could be overridden by [console/console.properties](https://github.com/georchestra/datadir/blob/master/console/console.properties)).

See #2173.

**Comment by fvanderbiest** [comment]
Extractorapp has no frontend anymore
