### ISSUE TITLE
Missing configuration option for the mapfish print config directory?

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2428]
Shouldn't this parameter come from a datadir option?
https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/webapp/WEB-INF/web.xml#L47

**Comment by landryb** [comment]
I think it should, but i'm not even sure this is used (or its correctly overriden somewhere), as iirc modifying parameters in the print.yml provided by the datadir correctly impacts runtime..

either way, it should be modified/documented for clarity :)
