### ISSUE TITLE
[console] doesnt allow dot in login

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2448]
master with #2408 on top, the login field on `console/manager/#!/users/<uid>/infos` has the save button greyed out/disabled if the login field contains a dot or a dash, preventing an admin to rename a user using those chars - prenom.nom is often used, and prenom-compose.nom too so those chars should be allowed.

It seems underscore & numbers are allowed - didnt find in the code where the regex was to specify what was allowed, but istr there's been a ticket about that to harmonize the various checks done on login in the console.

**Comment by landryb** [comment]
I'm not sure there should be a + after `[a-z]` either, we only want the login to *start* by a character.
```
>"prenom-compose.nom1".match(/^[a-z][\-\.\w]*$/)
Array [ "prenom-compose.nom1" ]
```

**Comment by landryb** [comment]
Ah, serverside validation is in https://github.com/georchestra/georchestra/blob/master/console/src/main/java/org/georchestra/console/ws/newaccount/NewAccountFormController.java#L322 - and does indeed accept dot and dash:
```
Pattern regexp = Pattern.compile("[a-zA-Z][a-zA-Z0-9.-]*");
```
some harmonization is definitely due..

**Comment by landryb** [comment]
I think the specification is 'letters, numbers, underscore, dash, dot' + 'starts with a letter' .. right @fvanderbiest ?

**Comment by landryb** [comment]
And now i wonder if the regex in https://github.com/georchestra/georchestra/blob/18.06/console/src/main/webapp/WEB-INF/views/createAccountForm.jsp#L182 should be synchronized/fixed too. Right now it \W removed dashes, dots & underscores, which is not what we want i think..

**Comment by landryb** [comment]
Ie testing `str = str.replace(/[^a-z0-9_.-]*/gi, '');` here, i'm a bit lost at what needs escaping when the js is inside jsp....

**Comment by landryb** [comment]
Tested working fine, adding non-alnum chars to nom field correctly sanitizes the uid in the account creation form. Ie `nom-foo&_bar` does `nom-foo_bar`

**Comment by fvanderbiest** [comment]
Many thanks Landry !
