### ISSUE TITLE
[console] tab titles should be routable urls without the middleware

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2449]
Added in 42b26032, fixed in 89c6a48 & d0c6c769, right now the 'users' tab isnt a routable url (the regexp doesnt match `browse/users` which should redirect to `browse/all/users`)and relying on the middleware/webserver to handle this is awkward - the webapp (or the sec-proxy?) should handle those rewrites/redirections so that things work ootb, without apache or nginx horrors...

right now (with the provided apache config), middle-clicking on the org console tab to open it in a new browser tab redirects to `/console/manager/#!/home#%2Forgs%2Fall` which just shows the console homepage, and not the org list. Same for the other tabs....

**Comment by fvanderbiest** [comment]
Agreed.

**Comment by fvanderbiest** [comment]
What do we miss here @tonio ?

**Comment by severo** [comment]
I couldn't find how to configure the `angular-new-router` (see #2470).

Two options, I think:

- fix the URLs in a frontend proxy, as currently done
- update the router package to [ui-router](https://ui-router.github.io/ng1/) (to be checked: will it allow to solve our current issue?)
- update the app from [AngularJS](https://angularjs.org) to [Angular](https://angular.io) or another framework (React, Vue.js...)

**Comment by severo** [comment]
Please comment on that issue before I keep working on it.

**Comment by fvanderbiest** [comment]
JS app generates links like /console/manager/org/c2c/infos which are not server-side routable (hence cannot be opened in a new browser window)
```
$ curl -I http://localhost:8080/console/manager/org/c2c/infos
HTTP/1.1 404 Not Found
```

/console/manager/#!/org/c2c/infos is routable
```
$ curl -I 'http://localhost:8080/console/manager/#!/org/c2c/infos'
HTTP/1.1 200 OK
```

Modifying the frontend proxy to handle these rewrite is not the good way to go, as Landry mentions.
I think we need a custom `urlrewritefilter` config for the console, as for mapfishapp.

**Comment by severo** [comment]
I understand that. What I propose is to replace

> JS app generates links like `/console/manager/org/c2c/infos` which are not server-side routable

by

> JS app generates links like `/console/manager/@!/org/c2c/infos` which are server-side routable

**Comment by fvanderbiest** [comment]
okay !

**Comment by fvanderbiest** [comment]
> if you think I should only fix the Apache configuration

I don't like this solution, but the doc is now fixed with c6926128129fd6a7252ed0ff8c134cb947e1403f
See my comment https://github.com/georchestra/georchestra/pull/2864#issuecomment-570616505 for the correct way to implement it.

**Comment by pmauduit** [comment]
This would require to (re)introduce org.tuckey's rewrite filter lib, as it does not seem that Spring allows such features as inhouse url rewriting.

**Comment by fvanderbiest** [comment]
... which now allows users to get redirected to the correct URL after they authenticate, via https://github.com/georchestra/datadir/commit/74a9b43bdbba885cb6c43dbaff9c30d0ae68696e

**Comment by fvanderbiest** [comment]
#2873 fixes the latest bits
