### ISSUE TITLE
[console] display role description when hovering on the role labels

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2450]
Nice to have and probably easy to do - on the user page, in the role tab, the 'raw' list of georchestra & other roles are displayed - it would be great to display the role description LDAP field when hovering over the role name so that a user admin knows that role 'FOO' means 'gives access to FOO, BAR and BAZ depending on BLAH' - otherwise you get to create a super long role name which needs to carry all this knowledge..

Would also be nice on the role/favorites list displayed in the left pane on the user list.

**Comment by fvanderbiest** [comment]
Agreed, interesting evolution.

**Comment by Gaetanbrl** [comment]
Currently, some descriptions are translate in [lang files](https://github.com/georchestra/georchestra/blob/19.04/console/src/main/webapp/manager/app/assets/lang/fr.json#L10).

- What about the others description read in english from the response as JSON ? 

- And what do you thing about this simple tooltip design ? 
![image](https://user-images.githubusercontent.com/16317988/61472120-1be0b800-a984-11e9-8992-24b8bebd4ecc.png)

**Comment by landryb** [comment]
ok for the tooltip design - and for the tooltip source, it should just be the description field in the json response. The value should come from ldap in all cases, no ? I find it strange that the description field cannot be modified for the georchestra roles (GN*, etc) - @fvanderbiest was it on purpose (i see it was done in 6370fda846) ? I can understand not being able to change the role name, but the description..

The ones coming from the translation files are only used when hovering the 'administrator/delegated administrator' badge on the upper right part of the console. It's not related to a role name.

**Comment by Gaetanbrl** [comment]
> The value should come from ldap in all cases, no ?
I tend to say yes, from the JSON file.

**Comment by Gaetanbrl** [comment]
@landryb could we validate this modification to realize PR and open new issue about translation / LDAP field ?

**Comment by landryb** [comment]
there's no issue with translations afaict, the value to display comes from LDAP, that's all.

A separate issue would be making the description modifiable for the privileged roles.

**Comment by landryb** [comment]
closed by #2703
