### ISSUE TITLE
[console] orgShortName should be mandatory ?

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2451]
Cf https://github.com/georchestra/datadir/blob/master/console/console.properties#L35 & https://github.com/georchestra/georchestra/blob/master/console/src/main/webapp/WEB-INF/spring/console.properties#L25 - i think since short name is used to name the ldap objects, it should be marked as mandatory, which is already the case in the webapp on the account creation page - so i'm not sure if requiredFields is in use... but the property defaults needs fixing ?

**Comment by fvanderbiest** [comment]
> i think since short name is used to name the ldap objects, it should be marked as mandatory

Yes.

**Comment by severo** [comment]
It's already done since https://github.com/georchestra/georchestra/commit/fe665f13da82ed229c1b29e3c463fc52bca29368.

Note that for organizations, it's hardcoded, and the console.properties file has no effect.

**Comment by landryb** [comment]
Hmm well then whats the supposed use of `requiredFields` in console.properties ? should it be removed for clarity ?

**Comment by severo** [comment]
No, I understand it's used for the required fields of the User form. It's not consistent, but it's the current state.

**Comment by fvanderbiest** [comment]
https://github.com/georchestra/datadir/commit/c04958f751420ce52a79ec7564b2d0f89738f08f

**Comment by landryb** [comment]
Ah right, used in the angular js admin user form, not the jsp 'account creation form' - makes sens now :)
