### ISSUE TITLE
[console] display user org as a link

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2452]
On the `/console/manager/#!/browse/all/users` page it'd be great to have the user org displayed as a direct link to this org page (right now it's 'just text'), instead of having to : 
- click on the org tab
- filter the org list for the corresponding org
- click on the org link

the direct link would be much faster :)

**Comment by fvanderbiest** [comment]
Agreed.
And it's probably immediate.

**Comment by severo** [comment]
Not immediate, because /console/private/users/ only gives the name of the org, it doesn't give any ID:

```json
[
  {
    "uid":"testuser",
    "givenName":"Test",
    "sn":"USER",
    "org":"Project Steering Committee",
    "mail":"psc+testuser@georchestra.org",
    "pending":false
  },{
    "uid":"testreviewer",
    "givenName":"Test",
    "sn":"REVIEWER",
    "org":"Conseil régional d'Alsace",
    "mail":"psc+testreviewer@georchestra.org",
    "pending":false
  }...
```

**Comment by landryb** [comment]
outch. good catch :) Well guess serverside needs to also return shortname...

**Comment by severo** [comment]
Yes, I will add it to the REST service

**Comment by severo** [comment]
See #2459.
