### ISSUE TITLE
Drop epsg_extension in favor of vanilla geoserver user projections support?

### ISSUE THREAD

**Issue by groldan** [georchestra/georchestra#2453]
It seems that the `epsg-extension` module was added back in [May 2011](https://github.com/georchestra/georchestra/blame/18.06/epsg-extension/src/main/java/org/geotools/referencing/factory/epsg/CustomCodes.java) right before GeoServer added support for custom CRS definitions in `<data dir>/user_projections/epsg.properties` in [June](https://github.com/geoserver/geoserver/blame/44bacafcf1352bfe0b1836262df686fd58036585/src/main/src/main/java/org/vfny/geoserver/crs/GeoserverCustomWKTFactory.java) of the same year.

Neither have changed over the years, so I wonder if we shouldn't just get rid of the custom `epsg_extension` module in favor of vanilla geoserver support for the same functionality.

Only thing to consider would be upgrading the config of anyone using the `-DCUSTOM_EPSG_FILE` system property by `-Duser.projections.file` or just saving the custom projections in `<data dir>/user_projections/epsg.properties`.

@fvanderbiest @pmauduit comments?

**Comment by fvanderbiest** [comment]
Agreed, this should be removed from the project as no one uses custom proj definitions (to my knowledge).
The only interest would be for someone to do extractions using custom projections, but again, no one uses it.

**Comment by groldan** [comment]
I've created a commit  (a41473e5c818d31f79255cf4b0bfdf1ea3866e87) that removes the `epsg-extension` module, but then I'm not so sure we got to remove it anymore as it at least fixes the `EPSG:27572` issue by default for non geoserver apps. In geoserver it's fixed by a custom `epsg.properties` in the default (geOrchestra) data directory.

**Comment by fvanderbiest** [comment]
`EPSG:27572` was deprecated years ago in France, so this makes sense to drop `epsg-extension` IMO.
Feel free to PR, thanks :-)

**Comment by pmauduit** [comment]
:+1: also about it

**Comment by groldan** [comment]
nice then, lets do it

**Comment by groldan** [comment]
Fixed by #2600
