### ISSUE TITLE
Don't show pending users/orgs on the all users/orgs page

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2456]
(taken from https://github.com/georchestra/georchestra/issues/2108#issuecomment-459320181)

on the 'all users' page (console/manager/#!/browse/all/users), pending users are listed and nothing differenciates them from regular users - i might be mistaken, but in the past (not 100% sure) pending users on this page were listed in italic ? Do we want to list pending users on the 'all users' page ? I think it's fine only having them on /console/manager/#!/browse/pending/users..

Same thing for orgs, pending orgs are listed on the all/orgs page and nothing makes them 'stand out' - all long name labels are in italic there.. maybe it'd be better to not show the pending orgs there ?

**Comment by fvanderbiest** [comment]
> pending users on this page were listed in italic ?

Nope, they were listed in here as the others, with nothing to differentiate them.
This would be an enhancement.

**Comment by landryb** [comment]
Looking a bit at the code, the json array returned by `users` has a boolean `pending` attribute for each user, so maybe it's only a matter of excluding/filtering out users where `pending==true` in https://github.com/georchestra/georchestra/blob/19.04/console/src/main/webapp/manager/app/components/users/users.tpl.html#L35 ? i don't know the angular syntax for that... or maybe it's just adding `!users.pending` to the test in https://github.com/georchestra/georchestra/blob/19.04/console/src/main/webapp/manager/app/components/users/users.es6#L50

**Comment by landryb** [comment]
Tried the following:
```
--- a/console/src/main/webapp/manager/app/components/users/users.es6
+++ b/console/src/main/webapp/manager/app/components/users/users.es6
@@ -47,7 +47,7 @@ class UsersController {
         return
       }
       this.users = this.allUsers.filter(
-        user => (role.users.indexOf(user.uid) >= 0)
+        user => (!user.pending && role.users.indexOf(user.uid) >= 0)
       )
     })
   }
```
rebuilt/reinstalled console webapp, but for some reason it doesnt seem to have any effect, pending users still shown on 'all users' tab

**Comment by landryb** [comment]
Also tried:
```
--- a/console/src/main/webapp/manager/app/components/users/users.es6
+++ b/console/src/main/webapp/manager/app/components/users/users.es6
@@ -18,7 +18,7 @@ class UsersController {
     this.newRoleName = ''
 
     this.users = User.query(() => {
-      this.allUsers = this.users.slice()
+      this.allUsers = this.users.slice().filter(user => !user.pending)
     })
 
     let active = $routeParams.id
```
which doesnt filter out pending users from the all users tab, except that now no users are shown on the pending users tab. Clearly, i have no idea what i'm doing with this angular spaghetti voodoo :) @tonio you have a nice job security here !

**Comment by tonio** [comment]
Filtering users in the [template](https://github.com/georchestra/georchestra/blob/19.04/console/src/main/webapp/manager/app/components/users/users.tpl.html#L35) sounds good. #spaghettimasta

**Comment by Gaetanbrl** [comment]
To continue our exploration i'd tried : 
`<tr dir-paginate="user in users.users | filter:users.q | itemsPerPage: users.itemsPerPage" ng-if="!user.pending">`

And pending user was completely dissapeared from pending list and from all users list... maybe i'm close !

**Comment by tonio** [comment]
you can pipe with another filter, you can have some inspiration from https://github.com/georchestra/georchestra/pull/2652/commits/927efa81a97f42d61857dbdc6f93fb9432585e61#diff-756f657a4b74e4aaf539b675d2ba4c20R51

**Comment by Gaetanbrl** [comment]
I had realize something like that, thanks.
