### ISSUE TITLE
mapfishapp: use WMC title to update a title div in header

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#246]
In my instance of mapfishapp (see http://ids.craig.fr/carto/), i have a header containing a ```<div id='maintitle'>```, which i update from the WMC title object if present.
I'd like to properly integrate this in github, so how should it be done ? a new configuration option (GEOR.config.TITLE_DIV) containing the id of the div to update with newContext.title (and do nothing with newContext.title if GEOR.config.TITLE_DIV is empty) ?
See https://github.com/landryb/georchestra/commit/0c326293ea41386ca1e5f6b7cd2258e7c7bda49b for what i'm using now.

**Comment by fvanderbiest** [comment]
closing because from 14.12 on, the context title + abstract is displayed after being restored
