### ISSUE TITLE
console - field naming mismatch

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2468]
The public form for user registration has a "Fonction" field, which maps to the `title` inetOrgPerson field
 ![capture du 2019-02-07 11-41-25](https://user-images.githubusercontent.com/265319/52406429-f9da3400-2acd-11e9-87ca-49744172315b.png)

This seems appropriate, as per https://tools.ietf.org/html/rfc2798
```
4.  Example of an inetOrgPerson Entry

   The following example is expressed using the LDIF notation defined in
   [LDIF].

   version: 1
   dn: cn=Barbara Jensen,ou=Product Development,dc=siroe,dc=com
   objectClass: top
   objectClass: person
   objectClass: organizationalPerson
   objectClass: inetOrgPerson
   cn: Barbara Jensen
   cn: Babs Jensen
   displayName: Babs Jensen
   sn: Jensen
   givenName: Barbara
   initials: BJJ
   title: manager, product development
   uid: bjensen
   mail: bjensen@siroe.com
   telephoneNumber: +1 408 555 1862
   facsimileTelephoneNumber: +1 408 555 1992
   mobile: +1 408 555 1941
   roomNumber: 0209
   carLicense: 6ABC246
   o: Siroe
   ou: Product Development
   departmentNumber: 2604
   employeeNumber: 42
   employeeType: full time
   preferredLanguage: fr, en-gb;q=0.8, en;q=0.7
   labeledURI: http://www.siroe.com/users/bjensen My Home Page
```

The user edit form `/console/manager/#!/users/fvanderbiest/infos` shows a different label for the `title` field. It is translated to "Titre". This is misleading:
![capture du 2019-02-07 11-42-54](https://user-images.githubusercontent.com/265319/52406633-7836d600-2ace-11e9-8219-7e56ba195863.png)

We should homogeneize all translations.

Geo2France would have liked this field to store the "civility" information, but I fear this won't be possible.
ping @bchartier

**Comment by severo** [comment]
To be homogenized:

- [JSP i18n strings](https://github.com/georchestra/georchestra/tree/18.12/console/src/main/webapp/WEB-INF/i18n/)
- [AngularJS appi 18n strings](https://github.com/georchestra/georchestra/tree/18.12/console/src/main/webapp/manager/app/assets/lang)

**Comment by severo** [comment]
See #2475

**Comment by fvanderbiest** [comment]
Thanks !
