### ISSUE TITLE
[console] add user filter on roles/org member tab

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2469]
On top of #2080, a nice addition would be to have the same filter field as seen on the users page on the member list for roles & orgs - when roles have 800+ users and you need to figure out if a member is in the role (or want to remove it) its another way to quickly manage role membership, instead of going to the users tab, look for the given user, and navigate to its role tab.

**Comment by fvanderbiest** [comment]
Nice enhancement indeed.

**Comment by Gaetanbrl** [comment]
About the view, @landryb  Is it correct ?
![image](https://user-images.githubusercontent.com/16317988/61637084-2f976180-ac97-11e9-850f-4cbe934ca6ee.png)

**Comment by landryb** [comment]
Yup, as long as it's obvious the second field is a filter (ie displays 'filtrer' when empty) - @fvanderbiest ok with you too ?

**Comment by Gaetanbrl** [comment]
> as long as it's obvious the second field is a filter

Indeed it's the same filter, so we can read "filtrer" if empty.

![image](https://user-images.githubusercontent.com/16317988/61638210-3c1cb980-ac99-11e9-933b-ff643caf5dcc.png)

**Comment by landryb** [comment]
Maybe align the filter above the 'User' label so that it's obvious its to filter users ? dunno. oh well, details..

**Comment by Gaetanbrl** [comment]
Like that ? 
![image](https://user-images.githubusercontent.com/16317988/61639518-f57c8e80-ac9b-11e9-8b24-e0ec6a880796.png)

**Comment by landryb** [comment]
No, above 'Utilisateur', left of 'Ajouter' :)

**Comment by Gaetanbrl** [comment]
Yeah sorry, it's better now ? 
![image](https://user-images.githubusercontent.com/16317988/61644033-44c6bd00-aca4-11e9-94cf-29fc7de7a4c4.png)

**Comment by landryb** [comment]
perfect, exactly what i meant ;)

**Comment by fvanderbiest** [comment]
Since the "Filter" widget is in the top right corner of page `/console/manager/#!/browse/all/users`, I would go for the same disposition here, moving the "User add" widget to the top left corner.

**Comment by landryb** [comment]
+1 for consistency, as long as we merge it :)

**Comment by Gaetanbrl** [comment]
> for the same disposition here, moving the "User add" widget to the top left corner

@fvanderbiest  you thought at this disposition ?

![image](https://user-images.githubusercontent.com/16317988/64435800-6c8eaa80-d0c3-11e9-9056-f148e3f13fd7.png)

**Comment by Gaetanbrl** [comment]
> "User add" widget to the top left corner

Or something like : 
![image](https://user-images.githubusercontent.com/16317988/64437409-8aa9da00-d0c6-11e9-8ebd-c7908d8fdc32.png)

**Comment by fvanderbiest** [comment]
First one is indeed :+1:

**Comment by landryb** [comment]
LGTM for the first option too :)

**Comment by landryb** [comment]
closed by #2657
