### ISSUE TITLE
Mapfishapp - Python 2.7 EOL

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#2474]
Mesage when building Mapfishapp (which makes use of jstools):

```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
```

So we would need a "B plan" to minify JS resources.

**Comment by severo** [comment]
See also #368

**Comment by fvanderbiest** [comment]
Not sure this issue will find it's way to any future release, given the fact that mapfishapp is EOL too
