### ISSUE TITLE
All pom.xml - remove <server> and use parent's one

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2483]
As pom.xml files use their `<parent>` values, there should be no need to specify the `<server>` value in every module pom.xml (see https://github.com/georchestra/georchestra/blob/master/analytics/pom.xml#L19 for example).

As mentioned in https://github.com/georchestra/georchestra/issues/2391#issuecomment-457978247 by  @groldan.

**Comment by pmauduit** [comment]
We shall also consider "factorizing" the `packageDatadirScmVersion` variable.

**Comment by fvanderbiest** [comment]
see #2853
