### ISSUE TITLE
Change security-proxy project name (ROOT)?

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2484]
Currently the artefacts created in the security-proxy project are name ROOT-something. Why not security-proxy, or proxy? It seems confusing to me.

**Comment by fvanderbiest** [comment]
Because, when deployed, they should be named as such to intercept all requests
ping @pmauduit

**Comment by landryb** [comment]
seconded - ROOT.war has a special status and gets all requests - if you want to rename the webapp and still send it all requests i think some context.xml fiddling is needed.

**Comment by landryb** [comment]
I dug the tomcat doc and https://tomcat.apache.org/tomcat-8.0-doc/config/context.html#Naming explains it - by default if the webapp is named ROOT.war then it gets an empty contextpath ie matches `/` - to my understanding it'd be possible to deploy security-proxy.war and make it match `/` by fiddling with `META-INF/context.xml` but i'm not tomcat/webapp expert, and i dont think spending time on this is worth the effort...
