### ISSUE TITLE
Find another way to pass the default language property to the JSP files in mapfishapp

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2494]
The `defaultLanguage` attribute is set at:

https://github.com/georchestra/georchestra/blob/c8fcd26e4b932267effac04897aca86b44d4ad3e/mapfishapp/src/main/webapp/WEB-INF/ws-servlet.xml#L70

And accessed in index.jsp using `request.getParameter`:

https://github.com/georchestra/georchestra/blob/c8fcd26e4b932267effac04897aca86b44d4ad3e/mapfishapp/src/main/webapp/WEB-INF/jsp/index.jsp#L50

It would be better to avoid using that method that also allows to access the GET parameters.

**Comment by severo** [comment]
See also #2495.

**Comment by fvanderbiest** [comment]
> It would be better to avoid using that method that also allows to access the GET parameters.

Yes, that's what I meant with https://github.com/georchestra/georchestra/pull/2430#discussion_r254182956

**Comment by severo** [comment]
Exactly, it's the way I found to make it work, but it does not feel like the correct manner to do it.

**Comment by pmauduit** [comment]
You have request.getAttribute(String) (specific to Java / Servlet) and getParameters (pure HTTP): https://docs.oracle.com/javaee/6/api/javax/servlet/ServletRequest.html#getAttribute(java.lang.String)

**Comment by severo** [comment]
See #2528.
