### ISSUE TITLE
Error in analytics (class not found)

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2499]
To reproduce:

```
git checkout 18.12
cd analytics
mvn jetty:run
```

We get the following error:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'waitForDb' defined in ServletContext resource [/WEB-INF/ws-servlet.xml]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/apache/commons/pool/KeyedObjectPoolFactory
```

**Comment by severo** [comment]
Related to https://github.com/georchestra/georchestra/commit/ae8dc682657ded02e8c8f985d921b1cfb95f4575.

**Comment by groldan** [comment]
Hey @severo can you check if you're not running with an outdated version of georchestra/commons? can't reproduce in 18.12 at 2edfa047fa525925b806d7ccd83e1ceed680e2ca, and indeed `commons`'s `WaitForDb` does not use any connection pool anymore. 

So I'm guessing you've built analytics without building commons previously, and the outdated commons jar might be trying to use dbcp which is no longer in analytics classpath?

**Comment by severo** [comment]
Exactly, my bad...
