### ISSUE TITLE
Replace Spring init-method configuration parameter by @PostConstruct annotation

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2504]
It seems to be recommended to use the [@PostConstruct](http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#beans-postconstruct-and-predestroy-annotations) annotation in the classes, instead of the Spring XML configuration `init-method` parameter.

See reasons here: https://stackoverflow.com/a/1089691/7351594.

**Comment by pmauduit** [comment]
the @PostConstruct only works when annotation processing is activated, this is not the case on the security-proxy, see https://github.com/georchestra/georchestra/pull/3119#issuecomment-692770971
