### ISSUE TITLE
analytics - why not using a simpler comma separated list for the excluded users?

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2507]
See 
https://github.com/georchestra/georchestra/blob/2387e6f374a0adf56f6d896a5e8a23e31ec14308/analytics/src/main/java/org/georchestra/analytics/StatisticsController.java#L697-L706

and

https://github.com/georchestra/datadir/blob/e6e08d2247174cb8a1a4158a8a84c258eaf4a839/analytics/analytics.properties#L12-L15

Note that it blocks passing the list as a parameter through Spring placeholders (see #2496).

**Comment by fvanderbiest** [comment]
If you can replace the current config with a comma separated list, I'm fine with it

**Comment by severo** [comment]
Note that it seems the comma separated list is mapped directly to an Array: https://www.baeldung.com/spring-value-defaults

**Comment by severo** [comment]
See also

https://github.com/georchestra/datadir/blob/2ce6e4d6eb0cd3fb2b45baf29cec0e1a6efd8f0f/security-proxy/removed-xforwarded-headers.properties#L1-L3

and where it is accessed:

https://github.com/georchestra/georchestra/blob/2387e6f374a0adf56f6d896a5e8a23e31ec14308/security-proxy/src/main/java/org/georchestra/security/RemoveXForwardedHeaders.java#L64-L76

**Comment by severo** [comment]
I suspect there are more occurrences of this pattern, that could be replaced with comma separated list. It would require scanning all the code.

**Comment by severo** [comment]
See #2526, and https://github.com/georchestra/datadir/pull/136.

If merged (please also test by your own before to be sure this does not break), we could look for other occurrences of that pattern and remove them all.

**Comment by severo** [comment]
See also:

- [ ] https://github.com/georchestra/datadir/blob/18.12/security-proxy/removed-xforwarded-headers.properties
- [ ] https://github.com/georchestra/datadir/blob/18.12/security-proxy/trusted-users.properties
- [ ] https://github.com/georchestra/datadir/blob/18.12/security-proxy/user-agents.properties
