### ISSUE TITLE
Remove older branches

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2520]
Push tags instead to keep a reference

**Comment by fvanderbiest** [comment]
Process is like
```
$ git checkout -b 12.11 origin/12.11
$ git tag -a v12.11-final -m "EOL version 12.11"
$ git push origin v12.11-final
$ git push origin :12.11
```

**Comment by fvanderbiest** [comment]
Done

**Comment by severo** [comment]
Excellent!

(maybe we should also try to clean the development branches, moving / creating them below our personal forks, and PR to georchestra's repository)
