### ISSUE TITLE
properly set version in 18.12 branch ?

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2521]
preemptively started working on stable buildbot for 18.12 release, and building from the 18.12 branch produces pkgs versionned `99_master`, as version is still `18.12-SNAPSHOT` in all the pom.xml files( https://github.com/georchestra/georchestra/blob/18.12/pom.xml#L18 ) - i know 18.12 is not released yet, but shouldnt this be 18.12 like was done in eb44e02977f for 18.06 ?

**Comment by fvanderbiest** [comment]
> i know 18.12 is not released yet, but shouldnt this be 18.12 like was done in [eb44e02](https://github.com/georchestra/georchestra/commit/eb44e02977f0bf74c4f46c0ffd31e8227c830010) for 18.06 ?

True.

**Comment by fvanderbiest** [comment]
See 60310c179c4ffef2ed2bb8c4594ac1afc263c36a

**Comment by landryb** [comment]
Thanks, the buildbot should pickup this commit and produce properly versioned debian packages from the 18.12 branch :)

**Comment by landryb** [comment]
That did work, https://packages.georchestra.org has them:
```
18.12|main|amd64: georchestra-analytics 18.12.201903191328~60310c1
18.12|main|amd64: georchestra-atlas 18.12.201903191328~60310c1
18.12|main|amd64: georchestra-cas 18.12.201903191328~60310c1
18.12|main|amd64: georchestra-console 18.12.201903191328~60310c1
18.12|main|amd64: georchestra-extractorapp 18.12.201903191328~60310c1
18.12|main|amd64: georchestra-geonetwork3 3.4.1-0.201903191328~2bd34de
18.12|main|amd64: georchestra-geoserver 18.12.201903191328~60310c1
18.12|main|amd64: georchestra-geowebcache 18.12.201903191328~60310c1
18.12|main|amd64: georchestra-header 18.12.201903191328~60310c1
18.12|main|amd64: georchestra-mapfishapp 18.12.201903191328~60310c1
18.12|main|amd64: georchestra-security-proxy 18.12.201903191328~60310c1
```
