### ISSUE TITLE
8df191a broke account creation form

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2522]
```
** Root cause is: Impossible de compiler la classe pour la JSP: 

Une erreur s'est produite à la ligne: 149 dans le fichier jsp: /WEB-INF/views/createAccountForm.jsp
readonlyUid cannot be resolved to a variable
```

unsurprising, since 8df191a only took care of `headerHeight`/`headerUrl`

**Comment by severo** [comment]
Oups

**Comment by landryb** [comment]
it's a boolean var, so dunno if a spring placeholder can be used directly in `webmvc-config.xml` or if it needs more code.

**Comment by landryb** [comment]
yeah it works - simple fix, added `readonlyUid`:
```
<entry key="readonlyUid" value="${readonlyUid:false}" />
```
and fixed the jsp:
```
<t:input path="uid" required="${uidRequired}" readonly="${readonlyUid}" appendIcon="user"> 
```

**Comment by landryb** [comment]
tested with `readonlyUid=true` in the `console.properties` files, properly applies readonly to the field on the form.

**Comment by severo** [comment]
feel free to PR

**Comment by severo** [comment]
See #2523
