### ISSUE TITLE
console - allow localhost in recaptcha

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2541]
When running the console locally, with `mvn jetty:run`, and accessing the new account form via http://localhost:8286/console/account/new, the ReCaptcha shows an error, since `localhost` isn't between the allowed domains for the [default pair of keys](https://github.com/georchestra/datadir/blob/18.06/console/console.properties#L54-L55).

The solution is just to add `localhost` from the account that created this pair of keys (in https://www.google.com/recaptcha/admin/site/xxxxxxxx), but it must be done by whom is managing the account.

Alternately, everybody can create their own pair of keys and allow localhost, but it requires more efforts, and implies modifying git-versioned files, that could lead to unwanted changes in commits. On the other hand, adding "localhost" to the allowed domains is clearly for development purposes, and might lead to security issues (I don't know which ones, but...)

**Comment by fvanderbiest** [comment]
> The solution is just to add `localhost` from the account that created this pair of keys (in https://www.google.com/recaptcha/admin/site/xxxxxxxx), but it must be done by whom is managing the account.

Done !
