### ISSUE TITLE
ldap - memberof.ldif seems to be defined two times

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2544]
See:

1. https://github.com/georchestra/georchestra/blob/master/ldap/memberof.ldif
2. https://github.com/georchestra/georchestra/blob/master/ldap/docker/modules/memberof.ldif.

Only the first one seems to be useful:

- the second one is copied to `/etc/ldap.dist/modules`: https://github.com/georchestra/georchestra/blob/master/ldap/Dockerfile#L19
- the first one is copied to `/tmp`: https://github.com/georchestra/georchestra/blob/master/ldap/docker/docker-entrypoint.d/01-populate#L34-L35
- `/etc/ldap.dist` is copied to `/etc/ldap`: https://github.com/georchestra/georchestra/blob/master/ldap/docker/docker-entrypoint.d/00-init#L33
- if defined in `SLAPD_ADDITIONAL_MODULES` env var (it's not in the docker-compose.yml: https://github.com/georchestra/georchestra/blob/master/ldap/docker-compose.yml#L15), the second one is imported in slapd: https://github.com/georchestra/georchestra/blob/master/ldap/docker/docker-entrypoint.d/00-init#L93
- finally the first one is imported in slapd: https://github.com/georchestra/georchestra/blob/master/ldap/docker/docker-entrypoint.d/01-populate#L34-L35

I think we should remove the second one. To be confirmed.

**Comment by severo** [comment]
Also:

why changing the backend with `sed` at https://github.com/georchestra/georchestra/blob/master/ldap/docker/docker-entrypoint.d/01-populate#L34. It would be better to change it in the versioned file https://github.com/georchestra/georchestra/blob/master/ldap/memberof.ldif

**Comment by fvanderbiest** [comment]
Closed by #2715
