### ISSUE TITLE
gwc standalone - do not store the geowebcache.xml config file next to the tile cache

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2555]
Backup strategies are not the same for a text file and a dir filled with lots of tiles...

The doc mentions: "location of the configuration file is set in WEB-INF/geowebcache-core-context.xml. If you wish to move the configuration file to a different location, open geowebcache-core-context.xml and look for the <bean> tag referencing gwcXmlConfig:
Uncomment the bottom <constructor-arg value= ...> tag and specify the location where you would like to place geowebcache.xml."

**Comment by fvanderbiest** [comment]
Same was done in https://github.com/PDOK/geowebcache-docker/blob/master/generate-tomcat-dockerfile.sh#L30-L32

**Comment by fvanderbiest** [comment]
This requires having an unzipped geowebcache war in the docker image.

**Comment by fvanderbiest** [comment]
... and I need a helping hand from our maven gurus here ;-)

**Comment by severo** [comment]
Fixed by https://github.com/georchestra/georchestra/pull/2560 and https://github.com/georchestra/datadir/pull/144
