### ISSUE TITLE
Harmonize common properties

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2564]
Some properties are used in many modules:

- [x] email
- [x] database
- [x] ldap - only 3 modules (+geonetwork) use LDAP: cas, console, security-proxy, and there are a lot of options... Maybe let them inside applications properties files.

See https://github.com/georchestra/datadir/pull/149 and #2565

**Comment by severo** [comment]
Ready for revision

**Comment by fvanderbiest** [comment]
> * ldap - only 3 modules (+geonetwork) use LDAP: cas, console, security-proxy, and there are a lot of options... Maybe let them inside applications properties files.

With nearly 4 modules to use LDAP, that would make sense IMO to globally define `ldapHost ldapPort ldapBaseDN ldapAdminDN ldapAdminPassword ldapUserSearchBaseDN ldapRoleSearchBaseDN ldapOrgSearchBaseDN` vars.

**Comment by severo** [comment]
OK, right, I will do it.

**Comment by severo** [comment]
Remaining:

- [ ] remove publicUrl
- [ ] geonetwork ?
- [ ] geoserver ?

**Comment by severo** [comment]
Ready to review.

Note: I did not work on geonetwork nor on geoserver. If it's important to use the default. properties too for them, please comment.

**Comment by landryb** [comment]
geoserver also uses ldap but the link/ldap urls are in its geoserver datadir so it cant reach those properties i think....

**Comment by fvanderbiest** [comment]
> Note: I did not work on geonetwork nor on geoserver. If it's important to use the default. properties too for them, please comment.

I think this is out of scope here. Not the same datadirs...

**Comment by severo** [comment]
OK. I think it's finished then.

**Comment by fvanderbiest** [comment]
If I were nit-picking, I would say "not completely" since
```
$ git grep smtp
atlas/atlas.properties:smtpHost=smtp
atlas/atlas.properties:#smtpPort=25
console/console.properties:smtpHost=smtp
console/console.properties:#smtpPort=25
extractorapp/extractorapp.properties:smtpHost=smtp
extractorapp/extractorapp.properties:#smtpPort=25
```
With the added benefit that it would nearly allow us to get rid of the `docker-*` branches !

**Comment by severo** [comment]
OK! I will put both to default.properties, good idea.

**Comment by fvanderbiest** [comment]
:heart: your attention to details ;-)

**Comment by fvanderbiest** [comment]
> With the added benefit that it would nearly allow us to get rid of the `docker-*` branches !

Spoke too soon.
The log4j configuration mostly differs.

**Comment by severo** [comment]
See https://github.com/georchestra/datadir/pull/151 and https://github.com/georchestra/georchestra/pull/2572.
