### ISSUE TITLE
geonetwork - extract webapp in the official docker image

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#2570]
In some GN version upgrades, the schemas could be saved at first bootstrap in the geonetwork datadir, and becoming incompatible with new GN versions.

Having the GN webapp uncompressed in the docker image will increase the size, but would also allow us to point the schema dir (in the georchestra datadir) directly into the exploded webapp.

**Comment by fvanderbiest** [comment]
The datadir was updated with https://github.com/georchestra/datadir/commit/558995659e1b001d041f8d99dd323e59a58ea213

**Comment by fvanderbiest** [comment]
But I'm not sure that geonetwork webapp is unzipped in public images.
ping @pmauduit

**Comment by pmauduit** [comment]
> But I'm not sure that geonetwork webapp is unzipped in public images.
> ping @pmauduit

They are in the `georchestra/geonetwork:341-18.06` docker image, as well as 341-latest (but the CI on packages.g.o seems to fail since some days)
