### ISSUE TITLE
cas logout broken in 18.12 ?

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2574]
Can reproduce on two instances, one pre-production with nginx and the other which should be more or less stock 18.12 with apache, if i login to cas then logout, i get the 'Déconnexion réussie' page displayed but the cas webapp internally errors out with a 401 when trying to reach `proxyCallback` url

```
10.0.0.8, 10.0.0.1 - - [01/Apr/2019:14:46:48 +0200] POST /login/cas HTTP/1.1 401 1045
172.20.85.109, 10.0.0.1 - - [01/Apr/2019:14:46:48 +0200] GET /cas/logout HTTP/1.1 
```
(10.0.0.1 is the reverse-proxy IP, 10.0.0.8 is the georchestra container IP)
and the cas log shows this:
```
[WARN] 2019-04-01 14:46:48,515 org.jasig.cas.util.SimpleHttpClient call - Error Sending message to url endpoint [https://georchestra.dev.craig.fr/login/cas]. Error is [Server returned HTTP response code: 401 for URL: https://georchestra.dev.craig.fr/login/cas]
```

so at that point you think you've logged out, but you're still logged in. Can this be related to the recent properties harmonization ? I see that `proxyCallback` url still looks the same, constructed from scheme + domainName + `/login/cas` ...

Can anyone reproduce this ?

**Comment by landryb** [comment]
Comparing with 18.06, it seems i'm seeing the same behaviour in the logs, but with the 18.06 production instance i have here i'm effectively logged out.
The only difference that i can see at first sight is `/cas/logout?fromgeorchestra` in the working case vs `/cas/logout` in the broken case, i'll have to investigate if this matters - seems this *has* to match logout-success-url ? If so, maybe something not obvious to document for ppl doing their own headers/banners..

**Comment by landryb** [comment]
Hmm, no luck, even after ensuring the url called *was* matching `logout-success-url`, i'm still logged in after trying to logout.

**Comment by landryb** [comment]
okay, it seems the proper link to logout the user is presented with should be `/logout`, and not `/cas/logout` or `/cas/logout?fromgeorchestra` - as specified by https://github.com/georchestra/georchestra/tree/18.06/security-proxy#entrypoints - so closing, local issue.

**Comment by fvanderbiest** [comment]
Glad my prose helped someone at least ;-)

**Comment by severo** [comment]
I like these auto-closing issues :)

**Comment by landryb** [comment]
i like them too, especially so close to release...

**Comment by landryb** [comment]
The 401 on `POST /login/cas` is still a bit worrying but it's been there since a while..
