### ISSUE TITLE
docker - images with unzipped war

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2577]
If we want to let people override our images (eg to modify a CSS file or some JSPs), an idea is to copy the exploded WAR rather than the WAR itself to the docker image.

Do you think it is good or bad practice ?
Of course we could also tell them to fork the project and build, but it's not as easy.

**Comment by fvanderbiest** [comment]
Related issue #2570 for geonetwork

**Comment by jeanpommier** [comment]
Wouldn't it make bigger images ?
Can't we instead provide some override mechanism ? For instance, copy the content of a folder over geoserver files, after deployment ?

**Comment by fvanderbiest** [comment]
Yes, images would be bigger. Is it really an issue ?

**Comment by jeanpommier** [comment]
Probably not. Would be easier to customize, for sure

**Comment by fvanderbiest** [comment]
If we could change what is copied into the image at build time, eg here: https://github.com/georchestra/georchestra/blob/5fa2f9283a561c912376ed72e1cc6a8b2d0dac6a/extractorapp/pom.xml#L529-L534 this would help us reduce docker image size by nearly a factor of 2 
Indeed, unzipping the war like in https://github.com/georchestra/georchestra/blob/5fa2f9283a561c912376ed72e1cc6a8b2d0dac6a/extractorapp/src/docker/Dockerfile#L16-L18 would be useless

**Comment by fvanderbiest** [comment]
> If we could change what is copied into the image at build time

see #2644 for CAS

**Comment by fvanderbiest** [comment]
https://github.com/georchestra/georchestra/commit/34b0bdcbe9dc45a78c50d34efd00bd564461f437 for SP on master (future 19.06)

**Comment by fvanderbiest** [comment]
Should be fixed with #2849
