### ISSUE TITLE
geonetwork - groupQueryPattern value for ldapUserContextMapper

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2581]
Set `groupQueryPattern` of bean `ldapUserContextMapper` to `${ldap.privilege.search.privilege.pattern}` or `${ldap.sync.role.search.pattern}` ?

As of 19.04:
 * ldap.privilege.search.privilege.pattern = GN_(.*)
 * ldap.sync.role.search.pattern = EL_(.*)

Or should `ldap.privilege.search.privilege.pattern` value be updated ?
This is a bit of a mess without proper comments, see #2579

![Capture du 2019-04-02 16-09-31](https://user-images.githubusercontent.com/265319/55409144-bea23180-5561-11e9-8ba8-114195556f22.png)

**Comment by landryb** [comment]
That maps to... geonetwork groups, right ? Do we want them to map to orgs instead of arbitrary EL_* roles ? I dont really see a usecase... but i agree this is confusing.

IIrc privilege maps to profile, ie editor/reviewer, and corresponds to georchestra roles. That shouldnt change.

**Comment by cmangeat** [comment]
cf. https://github.com/georchestra/geonetwork/blob/georchestra-gn3.4-18.06/core/src/main/java/org/fao/geonet/kernel/security/ldap/LDAPUserDetailsContextMapperWithProfileSearch.java#L208
