### ISSUE TITLE
console - pending users count not shown on dashboard page

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2587]
On /console/manager/#!/home

Branch 19.04 with 1 pending user :
![Capture du 2019-04-08 14-25-07](https://user-images.githubusercontent.com/265319/55723755-1f21ea80-5a0a-11e9-8708-3ed5c28c4929.png)

Branch 18.06 with 5 pending users
![Capture du 2019-04-08 14-26-20](https://user-images.githubusercontent.com/265319/55723838-4e385c00-5a0a-11e9-9581-b3632786541d.png)

To be fixed on 19.04

**Comment by landryb** [comment]
can confirm, https://github.com/georchestra/georchestra/blob/19.04/console/src/main/webapp/manager/app/components/home/home.es6 probably needs work after #2108

**Comment by tonio** [comment]
Can be closed with https://github.com/georchestra/georchestra/pull/2632 ?
