### ISSUE TITLE
console - communes_simplified.json should be served locally

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2599]
https://github.com/georchestra/datadir/blob/b11671d25e3b4f214bad6b82380f342136f87687/console/console.properties#L132

**Comment by landryb** [comment]
Agreed, it's a bit cumbersome to find a way to host the file somewhere outside the ids, or in the middleware ? Serve it from datadir/console/areas.json ?

here i serve it from a `/static/` dir in the ids virtualhost, but it's meh.
