### ISSUE TITLE
geoserver: upgrade to latest stable version 2.15.0

### ISSUE THREAD

**Issue by groldan** [georchestra/georchestra#2605]
We might want to upgrade to the latest geoserver before the version we're using (2.12.5) gets too old, since it's actually EOL already.

Also, 2.15.0 is the first one that runs on Java 11 which opens the door to migrate to a docker container that supports cgroups (i.e. respecting CPU and memory limits).

**Comment by RemiDesgrange** [comment]
This is a great idea.Can we list all the benefits of migration in PR ?

**Comment by fvanderbiest** [comment]
Was done with #2606
