### ISSUE TITLE
[console] weird sort order in user lists

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2610]
on the `/console/manager/#!/role/<role>/users` , `/console/manager/#!/org/<org>/users` & `/console/manager/#!/browse/all/users` pages it seems users are sorted by first name, and in reverse alphabetical order. That seems.. very weird.

How about sorting by last name, and in alphabetical order ?

**Comment by Gaetanbrl** [comment]
We can use an [AngularJs orderBy](https://docs.angularjs.org/api/ng/filter/orderBy) to sort.
