### ISSUE TITLE
[console] make org link on user page a link to the org

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2618]
on a user page, we can only see the org the user is linked to, there's no direct way to go to this org page; navigation-wise it would be useful to have a link to the org page from the user info page.

The other way is to go to the list of users, and filter the list on the user, which shows both links to the user page & to the org page

**Comment by landryb** [comment]
Tried blindly adding:
```
--- a/console/src/main/webapp/manager/app/templates/userForm.tpl.html
+++ b/console/src/main/webapp/manager/app/templates/userForm.tpl.html
@@ -45,6 +45,9 @@
         <div class="col-sm-8">
           <input ng-model="model.org" class="form-control" id="organization" organizations model="model" promise="promise" placeholder="{{'user.org' | translate}}" ng-required="required.org">
         </div>
+        <div class="col-sm-8">
+          <a ng-link="org({org: user.orgId, tab: 'infos'})">{{::user.org}}</a>
+        </div>
       </div>
 
```

but that doesnt work, div doesnt display, and apparently `user.orgId` is undefined. Damn angular..

**Comment by Gaetanbrl** [comment]
We can change the default view for the list : 
https://select2.org/selections

So, it's possible to link the user.org directly : 
![image](https://user-images.githubusercontent.com/16317988/61441892-d0f47f80-a946-11e9-9f18-8d358dade947.png)

Or it's possible to insert an icon without change or extend the select2 component :
![image](https://user-images.githubusercontent.com/16317988/61442040-1e70ec80-a947-11e9-892c-f9345a67eb89.png)

The first option seems to be more convenient ?

When user clic on the icon or in the text, it's the default behavior : do something and open the list.
You could clic on the cross to get an example ![image](https://user-images.githubusercontent.com/16317988/61442991-e5d21280-a948-11e9-830c-0f4727126dca.png).

**Comment by landryb** [comment]
ok for the first variant, it's more natural to ppl to click on the name of the org to reach the org page.
