### ISSUE TITLE
docker setup on master broken

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2619]
It's waiting for localhost instead of database
```
analytics_1                 | ------------------------> DB not ready - waiting <---------------------------
analytics_1                 |  url:             jdbc:postgresql://localhost:5432/georchestra?user=georchestra&password=georchestra
analytics_1                 |  username:        null
analytics_1                 |  driverClassName: org.postgresql.Driver
cas_1                       | -------------> LDAP Not Ready waiting... on ldap://127.0.1.1:389 with login : cn=admin,dc=georchestra,dc=org Searching entry with '(uid=*)' in ou=roles,dc=georchestra,dc=org (3/300) <---------------
console_1                   | ------------------------> DB not ready - waiting <---------------------------
console_1                   |  url:             jdbc:postgresql://localhost:5432/georchestra
console_1                   |  username:        georchestra
console_1                   |  driverClassName: org.postgresql.Driver
```

**Comment by fvanderbiest** [comment]
I just tested it again after https://github.com/georchestra/docker/commit/d79bb359496a0feae4766f439f98c59f3639d3b8 but no better luck.

@RemiDesgrange what's the status of this issue ?

**Comment by RemiDesgrange** [comment]
When on master branch, when building docker images, we are currently building images with the tag "19.06-SNAPSHOT". In `georchestra/docker` repo are pulling from latest tag. It seems that latest images are broken. 

I changed the `docker-compose.yml` and it took in consideration the properties files of the datadir.

I think images with the tag "latest" are broken on docker hub.

**Comment by fvanderbiest** [comment]
> I think images with the tag "latest" are broken on docker hub.

Yes, they are 3 months old ... eg https://hub.docker.com/r/georchestra/geoserver/tags/ 
ping @pmauduit

**Comment by RemiDesgrange** [comment]
ok, so maybe we should update the CI to build every night the latest tag ?
