### ISSUE TITLE
console - error on org creation without businessCategory

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/georchestra#2666]
On master, i can create org without specify a business category. This action generate a weird behavior.

* I get a 500 error (PUT request) :
![image](https://user-images.githubusercontent.com/16317988/62133632-639a0480-b2df-11e9-9444-907edb37a311.png)
![image](https://user-images.githubusercontent.com/16317988/62133666-76143e00-b2df-11e9-9cff-1e0c6fddc6f8.png)

* This new org is create / accessible in the ldap with ldapsearch command, display in all orgs page but i can't read informations or do anything on this org from the console.
![image](https://user-images.githubusercontent.com/16317988/62134583-0a32d500-b2e1-11e9-80e9-84aa65df4784.png)

* this is slapd.log information : 
`RESULT tag=105 err=21 text=businessCategory: value #0 invalid per syntax`

* If i create a new org with business category, all seems to be better without errors.

About the business category, should not it be required with name and short name to create org ?
![image](https://user-images.githubusercontent.com/16317988/62134948-a957cc80-b2e1-11e9-81ce-dd8ebab89afc.png)

**Comment by landryb** [comment]
businessCategory/orgType should be mandatory by default per https://github.com/georchestra/datadir/blob/19.04/console/console.properties#L110 - if it isnt, maybe something in the frontend doesnt properly handle  `requiredFields` now

**Comment by Gaetanbrl** [comment]
Maybe i'm wrong... but i had  uncomment  _requireFields_ line in the console.properties, [and the expected type value](https://github.com/georchestra/georchestra/blob/19.04/console/src/main/webapp/manager/app/templates/orgForm.tpl.html#L27) was not return by the requireFields service. 

Currently, the requireFields service return any type value :
`https://georchestra.example.org/console/public/orgs/requiredFields`
```
[
    "name",
    "shortName"
]
```

If we manually set the next line in [OrgsController.java](https://github.com/georchestra/georchestra/blob/19.04/console/src/main/java/org/georchestra/console/ws/backoffice/orgs/OrgsController.java#L327), the type selection is required.
``` add fields.put("type"); ```

But this don't take account of requiredFields set in console.properties.

**Comment by fvanderbiest** [comment]
I can confirm that /console/manager/#!/orgs/all?new=org does not mention that `businessCategory` is a redired field and it refuses to create the org as long this field is not filled.

**Comment by fvanderbiest** [comment]
I can also confirm that the LDAP is left in a strange state when one first forgets to fill the `businessCategory` field, then submits the creation form with a valid `businessCategory`:

```
dn: cn=tst,ou=orgs,dc=georchestra,dc=org
objectClass: groupOfMembers
objectClass: top
cn: tst
o: Test
ou: tst
seeAlso: o=tst,ou=orgs,dc=georchestra,dc=org

dn: cn=tst1,ou=orgs,dc=georchestra,dc=org
objectClass: groupOfMembers
objectClass: top
cn: tst1
o: Test
ou: tst
seeAlso: o=tst1,ou=orgs,dc=georchestra,dc=org

dn: o=tst1,ou=orgs,dc=georchestra,dc=org
objectClass: georchestraOrg
objectClass: organization
objectClass: top
o: tst1
businessCategory:: Q29tbXVuYXV0w6kgZGUgY29tbXVuZXM=
postalAddress: 
```

**Comment by Gaetanbrl** [comment]
Mandatory seems to be fixed by @RemiDesgrange  in #2868 

Error already exist if we set empty orgType (if not mandatory).

**Comment by Gaetanbrl** [comment]
#2868 fix this issue if always set as requiredFields value in the `console.properties` file :
`requiredFields= firstName,surname,org,orgType`

**Comment by fvanderbiest** [comment]
> if always set as requiredFields value in the `console.properties` file :
> `requiredFields= firstName,surname,org,orgType`

Instead, `orgType` should be hardcoded as mandatory in the source code. 
It's too fragile to depend on this config option.

**Comment by Gaetanbrl** [comment]
> should be hardcoded as mandatory in the source code

This could be a solution.

> It's too fragile to depend on this config option.

As well it's disruptive (for and admin) if he cannot really set this field as not mandatory.
