### ISSUE TITLE
Upgrade to GeoTools 21.3 when it's released

### ISSUE THREAD

**Issue by groldan** [georchestra/georchestra#2682]
Main pom.xml is at gt-21.2, mapfishapp is at 21-SNAPSHOT due to #2677 
When gt-21.3 is released, upgrade them all.

**Comment by fvanderbiest** [comment]
Checking ... https://github.com/geotools/geotools/releases but nope ;-)

**Comment by fvanderbiest** [comment]
Seems version 22 's been released today.

**Comment by fvanderbiest** [comment]
https://github.com/geotools/geotools/releases/tag/21.3
