### ISSUE TITLE
[Console] filtering by org in analytics doesn't work

### ISSUE THREAD

**Issue by RemiDesgrange** [georchestra/georchestra#2685]
When you go to the analytics tab in the console, filtering by role doesn't work.

maybe add a new line over here : https://github.com/georchestra/georchestra/blob/19.04/analytics/src/main/java/org/georchestra/analytics/StatisticsController.java#L313

**Comment by fvanderbiest** [comment]
```
curl 'https://username:password@www.geo2france.fr/analytics/ws/layersUsage.json' \
-H 'Content-Type: application/json;charset=UTF-8' \
--data-binary '{"service":"layersUsage.json","startDate":"2019-07-23","endDate":"2019-08-23","role":"GT_TELECOM","limit":10}'
```
produces indeed the same output as
```
curl 'https://username:password@www.geo2france.fr/analytics/ws/layersUsage.json' \
-H 'Content-Type: application/json;charset=UTF-8' \
--data-binary '{"service":"layersUsage.json","startDate":"2019-07-23","endDate":"2019-08-23","limit":10}'
```

BTW, why do we use POST to query this service ? Would be more logical to use GET instead ...

**Comment by fvanderbiest** [comment]
`18.06`, `19.04` and `master` are affected.

**Comment by RemiDesgrange** [comment]
maybe because of the data passed. But these data could be passed as query string easily
