### ISSUE TITLE
Debian 10 is available

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2688]
https://www.debian.org/News/2019/20190706

Tasks:
 * upgrade Dockerfiles
 * check a standard deployment (ie without docker) on a Debian 10 machine
 * upgrade the doc with new package versions

**Comment by fvanderbiest** [comment]
Upgrading https://github.com/georchestra/ansible is another story, but that would be a great addition

**Comment by pmauduit** [comment]
The official docker jetty image (latest) is still based on debian 9 FYI

**Comment by fvanderbiest** [comment]
Right, https://hub.docker.com/_/jetty - sigh

**Comment by RemiDesgrange** [comment]
Feel free to open an issue :smile: https://github.com/appropriate/docker-jetty/issues

**Comment by fvanderbiest** [comment]
Some preliminary work with 53188e280
