### ISSUE TITLE
[console] Organizations with accented char in the short name can cause charset issues

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#2693]
* console can be unwilling to perform modifications
* Apache Directory Studio will fail in decoding the string (ArrayOutOfBoundException)

ldapvi is then the last resort:

![ca-trois-frontieres](https://user-images.githubusercontent.com/594335/63602283-5bc03e00-c5c7-11e9-9f5b-8cfed0597b68.png)

**Comment by landryb** [comment]
Welcome to encoding hell :)

**Comment by fvanderbiest** [comment]
I'm not sure what we should do here: prevent accents in Org short names, or clean them ?

**Comment by jeanpommier** [comment]
What is exactly the purpose of Org short name ?

**Comment by landryb** [comment]
a machine-readable short key, used in all the internal places/fields where you dont need a "pretty name" with spaces and accents and whatnot.

**Comment by jeanpommier** [comment]
Thanks Landry. Well, if everybody agrees on this definition, I don't see any reason why we should accept accents there. It would be just looking for complications.

Additionally, if they are machine-readable for internal places only, do we need the capacity to change them afterwards ? I'm thinking about #2855

**Comment by landryb** [comment]
here we settled for uppercase letters, numbers and underscore only. I'd like to see something like this (maybe not that strong) enforced for short names directly in the field validation, at least forbidding non-alphanumeric/spaces/accentued chars..

As for the capacity to change them, sadly i think it's needed b/c the user requesting the account fills it, and often puts non-meaningful values that we 'fix'/harmonize (CC_  & COM_ prefixes, etc...) wrt the existing orgs when we validate the account.

**Comment by fvanderbiest** [comment]
> I'd like to see something like this (maybe not that strong) enforced for short names directly in the field validation, at least forbidding non-alphanumeric/spaces/accentued chars..

Agreed !

These forms should not allow non-alphanumeric/accentued chars for the Organisation short name:
 * `/console/account/new`
 * `/console/manager/#!/orgs/all?new=org`
