### ISSUE TITLE
Console - Handle password regeneration for SASL users

### ISSUE THREAD

**Issue by jusabatier** [georchestra/georchestra#2705]
Currently, password regeneration is made directly on the user in the OpenLDAP.

The problem is that when we use SASL for delegating authentification to an external Active Directory (or other solutions), the OpenLDAP user's password store informations for SASL account linking (ex : {SASL}julien.sabatier).

If an user imported from the AD regenerate his password, it will be done only in the LDAP, and not repercuted to the AD.

Is it possible to allow to configure an optional URL for AD users where they can reset their password ?

Maybe we can use an LDAP class (ADUser) to identify users from AD, and then if the user has this class, redirect to this page when he want regenerate his password, or if no URL found, not allow him to regenerate.

**Comment by MaelREBOUX** [comment]
18.06 @jusabatier  ?

**Comment by jusabatier** [comment]
More an improvement than a bug, so not targeting an old version I think.

**Comment by fvanderbiest** [comment]
For CD43 we're tackling this one.

**SASL-enabled user** won't be able to change password, either via `/console/account/passwordRecovery?email=toto@provider.com` or  `/console/account/changePassword?uid=toto`. These pages will show a text inviting them to contact their platform admin (who knows where the change can be done).

**local users** : a `SUPERUSER` (or delegated admin) will be allowed to configure remote authentication for a given user, rather than a local validation of the password, via a checkbox. The remote system id will be configured in `console.properties`.
Checkbox displayed if and only if the corresponding setting is filled in `console.properties`.

**Comment by fvanderbiest** [comment]
See also #1533 ... to be discussed !

**Comment by fvanderbiest** [comment]
> a `SUPERUSER` (or delegated admin) will be allowed to configure remote authentication for a given user, rather than a local validation of the password, via a checkbox

There's an issue here : a checkbox does not allow a different login to be used on the remote AD.

Proposal : on the `/console/manager/users/fvanderbiest/infos` page, if and only if a remote server is configured in console.properties, display something like this:
![Capture du 2020-09-03 11-14-39](https://user-images.githubusercontent.com/265319/92097449-60255680-edd8-11ea-8cc4-a626d2ea5524.png)
The second field being displayed if and only if the checkbox is checked. By default, this field is filled with the local user's login. The admin may change it if required.

**Comment by pmauduit** [comment]
What if the option is activated, then the admin unchecks the checkbox, should it regenerate an OpenLDAP password ? (because it will mean that the link OpenLDAP <-> AD is no longer wanted, but still we would need to set back an OpenLDAP password)

**Comment by fvanderbiest** [comment]
Good point Pierre.
On page load, the checkbox' state depends on the presence of the `{SASL}` prefix in the `userPassword` ldap field.

Password is either local or remote => we need radio buttons instead:
 * [ ] local password - link to regenerate
 * [x] remote password on ad.cg43.fr - remote username [ fvanderbiest ]

Transition from local to remote overwrites userPassword with `{SASL}fvanderbiest`.

Transition from remote to local overwrites userPassword with a random, secure password + sends a templated email to user (something like https://github.com/georchestra/datadir/blob/master/console/templates/changepassword-email-template.txt except it says that the password was reset to local by an admin)
