### ISSUE TITLE
geonetwork - improve LDAPSynchronizerJob

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2714]
GeoNetwork's LDAPSynchronizerJob should be improved to sync more information from the LDAP.

For groups (mapped onto LDAP organisations): `description`, `website` and `logo` are missing

![Capture du 2019-09-20 13-55-26](https://user-images.githubusercontent.com/265319/65325130-50543880-dbae-11e9-8b7d-5e9a3ec7cb61.png)

For users, the organisation name is missing: (it defaults to "myorganization")
![Capture du 2019-09-20 13-58-56](https://user-images.githubusercontent.com/265319/65325338-dbcdc980-dbae-11e9-92df-cc03691c17d9.png)

**Comment by pmauduit** [comment]
To be closed / won't do ? This has been totally revamped by @groldan during the GN4 migration

**Comment by fvanderbiest** [comment]
Unfortunately not:
 * for the organization, the description, website and logo fields are not set
 * for the user, the organization is still set to 'myorganization' (at least on geo2france dev)

**Comment by fvanderbiest** [comment]
This will be part of 23.0.0 with the migration to GeoNewtork 4.2 #3706
