### ISSUE TITLE
github package registry

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2716]
We just got access to github package registry beta.

We can push 
 * artifacts https://help.github.com/en/articles/configuring-apache-maven-for-use-with-github-package-registry
 * docker images (though I do not see any advantage for now, compared to docker hub) https://help.github.com/en/articles/configuring-docker-for-use-with-github-package-registry

**Comment by RemiDesgrange** [comment]
+1 on the artifact registry.

**Comment by RemiDesgrange** [comment]
Seems easy ! 
![image](https://user-images.githubusercontent.com/13271765/65691431-1b922680-e071-11e9-86a7-3ecd0381751d.png)

**Comment by fvanderbiest** [comment]
![aatt](https://user-images.githubusercontent.com/265319/65693843-36669a00-e075-11e9-99f7-c20a8845be0e.jpeg)

**Comment by pmauduit** [comment]
For maven, it would be a bit more complicated than the one-liner provided, as it requires:

1. a modification of the root pom to reference the repository
2. modifying our own maven settings.xml file (defaults to `~/.m2/settings.xml`) to add the credentials (we obviously need the username which gets along with the provided token).

Also, I did a rapid try with the 2 modifications above, and I still got a bad request trying to publish mapfishapp from current master:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project mapfishapp: Failed to retrieve remote metadata org.georchestra:mapfishapp:19.06-SNAPSHOT/maven-metadata.xml: Could not transfer metadata org.georchestra:mapfishapp:19.06-SNAPSHOT/maven-metadata.xml from/to github (https://maven.pkg.github.com/georchestra): Failed to transfer file: https://maven.pkg.github.com/georchestra/org/georchestra/mapfishapp/19.06-SNAPSHOT/maven-metadata.xml. Return code is: 400 , ReasonPhrase:Bad Request. -> [Help 1]
```

Maybe we might need to first create the "mapfishapp" repository/placeholder somewhere in the github UI ?

**Comment by pmauduit** [comment]
Actually one need to activate the repo:read / repo:write options on the token.

**Comment by pmauduit** [comment]
Even if the plugin takes a lot of 400 bad request return codes, it seems that the publication is possible:
https://github.com/georchestra/georchestra/packages

**Comment by pmauduit** [comment]
I wonder if we should also "replug" geonetwork and geoserver onto the georchestra root pom, as a `mvn deploy` does not currently publish any package for those 2.

**Comment by fvanderbiest** [comment]
> I wonder if we should also "replug" geonetwork and geoserver onto the georchestra root pom, as a `mvn deploy` does not currently publish any package for those 2.

Makes sense to me.

**Comment by fvanderbiest** [comment]
Limits are very low for gh package repository.
We won't use it.
