### ISSUE TITLE
console - Wrong character encoding - Export users as CSV

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/georchestra#2737]
With some accents or other typicals french characters, we get wrong representation.

An example with a fictive data :  donnÃ©

![image](https://user-images.githubusercontent.com/16317988/66225399-a1008100-e6d8-11e9-911e-1e2aba9126d1.png)

**Comment by Gaetanbrl** [comment]
Encoding seems good [here](https://github.com/georchestra/georchestra/blob/master/console/src/main/webapp/manager/app/components/users/users.es6#L99).

So, i think we lose characters from this line and we need to specify 'utf-8' like that : 

`new Blob([csvString], { type: 'text/csv; charset=utf-8' }),`

**Comment by Gaetanbrl** [comment]
This seems to works fine : 
`const blob = new Blob(['\ufeff', result.data], { type: mimetype })`

**Comment by Gaetanbrl** [comment]
I move here a good question asked by @fvanderbiest :
> OK, I'd like to collect other people's opinion here before deciding to merge it or not.
@landryb @pmauduit @RemiDesgrange @cmangeat Do you think it's a good idea to create invalid UTF-8 documents to please Excel and ease user experience ?

**Comment by landryb** [comment]
@fvanderbiest technically, a document starting with BOM is a valid UTF-8 document, no ? As much as i hate excel, it's what people use.... and we should strive to ease their experience, even if it means adding gross hacks.

**Comment by landryb** [comment]
That's why i usually run away screaming when faced with encoding issues :) Seems BOM usage is discouraged, but if that's the common denominator to workaround most issues..

**Comment by fvanderbiest** [comment]
OK, as long as LibreOffice is able to cope with it also ...
