### ISSUE TITLE
console - non-functional logs filters

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/georchestra#2740]
For the logs page /console/manager/#!/logs we can't use logs filters.

[This line](https://github.com/georchestra/georchestra/blob/master/console/src/main/webapp/manager/app/components/logs/logs.es6#L17) seems to be the source of the problems : 

> let extract = (key) => [ ...new Set(this.logs.logs.map(l => l[key])) ]

Indeed, if we replace `this.logs.logs` by `this.log` all filters appear to work.

**Comment by landryb** [comment]
Tested locally, definitely unbreaks filters on the log page. Nice catch !!
