### ISSUE TITLE
console - empty area is not permited 

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/georchestra#2743]
This issue is a question to know if it's possible to have an org without area ? @landryb @fvanderbiest @RemiDesgrange 

If we remove all area for an org `/console/manager/#!/org/craig/area`, we could save the zone with a success message.
![image](https://user-images.githubusercontent.com/16317988/66380283-67b96100-e9b7-11e9-9657-61796894e170.png)

But, i reload the window and org's area is not empty because [OrgController](https://github.com/georchestra/georchestra/blob/master/console/src/main/java/org/georchestra/console/ws/backoffice/orgs/OrgsController.java#L434) forbid to save an empty zone.

**Comment by fvanderbiest** [comment]
> This issue is a question to know if it's possible to have an org without area ?

Yes it should be possible.

> i reload the window and org's area is not empty because [OrgController](https://github.com/georchestra/georchestra/blob/master/console/src/main/java/org/georchestra/console/ws/backoffice/orgs/OrgsController.java#L434) forbid to save an empty zone.

Yes, see also #2471 which we're not sure to fix in time for the release.
Feel free to contribute ;-)

**Comment by Gaetanbrl** [comment]
> Yes, see also #2471 which we're not sure to fix in time for the release.

Thanks @fvanderbiest . Sorry for this dupplicate entry. I close this issue.
