### ISSUE TITLE
18.06 - Geoserver - "Corrupted Content Error"

### ISSUE THREAD

**Issue by bendeg** [georchestra/georchestra#2748]
geOrchestra is set up using debian/middleware configuration, in a VM (VirtualBox)

1) "viewer" link works on https://georchestra.mydomain.org/mapfishapp/, I can use tools, save workspace, change background layer, etc...
2) I can log in/out with every active users
3) "catalog" link works fine. It's just empty.
4) "administration" link works. I can change my password, add a new user (and see it in LDAP)

5) "services" link is there but leads me to a "Corrupted Content Error" message from FF (got a error as well with Chromium).

If I add "?0" (I don't remember why I tried this...) at the end of the URL, AND I'm "testadmin" or "geoserver_privileged_user", it show the geoserver admin page but clicking on any of the left or center panel links leads me to that "Corrupted Content Error" page again (links on the right about services work fine). If I'm not "testadmin" or "geoserver_privileged_user" I can see the anonymous page of geoserver.

Error page tells about some protocol error :

"
The site at https://georchestra.mydomain.org/geoserver/web/ has experienced a network protocol violation that cannot be repaired.

The page you are trying to view cannot be shown because an error in the data transmission was detected.

    Please contact the website owners to inform them of this problem.
"

I've no clue about what can cause this...

Any idea ?

**Comment by bendeg** [comment]
Here's Chromium error message :

"
This page isn’t working georchestra.mydomain.org sent an invalid response.
ERR_RESPONSE_HEADERS_MULTIPLE_LOCATION
"

**Comment by bendeg** [comment]
Logs

Each simple click on link "services" populates logs like this : 

In /var/lib/tomcat-proxycas/logs/localhost_access_log.2019-10-11.txt

Error version
0:0:0:0:0:0:0:1 - - [11/Oct/2019:10:59:36 +0200] "GET /geoserver/web/ HTTP/1.1" 302 -

Ok version
0:0:0:0:0:0:0:1 - - [11/Oct/2019:11:04:12 +0200] "GET /geoserver/web/?0 HTTP/1.1" 200 20134
============================================================================
In georchestra logs, looks good...

/var/lib/tomcat-georchestra/logs# tail -1000 localhost_access_log.2019-10-11.txt 

127.0.0.1 - - [11/Oct/2019:11:04:12 +0200] "GET /header/ HTTP/1.1" 200 8219
127.0.0.1 - - [11/Oct/2019:11:04:12 +0200] "GET /header/img/logo.png HTTP/1.1" 200 32411

============================================================================
In geoserver0 logs:

/var/lib/tomcat-geoserver0/logs# tail -1000 localhost_access_log.2019-10-11.txt 

127.0.0.1 - - [11/Oct/2019:11:02:00 +0200] "GET /geoserver/web/ HTTP/1.1" 302 -
127.0.0.1 - - [11/Oct/2019:11:04:12 +0200] "GET /geoserver/web/?0 HTTP/1.1" 200 4219

**Comment by fvanderbiest** [comment]
HEADERS_MULTIPLE_LOCATION means that the issue is on our side, it might be that the security-proxy is adding an extra Location header.

This is something we should already have fixed with #2034 and you're the only one to experience it.
Please paste here the full request with response headers so we can analyse it.

**Comment by bendeg** [comment]
Here it is but I'm not sure if that's what you want...

(Using  F12 in FF, I can only see Request Headers.
There's no Response payload at all. It is empty)

GET https://georchestra.mydomain.org/geoserver/web/
==============================================================================
Host: georchestra.mydomain.org
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://georchestra.mydomain.org/header/?lang=en&active=mapfishapp
Cookie: JSESSIONID=D046A1486C811BF789BD9BC0C1F78803
Connection: keep-alive
Upgrade-Insecure-Requests: 1
==============================================================================

**Comment by fvanderbiest** [comment]
This is the request. Theres should be a "response" tab in your debugging tools. This where the interesting stuff is.

**Comment by bendeg** [comment]
Maybe this can give a hint :

When configuring 3 tomcat instances, I had to modify the way of configuring the 3 services.

For each of them, I had to : 
- copy /usr/share/tomcat8 to /usr/share/tomcat-xxx
- change the NAME variable in /etc/init.d/tomcat-xxx to tomcat-xxx

This was the only way to start all 3 tomcat instances as services

Maybe this gives a hint of what's happening, not sure about that, this has maybe nothing to do with the error...

**Comment by fvanderbiest** [comment]
> This was the only way to start all 3 tomcat instances as services

Do you mean https://github.com/georchestra/georchestra/blob/19.04/docs/setup/tomcat.md#tomcat-proxycas is not up to date ?

> I can see Response headers only when using ?0 at the end of the URL, when there's no error

Yes, the response headers here are correct.
What's the output of `curl -I https://georchestra.mydomain.org/geoserver/web` ?

**Comment by bendeg** [comment]
1) Apparently, setup doc is up-to-date because others can start their 3 tomcat instances...Maybe I did something wrong, but I've tried 3 times, with 3 new VMs under Virtualbox without success.
I couldn't because each of the 3 instances use ports 8080 8005 (in fact, those of default tomcat8 instance) => only one of them can be started at a time.
I could start the 3 instances ONLY using /var/lib/tomcat-xxx/bin/startup.sh script, not as services.

2) 
root@georchestra:~# curl -I https://georchestra.mydomain.org/geoserver/web
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
root@georchestra:~#

**Comment by issep** [comment]
Is there something wrong with my auto-signed certificate ?

Here it is (myOU, myO, myL, myST and myC are set to my place. CN has been left unchanged) : 

root@georchestra:~# keytool -keystore /etc/tomcat8/keystore -alias georchestra_localhost -list -v
Entrez le mot de passe du fichier de clés :  
Nom d'alias : georchestra_localhost
Date de création : 03-oct.-2019
Type d'entrée : PrivateKeyEntry
Longueur de chaîne du certificat : 1
Certificat[1]:
Propriétaire : CN=localhost, OU=myOU, O=myO, L=myL, ST=myST, C=myC
Emetteur : CN=localhost, OU=myOU, O=myO, L=myL, ST=myST, C=myC
Numéro de série : 385d1351
Valide du : Wed Oct 02 11:36:38 CEST 2019 au : Tue Dec 31 10:36:38 CET 2019
Empreintes du certificat :
	 MD5 : 5A:74:22:4A:C6:0B:AA:3D:F1:5D:6C:6C:84:A9:2D:06
	 SHA1 : E0:3B:BC:BB:BF:7F:42:5D:AE:B4:B1:61:BB:F7:0C:AF:76:DA:96:7D
	 SHA256 : 36:16:47:6B:24:FD:30:34:68:5A:8C:8E:40:63:8A:A9:DE:27:A8:53:B4:C2:BF:2C:56:B8:36:BB:33:C1:ED:D5
Nom de l'algorithme de signature : SHA256withRSA
Algorithme de clé publique du sujet : Clé RSA 2048 bits
Version : 3

Extensions : 

#1: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 18 DE A0 14 C9 0B 37 30   47 0D 03 1F 98 7B 36 F6  ......70G.....6.
0010: 03 30 C5 BF                                        .0..
]
]
root@georchestra:~#

**Comment by bendeg** [comment]
When on that page (https://georchestra.mydomain.org/geoserver/web, though FF detects HTTPS there's no information about certificate : all is empty.

The same certificate is used for all georchestra, right ?

**Comment by bendeg** [comment]
Here they are but I have to use **-k option as well** : 

root@georchestra:/etc/georchestra# curl -Ik https://georchestra.mydomain.org/geoserver/web

**HTTP/1.1 302 
Date: Mon, 14 Oct 2019 11:07:24 GMT
Server: Apache/2.4.25 (Debian)
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Location: /geoserver/web/
Location: /geoserver/web/
Set-Cookie: JSESSIONID=B7D8139BFD2CE5FD3BD486871BDF24AD; Path=/; HttpOnly
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept**

root@georchestra:/etc/georchestra#

**Comment by fvanderbiest** [comment]
Thanks.
As you can see, the Location header is repeated 2 times, which is incorrect.

I just realized you're deploying 18.06
Why are you not using 19.04 which is the current stable ?

**Comment by bendeg** [comment]
I did install version 19.04 the very first time, but it didn't work because file default.properties wasn't present if I remember well and causes the whole thing to not work...

Should I just checkout /etc/georchestra to version 19.04 ?

**Comment by fvanderbiest** [comment]
> Should I just checkout /etc/georchestra to version 19.04 ?

Yes, it's a safe move if you're using 19.04 artifacts.
Indeed the default.properties file is not provided by any package. This is an issue @pmauduit had already raised.

**Comment by landryb** [comment]
> HEADERS_MULTIPLE_LOCATION means that the issue is on our side, it might be that the security-proxy is adding an extra Location header.
> 
> This is something we should already have fixed with #2034 and you're the only one to experience it.

There was also #2193 which affected 18.06 iirc

**Comment by fvanderbiest** [comment]
> There was also #2193 which affected 18.06 iirc

Thanks, and this has been fixed on 19.04.
@bendeg please tell us how it goes with 19.04

**Comment by bendeg** [comment]
Just finished middleware setup version 19.04 : it works now.

I can see geoserver page now, admin access with testadmin and geoserver_privileged_user, and as a standard user as well (testuser)

**Comment by fvanderbiest** [comment]
Congrats !
