### ISSUE TITLE
[console] add an admin-only 'internal notes' field on user & org

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2773]
Now that we can add freeform fields since #2552 can we add an `internal notes` field (shown only to SUPERUSER or ORGADMIN users) to users & orgs ldap classes ?

This way a team of admin users can share notes on orgs & users, without those being shown to users on the `/console/account/userdetails` page.

**Comment by fvanderbiest** [comment]
Sounds like a neat idea !

**Comment by landryb** [comment]
fixed by #2908
