### ISSUE TITLE
console - user erroneously advertised as expired 

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2779]
Expiration date set to 2020-01-01 (current date is 2019-10-16)
Console shows "One expired user"

![Capture du 2019-10-16 12-08-00](https://user-images.githubusercontent.com/265319/66909758-9cf42d80-f00d-11e9-88c6-ee92ff9aa53c.png)

**Comment by tonio** [comment]
It's server side. The `/console/private/roles` endpoint wrongly returns the user in `TEMPORARY` role.

**Comment by pmauduit** [comment]
> It's server side. The `/console/private/roles` endpoint wrongly returns the user in `TEMPORARY` role.

Being marked as temporary sounds the normal behaviour to me, but maybe we need to give the expiry date in the JSON response (which would need further processing client-side). Am i wrong ?

**Comment by pmauduit** [comment]
There might be a little bit of frontend dev on the PR above (poke @tonio)
