### ISSUE TITLE
console - role names should be regexp-validated

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2781]
UPPERCASED, no special chars, no space ...
![Capture du 2019-10-16 14-23-09](https://user-images.githubusercontent.com/265319/66918906-9de28a80-f020-11e9-9835-c93d796c6149.png)

**Comment by landryb** [comment]
yes please !!!!

**Comment by fvanderbiest** [comment]
No milestone for now ...

**Comment by fvanderbiest** [comment]
Something like https://github.com/georchestra/georchestra/commit/1046f9dce6ef80fb76b6e7fb99bf5973e0f608d2
