### ISSUE TITLE
[master] Geoserver - Bump to version 2.15.3

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#2782]
For the Deutsch-Telekom project, we had to upgrade to a new version of GeoServer. A branch in the GS fork has been prepared for this (see https://github.com/georchestra/geoserver/tree/2.15.3-georchestra), but there are still some work to wire it to the georchestra repository.

@groldan do you know if the directory here https://github.com/georchestra/georchestra/tree/master/geoserver/lib is still needed ? Since we have been with GeoTools v21.3 in this version of GeoServer.

I will prepare a branch in this repository to be able to PR.

**Comment by fvanderbiest** [comment]
superseded by 2.16.1
