### ISSUE TITLE
[19.04] Geonetwork - admin menu items don't work

### ISSUE THREAD

**Issue by bendeg** [georchestra/georchestra#2787]
**[19.04] Geonetwork  gn3.0.x - admin menu items don't work**

**Both admin menus "Contribute" and "Admin console" are present and populated with their respective menu items but a click on any of them don't show anything**

**To Reproduce**
1. Go to 'Catalogue'
2. Click on 'Admin console' or any of the admin menu item

**Expected behavior**
I should be able to manage Geonetwork as admin user but nothing shows up

**Comment by fvanderbiest** [comment]
Are you sure you're using Geonetwork gn3.0.x ? On 19.04 you should have GN 3.4

**Comment by pierrejego** [comment]
I had the same issue on a migration from 17.12 to 19.12.

To fix it I had to 
update geonetwork datadir with datadir 3.4x https://github.com/georchestra/geonetwork_minimal_datadir/tree/gn3.4.1

delete all wro4j files from geonetwork datadir.

But I didn't had you 404 error on lib.js

**Comment by bendeg** [comment]
I switched to gn3.4.1 and it works.
That was indeed the problem ! Much better :-), thanks !

Now, since I followed the instructions of the tomcat middleware setup (version 19.04), I would like to send a pull request to modify one line in tomcat.md : 

sudo git clone -b **gn3.4.1** https://github.com/georchestra/geonetwork_minimal_datadir.git /opt/geonetwork_data_dir

instead of : 
sudo git clone -b **gn3.0.x** https://github.com/georchestra/geonetwork_minimal_datadir.git /opt/geonetwork_data_dir

**Comment by bendeg** [comment]
Though all "Admin console" menu works, this is not the case for the "Contribute" menu.

When looking at "network" tab in FF, all request are 200 or 302 (cached) but there's nothing to interact with, the area is completely blank.

**Comment by bendeg** [comment]
Looks like I found the problem and there's some kind of initialisation issue :

As "testadmin" is not a member of the role GN_EDITOR,

1) I had first to login as "testeditor" (who is the only member of role GN_EDITOR)
2) go in "Catalog" and click on "Contribute" => takes some time to initialise "things" (in database ?)
3) logout and login as "testadmin"
4) go in "Catalog" and click on "Contribute" and VOILA !

Since I change geonetwork version AFTER installation (from gn3.0.X to gn3.4.1), could it be the reason I HAD to do those steps ?

**Comment by fvanderbiest** [comment]
`testadmin` should have role `GN_ADMIN` which is enough to edit/publish/manage metadata 


> Since I change geonetwork version AFTER installation (from gn3.0.X to gn3.4.1), could it be the reason I HAD to do those steps ?

Who knows ? ;-)

**Comment by bendeg** [comment]
I see testeditor is member of CKAN_EDITOR (metadata admin), testadmin is not...
