### ISSUE TITLE
geonetwork - metadata view permission to be renamed

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2791]
The following screenshot shows "publier" instead of "voir":
![Capture du 2019-10-19 13-57-45](https://user-images.githubusercontent.com/265319/67144602-81d92600-f278-11e9-85d9-2da2d960f061.png)

**Comment by fvanderbiest** [comment]
cc @fxprunayre

**Comment by fxprunayre** [comment]
Maybe Consulter/Visualiser/Télécharger/Notifier would be better translations ? Can be done in transifex.

**Comment by fvanderbiest** [comment]
Yeah, sure !
That would be awesome. It's so misleading for end users...

**Comment by fvanderbiest** [comment]
Even the associated logos (a share button for the view permission) are misleading.

**Comment by fvanderbiest** [comment]
How can we deal with it ? An issue on the geonetwork project ? A direct fix in transifex ? a PR for the logo ?

**Comment by fxprunayre** [comment]
> How can we deal with it ?

Just do it https://github.com/geonetwork/core-geonetwork/pull/4126. Review welcomed. Translation for operation is in database, not in transifex.

**Comment by fvanderbiest** [comment]
Thanks a bunch :-)
