### ISSUE TITLE
geonetwork - csw harvester does not provide any UI to filter incoming metadata

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2792]
When creating a CSW harvester, there is no way to create a filter, the panel is empty:

![Capture du 2019-10-20 10-47-07](https://user-images.githubusercontent.com/265319/67157072-17cb8a00-f327-11e9-91f1-f45262fbdfe3.png)

**Comment by fxprunayre** [comment]
The filter list is based on the GetCapabilities declared queryables (which can change from on service to another), so if you add a URL, the filter list should be updated ?

**Comment by fvanderbiest** [comment]
I'm not sure I understand what you mean.
I'd like to harvest a single metadata record from https://data.laregion.fr/api/csw based on the record title.

**Comment by fxprunayre** [comment]
https://data.laregion.fr/api/csw?&SERVICE=CSW&REQUEST=GetCapabilities&VERSION=2.0.2
advertised no filter in GetRecords operation so there is no filter available in the configuration

Usually a discovery service proposed something like:
```
  <ows:Constraint name="SupportedISOQueryables">
        <ows:Value>CreationDate</ows:Value>
        <ows:Value>GeographicDescriptionCode</ows:Value>
        <ows:Value>OperatesOn</ows:Value>
        <ows:Value>Modified</ows:Value>
```

For harvesting opendatasoft, https://github.com/geonetwork/core-geonetwork/pull/4034 may help but it is experimental for now. I never managed to harvest the opendatasoft CSW endpoint (even with no filter) - depends on the version probably.

**Comment by fvanderbiest** [comment]
Interesting, thanks François.
I managed to harvest this "data.laregion" CSW but the result is pretty disappointing...
![Capture du 2019-10-20 19-45-41](https://user-images.githubusercontent.com/265319/67163688-4b7fd180-f372-11e9-907a-e99fa7e58662.png)

I hope we'll be able to help with #4034
