### ISSUE TITLE
[19.04] Can't add new user

### ISSUE THREAD

**Issue by bendeg** [georchestra/georchestra#2793]
After filling the 3 mandatory fields (Second name, first name and email) and clicking "Save", I have an error 500 in FF :

in "Console" tab : 

**XML Parsing Error: syntax error
Location: https://georchestra.mydomain.org/console/private/users
Line Number 1, Column 1:
users:1:1**

in "Network" tab : 

**org.springframework.ldap.InvalidAttributeValueException: [LDAP: error code 21 - objectclass: value #5 invalid per syntax]; nested exception is javax.naming.directory.InvalidAttributeValueException: [LDAP: error code 21 - objectclass: value #5 invalid per syntax]; remaining name 'uid=bddd,ou=users'**

All other users can login/logout.
There's a clear distinction between admin and standard users, and geoserver-privleged_user as well.

**Comment by fvanderbiest** [comment]
"objectclass: value #5 invalid per syntax" makes me think of a missing insert of `openssh.ldif`
See https://github.com/georchestra/georchestra/blob/19.04/docs/setup/openldap.md#add-sshpublickey-objectclass

**Comment by bendeg** [comment]
I though something similar but when trying to simply modify "testadmin" user address : 

**org.springframework.ldap.InvalidAttributeValueException: [LDAP: error code 21 - objectClass: value #0 invalid per syntax]; nested exception is javax.naming.directory.InvalidAttributeValueException: [LDAP: error code 21 - objectClass: value #0 invalid per syntax]; remaining name 'uid=testadmin,ou=users'**

**Comment by bendeg** [comment]
I would like to reconfigure LDAP from scratch but this time, without sshpublicKey used only by "testadmin" user.

Is it possible to :

1) delete all configuration provided by georchestra's openldap.md (how ?)
2) edit georchestra.ldif file, and simply delete sshPublicKey of user testadmin
3) restart configuration (obviously without sshPublicKey step this time)

?

**Comment by fvanderbiest** [comment]
Maybe you can `apt remove --purge openldap` and then install it again.

**Comment by bendeg** [comment]
Removing and purging works fine and deletes all the config, thanks.

Re-creating all LDAP users, with or without sshPublicKey, doesn't seem to change anything (I've done both) : in both cases, LDAP configuration goes fine until the end and all seems to work (modifying user role, creating orgs, creating roles,...) except modifying a user (objectClass #0) or creating one (objectClass #5) via the console, or requesting a new account.

I remember having no such issue in version 18.06 : I could request a new account or create a new user via the admin console.

The problem seems to be only related to basic user information (address, tel, etc...).

**Comment by bendeg** [comment]
I'm not an expert but there's a detail that took my attention in line 428 : 

Is objectClass "georchestraUser" still used in LDAP configuration ?

I've seen in another post ( https://groups.google.com/forum/#!topic/georchestra-dev/rUID65wlfKo ), where they're talking about the issue

**Comment by fvanderbiest** [comment]
> Is objectClass "georchestraUser" still used in LDAP configuration ?

It is indeed required.

**Comment by fvanderbiest** [comment]
It is indeed required, but only on master, if we did not screw up...

**Comment by issep** [comment]
For the fun, I build geOrchestra 19.04 following instructions in georchestra/build.md, now, that's a gas factory !

But hey, it went well and I can see all generated wars in their respective target directory.

Is there any "easy" way I can move back one step to the previous backport (I don't even know what that is...) which, I assume, were modified to take the SSH thing into account, to try without SSH key ? I don't think it's the best idea, just asking, trying to get into the geoRchestra developement process, who knows, I might help in some way or even add new things...

**Comment by bendeg** [comment]
For the fun, I build geOrchestra 19.04 following instructions in georchestra/build.md, now, that's a gas factory !

But hey, it went well and I can see all generated wars in their respective target directory.

Is there any "easy" way I can move back one step to the previous backport (I don't even know what that is...) which, I assume, were modified to take the SSH thing into account, to try without SSH key ? I don't think it's the best idea, just asking, trying to get into the geoRchestra developement process, who knows, I might help in some way or even add new things...

**Comment by bendeg** [comment]
Ok, if I understand well backporting is bringing modification made on a version to an older version, right ?
pierrjego talks about backport 42ac1e1.

Does the **git cherry-picking** command do that ?

**Comment by pmauduit** [comment]
> if we did not screw up...

We (well, I) did

**Comment by bendeg** [comment]
gitpulled, compiled, deployed : working !

Thank you sooooo much for all your work and time !

**Comment by bendeg** [comment]
Looks like there's another problem : 

1) adding a new user via the admin console works. I can change the user password and log in with that new user.
But once logged in, the user can't see his own profile : 
**java.io.IOException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0**

2) Another problem shows up after adding a new user who signed up : once again the user creation works and is first in a pending status.
After the admin confirmation the user is added.
The new user can log in but if he tries to go and see his profile, an error says he's in more than one org

3) After, as testadmin, If I put the user in an organization, he can log in and see his profile without any issue.
BUT : the user's organization is "empty" but he's a member of the organization !

4) Taking a look directly at organizations : none of them owns any member

Do anyone got the same problem ?

**Comment by bendeg** [comment]
I can see some weird behaviours concerning organizations but I'm not sure if it's me or not.

But there's something wrong during a sign-up, though I mention a valid email address  : 
**java.io.IOException: javax.mail.SendFailedException: No recipient addresses**

(I tested the SMTP with that email address and it works when sending a message with user testadmin and it works fine)

**Comment by bendeg** [comment]
My bad this time, and for those who gets a similar issue : I forgot to mention a valid email address for administratorEmail in /etc/georchestra/default.properties

**Comment by bendeg** [comment]
My bad this time, and for those who gets a similar issue : I forgot to mention a valid email address for administratorEmail in /etc/georchestra/default.properties
