### ISSUE TITLE
GDPR - add an option to disable account deletion

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2795]
Some professionnal plateforms on intranet are not subject to GDPR.
Having users deleting their account (accidentally or not) is not expected in this context.

We should implement in `console.properties` a boolean value like `gdpr.enable` (defaulting to `true`). 

When set to `false`, it:
 * hides the "delete account" button
 * prevents the service from being called programatically

I guess it does not harm to keep the "download my data" button, even if `gdpr.enable = false`

**Comment by fvanderbiest** [comment]
PRs are not merged nor reviewed, and, to my knowledge, do not obey the issue description, since the boolean flag disables both account deletion and data download when only account deletion is required.

Maybe the option is badly named. It should probably be renamed into `gdpr.account.deletion`.

**Comment by RemiDesgrange** [comment]
Ahhhh I thought you wanted to disable the whole feature :-) I'll update the PR accordingly

**Comment by fvanderbiest** [comment]
> Maybe the option is badly named. 

Yes, the option should be renamed into gdpr.allowAccountDeletion (defaulting to true) to make it clear what it really means.
Sorry for the noise.

**Comment by fvanderbiest** [comment]
> the option should be renamed into gdpr.allowAccountDeletion

not taken into account ?

**Comment by pmauduit** [comment]
> not taken into account ?

missed it.
