### ISSUE TITLE
security-proxy - removedXForwardedHeaders not honored with multiple servers

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2797]
On master, spotted a regression regarding the `removedXForwardedHeaders` server list.
Works when there's a single value, breaks when there are several comma-separated servers:
```
# A comma-separated list of patterns of urls that (when matched) will have
# the x-forwarded-* headers removed
# default: .*geo.admin.ch.*,.*rolnp.fr.*
removedXForwardedHeaders=.*maps.heigit.org.*,.*ows.mundialis.de.*
```

**Comment by fvanderbiest** [comment]
Use case is with WMS servers http://maps.heigit.org/osm-wms/service & http://ows.mundialis.de/services/service?

**Comment by landryb** [comment]
Cf https://groups.google.com/forum/#!topic/georchestra/0NG-8M7NiQw , especially my last msg ?

**Comment by fvanderbiest** [comment]
Thanks ! 
I knew it had already been reported recently but could not find it... ("infobesity" syndrom)
