### ISSUE TITLE
[all versions] SP - getting rid of charset guessing ?

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#2812]
Since the begining of geOrchestra, there is this part of code in the huge `Proxy.java` class from the SP which is trying to do charset guessing and "fix" the headers sent from upstream:

https://github.com/georchestra/georchestra/blob/19.04/security-proxy/src/main/java/org/georchestra/security/Proxy.java#L1047-L1210

We are currently encountering a strange bug where the GZIP implementation from upstream differs from the one we are using in the SP. As a result, there is a difference of 1 byte between the response from upstream and the re-compressed stream in the SP, but it is still the Content-Length header received from upstream which is sent back to the actual client:

![gzip-stream](https://user-images.githubusercontent.com/594335/68194511-721a4b00-ffb5-11e9-9738-83aa3d507f3d.png)

I wonder if this is really the role of the SP to mangle a request coming from another server / platform, and trying to "fix" these charset issues. I think that we should send back to the client the response of the upstream server the closest possible as we received it.

My idea would be to remove this code and keep the headers as they are from upstream, but I also fear to break something, as this code is here since almost the begining.

**Comment by fvanderbiest** [comment]
> My idea would be to remove this code and keep the headers as they are from upstream

I'm +1 on it.
Makes sense nowadays.

> but I also fear to break something, as this code is here since almost the begining.

Tests ...

**Comment by pmauduit** [comment]
related PR has been merged, closing
