### ISSUE TITLE
[19.04] CONSOLE - Members of an organization don't show up

### ISSUE THREAD

**Issue by bendeg** [georchestra/georchestra#2817]
**19.04**

**CONSOLE - Members of an organization don't show up**

In console, in Organization tab, though an organization has members, they don't appear in the list of members.

**Expected behavior**
Members should appear in the list of members.

In the Network tab of FF, one can clearly see that the 3 users members of PSC have been found, but it's like the console would do nothing with it.

**Screenshots**
![console_orgs_members](https://user-images.githubusercontent.com/12762673/68400989-421ba500-0179-11ea-9772-c96c5df3770e.png)

**Additional context**
1) What could be related is that when "testadmin" is viewing a user profile, whoever it is, there's by default no organization shown for the user. He can choose one, but none appear when viewing the profile (listbox doesn't show the organization, we have to choose one).

2) for all user or after adding a user, they can all be seen in LDAP, as well as their membership in their organization. So, on LDAP size, everything looks fine.

3) When a user is viewing its own profile, he can see the organization he's member of and all other members of the same organization.

4) I've been advice to check if "memberOf" was functionnal and as I don't know how to check that, I've found this : [https://www.adimian.com/blog/2014/10/how-to-enable-memberof-using-openldap/](https://www.adimian.com/blog/2014/10/how-to-enable-memberof-using-openldap/) : I modified to match the setup, all steps work fine but it doesn't change anything.

5) I can see the module memberof in /usr/lib/ldap/

6) When using ldap command line, looks like memberOf doesn't seem to work, I should see a second line with "member of : ..." : 
```
ben@georchestra:~$ ldapsearch -x -LLL -H ldap:/// -b uid=testadmin,ou=users,dc=georchestra,dc=org dn memberof
dn: uid=testadmin,ou=users,dc=georchestra,dc=org
```

**Comment by fvanderbiest** [comment]
`memberOf` overlay indeed targets `dn: olcOverlay=memberof,olcDatabase={1}mdb,cn=config` according to https://github.com/georchestra/georchestra/blob/19.04/ldap/memberof.ldif which might not be what you want, depending on your local setup.
You have to check this matches your LDAP db name.

If you're unsure about all this, use LDAP image tagged 19.04 where we already took care of all this stuff.
https://github.com/georchestra/docker/blob/96a7bd4e9cf1311fdff80525a145ba9e183f1a54/docker-compose.yml#L23-L31

**Comment by fvanderbiest** [comment]
After shutting down local LDAP server, you can run `docker-compose up` with https://github.com/georchestra/georchestra/blob/19.04/ldap/docker-compose.yml where you replace 10389 port by 389 to bind it to localhost (or change in your datadir the port where geOrchestra expects to find a LDAP service to 10389)

**Comment by bendeg** [comment]
This is where it becomes very confused to me.

1) After removing/purging slapd, I can only see : /etc/ldap/ldap.conf file.
There's nothing else in there.

2) After a new and fresh slapd install : 3 new directories (sasl2, schema, slapd.d).

In **/etc/ldap/slapd.d/cn=config/** there's already a **olcDatabase={1}mdb.ldif** file

3) After adding **bootstrap.ldif** there's a new ldif file in that same directory (it's the first time I notice that...) : **olcDatabase={2}mdb.ldif**

I think that it's that last name that I must use when adding memberOf overlay, so instead of : 

**dn: olcOverlay=memberof,olcDatabase={1}mdb,cn=config**

I must use this name in memberOf.ldif : 

dn: olcOverlay=memberof,olcDatabase={2}mdb,cn=config

Is this the root of my problem ?

**Comment by bendeg** [comment]
Man oh man, that was the problem !

Issue solved.
