### ISSUE TITLE
[19.04] EXTRACTORAPP - Tracking URL malformed

### ISSUE THREAD

**Issue by bendeg** [georchestra/georchestra#2819]
**[19.04] EXTRACTORAPP - Tracking URL malformed**

**To Reproduce**

(as user "testadmin") Extractor tool works fine : 
I get 2 emails : 1 for pending status and 1 one when done but in that last email the URL is wrong : 

https://georchestra.mydomain.org/null/extractor/package?uuid=06671eed-2e81-4973-9dab-f3f08b0703ee

Looking at old closed issues I can see "null" should be replaced by "extractorapp" : 

https://georchestra.mydomain.org/extractorapp/extractor/package?uuid=06671eed-2e81-4973-9dab-f3f08b0703ee

Which I did manually and, in that case, it works fine and a popup opens to download the zip file.

**Comment by fvanderbiest** [comment]
Is it running on tomcat ?
I have no such issue running extractorapp master currently.

**Comment by fvanderbiest** [comment]
@pmauduit was able to reproduce

**Comment by bendeg** [comment]
@fvanderbiest  I didn't answer your question yet : yes, it is running on Tomcat (version 8)

**Comment by fvanderbiest** [comment]
I thought that tweaking the connectors wrt #3179 would help, but it seems not.

**Comment by fvanderbiest** [comment]
@pmauduit has an interesting point with #2898

**Comment by fvanderbiest** [comment]
Fixed from 20.0.8 on (to be released)
