### ISSUE TITLE
console - renaming a short org name on master leads to a org id change in LDAP

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2855]
Side effects : 
 * the org on CKAN looses its related metadata, which is annoying.
 * geonetwork : to be double checked

**Comment by landryb** [comment]
welcome to my world :)

side effect: the `idgroup` field in the `groupe_autorisation` table in the cadastrapp database needs to be updated too..

**Comment by jeanpommier** [comment]
does this pb concern current version, or only master ? If only master, maybe it would be good to address this before the release ?

**Comment by fvanderbiest** [comment]
> does this pb concern current version, or only master ?

It does not happen on 18.06.
I'm not sure it happens on 19.04 (to be tested)
Master is clearly affected.

**Comment by jeanpommier** [comment]
Where are we with this ? Does renaming the short org name still alter the LDAP id, on master ?

**Comment by landryb** [comment]
it still does and that's imo an expected behaviour as its the key used to name the ldap object (ie its RDN)

**Comment by jeanpommier** [comment]
Yes, in the current state of things, yes. But this leaves us with having to propagate the change on every dependencies (e.g. ckanext-georchestra) without giving them the means to trace the change, since the ID is modified (see our december's discussion above). Shouldn't we address this before the incoming release ?

**Comment by fvanderbiest** [comment]
> Shouldn't we address this before the incoming release ?

I'm not sure we have to address this.
Just warn admins what a short org renaming implies...

**Comment by landryb** [comment]
i have the same problem with nextcloud & geonetwork where ldap sync "sort of but not always" works across org renames, and handcrafted code to workaround such issues.. the short name is used in other places to name folders & generated files, etc, and not changing it anymore upon short name changes would lead to other issues outside of georchestra :)

**Comment by fvanderbiest** [comment]
I think we all agree on the fact that identifiers should never change.

For LDAP Orgs, the identifier is the `cn` field, which the console currently sets to a "cleaned" version of the Org short name (eg `DDAF 80` becomes `ddaf_80`).

If I understand correctly, we have to options to make immutable identifiers here:
 * either we never modify the initially generated `cn`, even when the short name changes,
 * or we initially set the `cn` to some random uuid, and never change it afterwards

Drawbacks :
 * solution 1 might lead to discrepancies between the short name and `cn` which might be weird, eg if the `cn` value is used as identifier in URLs (think CKAN Org pages like https://www.geo2france.fr/ckan/organization/dreal) 
 * solution 2 might lead to difficulties finding Orgs when browsing the LDAP tree

I think solution 2 is to be prefered.

Be warned that this will lead to CKAN Org pages like https://www.geo2france.fr/ckan/organization/d6014656-52f7-11ea-857f-6b3478202c1f rather than https://www.geo2france.fr/ckan/organization/dreal

**Comment by jeanpommier** [comment]
Yep, I believe y'ouve summed it up.
In case of solution 2, you still can search on the shortname field, so it's not such a big deal, I'd say

**Comment by fvanderbiest** [comment]
@landryb told us there's already a `entryUUID` operational attribute which provides a stable identifier as per https://tools.ietf.org/html/rfc4530 
But this adds many constraints on dump/restore operations to keep them unmodified (https://serverfault.com/a/584609) - slapcat becoming mandatory.

**Comment by landryb** [comment]
> But this adds many constraints on dump/restore operations to keep them unmodified (https://serverfault.com/a/584609) - slapcat becoming mandatory.

maybe, but this is the elegant way to do it :)
