### ISSUE TITLE
extractorapp - geoserver privileged user password commented

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2857]
The password is commented out by default in extractorapp.properties:
https://github.com/georchestra/datadir/blob/998fa140647dc0c203c3a147db454ec050d42b41/extractorapp/extractorapp.properties#L55-L57

...which makes our [3 steps editing](https://github.com/georchestra/datadir#3-steps-editing) guide unrelevant

**Comment by fvanderbiest** [comment]
Fixed with https://github.com/georchestra/datadir/commit/54486e4b6e128e34e03256d36125944dc5f7e378

This and geoserver privileged user's name should probably belong to defaults.properties but that's another story

**Comment by landryb** [comment]
that geoserver privileged user has always made me uneasy.. it's in the ldap, and if other services use the ldap that's a potential security issue. Could we make it a geoserver-only user (ie internal to geoserver, not in the ldap) ?

**Comment by fvanderbiest** [comment]
This indeed an option.
