### ISSUE TITLE
SP - secure=true on the cookie breaks non-https setups

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#2858]
One cannot connect anymore to the platform if the endpoint is not secured via https. This is due to the "secure=true" cookie provided by the SP. Removing the following line fixes the issue:

https://github.com/georchestra/georchestra/blob/master/security-proxy/src/main/webapp/WEB-INF/web.xml#L61

**Comment by fvanderbiest** [comment]
I'm not sure we want to support unsecured http nowadays...

**Comment by pmauduit** [comment]
I am still using it for development purposes: it's way more convenient to use regular http than having to create a certificate (either by LE, or a self-signed one), fiddling with java truststores and so on ...

**Comment by RemiDesgrange** [comment]
we could add a `secureCookie` property with default to true ? Not fund of  insecure cookie neither and we should always test in HTTPS but ¯\_(ツ)_/¯
