### ISSUE TITLE
header - link to the GN admin console does not work 

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#2895]
the lang parameter in the header is encoded on 2 characters, geonetwork in v3.8.x expects now the language to be 3 chars long. Hence the following link ends in 404:

https://platform/geonetwork/srv/en/admin.console

it should now be:

https://platform/geonetwork/srv/eng/admin.console

**Comment by fvanderbiest** [comment]
Nice catch, thanks.

**Comment by fvanderbiest** [comment]
Suggestion : in our fork, maintain the redirection `en -> eng`, `fr ->fra`, and so on ?
https://github.com/georchestra/geonetwork/blob/georchestra-gn3.8.2-master/web/src/main/webResources/WEB-INF/urlrewrite.xml
