### ISSUE TITLE
docker images not up to date

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2910]
https://hub.docker.com/r/georchestra/console/tags/ shows they were produced 3 months ago
Can we produce them with github actions ?

**Comment by fvanderbiest** [comment]
7b6f2cb5821a6df99b72ea85ae79c68ce4e14066 for master

**Comment by landryb** [comment]
i didnt ask for it and now i receive more spam from github when i push to branches on my fork complaining about failures as https://github.com/landryb/georchestra/runs/419578555

so fwiw i disabled the actions on my fork, less global warming this way :)
