### ISSUE TITLE
[19.04] CONSOLE - Exception when displaying testadmin profile

### ISSUE THREAD

**Issue by bendeg** [georchestra/georchestra#2927]
Clicking on user name (to the left of "Connexion" in the right upper corner) gives an exception : 

**java.io.IOException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0**

By default, **testadmin** is not a member of any organisation and if we put **testadmin** in an organisation, the exception disappears.

When displaying **testadmin** profile via Administration | Users, there's no issue.

**Comment by fvanderbiest** [comment]
Fixed on master / 20.0 with #2651 
I'm not sure it's easy to backport.
