### ISSUE TITLE
console - userdetails page displays org short name rather than full name

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2935]
On /console/account/userdetails:
![Capture du 2020-02-06 14-55-58](https://user-images.githubusercontent.com/265319/73943376-ed5f0600-48f0-11ea-8b3e-5610f20dfa9c.png)

**Comment by RemiDesgrange** [comment]
This (would) need a major refactor.

In Account class (https://github.com/georchestra/georchestra/blob/7e3fda7c7f7a570f39c065e92e4d38c831963df7/console/src/main/java/org/georchestra/console/dto/Account.java#L135) we are using string all the way. Maybe we could add something to lookup for org when display, but it will be ugly.
