### ISSUE TITLE
SP - improving log traces & HTTP handleRequest logic

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#2948]
When the SP is unable to reach a target (defined in the targets-mapping.properties from the Datadir), we got the following trace in the logs:

```
Exception occured when trying to connect to the remote host
```

Adding some infos about which host  / url is causing isues is not a big deal / trivial:
https://github.com/georchestra/georchestra/blob/master/security-proxy/src/main/java/org/georchestra/security/Proxy.java#L712

We could add the `sUrl` parameter in the log message.

There is another issue with the log trace from the following method:

https://github.com/georchestra/georchestra/blob/master/security-proxy/src/main/java/org/georchestra/security/Proxy.java#L396-L403

It could be either `request.getServerName()` causing the Exception, as well as `InetAddress.getByName(url.getHost())`.

While digging the issues above, I also found out that in case of a DNS resolution error, the Async HTTP client was reporting the error quite fast (some ms), but we still get stuck for 5 minutes at the following statement waiting for an HTTP Request that won't never come:
https://github.com/georchestra/georchestra/blob/master/security-proxy/src/main/java/org/georchestra/security/Proxy.java#L813

**Comment by fvanderbiest** [comment]
Status ?

**Comment by pmauduit** [comment]
I can't remember but I think we can close it
