### ISSUE TITLE
SP - Java11 not more include JAXB libraries

### ISSUE THREAD

**Issue by jusabatier** [georchestra/georchestra#2953]
As version 20.0 of georchestra ain to support JAVA 11/Tomcat 9 packaged in Debian 10, I tested the security-proxy with them.

Security Proxy doesn't start well, and in the logs I have an error : 

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'proxy' defined in ServletContext resource [/WEB-INF/proxy-servlet.xml]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

With some searchs, it appears that it's due to JAVA SE 11 which not more include JAXB libs.

The right solution seems to include them in maven dependencies : 

```
<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.2.11</version>
</dependency>
<dependency>
    <groupId>com.sun.xml.bind</groupId>
    <artifactId>jaxb-core</artifactId>
    <version>2.2.11</version>
</dependency>
<dependency>
    <groupId>com.sun.xml.bind</groupId>
    <artifactId>jaxb-impl</artifactId>
    <version>2.2.11</version>
</dependency>
<dependency>
    <groupId>javax.activation</groupId>
    <artifactId>activation</artifactId>
    <version>1.1.1</version>
</dependency>
```

Source : https://www.journaldunet.fr/web-tech/developpement/1441023-comment-corriger-l-erreur-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception/

**Comment by RemiDesgrange** [comment]
Could you do a PR with a change in the  `pom.xml` ? And maybe doc.

**Comment by landryb** [comment]
pretty sure many ppl wont look at the docs and try running it with the default java present in buster, so would be good to at least have the basic blocks running...
