### ISSUE TITLE
console - npm build error on github actions

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2955]
Witnessed on https://github.com/georchestra/georchestra/runs/443501618?check_suite_focus=true
```
[INFO] compiling app/components/roles/roles.tpl.html
[INFO] compiling app/components/stats/stats.tpl.html
[INFO] compiling app/components/users/users.tpl.html
[INFO] compiling app/components/user/user.tpl.html
[INFO] 12:27:26 - info: compiling
[INFO] 12:27:26 - info: compiled 79 files into 6 files, copied 13 in 4.1 sec
[WARNING] npm WARN manager@0.0.1 No license field.
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[ERROR] 
```
![Capture du 2020-02-13 13-29-50](https://user-images.githubusercontent.com/265319/74435540-ef7f1280-4e64-11ea-8633-4ffb4cfb117a.png)

**Comment by RemiDesgrange** [comment]
It's "normal" :sweat_smile:

**Comment by pmauduit** [comment]
yes, the frontend-maven-plugin does this since ages, that is not the first time we encounter it in the logs, and I think we can ignore it.

I thought it was an error in the plugin, but relying on https://github.com/eirslett/frontend-maven-plugin/issues/411 "it has to be fixed in npm" Oo

**Comment by fvanderbiest** [comment]
Thanks Pierre

**Comment by qixiaobo** [comment]
> It's "normal" 😅

Sorry to hear this……
But I use 1.8.0 version , it works fine
![image](https://user-images.githubusercontent.com/2881751/76589520-4db31a00-6525-11ea-938f-12193c5f5fba.png)
