### ISSUE TITLE
[Header] - Special characters display incorrectly with OpenJDK 11

### ISSUE THREAD

**Issue by jusabatier** [georchestra/georchestra#2965]
Since Java9, properties files are read as UTF8, before they were read as ISO-8859-1.

So in the 20.x version which target Java11, all accents display incorrectly : d�connexion

The best solution seems to adapt this line : https://github.com/georchestra/georchestra/blob/20.0.x/header/src/main/java/org/georchestra/_header/Utf8ResourceBundle.java#L78

Another temporary one is to add : 
-Djava.util.PropertyResourceBundle.encoding=ISO-8859-1
in JAVA_OPTS

Source : https://community.microstrategy.com/s/article/Special-characters-display-incorrectly-with-OpenJDK-11?language=en_US

**Comment by landryb** [comment]
what if ppl still use java8? we consider it's unsupported ?

**Comment by jusabatier** [comment]
Tested with : 
https://github.com/georchestra/georchestra/pull/2966/commits/6266b728c3758c620ac9a81a43fe74d137fe35e9

And it works well with JAVA 8 and JAVA 11.

**Comment by fvanderbiest** [comment]
Do you currently run geOrchestra OpenJDK 11 in production ? I'd be interested by your feedback

**Comment by jusabatier** [comment]
Not in production yet, some modules of Georchestra doesn't support JAVA11.

Actually appear to work : 

- Security Proxy
- Header
- GeoServer
- Mapfishapp

Actually not work : 

- GeoNetwork, have a pending pull request to make it work : https://github.com/geonetwork/core-geonetwork/pull/4488

Actually not tested yet : 

- GeoWebCache
- Extractor
- Cadastrapp
- Atlas
- Analytics
- Console

**Comment by fvanderbiest** [comment]
> * GeoServer

Actually, Gabriel had issues running it with Java 11 - recommended to stick to Java 8 until further notice

**Comment by jusabatier** [comment]
Any link to the issue ?
I use it and actually not have any problems.

**Comment by fvanderbiest** [comment]
Issues with shapefile stores IIRC. ping @groldan
