### ISSUE TITLE
version numbering - which strategy for submodules ?

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#2970]
If I look in the geonetwork fork, I can see:

* a branch corresponding to the georchestra "20.0.x" branch (georchestra-gn3.8.2-20.0)
* a tag for 20.0.0 (which should match the 20.0.0 georchestra tag)

But there is no tag for the 20.0.1 version of georchestra. Is it missing ? I'd expect it to point onto the commit https://github.com/georchestra/geonetwork/tree/f798cfd92cfb4802b0a50cb7bafbbc0b93b38ba7

**Comment by fvanderbiest** [comment]
> But there is no tag for the 20.0.1 version of georchestra. Is it missing ?

Yes.

**Comment by fvanderbiest** [comment]
Glad to see you fixed it :-)
