### ISSUE TITLE
[console] import csv area doesnt work ?

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2971]
feature added in #2100, just tested now on 19.04 & 20.0, trying to upload a csv on the org area tab in ffx 74.0beta yields nothing in js console nor in network console nor on the visual map, features are not highlighted nor added to the list. @tonio @fvanderbiest works for you ?

**Comment by landryb** [comment]
after testing a bit more, its broken if the csv comes from windows/office and has windows-style line endings, it works if you force it to have unix-style line endings (via, say notepad++) - so i think there's a genuine bug as users might use the feature exporting a csv from excel. the code should handle both ?

**Comment by landryb** [comment]
from my understanding the split here: https://github.com/georchestra/georchestra/blob/master/console/src/main/webapp/manager/app/components/area/area.es6#L255

should also handle `\r\n` ?

**Comment by RemiDesgrange** [comment]
We should maybe use a lib that does all the heavy lifting for us :-/

**Comment by landryb** [comment]
leftpad ? ;)

**Comment by fvanderbiest** [comment]
> from my understanding the split here: https://github.com/georchestra/georchestra/blob/master/console/src/main/webapp/manager/app/components/area/area.es6#L255
> 
> should also handle `\r\n` ?

ping @tonio
