### ISSUE TITLE
GeoNetwork on 20.0 - editor fails to load 

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2977]
Checked on the public docker composition with 3.8.3
```
Error: Syntax error, unrecognized expression: �����������}�r�8��������M�ʊ�e9��݌��x&_�;�s�ԩ�EA�7��%);�ɜg��q��<���H������%9bU���Gw�ht7���&�
�&?4fN�N���������P���w���A�y��L������k7�����?N]o�i�k��XP|���k��4�2h�s��i�C���+h�,h0w���wW׍�M�8�a[�#�fҿ��`�͹�Y�F�m�����cܜЩ�������6���'��/�~h�&������7CؿKን҅�U���biS�ޝNcr!�,g�
```
![Capture du 2020-03-04 09-51-26](https://user-images.githubusercontent.com/265319/75861512-ce736700-5dfd-11ea-9b0a-7ab1fafaac75.png)

**Comment by RemiDesgrange** [comment]
gzip not announced as gzip? :thinking:

**Comment by landryb** [comment]
interesting, issue with apache config wrt mod_gzip then ?

**Comment by fvanderbiest** [comment]
no apache involved in the docker composition, it's a `traefik` instance

**Comment by RemiDesgrange** [comment]
It's this request that causes problem `https://georchestra.mydomain.org/geonetwork/srv/api/records/137/editor?currTab=default&starteditingsession=yes&_random=1486`
It return gzip encoded, but requested encoding is json or plain text.

**Comment by fvanderbiest** [comment]
@cmangeat do you see what happens here on GN side ?
