### ISSUE TITLE
trouble with gn 3.8, switching from simple view to full view

### ISSUE THREAD

**Issue by cmangeat** [georchestra/georchestra#2995]
![trouble_gn_3_8](https://user-images.githubusercontent.com/18677090/76745551-59494f80-6776-11ea-92a3-488266178d1c.png)

**Comment by fvanderbiest** [comment]
What happens exactly when switching ?

**Comment by cmangeat** [comment]
![srv](https://user-images.githubusercontent.com/18677090/77118649-0650f000-6a35-11ea-8174-16d6f5a7d60a.png)
![reinit](https://user-images.githubusercontent.com/18677090/77118657-094be080-6a35-11ea-9fef-407d5536d07b.png)

Reinit json config from admin interface seems to do the job.
