### ISSUE TITLE
impossible to add a new record (GeoNetwork) : error 403

### ISSUE THREAD

**Issue by alexis55200** [georchestra/georchestra#3008]
Good morning, everyone,

I am currently working on a PHP application able to publish metadata sheets and layers on a GeoNetwork + Geoserver (GeOrchestra package).
I'm encountering a problem, following an upgrade of GeoNetwork (3.8.1), I'm no longer able to publish a new metadata sheet via the API.
I tested the new webservices of swagger API (/geonetwork/doc/api/index.html) : " /geonetwork/srv/api/0.1/records? "(POST)
As well as the old webservice: "/geonetwork/srv/eng/xml.metadata.insert?". (POST)
Obective: publish a metadata sheet from an .xml file.

However, I always get a 403 error (access denied). However the user I use for authentication has all the rights on the GeoNetwork (administrator, editor, etc...).

The error message :
`<!DOCTYPE html>

<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Access denied</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='/_static/bootstrap_3.0.0/css/bootstrap.min.css' rel="stylesheet" />
</head>

<body>
    <c:choose>
        <c:when test='true'>
            <div id="go_head">
                <iframe src="" style="width:100%;height:px;border:none;overflow:none;" scrolling="no"></iframe>
            </div>
        </c:when>
    </c:choose>
    <div class="container">
        <div class="page-header">
            <h1>Access denied</h1>
        </div>
        <p class="lead">Sorry, you can't access this page.p>
    </div>
</body>

</html>
`
Do you have any ideas?

Have a nice day,

Alexis MESSANT

**Comment by fvanderbiest** [comment]
This issue found a solution with the https://groups.google.com/d/msg/georchestra-dev/YNRQD9pa530/4hGymTsfBAAJ thread
