### ISSUE TITLE
SP - dead code on custom Spring-Security-CAS related classes

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#3017]
grepping the class names from the package `org.georchestra.security.workaround` does not show any relevant usage in the SP at runtime.

Looking at the code, I'm not sure they can be of any use but I might be wrong. From my memories of the project they meant to emulate a behaviour not implemented in the CAS client from Spring-Security (the gateway mode).

Maybe we can get rid of them now ?

**Comment by RemiDesgrange** [comment]
I'll get rid of it in a branch and test (U, IT and live) if it's working.
