### ISSUE TITLE
docker - postgres 12

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3018]
See https://github.com/georchestra/georchestra/blob/master/postgresql/Dockerfile#L5

Caution, this latest release already broke several applications elsewhere !
https://www.postgresql.org/docs/12/release-12.html

**Comment by RemiDesgrange** [comment]
With postgres 12 we will install postgis3. Postgis comes with **no support for raster** in order to have raster support, we need to install postgis3_raster. The question is : do we want it in this image? My opinion is yes.

**Comment by fvanderbiest** [comment]
> do we want it in this image? My opinion is yes.

Why not, it's a nice to have. 
But we're not making use of it in the core.

**Comment by pmauduit** [comment]
One first thing playing with PostGreSQL 12 (but I think previous versions are also affected):

https://github.com/georchestra/georchestra/blob/master/postgresql/fix-owner.sql#L9-L13

I can't get why we need to iterate over and generate several queries to change the schema ownership. Why not just a "ALTER SCHEMA ... OWNER TO ..." ?

Also the function won't work on an empty (e.g. with no table) schema. As a result, the schema "atlas" coming empty, the "SELECT change_owner()" call on it won't work.

**Comment by RemiDesgrange** [comment]
Maybe we should use [this](https://www.postgresql.org/docs/8.2/sql-reassign-owned.html) ?

**Comment by fvanderbiest** [comment]
see #3019
