### ISSUE TITLE
[geonetwork packaging] checkout the corresponding datadir branch when packaging a branch

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#3029]
other wapps have it (cf https://github.com/georchestra/georchestra/blob/master/header/pom.xml#L111), but i think geonetwork lacks the `scmVersion` lines in the maven-scm-plugin config:
```
              <scmVersion>${packageDatadirScmVersion}</scmVersion>
              <scmVersionType>branch</scmVersionType>
```
 in https://github.com/georchestra/geonetwork/blob/georchestra-gn3.8.2-20.0/web/pom.xml#L1059, ie if you build a geonetwork debian package from the 20.0 or 19.04 georchestra branch the datadir files bundled with the package will be from the master branch of the datadir repo, and you might get a broken geonetwork.

Of course packageDatadirScmVersion doesnt exist in geonetwork so i dunno if it should percolate from the parent dir... but as i repeatedly said i aint no maven expert, @pmauduit is !

I know, nobody cares about debian packages :)

**Comment by fvanderbiest** [comment]
Good catch Landry !

**Comment by fvanderbiest** [comment]
See https://github.com/georchestra/geonetwork/commit/f6d2f7fa533d02165446aba461d1a06405db9c8d

**Comment by fvanderbiest** [comment]
There's too much complexity handling two branches `georchestra-gn3.8.2-20.0` and `georchestra-gn3.8.2-master` in the `georchestra/geonetwork` repository, compared with what it brings.

Decided to merge both into `georchestra-gn3.8.2` which will be submoduled from `georchestra/georchestra`'s `20.0.x` and `master` branches, as long as master is not upgraded to some [other version](https://github.com/geonetwork/core-geonetwork/releases).

**Comment by fvanderbiest** [comment]
geOrchestra's future releases in the `20.0.x` branch will be able to use bugfix releases from the `3.8.x` branch as well.

If we upgrade GeoNetwork version (like if we decide to go for `2.10.x`), this should happen on `master`, targetting a future major release like `20.1.x`
