### ISSUE TITLE
Do we still need PATCHES.md

### ISSUE THREAD

**Issue by RemiDesgrange** [georchestra/georchestra#3044]
Is https://github.com/georchestra/georchestra/blob/master/PATCHES.md still needed ? As Dependabot take care of updating libs and submodules.

**Comment by fvanderbiest** [comment]
Oh my god.
Yes, I think it can safely be removed from master now !

**Comment by fvanderbiest** [comment]
b461401af59c4e8d12cad12e7389faed9f6a17c3
