### ISSUE TITLE
[build] remove repo.boundlessgeo.com from pom.xml in all branches ?

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#3061]
i dont think its going to come back, we still have some occurences:
https://github.com/georchestra/georchestra/search?q=repo.boundlessgeo.com&unscoped_q=repo.boundlessgeo.com
and it fails some builds.

encountered while tryingto build gs-authkey on 19.04... had to replace it by packages.georchestra.org in geoserver-submodule/src/pom.xml.

**Comment by fvanderbiest** [comment]
Good catch !
Could you provide a PR ?

**Comment by landryb** [comment]
well im not sure if it should be replaced by packages.geor.org or by the osgeo repo (or smth else?), as @pmauduit told me that packages.geor is proxying them and its config will also need fixing, and i dont want to provide him more work :)

**Comment by landryb** [comment]
cf #3065

**Comment by landryb** [comment]
maybe we could use http://maven.geo-solutions.it as a new upstream for geoserver jars ?

**Comment by pmauduit** [comment]
> maybe we could use http://maven.geo-solutions.it as a new upstream for geoserver jars ?

I'd expect the GS artifacts to be present on the osgeo nexus already, what would be the added value of using GeoSolutions' one ?

**Comment by landryb** [comment]
dunno, i wasnt aware of the osgeo nexus at the time, and all this stuff is cloud voodoo to me :)
