### ISSUE TITLE
mapfishapp - server generates invalid SLD v1

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3072]
Upgrading server-side libs has somehow broken layer classification.

Here's what happens : the SLD is generated, but instead of the expected ...
```xml
<WellKnownName>circle</WellKnownName>  
```
...the client gets the following:
```xml
<sld:WellKnownName>
    <ogc:PropertyName>circle</ogc:PropertyName>
</sld:WellKnownName>
``` 
... which cannot be parsed by OpenLayers' [SLD v1 format](https://github.com/openlayers/ol2/blob/e85a087c8fb857648aa7c5e4f771d1d2a13fc48b/lib/OpenLayers/Format/SLD/v1.js#L478-L480).

As a result, the graphicName is blank, and GeoExt explodes when trying to generate a thumbnail for the rule.

**Comment by fvanderbiest** [comment]
GeoTools' StyleBuilder invoked in  https://github.com/georchestra/georchestra/blob/50dafb77cf183d6815e76f1a43d716c47351bdc5/mapfishapp/src/main/java/org/georchestra/mapfishapp/ws/classif/PointSymbolizerFactory.java#L72

**Comment by groldan** [comment]
like you need to replace
```
_styleBuilder.createMark(_styleBuilder.attributeExpression(_knownSymbol),
                    _styleBuilder.createFill(_color, _opacity), // color, opacity
                    null);
```
by
```
_styleBuilder.createMark(_knownSymbol,
                    _styleBuilder.createFill(_color, _opacity), // color, opacity
                    null);
```
Looks lik the encoder is doing exactly what it's been instructed to, and it used to work by accident before?

**Comment by groldan** [comment]
The style buildder will do this in the first case:
```
    public Mark createMark(Expression wellKnownName, Fill fill, Stroke stroke) {
        Mark mark = sf.createMark();
        mark.setWellKnownName(wellKnownName);
       ....
```

And this in the second case:
```
    public Mark createMark(String wellKnownName, Color fillColor) {
        Mark mark = sf.createMark();
        mark.setWellKnownName(literalExpression(wellKnownName));
       ...
```
Note if given a string instead of a `PropertyName` expression, then the literal should be encoded as expected
