### ISSUE TITLE
mapfishapp - test failures

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3080]
There are test failures:
```
[ERROR] Failures: 
1879
[ERROR]   GeotoolsFeatureReaderTest.testGMLCoordinatesTransformToEPSG2154:246->assertCoordinatedOrder:286 expected:<310725.6202480312> but was:<7279519.55852178>
1880
[ERROR]   GeotoolsFeatureReaderTest.testGMLCoordinatesTransformToEPSG3857:224->assertCoordinatedOrder:286 expected:<-252175.4516143718> but was:<5390249.467066344>
1881
[ERROR]   UpLoadFileManagementGTImplTest.testGMLCoordinatesFrom4326to3857:228->assertCoordinateContains:252 expected:<-252175.4516143718> but was:<5390249.467066344>
1882
[ERROR]   UpLoadFileManagementGTImplTest.testKMLCoordinatesEPSG4326:180->assertCoordinateContains:252 expected:<-2.265330624649336> but was:<48.42143481482802>
1883
[ERROR]   UpLoadFileManagementGTImplTest.testSHPCoordinatesEPSG4326:78->assertCoordinateContains:252 expected:<-2.265330624649336> but was:<48.421434814828025>
```

Are we missing the `org.geotools.referencing.forceXY` option ?

See https://github.com/georchestra/georchestra/runs/757142548?check_suite_focus=true
(In addition, one can see we're using the IT profile which does not exist)

**Comment by RemiDesgrange** [comment]
Tests are running fine one my machine.

https://github.com/georchestra/georchestra/blob/39e7175bc4717e41769de2c3675d952cc32d108d/mapfishapp/src/test/java/org/georchestra/mapfishapp/ws/upload/GeotoolsFeatureReaderTest.java#L45 here we can see that even if `forceXY` is not set the test forces it.

**Comment by RemiDesgrange** [comment]
fixed by https://github.com/georchestra/georchestra/pull/3082
