### ISSUE TITLE
mapfishapp - upload geojson, bug in tmp folder

### ISSUE THREAD

**Issue by RemiDesgrange** [georchestra/georchestra#3083]
Currently, in mapfishapp, upload of a GeoJSON file is managed by `UpLoadGeoFileController` class.

There is two temporary directories. `tempDirectory` and `docTempDir`. `tempDirectory` cannot be overridden (see https://github.com/georchestra/georchestra/blob/5e1779997d30a21a2a1c8090354e3b1b051b0fcb/mapfishapp/src/main/webapp/WEB-INF/ws-servlet.xml#L46). 

There is a difference in behavior between [init method](https://github.com/georchestra/georchestra/blob/39e7175bc4717e41769de2c3675d952cc32d108d/mapfishapp/src/main/java/org/georchestra/mapfishapp/ws/UpLoadGeoFileController.java#L146) and [makeDirectoryRequest](https://github.com/georchestra/georchestra/blob/39e7175bc4717e41769de2c3675d952cc32d108d/mapfishapp/src/main/java/org/georchestra/mapfishapp/ws/UpLoadGeoFileController.java#L750). There are also hardcoded reference to `/geoFileUploadsCache`. 
As a consequence, every GeoJSON uploaded files are saved to `/geoFileUploadsCache`. This behavior breaks the docker image of mapfishapp.

* We should clarify behavior
* Fix divergent behavior in this class.

**Comment by fvanderbiest** [comment]
Can you also explain the primary reason why we're working on it ?
