### ISSUE TITLE
OSM lacking attribution in code

### ISSUE THREAD

**Issue by flacombe** [georchestra/georchestra#3090]
Hi

I think following line :
https://github.com/georchestra/georchestra/blob/022038fcc24cb75d0e82ebd25166473fdd26a668/console/src/main/webapp/manager/app/components/area/area.es6#L60

is not valid regarding OSM attribution policy.
https://www.openstreetmap.org/copyright

Do you guys really intend to use this work without credit?

All the best

**Comment by fvanderbiest** [comment]
Thanks for chiming in @flacombe, we're dealing with this issue asap, see eg abefe5b56e1008a63d47bc1fab5496bb3e18ef1c
geOrchestra is free software and loves free/open data. Be assured we fully support the OSM community as much as possible, see eg https://www.georchestra.org/blog/2010/10/01/openstreetmap-et-ids/

**Comment by fvanderbiest** [comment]
In addition, it seems our code currently displays an attribution, see https://github.com/georchestra/georchestra/blob/master/console/src/main/webapp/manager/app/components/area/area.tpl.html#L5-L7 and the screenshot below.
It's just that our developers chose to customize it, hence the `{ attributions: null }` object.

![Capture du 2020-06-24 08-53-31](https://user-images.githubusercontent.com/265319/86111832-84f30a00-bac7-11ea-84c5-36f28c7b1a29.png)
