### ISSUE TITLE
georchestra/ldap:20.0.x not updated as frequently as expected

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3096]
See https://hub.docker.com/r/georchestra/ldap/tags/ compared to 
https://hub.docker.com/r/georchestra/mapfishapp/tags/

**Comment by fvanderbiest** [comment]
Same issue with https://hub.docker.com/r/georchestra/database/tags/

**Comment by fvanderbiest** [comment]
Would be nice if you could have a look @RemiDesgrange

**Comment by RemiDesgrange** [comment]
This is quite normal. We do not modify the `/postgresql` folder nor the `/ldap` one or the `mapfishapp` one. The workflow is not even played.

Maybe we should create a new workflow specifically for releases.

**Comment by RemiDesgrange** [comment]
This is "normal". We are looking at 3 events :

* pull requests
* push
* releases

For the first two we are launching the workflow _only_ if a specific path has been modified (`/postgresql`, `mapfishapp` etc..). So if the 20.0 branch has been modified (pushed) then we trigger a build _only_ if  the specific path has been modified. So no problem here. For example the 20.0.5 PostgreSQL image is _exactly_ the same as the one generated 6 months before (20.0.x) there is just a difference in tag.

**Comment by fvanderbiest** [comment]
Cool, indeed ! 
Thanks for the investigation.
