### ISSUE TITLE
Mapstore-related roles are missing

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3112]
By default, MapStore roles should be provided by the LDAP docker image

**Comment by fvanderbiest** [comment]
@landryb `MAPSTORE_ADMIN` ... are there any other roles ?

**Comment by landryb** [comment]
not to my knowledge, at least in the default setup according to https://github.com/georchestra/mapstore2-georchestra/blob/master/docs/source/security/index.rst#authentication-filter
