### ISSUE TITLE
Docker hub container image retention policy

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3120]
"Docker is introducing a container image retention policy which will be enforced starting November 1, 2020. The container image retention policy will apply to the following plans:
 * Free plans will have a 6 month image retention limit
 * Pro and Team plans will have unlimited image retention"

Which basically means that users running an older geOrchestra version won't be able to pull images anymore, unless they upgrade. This can be annoying in case of failure recovery...

**Comment by fvanderbiest** [comment]
Time to switch to github package repository ? 
I'm not sure their terms are more interesting... https://github.com/features/packages

**Comment by RemiDesgrange** [comment]
For me it's not really an issue. You can still build yourself from the source. And it's not event "that hard" (`make docker-build`).

**Comment by fvanderbiest** [comment]
Not a single pull in 6 months, ok, I'm fine with it !
Thanks

**Comment by RemiDesgrange** [comment]
We could have a github action schedule that pull all the images on docker hub related to georchestra. Ugly but working :sweat_smile:
