### ISSUE TITLE
[DOC] Document JAVA 11 Compatibility

### ISSUE THREAD

**Issue by jusabatier** [georchestra/georchestra#3130]
Actually a part of Georchestra's modules support JAVA 11, but some still not support it and need to run on JAVA 8.

In the doc, we have : 

> geOrchestra 20.0.x has been tested with tomcat 9 on Debian 10 (Buster). This is the recommended setup as of today.

But in reality, if we install a fresh buster with tomcat9, JAVA 11 is installed by default, and some apps still not support it.
Maybe it can be usefull to provide a table that inform the compatible and uncompatible apps, and inform that it can be necessary to install JAVA 8 for some.

**Comment by landryb** [comment]
totally agree - iirc mostly geonetwork requires java8 (the java11 support/full compat was one of the things planned for GN4 iirc), i think geoserver is java11 compatible per https://docs.geoserver.org/latest/en/user/production/java.html, havent tested the other bits.

**Comment by fvanderbiest** [comment]
:+1:

**Comment by RemiDesgrange** [comment]
@landryb the [kartoza geoserver image](https://hub.docker.com/r/kartoza/geoserver) use java11

**Comment by pmauduit** [comment]
We are also using Java11 on GeoServer on one c2c project, and for now it required to update the commons-lang3 dependency in the georchestra root pom (and making sure that the icu4j jar was not in the classpath, see #3121). I did not have the time to do a PR yet.

**Comment by jusabatier** [comment]
Here is what I have found : 

Application | Support
-|-
Analytics | JAVA 8 -> OK, JAVA 11 -> ?
Atlas | JAVA 8 -> OK, JAVA 11 -> ?
CAS | JAVA 8
Console | JAVA 8 -> OK, JAVA 11 -> ?
ExtractorApp | JAVA 8 -> OK, JAVA 11 -> ?
GeoNetwork | Actually JAVA 8, but some work in progress for JAVA 11 support in next version ?
GeoServer | Actually JAVA 8, but future 2.17 version is supposed to support JAVA 11
GeoWebCache | JAVA 8 -> OK, JAVA 11 -> ?
Header | JAVA 11
Mapfishapp | JAVA 8 -> OK, JAVA 11 -> ?
Security Proxy | JAVA 11

To complete when you have the opportunity to test

**Comment by RemiDesgrange** [comment]
@jusabatier you may want to remove "actually". I don't think it mean what you think it means.

**Comment by pmauduit** [comment]
Console does not work with Java11 yet (when compiled with java8):

```
17-Feb-2022 10:52:30.217 SEVERE [http-nio-8280-exec-4] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [console]
	java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
```
It works back when injecting https://repo1.maven.org/maven2/javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar into its classpath

**Comment by fvanderbiest** [comment]
We should grep for java8 on the repo, yes.
eg https://github.com/georchestra/georchestra/blob/master/docs/setup.md
