### ISSUE TITLE
[geoserver] headerHeight & headerUrl still hardcoded in 2.16 & master

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#3134]
cf https://github.com/georchestra/geoserver/blob/2.16.1-georchestra/src/web/core/src/main/java/org/geoserver/web/GeoServerBasePage.html#L32 - similar to #2422 & #2423 but unsure if those two are still valid issues.

**Comment by fvanderbiest** [comment]
Oh yes ... unfortunately.
Patches welcome.

**Comment by landryb** [comment]
as its not jsp, i have no idea whats required to make this dynamic, so few chances of simple patches from external contributors ;)

**Comment by landryb** [comment]
looking at git history, i think ab98b34c3c was lost in the update to 2.16.x ?

**Comment by landryb** [comment]
And it should probably be put on top of #3070 cc @pmauduit  :)

**Comment by pmauduit** [comment]
GS 2.17.2 merged, closing.
