### ISSUE TITLE
console - the "change password" page should not require a UID parameter

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3138]
Currently the "change password" page is accessible at `/console/account/changePassword?uid=fvanderbiest`.
Without the `uid` parameter, one gets "Required String parameter 'uid' is not present"
Instead, `uid` should be obtained from the security-proxy-provided `sec-username` header.

This paves the way for https://web.dev/change-password-url/ ...

**Comment by pmauduit** [comment]
or even better via the spring security context (which basically does the same thing, actually):
https://github.com/georchestra/georchestra/blob/f879c98a3b535a5ce071a6327aec2f8f369856f1/console/src/main/java/org/georchestra/console/ws/backoffice/users/UsersExport.java#L72
