### ISSUE TITLE
GeoServer - specify submodule's version in docker image

### ISSUE THREAD

**Issue by jeanpommier** [georchestra/georchestra#3143]
geOrchestra 20.x docker images  are designed to be overridden, when someone wants to add specific features, instaed of rebuilding it from the source code. 
For instance, when addind extensions to the geoserver instance, the best practice is supposedly to start FROM the georchestra/geoserver image and create an override Dockerfile above it.
For this, it would be nice to know straight away the version of the geoserver instance (needed to retrieve the extensions).
A simple way would probably be to set an environment variable with the geoserver version number, in the georchestra/geoserver image

**Comment by fvanderbiest** [comment]
Agreed !
