### ISSUE TITLE
console - the "delete my account" button does not work

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#3181]
Nothing happens when I click on the "delete my account" button in my user details page from the console:

![Screenshot from 2020-10-15 16-49-26](https://user-images.githubusercontent.com/594335/96146446-95a87e00-0f06-11eb-9226-7ac36506a0a5.png)

No request is made from the browser, and I cannot see any error in the JS console either.

**Comment by fvanderbiest** [comment]
I guess it was witnessed on master at that time, and now this is a bug in 20.1.0 (and probably on 20.0.6 too).
To be double checked...

**Comment by fvanderbiest** [comment]
Was fixed on 20.1.x and master.
Shipped with future 20.1.1 release
