### ISSUE TITLE
[Console] Remove objectClass other than geOrchestra's ones

### ISSUE THREAD

**Issue by jusabatier** [georchestra/georchestra#3185]
When I use console for editing a user, it reset LDAP's objectClass to the ones needed by geOrchestra.

The big problem is that geOrchestra isn't the only application which uses the LDAP, 
and objects can have other classes than the geOrchestra's ones which are needed for other apps.

I think this point a huge problem and need to be corrected ASAP because it doesn't allow geOrchestra to share the LDAP with other apps without risks of breaking them.

**Comment by jusabatier** [comment]
For example, I use an objectClasse "activeDirectoryUser" on users to identify the ones who are retrieved from our ActiveDirectory, and allow to synchrinze them periodicaly.

**Comment by landryb** [comment]
oh nice catch - indeed that's a problem...

**Comment by fvanderbiest** [comment]
Agreed, very annoying.
