### ISSUE TITLE
Revisit default GeoServer extensions shipped with the releases

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3219]
The Makefile currently builds GeoServer with the following extensions:
```
GEOSERVER_EXTENSION_PROFILES=colormap,mbtiles,wps-download,app-schema,control-flow,csw,feature-pregeneralized,importer,inspire,libjpeg-turbo,monitor,pyramid,wps,css,s3-geotiff,jp2k,authkey,mapstore2
```
Some of them should probably be removed (importer, feature-pregeneralized ?) and others added: 
 * MBStyle
 * OGC API
 * SLDService
 * Resource browser
 * FlatGeoBuf

**Comment by landryb** [comment]
+1 for resource browser, can definitely be useful for ftl uploads

**Comment by jeanpommier** [comment]
FYI, @landryb , I had written an extension to edit ftl templates directly in the UI. It never made it to comunity extensions, but I can refresh it if you're interested

**Comment by pmauduit** [comment]
* [ ] MBStyle
* [ ] OGC API
* [ ] SLDService
* [ ] Resource browser
* [ ]FlatGeoBuf
