### ISSUE TITLE
Link to RELEASE_NOTES.md is broken on documentation page

### ISSUE THREAD

**Issue by gryckelynck** [georchestra/georchestra#3234]
I would like to check the release notes but link on documentation page is broken (for 20.0.x, 20.1.x and master):
Documentation page link: https://github.com/georchestra/georchestra/blob/20.1.x/docs/index.md
Release notes link: https://github.com/georchestra/georchestra/blob/master/RELEASE_NOTES.md (broken)

**Comment by fvanderbiest** [comment]
Thanks for the notice Guillaume.
I'll fix it. The new link is https://github.com/georchestra/georchestra/releases

**Comment by fvanderbiest** [comment]
Now fixed in the 3 supported branches
