### ISSUE TITLE
[console] Impossible to create a new Organisation

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/georchestra#3247]
Hello.

Reported twice on our current portal in 20.x : I cannot create a new organism because the UI checks do not let me do that.

The short name field stay always in red and the "Save" button remains unactivated.
No console message. Nothing apperas on the UI.

![capture_028](https://user-images.githubusercontent.com/6370443/104597237-5d374e00-5675-11eb-9860-bd55e2db4233.png)

**Comment by RemiDesgrange** [comment]
Can you also post the result of what happened in your dev tools (if the backend respond 500) or error in the console ? Thx.

**Comment by fvanderbiest** [comment]
I can confirm this works on 20.0.3, and is broken on 20.0.4, 20.1.0 and later releases
What happened in between ? https://github.com/georchestra/georchestra/milestone/21?closed=1

@RemiDesgrange seems like a client-side issue only.

**Comment by jusabatier** [comment]
Here is the problem : https://github.com/georchestra/georchestra/blob/20.1.x/console/src/main/webapp/manager/app/app.es6#L174

Lowercase isn't allowed for shortName.

**Comment by fvanderbiest** [comment]
Ok, the regression comes from #2897 then ...

**Comment by landryb** [comment]
as long as only alphanumeric chars and underscore/dash is allowed for shortName..
