### ISSUE TITLE
GeoServer submodule & update policy

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3253]
We now depend on dependabot (!) to update our submodules.
Dependabot periodically checks for updates on the remote branches which are targeted by the `.gitmodules` file at the repository root.

eg:
```
[submodule "geoserver/geoserver-submodule"]
	path = geoserver/geoserver-submodule
	url = https://github.com/georchestra/geoserver.git
	branch = 2.16.5-georchestra
```

In order to ease the maintenance tasks and geoserver upgrades, I would find it convenient to have a stable geOrchestra branch pointing at another stable geoserver branch, rather than a "patch release".

Eg: I would currently expect:
 * branch `20.0` to target https://github.com/georchestra/geoserver.git @ `2.16.x-georchestra` rather than `2.16.5-georchestra`
 * branch `20.1` to target https://github.com/georchestra/geoserver.git @ `2.17.x-georchestra` rather than `2.17.4-georchestra`
 * branch `master` to target https://github.com/georchestra/geoserver.git @ `2.17.x-georchestra` rather than `2.17.4-georchestra`

**Comment by jeanpommier** [comment]
Sounds reasonable. +1

**Comment by fvanderbiest** [comment]
Branch 2.17.x created with https://github.com/georchestra/geoserver/pull/22 - should be targeted by 20.0.x for 20.0.7 and 20.1.x for 20.1.1

**Comment by fvanderbiest** [comment]
Tried forking 2.17.x from upstream's 2.17.x but this does not work as expected - dependencies upstream are -SNAPSHOT 
falling back to 2.17.5-georchestra.
