### ISSUE TITLE
[Extractorapp] Problem with wfs layer

### ISSUE THREAD

**Issue by jusabatier** [georchestra/georchestra#3266]
I'm getting an error trying extract WFS Layer via Extractorapp : 

> 2021-01-27 16:34:32 task [INFO] Attempt 1 for extracting layer: https://geoportail.lepuyenvelay.fr/geoserver/wfs? -- referentiels:communes
> 2021-01-27 16:34:32 extractor [DEBUG] WfsExtractor.checkPermission - Secured Server: adding username header and role headers to request for checkPermission
> 2021-01-27 16:34:33 extractor [DEBUG] WfsExtractor.extract - Secured Server: Adding extractionUserName to connection params
> 2021-01-27 16:34:34 extractor [DEBUG] Number of features returned : 4
> 2021-01-27 16:34:34 task [INFO] Attempt 2 for extracting layer: https://geoportail.lepuyenvelay.fr/geoserver/wfs? -- referentiels:communes
> 2021-01-27 16:34:34 extractor [DEBUG] WfsExtractor.checkPermission - Secured Server: adding username header and role headers to request for checkPermission
> 2021-01-27 16:34:35 extractor [DEBUG] WfsExtractor.extract - Secured Server: Adding extractionUserName to connection params
> 2021-01-27 16:34:36 extractor [DEBUG] Number of features returned : 4
> 2021-01-27 16:34:36 task [INFO] Attempt 3 for extracting layer: https://geoportail.lepuyenvelay.fr/geoserver/wfs? -- referentiels:communes
> 2021-01-27 16:34:36 extractor [DEBUG] WfsExtractor.checkPermission - Secured Server: adding username header and role headers to request for checkPermission
> 2021-01-27 16:34:37 extractor [DEBUG] WfsExtractor.extract - Secured Server: Adding extractionUserName to connection params
> 2021-01-27 16:34:37 extractor [DEBUG] Number of features returned : 4
> 2021-01-27 16:34:38 task [ERROR] Exception occurred while extracting data
> java.lang.RuntimeException: java.lang.IllegalArgumentException: No such attribute:geom
>         at org.georchestra.extractorapp.ws.extractor.WfsExtractor$1.exceptionOccurred(WfsExtractor.java:281)
>         at org.geotools.data.store.ContentFeatureSource.accepts(ContentFeatureSource.java:797)
>         at org.geotools.data.store.ContentFeatureCollection.accepts(ContentFeatureCollection.java:124)
>         at org.georchestra.extractorapp.ws.extractor.FileFeatureWriter.generateFiles(FileFeatureWriter.java:86)
>         at org.georchestra.extractorapp.ws.extractor.WfsExtractor.extract(WfsExtractor.java:305)
>         at org.georchestra.extractorapp.ws.extractor.task.ExtractionTask.extractWfsLayer(ExtractionTask.java:346)
>         at org.georchestra.extractorapp.ws.extractor.task.ExtractionTask.run(ExtractionTask.java:127)
>         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
>         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         at java.base/java.lang.Thread.run(Thread.java:834)
> Caused by: java.lang.IllegalArgumentException: No such attribute:geom
>         at org.geotools.feature.simple.SimpleFeatureBuilder.set(SimpleFeatureBuilder.java:247)
>         at org.georchestra.extractorapp.ws.extractor.WriteFeatures.copyFeature(WriteFeatures.java:175)
>         at org.georchestra.extractorapp.ws.extractor.WriteFeatures.visit(WriteFeatures.java:131)
>         at org.geotools.data.store.ContentFeatureSource.accepts(ContentFeatureSource.java:792)

In geoserver I can see that the layer have a geom attribute and it display well in mfapp and other viewers.
We can also see in the logs that features are returned and correctly filtered (4 selected of 73).

Any idea what's happen ? Anyone ever had the same error ?

**Comment by RemiDesgrange** [comment]
Which version ?

**Comment by fvanderbiest** [comment]
https://geoportail.lepuyenvelay.fr/geoserver/wfs?service=WFS&version=1.1.0&request=describeFeatureType&typeName=referentiels:communes

Maybe `gml:MultiSurfacePropertyType` type is unsupported ?

**Comment by jusabatier** [comment]
I use version 20.1 of extractorapp.

**Comment by jusabatier** [comment]
Tested with a point layer which have `gml:PointPropertyType` and I have the same problem.

**Comment by fvanderbiest** [comment]
I can indeed reproduce on master:
```
extractorapp_1              | 2021-02-04 14:06:40 task [ERROR] Exception occurred while extracting data
extractorapp_1              | java.lang.RuntimeException: java.lang.IllegalArgumentException: No such attribute:departement
extractorapp_1              | 	at org.georchestra.extractorapp.ws.extractor.WfsExtractor$1.exceptionOccurred(WfsExtractor.java:281)
extractorapp_1              | 	at org.geotools.data.DataUtilities.visit(DataUtilities.java:2804)
extractorapp_1              | 	at org.geotools.feature.collection.DecoratingSimpleFeatureCollection.accepts(DecoratingSimpleFeatureCollection.java:61)
extractorapp_1              | 	at org.georchestra.extractorapp.ws.extractor.FileFeatureWriter.generateFiles(FileFeatureWriter.java:86)
extractorapp_1              | 	at org.georchestra.extractorapp.ws.extractor.WfsExtractor.extract(WfsExtractor.java:305)
extractorapp_1              | 	at org.georchestra.extractorapp.ws.extractor.task.ExtractionTask.extractWfsLayer(ExtractionTask.java:346)
extractorapp_1              | 	at org.georchestra.extractorapp.ws.extractor.task.ExtractionTask.run(ExtractionTask.java:127)
extractorapp_1              | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
extractorapp_1              | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
extractorapp_1              | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
extractorapp_1              | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
extractorapp_1              | 	at java.lang.Thread.run(Thread.java:748)
extractorapp_1              | Caused by: java.lang.IllegalArgumentException: No such attribute:departement
extractorapp_1              | 	at org.geotools.feature.simple.SimpleFeatureBuilder.set(SimpleFeatureBuilder.java:247)
extractorapp_1              | 	at org.georchestra.extractorapp.ws.extractor.WriteFeatures.copyFeature(WriteFeatures.java:175)
extractorapp_1              | 	at org.georchestra.extractorapp.ws.extractor.WriteFeatures.visit(WriteFeatures.java:131)
extractorapp_1              | 	at org.geotools.data.DataUtilities.visit(DataUtilities.java:2799)
extractorapp_1              | 	... 10 more
extractorapp_1              | 2021-02-04 14:06:40 task [ERROR] Exception occurred while extracting data
extractorapp_1              | java.lang.RuntimeException: java.lang.IllegalArgumentException: No such attribute:departement
extractorapp_1              | 	at org.georchestra.extractorapp.ws.extractor.WfsExtractor$1.exceptionOccurred(WfsExtractor.java:281)
extractorapp_1              | 	at org.geotools.data.DataUtilities.visit(DataUtilities.java:2804)
extractorapp_1              | 	at org.geotools.feature.collection.DecoratingSimpleFeatureCollection.accepts(DecoratingSimpleFeatureCollection.java:61)
extractorapp_1              | 	at org.georchestra.extractorapp.ws.extractor.FileFeatureWriter.generateFiles(FileFeatureWriter.java:86)
extractorapp_1              | 	at org.georchestra.extractorapp.ws.extractor.WfsExtractor.extract(WfsExtractor.java:305)
extractorapp_1              | 	at org.georchestra.extractorapp.ws.extractor.task.ExtractionTask.extractWfsLayer(ExtractionTask.java:346)
extractorapp_1              | 	at org.georchestra.extractorapp.ws.extractor.task.ExtractionTask.run(ExtractionTask.java:127)
extractorapp_1              | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
extractorapp_1              | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
extractorapp_1              | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
extractorapp_1              | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
extractorapp_1              | 	at java.lang.Thread.run(Thread.java:748)
extractorapp_1              | Caused by: java.lang.IllegalArgumentException: No such attribute:departement
extractorapp_1              | 	at org.geotools.feature.simple.SimpleFeatureBuilder.set(SimpleFeatureBuilder.java:247)
extractorapp_1              | 	at org.georchestra.extractorapp.ws.extractor.WriteFeatures.copyFeature(WriteFeatures.java:175)
extractorapp_1              | 	at org.georchestra.extractorapp.ws.extractor.WriteFeatures.visit(WriteFeatures.java:131)
extractorapp_1              | 	at org.geotools.data.DataUtilities.visit(DataUtilities.java:2799)
extractorapp_1              | 	... 10 more
```

To reproduce :
curl 'https://georchestra.mydomain.org/extractorapp/extractor/initiate' --user 'testadmin:testadmin'  -H 'Content-Type: application/json' -H 'X-Requested-With: XMLHttpRequest' -H 'Origin: https://georchestra.mydomain.org' -H 'Connection: keep-alive'  --data-raw '{"emails":["francois.vanderbiest@camptocamp.com"],"globalProperties":{"projection":"EPSG:4326","resolution":0.5,"rasterFormat":"geotiff","vectorFormat":"shp","bbox":{"srs":"EPSG:3857","value":[-517718.28517833,6161366.4299357,-483627.36498465,6186284.9067351]}},"layers":[{"owsUrl":"https://geobretagne.fr/geoserver/cadastre/wfs?","owsType":"WFS","layerName":"cadastre:CP.CadastralZoningLevel1_2014"}]}'

**Comment by fvanderbiest** [comment]
Same on 20.0.x

**Comment by pmauduit** [comment]
The error arises here:
https://github.com/georchestra/georchestra/blob/master/extractorapp/src/main/java/org/georchestra/extractorapp/ws/extractor/WriteFeatures.java#L175

The builder object is our target set of features (org.geotools.feature.simple.SimpleFeatureBuilder), its featuretype is already "configured" to comply with a Shapefile specification (normalized column names ...), whereas entry is our featureset coming from the remote WFS, which does not require normalization. We are then trying to map the value onto the "departement" attribute on the builder, which actually does not exist (because of the normalization, it's "departemen".

See screenshots below, here is the featuretype for the builder object:

![Screenshot from 2021-02-18 15-32-06](https://user-images.githubusercontent.com/594335/108372422-1b16a480-71ff-11eb-92b8-e53bf759d4ab.png)


Here is the one from the source featuretype:

![Screenshot from 2021-02-18 15-38-15](https://user-images.githubusercontent.com/594335/108372797-75b00080-71ff-11eb-9711-b2b91f0b1a26.png)

We can see that a mapping between the original datasource & the target datasource has been anticipated in the code to avoid this featuretype column name mismatch, but somehow it does not work as expected, or it hsa not been implemented to manage column normalization on shapefiles:

https://github.com/georchestra/georchestra/blob/master/extractorapp/src/main/java/org/georchestra/extractorapp/ws/extractor/WriteFeatures.java#L226-L239

**Comment by pmauduit** [comment]
If a fix is possible, it could be done in those two methods (and probably the first one, I don't know if the case where the geometric attribute is named with a string longer than 10 chars has to be managed): https://github.com/georchestra/georchestra/blob/master/extractorapp/src/main/java/org/georchestra/extractorapp/ws/extractor/WriteFeatures.java#L81-L118

**Comment by pmauduit** [comment]
A quick n' ugly fix would be the following:

```diff
index 54dc2e1b9..ecd85c99b 100644
--- a/extractorapp/src/main/java/org/georchestra/extractorapp/ws/extractor/WriteFeatures.java
+++ b/extractorapp/src/main/java/org/georchestra/extractorapp/ws/extractor/WriteFeatures.java
@@ -18,6 +18,7 @@ import org.geotools.feature.AttributeTypeBuilder;
 import org.geotools.feature.DefaultFeatureCollection;
 import org.geotools.feature.simple.SimpleFeatureBuilder;
 import org.geotools.feature.simple.SimpleFeatureTypeBuilder;
+import org.locationtech.jts.geom.Geometry;
 import org.opengis.feature.Feature;
 import org.opengis.feature.FeatureVisitor;
 import org.opengis.feature.simple.SimpleFeature;
@@ -172,7 +173,17 @@ public class WriteFeatures implements FeatureVisitor {
         Set<Entry<String, String>> entries = _attNameMapping.entrySet();
         for (Entry<String, String> entry : entries) {
             Object value = simpleFeature.getAttribute(entry.getKey());
-            builder.set(entry.getValue(), value);
+            // SHP normalization
+            String shpNormalizedColumnName = entry.getValue();
+
+            if (shpNormalizedColumnName.length() >= 10) {
+                shpNormalizedColumnName = entry.getValue().substring(0, 10);
+            }
+            if (value instanceof Geometry) {
+                builder.set("the_geom", value);
+            } else {
+                builder.set(shpNormalizedColumnName, value);
+            }
         }
         SimpleFeature copy = builder.buildFeature(id);
         return copy;
```

This at least works with the provided spec, but is clearly not the best way of fixing it ....

**Comment by fvanderbiest** [comment]
Asking @groldan for a review of your patch ... or hints to make it better. 
Thanks Gabriel !

**Comment by groldan** [comment]
http://switchfromshapefile.org/ :)

**Comment by groldan** [comment]
See #3302
The most relevant commit being https://github.com/georchestra/georchestra/pull/3302/commits/c6bec8c5fc394d9722add23bb65483a2a7f44497

Took the opportunity to make other improvements too
