### ISSUE TITLE
[console] No more pagination on the log tab (20.1 regression ?)

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/georchestra#3293]
Here in Rennes we note that there is no longer pagination on the main "logs" tab.

We only see 15 lines. Any way to go / search / find older operations made by administrators.
Very ennoying.

Confirmed under Chrome and FireFox

**Comment by fvanderbiest** [comment]
Thanks for the report. We will investigate

**Comment by tonio** [comment]
Already fixed with https://github.com/georchestra/georchestra/commit/80c10e50d9965fc22969a4dadc07af1d37e6f31e

**Comment by fvanderbiest** [comment]
To be deployed with next release 20.0.7... (soon)
