### ISSUE TITLE
DNS settings for docs.georchestra.org

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3312]
"The page build completed successfully, but returned the following warning for the `master` branch:
Your site's DNS settings are using a custom subdomain, docs.georchestra.org, that's not set up with a correct CNAME record. We recommend you set this CNAME record to point at georchestra.github.io. For more information, see https://docs.github.com/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site."

**Comment by pmauduit** [comment]
I can't remember why, but for now docs.g.o points onto the servers At PauLLA:

```
% host docs.georchestra.org
docs.georchestra.org is an alias for s01.georchestra.org.
s01.georchestra.org has address 193.55.222.230
```

I have no objection to update the record (I must have access to the gandi panel to administer the domain).

**Comment by landryb** [comment]
maybe talk to @MaelREBOUX iirc he took care of building `docs.georchestra.org` at paulla. Or taht's intended, and github should just ignore the fact that it doesnt point at (sometimes greedy 'i want to take over everything') github..

**Comment by MaelREBOUX** [comment]
yes : we point to the 1st PAULLA server for this sub-domain since several months.

**Comment by MaelREBOUX** [comment]
And I want to create an individual GANDI account for managing in community our DNS zone...
