### ISSUE TITLE
[mapfishapp] open the metadata floating window renames the layer in the TOC

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/georchestra#3364]
Below a very very annoying (and new ?) behaviour :

The name of a layer in a map context is automaticallyer renamed by viewing its metadata :

![mapfishapp_md_autorename_layer](https://user-images.githubusercontent.com/6370443/116208890-a487ad00-a741-11eb-8ce8-a5e9880fbb0a.gif)

This breaks all the custom map !

**Comment by fvanderbiest** [comment]
I'm puzzled !
Please share the map context, eventually directly with me.

**Comment by MaelREBOUX** [comment]
WMC file attached

[55-urbanisme_ADS.txt](https://github.com/georchestra/georchestra/files/6384642/55-urbanisme_ADS.txt)
