### ISSUE TITLE
Upgrade master to geoserver 2.20.x

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3380]
http://geoserver.org/announcements/2021/03/22/geoserver-2-19-0-released.html

**Comment by landryb** [comment]
* http://geoserver.org/announcements/2022/01/24/geoserver-2-20-2-released.html
* http://geoserver.org/announcements/2021/12/22/geoserver-2-19-4-released.html

**Comment by fvanderbiest** [comment]
Gave it a try for 22.0, but not straigtforward => will require some $$$funding$$$

**Comment by landryb** [comment]
for those following at home, wip in https://github.com/georchestra/geoserver/commits/2.20.4-georchestra
