### ISSUE TITLE
Upgrade 20.1.x to GeoServer 2.18.3

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3381]
http://geoserver.org/announcements/2021/04/23/geoserver-2.18.3-released.html

**Comment by pmauduit** [comment]
this comment will have to be taken into account when migrating: https://github.com/georchestra/georchestra/issues/3358#issuecomment-836845520

**Comment by landryb** [comment]
georchestra/geoserver#24 should take care of the CORS regression
