### ISSUE TITLE
doc - enrich the setup doc regarding datafeeder

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3405]
https://github.com/georchestra/georchestra/tree/master/docs/setup

**Comment by landryb** [comment]
cf georchestra/ansible#77 ;) and ... some github action or buildbot knob to produce wars ?

**Comment by pmauduit** [comment]
> cf georchestra/ansible#77 ;) and ... some github action or buildbot knob to produce wars ?

I don't really see the point of using GH actions here if we cannot store the artifact. I mean github provides a maven repository, but it requires to be authenticated, so I would go for our own CI on our server for such things.

Or we could also use a gh actions with a secret config.xml file for maven, which would allow us to publish the DF artifact onto the artifactory ? It could be nice, just thinking out loud. If so we could probably go further with the other artifacts as well.

**Comment by landryb** [comment]
or .. add the missing plumbing to produce a debian package like things are done for other modules ? :)

**Comment by pmauduit** [comment]
> add the missing plumbing to produce a debian package like things are done for other modules ?

Well there would be 2 different modules to consider:
* the datafeeder (spring boot app, so it would slightly differ compared to the other georchestra modules which can already be packaged as a debian package)
* the frontend (import.war, should be similar to the other ones)

**Comment by fvanderbiest** [comment]
> or .. add the missing plumbing to produce a debian package like things are done for other modules ? :)

If you're ready to fund this, that would ease things a lot :-)
(considering we already invested a lot on the datafeeder app)

**Comment by landryb** [comment]
> > or .. add the missing plumbing to produce a debian package like things are done for other modules ? :)
> 
> If you're ready to fund this, that would ease things a lot :-)
> (considering we already invested a lot on the datafeeder app)

who needs funding when you can have a PR instead ? ;)

**Comment by pmauduit** [comment]
Added some doc specific to the DF, see https://github.com/georchestra/georchestra/pull/3656/files

**Comment by fvanderbiest** [comment]
We forgot to modify https://github.com/georchestra/georchestra/blob/master/docs/setup/apache.md

... but should we maintain this "manual install" documentation as it is ? or should we remove it, in favor of the ansible / docker setups ?
