### ISSUE TITLE
SP - test failure due to java.net.UnknownHostException: sdi.georchestra.org

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3429]
```
Error:  Tests run: 13, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 0.744 s <<< FAILURE! - in org.georchestra.security.PermissionsTest
Error:  testHost(org.georchestra.security.PermissionsTest)  Time elapsed: 0.341 s  <<< ERROR!
java.net.UnknownHostException: sdi.georchestra.org: Name or service not known
	at org.georchestra.security.PermissionsTest.load(PermissionsTest.java:19)
	at org.georchestra.security.PermissionsTest.testHost(PermissionsTest.java:91)
```

Proposal: replace with another service ?

**Comment by fvanderbiest** [comment]
https://github.com/georchestra/georchestra/runs/2802575162?check_suite_focus=true

**Comment by isanchez-c2c** [comment]
if replacing sdi.georchestra.org and sdi-stable.georchestra.org by the url of current running georchestra pf we still get :
`[ERROR] Tests run: 13, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 0.656 s <<< FAILURE! - in org.georchestra.security.PermissionsTest
[ERROR] testHost(org.georchestra.security.PermissionsTest)  Time elapsed: 0.295 s  <<< FAILURE!
java.lang.AssertionError
	at org.georchestra.security.PermissionsTest.testHost(PermissionsTest.java:95)

[ERROR] testDenyBydefault(org.georchestra.security.PermissionsTest)  Time elapsed: 0.022 s  <<< FAILURE!
java.lang.AssertionError
	at org.georchestra.security.PermissionsTest.testDenyBydefault(PermissionsTest.java:78)

[ERROR] testAllowBydefault(org.georchestra.security.PermissionsTest)  Time elapsed: 0.085 s  <<< FAILURE!
java.lang.AssertionError
	at org.georchestra.security.PermissionsTest.testAllowBydefault(PermissionsTest.java:62)
`

**Comment by pmauduit** [comment]
yes the DNS  resolution does not work anymore, so the test will have to be updated, or the code instrumented so that we don't have to rely on an external DNS resolution to make it pass.

**Comment by fvanderbiest** [comment]
Maybe requires a backport ?
