### ISSUE TITLE
geoserver - sldservice does not build on 20.0.x

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3430]
https://github.com/georchestra/georchestra/runs/2802634329?check_suite_focus=true

Error:  Failed to execute goal on project geoserver-webapp: Could not resolve dependencies for project org.georchestra:geoserver-webapp:war:20.0.8: Could not find artifact org.geoserver.community:gs-sldservice:jar:2.17.5 in artifactory-georchestra (https://artifactory.georchestra.org/artifactory/maven) -> [Help 1]

**Comment by landryb** [comment]
seen the same thing building master, repository shuffling ?
