### ISSUE TITLE
geoserver - 20.1.x - docker - regression with the web.xml provided

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#3458]
It seems that the session-tracking parameter is not set to "COOKIE" anymore, this can lead to unexpected behaviour from spring-security in regards to browsing geoserver via the header, as it will try to pass the cookie in the url using the ";" which is not allowed.

On a pretty-new deployment based on 20.1.3, I have been redirected to:
```
https://<host>/geoserver/web/;jsessionid=node01ir627hn4sm711sl6jzqk61mau1.node0?0
```

Leading to a 500 error.

The fix is pretty trivial and requires to revert the session-tracking parameter back into the web.xml from this commit:
https://github.com/georchestra/georchestra/commit/661091de3043f2bd0b6f649ea2a2210d3725ee6e

Note: **this seems specific to version 20.1.x on the docker images**, as the master branch provides a fixed version of the web.xml, and checking into the last available geoserver artifact from https://packages.georchestra.org/bot/wars/20.1.x/, regular war does not seem affected either.

**Comment by fvanderbiest** [comment]
My bad, https://github.com/georchestra/georchestra/pull/3442/files
