### ISSUE TITLE
Deprecate non-SSL mode

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3461]
https://github.com/georchestra/datadir/blob/master/default.properties#L9 could be hardwired nowadays

**Comment by jeanpommier** [comment]
+1
I've tested with the docker compo, with scheme=http, it doesn't fully work. It seems authentication does not support http anymore. So, better to remove this option.

**Comment by pmauduit** [comment]
I personally found it convenient to be able to keep http without ssl/tls, but I won't cry if you set the default to https. I could probably be able to hack around a default setup to get back to http if I really need it (for dev. purposes obviously).

**Comment by fvanderbiest** [comment]
Yes, switching back to http is still possible.

**Comment by pmauduit** [comment]
mentioned PR in the datadir has just been merged, anything else I shall do here ?

**Comment by fvanderbiest** [comment]
Testing + merging #3672 ? Thanks !
