### ISSUE TITLE
Hardcoded password for geonetwork (DB)

### ISSUE THREAD

**Issue by jeanpommier** [georchestra/georchestra#3467]
Hi,
I found out that the postgresql password for geonetwork user is hardcoded in the DB's definition: https://github.com/georchestra/georchestra/blob/master/postgresql/00-create-user.sql#L1
While, I believe, we are supposed to be able to change it in the georchestra_datadir

It doesn't look like a very good idea, security-wise. Particularly if geonetwork user is SUPERUSER...
BTW, is it really needed to be SUPERUSER ?

**Comment by pmauduit** [comment]
> is it really needed to be SUPERUSER ?

no, I guess owner of its own schema should suffice.

**Comment by fvanderbiest** [comment]
feee44d0d65ac838ae4af2933c4ad100af7b6ae1
