### ISSUE TITLE
[Console] Problem persisting empty area for an org to the LDAP

### ISSUE THREAD

**Issue by jusabatier** [georchestra/georchestra#3468]
I tested with a war from 20.1.x and an empty area for an org isn't persisted to the LDAP.

Same behavior as this old issue : https://github.com/georchestra/georchestra/issues/2471

To reproduce : 

1. Assign an area to an org and save
2. Remove the area from the org and save
3. Refresh and the area still assigned to the org

**Comment by fvanderbiest** [comment]
Thanks for the report Julien.
This means #2869 did not fix the original issue IIUC.
Bumping.

**Comment by fvanderbiest** [comment]
Feel free to provide a patch. Thanks !

**Comment by pmauduit** [comment]
see PR above (codacy check fixed in a second commit).
