### ISSUE TITLE
[build] find a replacement for jsbuild / debian 11 compat

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#3473]
jsbuild is being used by at least mapfishapp and cadastrapp, and will likely not be available (unless via twisted ways) on debian bullseye which drops python2/pip. Maybe that's just more incentive to drop mapfishapp build with debian 11 :)

**Comment by landryb** [comment]
unless we make sure to use https://github.com/camptocamp/jstools/commit/ab60cd87c172325f2b8f3c949e9eefbe10bc4940 ...

**Comment by fvanderbiest** [comment]
IIRC we already tested this commit, but this messes up the file order in the final bundle, which breaks --at least-- the mapfishapp build.

**Comment by pmauduit** [comment]
If we know which files & in which order we have to minify, maybe a simple webpack configuration should do the job ?

**Comment by landryb** [comment]
Fwiw, maybe that's a non-issue, as debian 11 still has a minimal python2.7, and building master still works (ok, maybe just because i have some wheels in the pip cache...)
```
[INFO] --- exec-maven-plugin:1.5.0:exec (default) @ mapfishapp ---
creating virtual env and installing jstools...
created virtual environment CPython2.7.18.final.0-64 in 856ms
  creator CPython2Posix(dest=/data/src/georchestra/georchestra/mapfishapp/jsbuild/env, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, wheel=bundle, setuptools=bundle, via=copy, app_data_dir=/home/landry/.local/share/virtualenv)
    added seed packages: pip==20.3.4, setuptools==44.1.1, wheel==0.37.0
  activators PythonActivator,CShellActivator,FishActivator,PowerShellActivator,BashActivator
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pyp.
Processing /home/landry/.cache/pip/wheels/08/60/67/9e91512e7ae5d3e9b919c68ca2b658ea1595256bacc67f8db6/JSTools-0.6-py2-none-any.whl
Installing collected packages: jstools
Successfully installed jstools-0.6
done.
running jsbuild for main app...
```
