### ISSUE TITLE
[Console] Password recovery login link

### ISSUE THREAD

**Issue by jusabatier** [georchestra/georchestra#3484]
Itried the password recovery function : 

1. Click recover password button
2. Click on link sent by email
3. Define new password
4. Click on connect button

But when clicking on connect button, it appear it redirect to `/cas/login` what result in a 404 if an external CAS server is used.

It should redirect to `/console?login` instead.

**Comment by pmauduit** [comment]
CAS url is indeed hardcoded in the console in several locations:
* https://github.com/georchestra/georchestra/blob/master/console/src/main/webapp/WEB-INF/views/passwordUpdated.jsp#L23
* https://github.com/georchestra/georchestra/blob/master/console/src/main/webapp/WEB-INF/views/welcomeNewUser.jsp#L23

Also in a mail template by default:
https://github.com/georchestra/georchestra/blob/master/console/src/main/webapp/WEB-INF/templates/newaccount-was-created-template.txt#L4
but you can probably override the latter in the datadir already.
