### ISSUE TITLE
[datafeeder] hardcodes /header/ and header height ?

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#3499]
from https://github.com/georchestra/georchestra/pull/3493#issuecomment-918140759, seems https://github.com/georchestra/geonetwork-ui/blob/8a4fc6f13178efe702d7139f2e4fcd7532b8ddc1/apps/datafeeder/src/index.html#L25 hardcodes `90px` for `headerHeight` and `/header/` for `headerUrl` instead of taking them from `$datadir/default.properties`

**Comment by pmauduit** [comment]
The two properties (header url & height) could also be provided by the backend (https://github.com/georchestra/datadir/blob/master/datafeeder/frontend-config.json) and consumed by the UI. This would address every artifacts behaviour at the same time, and sounds more relevant to me than diverging between regular war artifacts & the docker approach.
But I am incompetent on the topic of frontend development and call myself out.

**Comment by fvanderbiest** [comment]
Right. Thanks for investigating Pierre.
Calling @fgravin, @tonio and @jahow to the rescue then. 

It's important to have a nice integration of the datafeeder into the whole geOrchestra stack.

**Comment by f-necas** [comment]
With the new header, this part has been removed and moved to the datadir with a custom script. 

The second step would be to remove custom scripts to implement header. #4248
