### ISSUE TITLE
geonetwork to provide 20.1.x docker images

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3500]
Currently only tags are built, but not `20.1.x`

In addition, the composition uses `20.1.0` instead of `20.1.x`:
https://github.com/georchestra/docker/blob/ce731ad0c59f2a612309aa399c2e80f01f5f7461/docker-compose.yml#L128

**Comment by fvanderbiest** [comment]
See also https://github.com/georchestra/docker/issues/111

**Comment by fvanderbiest** [comment]
won't do with an action => manual push on tag

**Comment by pmauduit** [comment]
Pushed on docker-hub: `georchestra/geonetwork:20.1.x`.

As we are moving to gn4 and 3.8.2 won't budge much anymore, I guess we could tag the same image `20.1.5` and push it as well ?

**Comment by fvanderbiest** [comment]
> I guess we could tag the same image `20.1.5` and push it as well ?

ok !

**Comment by pmauduit** [comment]
Done
