### ISSUE TITLE
mapstore - rename docker image

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3501]
Rename `georchestra/mapstore2-georchestra` docker image into `georchestra/mapstore`

**Comment by fvanderbiest** [comment]
Here's my understanding:
 * mapstore belongs to https://github.com/georchestra/mapstore2-georchestra
 * the CI (managed by https://github.com/georchestra/mapstore2-georchestra/blob/master/.github/workflows/mapstore.yml) builds `master` (pushed to `latest`) and tagged releases (but no tag was pushed since the CI builds them)
 * which results in https://hub.docker.com/r/georchestra/mapstore/tags having a single tag for `latest` at the moment.
 * the docker composition [uses georchestra/docker:latest on master](https://github.com/georchestra/docker/blob/7aaf9c00a3c10058a8e4d46c4c5f9428ef88e8ee/docker-compose.yml#L173-L174) (which is fine).
 * the docker composition [uses geosolutionsit/mapstore2-georchestra:1.1.x on 20.1](https://github.com/georchestra/docker/blob/9c1e667796b6c757105f5b10b73b348ecc1d9fdf/docker-compose.yml#L154) => this should be improved for 22.0 : I'd rather have `georchestra/mapstore:2021.02.xx` (or georchestra/mapstore:whatever) instead.

**Comment by fvanderbiest** [comment]
This also relates to https://github.com/georchestra/mapstore2-georchestra/issues/425

**Comment by jmbourdaret** [comment]
some additional information about configuration and versions: georchestra/docker#122

**Comment by jmbourdaret** [comment]
> Here's my understanding:
> 
> * mapstore belongs to https://github.com/georchestra/mapstore2-georchestra
> * the CI (managed by https://github.com/georchestra/mapstore2-georchestra/blob/master/.github/workflows/mapstore.yml) builds `master` (pushed to `latest`) and tagged releases (but no tag was pushed since the CI builds them)
> * which results in https://hub.docker.com/r/georchestra/mapstore/tags having a single tag for `latest` at the moment.
> * the docker composition [uses georchestra/mapstore:latest on master](https://github.com/georchestra/docker/blob/7aaf9c00a3c10058a8e4d46c4c5f9428ef88e8ee/docker-compose.yml#L173-L174) (which is fine).
> * the docker composition [uses geosolutionsit/mapstore2-georchestra:1.1.x on 20.1](https://github.com/georchestra/docker/blob/9c1e667796b6c757105f5b10b73b348ecc1d9fdf/docker-compose.yml#L154) => this should be improved for 22.0 : I'd rather have `georchestra/mapstore:2021.02.xx` (or `georchestra/mapstore:whatever`) instead.

what about the https://github.com/georchestra/MapStore2 repo (fork of geosolutions's )? is it replaced by https://github.com/georchestra/mapstore2-georchestra ?

**Comment by pmauduit** [comment]
> what about the https://github.com/georchestra/MapStore2 repo (fork of geosolutions's )? is it replaced by https://github.com/georchestra/mapstore2-georchestra ?

I think it was used previously because a hack was required somehow (ping @tkohr  for confirmation). The repositories are not equivalent though, one is used as a submodule for the other one: georchestra/Mapstore2 is a fork from geosolutions-it/Mapstore2, which is integrated as a submodule into georchestra/mapstore2-georchestra.

**Comment by tkohr** [comment]
We created the https://github.com/georchestra/MapStore2 fork last fall, when we needed a recent dev (that had been merged in Mapstore2) without updating the entire submodule, which included other obstacles: https://github.com/georchestra/mapstore2-georchestra/pull/427
Since then, several updates of the submodule have been applied and the fork should not be in use anymore. I guess we could remove it.

**Comment by jmbourdaret** [comment]
indeed. thanks Tobias
https://github.com/georchestra/mapstore2-georchestra/commits/master/.gitmodules

it doesn't seems to be used anymore.

**Comment by tkohr** [comment]
Me neither, I think @pmauduit can help out here ;)

**Comment by pmauduit** [comment]
> Me neither, I think @pmauduit can help out here ;)

done, I archived georchestra/MapStore2
