### ISSUE TITLE
extractorapp docker image doesn't build anymore, base image has no libgdal-java

### ISSUE THREAD

**Issue by groldan** [georchestra/georchestra#3506]
Base image [jetty:9-jre8](https://github.com/eclipse/jetty.docker/blob/master/9.4-jre8/Dockerfile) in turn has `openjdk:8-jre` as base.

`openjdk:8-jre` is now based on Debian 11  (bullseye), which doesn't contain GDAL, whereas Debian 10 (buster) based images did.

Which leads to the following error when building `georchestra/extractorapp`:

```
...
Building dependency tree...

Reading state information...
E: Unable to locate package libgdal-java

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.981 s
[INFO] Finished at: 2021-09-22T03:37:53-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:1.2.2:build (default-cli) on project extractorapp: Exception caught: The command '/bin/sh -c apt-get update &&    apt-get install -y libgdal-java gdal-bin &&    rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100 -> [Help 1]
```

**Comment by pmauduit** [comment]
This one has been investigated here: https://github.com/georchestra/georchestra/issues/3502#issuecomment-923007908

**Comment by pmauduit** [comment]
done with cherry-picking from 20.1.x: https://github.com/georchestra/georchestra/commit/3307371055538688e46b01fafa6370e7086677e4
