### ISSUE TITLE
[header] broken link to GN4 admin page

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#3515]
when logged in, in the header there's a link to geonetwork admin page in https://github.com/georchestra/georchestra/blob/master/header/src/main/webapp/WEB-INF/jsp/index.jsp#L321

from testing here, GN4 doesnt support anymore the two-letter codes (eg `/geonetwork/srv/fr/admin.console` gives a 404) so the code should use the 3-letters codes (`/geonetwork/srv/fre/admin.console` works)

**Comment by pmauduit** [comment]
Should be fixed by the mentioned PR
