### ISSUE TITLE
[build] master is broken since GN4 merge (wrong/missing build dependencies?)

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#3518]
cf comments on georchestra/geonetwork#182, since georchestra/georchestra#3497 was merged to master the Makefile-based builds are broken.
```
gn-externalized-accounts: Could not resolve dependencies for project org.geonetwork-opensource:gn-externalized-accounts:jar:4.0.6-georchestra-SNAPSHOT: Could not find artifact org.georchestra:georchestra-testcontainers:jar:21.0-SNAPSHOT
```

Maybe github actions works (and sometimes it also breaks, eg see the failure on https://github.com/georchestra/geonetwork/runs/4023053411?check_suite_focus=true), but not everyone uses that - the buildbot on https://packages.georchestra.org/bot/ uses the Makefile.

after much hair pulling, i've figured out that GN4 submodule wont build as long as one hasnt built/installed the jars for `security-proxy-spring-integration`, `georchestra-testcontainers` and `georchestra-ldap-account-management`

so my take is that `geonetwork/pom.xml` lacks some `dependencies` on the said external modules (even if they seem to be at https://github.com/georchestra/geonetwork/blob/georchestra-gn4-4.x-dev/georchestra-integration/pom.xml#L22 - they should be moved to the toplevel pom.xml ??), or it can be fixed at the Makefile level too - i'm finally able to build with:

```
[03/11 15:27] landry@build.fluela:/data/src/georchestra/georchestra $git diff
diff --git a/Makefile b/Makefile
index 27f176342..54fc141b6 100644
--- a/Makefile
+++ b/Makefile
@@ -80,6 +80,7 @@ war-build-geowebcache: build-deps
        mvn clean install -pl geowebcache-webapp -DskipTests -Dfmt.skip=true

 war-build-gn:
+       mvn clean install -pl testcontainers,ldap-account-management,security-proxy-spring-integration -DskipTests
        mvn clean install -f geonetwork/pom.xml -DskipTests

 war-build-georchestra: war-build-gn war-build-geoserver
```

can do a PR with that, but i think it'd be better if the geonetwork dependencies could be properly fixed in maven. cc @pmauduit @groldan

**Comment by landryb** [comment]
rebuilding from a clean `~/.m2`, it seems geonetwork also depends on `commons` module too.

**Comment by landryb** [comment]
closed by #3521, buildbot working on master branch is happy now :)

**Comment by landryb** [comment]
Fwiw, reopening the issue, since github actions still fail to build geonetwork from `georchestra-gn4-4.x-dev` branch with missing dependencies (cf https://github.com/georchestra/geonetwork/actions/runs/1504282132 for the last one) and imo that's not great to have a broken CI for ages. @fvanderbiest @groldan ?

```
Error: 9,741 [ERROR] Failed to execute goal on project gn-externalized-accounts: Could not resolve dependencies for project org.geonetwork-opensource:gn-externalized-accounts:jar:4.0.6-georchestra-SNAPSHOT: Could not find artifact org.georchestra:georchestra-testcontainers:jar:21.0-SNAPSHOT -> [Help 1]
```

**Comment by pmauduit** [comment]
Shall we consider maintaining the github action from georchestra/geonetwork, or keeping georchestra/georchestra dedicated one to geonetwork ? (first one is broken but had the advantage of building new artifacts more often, the other one should work, but will only build when the GN submodule is updated).

**Comment by pmauduit** [comment]
as discussed on IRC, this is fixed by the following commit:
https://github.com/georchestra/geonetwork/commit/a9a23b709966fe4ffe558ca65aa0d2904baf80b7

**Comment by pmauduit** [comment]
There is still a gh action coming from upstream which does not succeed though:
https://github.com/georchestra/geonetwork/blob/georchestra-gn4-4.x-dev/.github/workflows/linux.yml

I'm wondering if we should remove it or not
