### ISSUE TITLE
debian bullseye stopped building libgdal-java/shipping gdal.jar -> impact on geoserver ?

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#3525]
in `geoserver/NATIVE_LIBS.md`, the doc explains how to install/configure gdal access within geoserver. I dunno how much this feature is used by various platforms (and i think its also used by extractorapp?), but there's no `libgdal-java` package anymore in debian bullseye, cf https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=947960 / https://salsa.debian.org/debian-gis-team/gdal/-/commit/936e50e1a9e5eb3d1bd10147b5d5c25476845b23

**Comment by landryb** [comment]
cf georchestra/ansible@1fdd53a0 too - so maybe just a headsup for ppl using gdal datastores in geoserver ?

**Comment by landryb** [comment]
https://github.com/georchestra/georchestra/blob/master/geoserver/NATIVE_LIBS.md is ... outdated, to say the least :)

**Comment by landryb** [comment]
from my understanding of https://docs.geoserver.org/stable/en/user/data/raster/gdal.html it seems gdal support in geoserver was to add additional raster formats in input, but to my recollection i never managed to make it properly work, nor had a use for it.

**Comment by landryb** [comment]
according to https://docs.geoserver.org/stable/en/user/community/ogr-store/index.html it was also used for an ogr datastore type, but i dunno if its still relevant.

**Comment by pmauduit** [comment]
Checking if there was a geotools module in the GeoServer classpath of my ansible/vagrant box, it does not seem to be the case, so I'd go for dropping the need for the gdal/ogr native libs by default (as far as I am aware of, no gdal/ogr datastore are currently used on platforms maintained by camptocamp)

**Comment by fvanderbiest** [comment]
@pmauduit agreed.

**Comment by fvanderbiest** [comment]
Let's also remove the doc on gdal native, if unrelevant.
