### ISSUE TITLE
geonetwork4 - Creating a new MD / saving does not work

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#3526]
It seems that there is an issue with session persisting when editing a MD. the steps to reproduce the bug is quite easy:

1. launch a georchestra instance along with GN4
2. connect as testadmin/testadmin
3. load the default templates
4. create a new MD
5. click on "save MD"

Then we can see in the developer console that a 404 is returned from a `POST /geonetwork/srv/api/records/<md id>/editor?`.

It turns out that something is wrong when editing a MD and setting it into the session hashtable of the current logged user. Indeed, if we set a breakpoint onto the jetty sources (using the docker image from the composition) onto Response.setStatus(404), we can get back to our webapp code, and see that:

JeevesDispatcherServlet calls doDispatch from the parent class (org.springframework.web.servlet.DispatcherServlet), and this catches an exception at line 1050. Digging into this exception, we discover that the exception being caught comes actually from the following code:

https://github.com/georchestra/geonetwork/blob/georchestra-gn4-4.x-dev/services/src/main/java/org/fao/geonet/api/records/editing/AjaxEditUtils.java#L66-L68

**Comment by pmauduit** [comment]
git grepping the code, I think we will have a similar bug with the MD selection interface. Here we have 3 selected items, yet only one is "detected" by the UI:

![image](https://user-images.githubusercontent.com/594335/140785957-7927729e-d78b-4467-bfed-eebebd351682.png)

```
% git grep -n session.setProperty
core/src/main/java/jeeves/services/session/Put.java:85:        session.setProperty(groupName, group);
core/src/main/java/org/fao/geonet/kernel/SelectionManager.java:160:            session.setProperty(Geonet.Session.SELECTED_RESULT, manager);
core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataValidator.java:502:        session.setProperty(Geonet.Session.VALIDATION_REPORT + metadataId, errorReport);
core/src/main/java/org/fao/geonet/services/util/SearchDefaults.java:104:        session.setProperty(Geonet.Session.MAIN_SEARCH, elData);
services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java:321:                            session.setProperty(Geonet.Session.SEARCH_REQUEST + selectionBucket, node);
services/src/main/java/org/fao/geonet/api/records/editing/AjaxEditUtils.java:317:        session.setProperty(Geonet.Session.METADATA_EDITING + id, md);
services/src/main/java/org/fao/geonet/api/records/editing/EditUtils.java:122:            session.setProperty(sessionTabProperty, elCurrTab.getText());
services/src/main/java/org/fao/geonet/api/records/editing/EditUtils.java:125:            session.setProperty(Geonet.Session.METADATA_POSITION, elCurrPos.getText());
services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java:305:        session.setProperty(Geonet.Session.SEARCH_KEYWORDS_RESULT,
services/src/main/java/org/fao/geonet/services/feedback/AddLimitations.java:196:        session.setProperty(Geonet.Session.FILE_DISCLAIMER, resourceData);
services/src/main/java/org/fao/geonet/services/main/XmlSearch.java:133://            session.setProperty(Geonet.Session.SEARCH_REQUEST + bucket, elData.clone());
services/src/main/java/org/fao/geonet/services/thesaurus/GetKeywords.java:138:            session.setProperty(Geonet.Session.SEARCH_KEYWORDS_RESULT,
```

**Comment by groldan** [comment]
Fixed at https://github.com/georchestra/geonetwork/commit/aee4456575fc5d0cb61c036e4a581d8aa3cb8668

**Comment by pmauduit** [comment]
Tested on the last deploy on dev.g2f.fr, it works, thanks !

It seems to also fix the selection interface
