### ISSUE TITLE
[console] Bogue sur message "utilisateur en attente"

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/georchestra#3541]
On va sur le compte à examiner / valider

![image](https://user-images.githubusercontent.com/6370443/143210664-357b56d4-8c7b-487d-93a3-adfdd3ba1e3c.png)

Modification de 1 attribut (ex : prénom, n° de tel) => clic sur Enregistrer

![image](https://user-images.githubusercontent.com/6370443/143210776-c7847895-f938-46c6-8c79-342362d16049.png)

Du coup : pas possible de valider l'utilisateur en cours. Il faut soit aller sur l'onglet Rôles soit recharger la page.

**Comment by fvanderbiest** [comment]
Si je comprends bien, tu souhaiterais modifier des attributs d'un utilisateur en le conservant dans son statut "non confirmé" ?

**Comment by landryb** [comment]
c'est qqch sur lequel mes collegues ralent, ils préféreraient d'abord corriger tout ce qu'a entré l'utilisateur lors de sa demande de compte **avant** de le valider.

**Comment by MaelREBOUX** [comment]
> tu souhaiterais modifier des attributs d'un utilisateur en le conservant dans son statut "non confirmé" ?

Ben : c'est ce qu'on fait à chaque fois qu'on a une demande de compte. Quasiment.

Mais ce n'est pas le sujet car la sauvegarde des valeurs modifiées fonctionnement. Le sujet est que, APRÈS, avoir cliqué sur le bouton "enregistrement" le message affiché dans la zone rouge déconne. L'organisme étant dans la quasi totalité des cas déjà validé.

**Comment by fvanderbiest** [comment]
@jmbourdaret I think we fixed it with your PR, right ?
#3660

**Comment by jmbourdaret** [comment]
> @jmbourdaret I think we fixed it with your PR, right ? #3660

Ce bug de l'encoding, + la possibilité de modifier/enregistrer _sans_ confirmer le user me font penser a une ancienne version,
et au fix qu'avait fait Ivanne ici : #3410

Pour résumer: je dirais:
- < 20.1.2
   bug encoding/bouton confirm
   possibilité de _modifier_ indépendamment de _confirmer_
- 20.1.2 - 22.0.0
  plus de bug encoding
  impossible de _modifier_ indépendamment de _confirmer_ (bouton "Save" grisé tant que le user n'est pas confirmé)
- 22.0.0 ...
  plus de bug encoding
  rétablissement de la possibilité de _modifier_ indépendamment de _confirmer_ 

@MaelREBOUX : quelle version de georchestra avez vous ?

**Comment by fvanderbiest** [comment]
We should probably backport #3660 to `20.1.x` branch.

**Comment by jmbourdaret** [comment]
> We should probably backport #3660 to `20.1.x` branch.

PR #3677 submitted to re-enable the save button.

about the original encoding bug mentioned in the OP, I re-checked, #3410 is already in place on the `20.1.X` branch.

**Comment by fvanderbiest** [comment]
Thanks JM !

**Comment by MaelREBOUX** [comment]
Hâte de tester.
