### ISSUE TITLE
[header] add mapstore home link ?

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#3573]
upcoming mapstore will have a new 'home' entrypoint listing/showing available maps/contexts/etc like upstream mapstore, cf georchestra/mapstore2-georchestra#438

maybe we should add (or replace the actual mapstore link pointing to the map),cf georchestra/mapstore2-georchestra#459 ?

**Comment by fvanderbiest** [comment]
Good question ... I don't know what users want for now.
Would make a good candidate for a GEORIP ;-)

**Comment by fvanderbiest** [comment]
see #3608

**Comment by landryb** [comment]
closed by #3695

**Comment by landryb** [comment]
can confirm that the 'active' behaviour works fine on maps with #3695, thanks @fvanderbiest
