### ISSUE TITLE
ldap-account-mgmt - case-sensivity (java-side) vs case-insensivity (openldap)

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#3626]
Given the following ldap objects to describe an organization:
https://github.com/georchestra/georchestra/blob/master/ldap/docker-root/georchestra.ldif#L378-L398

OpenLDAP o / cn fields are case insensitive, which means we can ldapsearch on o=c2c or o=C2C which will return the same result.

The issue is that the ldap-account-management will try to figure out one object to the other using a lookup into a map:
https://github.com/georchestra/georchestra/blob/master/ldap-account-management/src/main/java/org/georchestra/ds/orgs/OrgsDaoImpl.java#L330 which will return the expected object only if the case matches.

**Comment by pmauduit** [comment]
My guess to solve it would be to add a `toLowerCase()` call here:
https://github.com/georchestra/georchestra/blob/master/ldap-account-management/src/main/java/org/georchestra/ds/orgs/OrgExt.java#L53

But I don't know if this is the cleanest way to do so. @groldan any opinion ?

**Comment by groldan** [comment]
ok that's gonna be an easy fix, but I wonder if it

> My guess to solve it would be to add a `toLowerCase()` call here: https://github.com/georchestra/georchestra/blob/master/ldap-account-management/src/main/java/org/georchestra/ds/orgs/OrgExt.java#L53
> 
> But I don't know if this is the cleanest way to do so. @groldan any opinion ?

Although that looks like an easy fix, the moment you do that, `OrgExt` stops being a pure data object, and you're opening a different can of worms.
