### ISSUE TITLE
[datafeeder] hardcodes resourceType=series

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#3627]
I dunno why this has been made this way, but metadata created via datafeeder hardcode the `series` resource type ('Collection de données'), while so far most of the catalogs we know use `dataset` (eg 'Jeu de données') cf for example https://public.sig.rennesmetropole.fr/geonetwork/srv/fre/catalog.search#/home or https://ids.craig.fr/geocat/srv/fre/catalog.search#/home

why this choice ?

i'm asking this, because by default mapstore2 CSW search applies a filter on `dataset` (cf https://mapstore.readthedocs.io/en/latest/user-guide/catalog/#static-filter-and-dynamic-filter) so not all records are shown from the catalog. Sure, the default CSW filter can be amended....

**Comment by fvanderbiest** [comment]
Good catch, thanks !
We'll have a look at it. Makes no sense to me.

**Comment by jahow** [comment]
The `series` value is hardcoded here FYI: https://github.com/georchestra/georchestra/blob/10c251d197e62244e467fb16b5926f0953a1ad6c/datafeeder/src/main/resources/default_iso_2005_gmd.xsl#L215-L218

**Comment by fgravin** [comment]
Thanks @landryb for pointing this out.

It's weird that the hierachy level is overridden in the XSL transfo
https://github.com/georchestra/datadir/blob/master/datafeeder/metadata_transform.xsl#L223

while correctly set in the template https://github.com/georchestra/datadir/blob/master/datafeeder/metadata_template.xml#L22

I think it is just a mistake while taking a XSL file as inspiration for the transformation.
I let @groldan confirm that, thank you !

**Comment by pmauduit** [comment]
See https://github.com/georchestra/datadir/pull/233 & https://github.com/georchestra/georchestra/pull/3671

**Comment by pmauduit** [comment]
Merged both PR above.
