### ISSUE TITLE
[datafeeder] missing docker image for the frontend part

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#3659]
We only have this `georchestra/datafeeder-frontend:21.0-SNAPSHOT` image for now. Maybe a georchestra/datafeeder-frontend:latest would be relevant ?

**Comment by fvanderbiest** [comment]
Yes for sure !
Thanks Pierre

**Comment by fvanderbiest** [comment]
To be double checked with @jahow 
Thanks !

**Comment by pmauduit** [comment]
One of the questions we had was about the need to keep the georchestra/geonetwork-ui repository recently, as it induces some confusion with the upstream (geonetwork/geonetwork-ui).

It turns out that we will need to keep the repository georchestra/geonetwork-ui, because of the datafeeder ui ; even if this could be considered as a geonetwork project, we will still require the header integration as a needed feature justifying a fork.

So, having this in mind - keeping the fork - then we are free to set whatever github actions to generate the image here.

**Comment by pmauduit** [comment]
ok, done (I took the opportunity to set a tag 22.0.0 already, I don't expect the df frontend to evolve before the release)
