### ISSUE TITLE
mapfishapp - obsolete module should be removed from main repository

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3661]
After release 22.0 is published I plan to remove mapfishapp code from the main repository (master branch), hosting it forever on https://github.com/georchestra/mapfishapp

This means that release 22.1 will not have mapfishapp included and new deployments will not include mapfishapp by default.

This has several consequences to be investigated, eg for the extractorapp addon, which to my knowledge, has no counterpart in the mapstore realm.

**Comment by landryb** [comment]
mapstore has a "download layer" button which uses WPS iirc for reprojection/format.

**Comment by landryb** [comment]
maybe it should be closed only when the code is removed from the repo :)

**Comment by landryb** [comment]
also with #3814 merged

**Comment by fvanderbiest** [comment]
> maybe it should be closed only when the code is removed from the repo :)

Oh gosh, I thought it was already !
More hairy than I thought...

**Comment by fvanderbiest** [comment]
#3815 for a first attempt.
GDPR stuff to be reworked to not expect mapfishapp schema but mapstore's
