### ISSUE TITLE
gn4 - header url is not customizeable

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#3667]
base-layout.xsl hardcodes the target source for the iframe to `/header/`:
https://github.com/georchestra/geonetwork/blob/georchestra-gn4-4.0.6/web/src/main/webapp/xslt/base-layout.xsl#L71

Ignoring the parameters coming from the georchestra datadir.

**Comment by pmauduit** [comment]
Same for mapstore, but the doc indicates the oposite ?!

https://github.com/georchestra/mapstore2-georchestra/blob/5f122b11ee1ead2266e1aa3167719ebfbcd19904/docs/source/configuration/other/index.rst#header-configuration

**Comment by landryb** [comment]
i *think* for ms2-geor it's supposed to be handled by https://github.com/georchestra/mapstore2-georchestra/blob/master/js/plugins/Header.jsx#L36 but i dont remember testing it with a different value for the url. I know on our production setup the header Height is 60px (so different from the default) and it's properly handled.

**Comment by pmauduit** [comment]
I was wondering if it wasn't taking the headers parameters during first config computation, then never updating them afterwards.

looking at my localConfig.json, I can find back the default params:

```
    "header": {
      "height": 90,
      "url": "/header/"
    },
```

**Comment by landryb** [comment]
> I was wondering if it wasn't taking the headers parameters during first config computation, then never updating them afterwards.
> 
> looking at my localConfig.json, I can find back the default params:
> 
> ```
>     "header": {
>       "height": 90,
>       "url": "/header/"
>     },
> ```

yeah those work because i have height:60 in my localConfig.json. Granted, it doesnt use `default.properties` but the user-configurable settings work.

**Comment by pmauduit** [comment]
It actually works with mapstore, not sure if updating the default.properties will do in the localConfig.json, but my issue was that the georchestra datadir was bootstrapped once and then never updated.
