### ISSUE TITLE
console - latin1 not mandatory anymore for properties file

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3708]
https://docs.oracle.com/javase/9/intl/internationalization-enhancements-jdk-9.htm#JSINT-GUID-974CF488-23E8-4963-A322-82006A7A14C7

"Most existing properties files should not be affected: UTF-8 and ISO-8859-1 have the same encoding for ASCII characters, and human-readable non-ASCII ISO-8859-1 encoding is not valid UTF-8. If an invalid UTF-8 byte sequence is detected, the Java runtime automatically rereads the file in ISO-8859-1."

A s a result, this restriction is not useful anymore, since version `22.0.0`
https://github.com/georchestra/datadir/blob/362b3d97d2d10c449889f2efd70c316c4ae45b71/console/console.properties#L1

**Comment by pmauduit** [comment]
2 things can be done to consider this issue as resolved:

* iconv to reencode concerned files from the datadir to UTF-8 (only on master / 22.0.x branch)
* or just remove the comment, as we can't tell which java runtime the user will actually install ...

**Comment by pmauduit** [comment]
I did not `iconv` the file in case some people are still using a former version of Java for the sake of backward compatibility, but removed the comment in console.properties on the 4 branches (master, docker-master, 22.0, docker-22.0).
