### ISSUE TITLE
geonetwork - ldap sync - debug trace not formatted correctly

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#3719]
One can see the following in the logs:

```
2022-04-11 12:47:08,896 DEBUG [org.georchestra.geonetwork.security.authentication] - geOrchestrea pre-auth not provided. URI: %s
```

Typo (s/georchestrea/georchestra/) and missing a .format(...) call probably.

**Comment by fvanderbiest** [comment]
https://github.com/georchestra/geonetwork/blob/37f1b5bb8abd54856b608440fd34f83f178e2d2c/georchestra-integration/georchestra-authnz/src/main/java/org/georchestra/geonetwork/security/authentication/GeorchestraPreAuthenticationFilter.java#L70-L80

**Comment by pmauduit** [comment]
Need two PRs from dependabot, and we should be good for this one.

**Comment by pmauduit** [comment]
dependabot lagged, I did it directly on both branches

Not relevant for 20.1.x serie which is still on gn3.8
