### ISSUE TITLE
gn4 header conflicts with georchestra header

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3733]
![image-2022-04-26-09-21-50-764](https://user-images.githubusercontent.com/265319/165280256-4dbe532f-1bc6-4dca-a729-e76b83a284db.png)

On /geonetwork/srv/fre/catalog.edit#/create the GN admin header masks geOrchestra's header
Same happens while editing a metadata.

**Comment by landryb** [comment]
not new (https://github.com/georchestra/georchestra/issues/3218#issuecomment-884709762), been happening since at least gn 3.8 :)

**Comment by f-necas** [comment]
Not applicable anymore
