### ISSUE TITLE
ldap upgrade notes for 22.0 should be fixed

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#3759]
following https://github.com/georchestra/georchestra/tree/master/migrations/22.0#from-20x-to-22x the two ldap steps to add `georchestraRole` *then* replace `georchestraOrg` & `georchestraUser` result in a schema without `georchestraRole`.

ideally, both operations should be merged - eg replace the `olcObjectClasses` which previously had 2 classes without `georchestraObjectIdentifier` by 3 classes with a `georchestraObjectIdentifier` attribute.

**Comment by landryb** [comment]
to be clearer, https://github.com/georchestra/georchestra/tree/master/migrations/22.0#adding-the-georchestrarole-objectclass-to-the-schema should be done after https://github.com/georchestra/georchestra/tree/master/migrations/22.0#adding-the-identifier-to-the-2-existing-object-classes, or merged in the same ldif..

**Comment by fvanderbiest** [comment]
:+1:

**Comment by pmauduit** [comment]
PR has been merged, closing
