### ISSUE TITLE
datahub search component as default SDI entrypoint ?

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3762]
A long awaited feature IMO... a simple and efficient, lightweight search engine in the home page.

Example datahub implementation: https://dev.geo2france.fr/datahub/search

Opinions ?

**Comment by fvanderbiest** [comment]
cc @fgravin

**Comment by landryb** [comment]
iff all the setup/infra docs are updated to explain how to install/setup/customize the datahub :)

**Comment by fvanderbiest** [comment]
> iff all the setup/infra docs are updated to explain how to install/setup/customize the datahub :)

Elementary, my dear Landry !

**Comment by fgravin** [comment]
I think it would be great to have it as the SDI entry point (by default, usually the organisation set up a CMS for that).
That said, the geo2france datahub does not include the header, I wonder how it would feel with the geOrchestra header on top...
To be discussed as well.

**Comment by fvanderbiest** [comment]
> That said, the geo2france datahub does not include the header, I wonder how it would feel with the geOrchestra header on top...

Good point. There's probably integration work to be done here.
Would it be possible (at the current time) to have a static html page with gn-ui webcomponents for a search bar, results, and dataset description ? My idea is that this static html page would have the georchestra header on top.

The datafeeder app, as it currently exists, targets the general public. There's no interest in having the georchestra header integrated IMO.

**Comment by fvanderbiest** [comment]
See the demos on https://geonetwork.github.io/geonetwork-ui/gn-results-list/demo/webcomponents/index.html
Love it !

- https://geonetwork.github.io/geonetwork-ui/gn-results-list/demo/eea/index.html
- https://geonetwork.github.io/geonetwork-ui/gn-results-list/demo/webcomponents/gn-search-input-and-results.sample.html

**Comment by fvanderbiest** [comment]
> I wonder how it would feel with the geOrchestra header on top...

Well, the geOrchestra header can be included, see eg https://dev.geo2france.fr/datahub/home/news
(regarding this point, a bit of documentation would be good)

**Comment by fvanderbiest** [comment]
Implemented during the Rennes code sprint (February 2023)
eg https://demo.georchestra.org/

**Comment by fvanderbiest** [comment]
Sources for the homepage app are available in the https://github.com/georchestra/homepage repository.
A built version ships with https://github.com/georchestra/htdocs (`index.html` and `_header.js` files).

**Comment by landryb** [comment]
https://demo.georchestra.org/ was just updated from htdocs' repo :)

**Comment by fgravin** [comment]
Thanks @landryb 
Just need now that the backend service of @arnaud-morvan  is deployed then I'll remove the mock and use the real service.

Notice that a real UI designer is free to revamp the whole design, was just a structuring template, cf Agathe :smiley:

**Comment by Gaetanbrl** [comment]
pop @Agath21

**Comment by landryb** [comment]
Fwiw, https://ids.craig.fr doesn't use the new 'homepage', but now redirects to our datahub instance now :)
