### ISSUE TITLE
google closure compiler rather than jsbuild ?

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#378]
... or just as a second pass optimizer after jsbuild...

**Comment by pmauduit** [comment]
:+1: with this move, so that we can have a CI with no extra needed packages. I'd like to have a look on this.

**Comment by pmauduit** [comment]
Impacted webapps:

- [] catalogapp
- [] mapfishapp
- [] extractorapp

**Comment by fvanderbiest** [comment]
I'm not sure we could completely remove the need for jsbuild, since all source files (including openlayers & geoext sources) have the required headers for jsbuild.

**Comment by fvanderbiest** [comment]
We'd better change our viewer to use more modern libraries.

**Comment by pmauduit** [comment]
Could be of interest:

https://github.com/geonetwork/core-geonetwork/commit/da250f9b5ea7e77d6afd939db5f50e4311410d30
