### ISSUE TITLE
CAS6 - could not create plugin of type class org.apache.logging.log4j.core.appender.RollingFileAppender

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3788]
cas_1                                | 2022-08-25 15:01:33,081 main ERROR Could not create plugin of type class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile: java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@34e4fb39] unable to create manager for [/var/log/cas.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$FactoryData@36fe83d[pattern=/var/log/cas-%d{yyyy-MM-dd-HH}-%i.log, append=true, bufferedIO=true, bufferSize=8192, policy=CompositeTriggeringPolicy(policies=[OnStartupTriggeringPolicy, SizeBasedTriggeringPolicy(size=10485760), TimeBasedTriggeringPolicy(nextRolloverMillis=0, interval=1, modulate=false)]), strategy=DefaultRolloverStrategy(min=1, max=7, useMax=true), advertiseURI=null, layout=%d %p [%c] - <%m>%n, filePermissions=null, fileOwner=null]] java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@34e4fb39] unable to create manager for [/var/log/cas.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$FactoryData@36fe83d[pattern=/var/log/cas-%d{yyyy-MM-dd-HH}-%i.log, append=true, bufferedIO=true, bufferSize=8192, policy=CompositeTriggeringPolicy(policies=[OnStartupTriggeringPolicy, SizeBasedTriggeringPolicy(size=10485760), TimeBasedTriggeringPolicy(nextRolloverMillis=0, interval=1, modulate=false)]), strategy=DefaultRolloverStrategy(min=1, max=7, useMax=true), advertiseURI=null, layout=%d %p [%c] - <%m>%n, filePermissions=null, fileOwner=null]]
cas_1                                | 	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:116)
cas_1                                | 	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:100)

**Comment by fvanderbiest** [comment]
task : cleaning the file appender from https://github.com/georchestra/datadir/blob/docker-22.0/cas/config/log4j2.xml

**Comment by fvanderbiest** [comment]
Then, docker-22 to be merged into docker-master

**Comment by pmauduit** [comment]
https://github.com/georchestra/datadir/pull/248 targets the wrong branche, but that's the idea

**Comment by arnaud-morvan** [comment]
Everything has been done by @fvanderbiest this morning
