### ISSUE TITLE
TLS versions support

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3808]
For compatibility we had to explicitly authorize TLS V1 for geoserver:
https://github.com/georchestra/georchestra/blob/f8e67f5fde57f8f089263af72664f081773f8f9e/geoserver/webapp/src/docker/Dockerfile#L48

I'm not sure this is relevant anymore
Also, TLS v1.3 is to be considered I guess.

A bit of history: this was introduced by https://github.com/georchestra/georchestra/commit/18ecf5a511972624a5a2746de543c97dc2de5506 to prevent `Could not list layers for this store, an error occurred retrieving them: Remote host closed connection during handshake` when hitting remote OGC services.

**Comment by edevosc2c** [comment]
If the application support TLS1.3 then only `-Dhttps.protocols=TLSv1.2,TLSv1.3` should be used.

**Comment by fvanderbiest** [comment]
This was my idea too :-)

**Comment by fvanderbiest** [comment]
TLS 1.0 and 1.1 are currently deprecated on all major browsers - https://caniuse.com/tls1-1
