### ISSUE TITLE
docker-compo  - traefik.me certificates have expired 

### ISSUE THREAD

**Issue by ChiranthTL** [georchestra/georchestra#3812]
Hello guys am using the docker version of the GeOrchestra and once i do the docker-compose up. the application gives the error. 
"georchestra-127-0-1-1.traefik.me normally uses encryption to protect your information. When Chrome tried to connect to georchestra-127-0-1-1.traefik.me this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be georchestra-127-0-1-1.traefik.me or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Chrome stopped the connection before any data was exchanged.

You cannot visit georchestra-127-0-1-1.traefik.me right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later." and also the SSL error. it says the SSL has been expired. 

any help would be appreciated.

**Comment by pmauduit** [comment]
I am assuming that you are using the docker composition, and you launched it earlier in the past (you might have bootstrapped it more than 3 months ago). You have to update the traefik-me localhost certificates, this can be done using the following:

``
% docker-compose up traefik-me-certificate-downloader`

```

**Comment by pmauduit** [comment]
Checking from my side, it does seem that the certificate provided on https://traefik.me/ can be the cause.
 

```
% docker-compose up traefik-me-certificate-downloader
Starting docker_traefik-me-certificate-downloader_1 ... done
Attaching to docker_traefik-me-certificate-downloader_1
traefik-me-certificate-downloader_1  | Connecting to traefik.me (54.75.7.115:80)
traefik-me-certificate-downloader_1  | saving to 'traefik.me.crt'
traefik-me-certificate-downloader_1  | traefik.me.crt       100% |********************************|  5596  0:00:00 ETA
traefik-me-certificate-downloader_1  | 'traefik.me.crt' saved
traefik-me-certificate-downloader_1  | Connecting to traefik.me (54.75.7.115:80)
traefik-me-certificate-downloader_1  | saving to 'traefik.me-key.pem'
traefik-me-certificate-downloader_1  | traefik.me-key.pem   100% |********************************|  1704  0:00:00 ETA
traefik-me-certificate-downloader_1  | 'traefik.me-key.pem' saved
docker_traefik-me-certificate-downloader_1 exited with code 0

% openssl x509 -in resources/ssl/traefik.me.crt -noout -text
[...]
        Validity
            Not Before: Jun 28 06:22:12 2022 GMT
            Not After : Sep 26 06:22:11 2022 GMT
        Subject: CN = traefik.me
[...]
            X509v3 Subject Alternative Name: 
                DNS:*.traefik.me, DNS:traefik.me
[...]
```

The certificate expired this morning, and there a no more recent versions for it ... I'm afraid there is not so much we can do for now.

**Comment by ChiranthTL** [comment]
that's very unfortunate...this might take some time to fix right? any workaround you could suggest?

**Comment by pmauduit** [comment]
> that's very unfortunate...this might take some time to fix right?

this is actually fixed, I took contact with the person in charge of traefik.me on twitter,  and he told me that it has been fixed, you should retry by now (in french: https://twitter.com/pyrou/status/1574489444131819522).

**Comment by pmauduit** [comment]
indeed, redoing the previous commands made it:

```
        Validity
            Not Before: Sep 26 18:56:35 2022 GMT
            Not After : Dec 25 18:56:34 2022 GMT
```

**Comment by ChiranthTL** [comment]
@pmauduit Thank you very much for the help...it is working fine..
have a good one ..!

**Comment by pmauduit** [comment]
I used it 2 days ago and the certificates were valid. Unfortunately, they expired today:

```
% openssl x509 -in resources/ssl/traefik.me.crt -noout -text
[...]
            Not Before: Nov 25 09:43:40 2022 GMT
            Not After : Feb 23 09:43:39 2023 GMT
[...]
```

Maybe we will need to wait a bit for renewal ?

**Comment by ChiranthTL** [comment]
OK thanks, when  can i expect this to be done ?

**Comment by pmauduit** [comment]
checked this morning, and they have been updated:

```
% openssl x509 -in traefik.me.crt -noout -dates
notBefore=Feb 23 20:23:11 2023 GMT
notAfter=May 24 20:23:10 2023 GMT
```
