### ISSUE TITLE
geonetwork - remove dcat schema support

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3841]
Experience shows it's far from production-ready

Curretly breaks CSW output with:

```
java.lang.RuntimeException: org.fao.geonet.csw.common.exceptions.InvalidParameterValueEx: code=InvalidParameterValue, locator=OutputSchema, 
message=Error occured while transforming metadata with id '<md id>' using 'csw-full.xsl
```

**Comment by pmauduit** [comment]
* on branch 4.2: already done by @jahow https://github.com/georchestra/geonetwork/commit/1f7b479b95d1775df57beec7e65be635c1e501a1
* on branch 4.6 (only considering the maintenance branch: `georchestra-gn4-4.0.6-22.0.x`), PR on its way.

**Comment by landryb** [comment]
cf/dupe #3720 ?

**Comment by pmauduit** [comment]
indeed, closing the other one

**Comment by pmauduit** [comment]
geonetwork submodule is up-to-date on 22.0.x, closing.
