### ISSUE TITLE
console - broken logs filtering

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3849]
Filtering combos are empty on /console/manager/logs :
![image](https://user-images.githubusercontent.com/265319/202209034-a68b5e0e-85d6-40ab-973f-2e8afc3547f6.png)

Witnessed on 22.0.2

**Comment by landryb** [comment]
it works for me on 22.0.something - but it always takes some time to populate from the somewhat heavy 4Mb json file sent by `/console/private/admin_logs/100000/0` - might want to have a look at your browser console logs to see what happened with this request.

or maybe the platform has zero admin logs ?

**Comment by pmauduit** [comment]
Looks like working on one of our deploys based on 22.0.4 version:

![image](https://user-images.githubusercontent.com/594335/209358312-e0160aa7-422e-49af-96d1-ad9c23259774.png)

But indeed, even with a small amount of events, it takes some time to load.

**Comment by pmauduit** [comment]
Actually the comboboxes look broken on the previous mentioned deployment. But I do'nt know what I can do here to fix this.
