### ISSUE TITLE
header - not responsive

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3867]
800 px width is handled ok:
![image](https://user-images.githubusercontent.com/265319/209538557-59eedffb-5e5a-400c-8b4f-88acaf82edf4.png)

Below not at all.
At 740 px, the login div disappears:
![image](https://user-images.githubusercontent.com/265319/209538674-5a30a71c-4c5b-4468-b9df-5b5cadce4782.png)

At 580 px, everything but the logo disappears:
![image](https://user-images.githubusercontent.com/265319/209538785-11c2bf75-95a6-4da6-a345-eb538875283e.png)

**Comment by fvanderbiest** [comment]
There's no future for the header webapp in its current form

**Comment by landryb** [comment]
> There's no future for the header webapp in its current state
100% agreed, but it's still included via iframe in geoserver/geonetwork/console/mapstore/analytics/etc :) The old header looks so dull and boring now that we have the new shiny one ....

**Comment by f-necas** [comment]
- https://github.com/georchestra/header/pull/11
