### ISSUE TITLE
GeoNetwork - submodule branch on master KO

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3868]
https://github.com/georchestra/georchestra/blob/master/.gitmodules#L12

**Comment by fvanderbiest** [comment]
This is getting critical and misleading IMO.
@jeanpommier was a bit lost when comparing the commit hash with the target branch

**Comment by fvanderbiest** [comment]
There are so many 4.2 branches in https://github.com/georchestra/geonetwork/

Is https://github.com/georchestra/geonetwork/tree/georchestra-gn4.2.x the correct one  to get geonetwork latest ?
We may need some cleaning

**Comment by fvanderbiest** [comment]
If I try to update the geonetwork submodule to 4.2.x, I currently get this warning:
```
fvanderbiest@wrk75:~/workspace/georchestra/georchestra/geonetwork ((d8415e8963...) $%)$ g co georchestra-gn4.2.x
warning: unable to rmdir 'schemas/dcat2': Le dossier n'est pas vide
M	docs/manuals
M	web-ui/src/main/resources/catalog/lib/style/font-awesome
Attention : vous abandonnez 1 commit, non connecté à
une branche :

  d8415e8963 org lastupdated hash now take logo size into account if one

Si vous souhaitez le garder en créant une nouvelle branche, c'est le bon moment
pour le faire avec :

git branch <nouvelle-branche> d8415e8963

La branche 'georchestra-gn4.2.x' est paramétrée pour suivre la branche distante 'georchestra-gn4.2.x' depuis 'origin'.
Basculement sur la nouvelle branche 'georchestra-gn4.2.x'
Chemin de sous-module 'docs/manuals' : 'f56a807578d9527ca77a138e19d3cc7c8edcaac1' extrait
Chemin de sous-module 'web-ui/src/main/resources/catalog/lib/style/font-awesome' : 'a8386aae19e200ddb0f6845b5feeee5eb7013687' extrait
```

**Comment by jahow** [comment]
> Is https://github.com/georchestra/geonetwork/tree/georchestra-gn4.2.x the correct one to get geonetwork latest ?

Yes; I've deleted the other one (`georchestra-gn4-4.2.0`) which was outdated and misleading.

**Comment by jahow** [comment]
Updated https://github.com/georchestra/georchestra/pull/3842 to point to the latest GN 4.2.x branch on geor/gn

**Comment by fvanderbiest** [comment]
Awesome, thanks !
