### ISSUE TITLE
gn-cloud-ogc-api-records-service workflow file

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3872]
Where is georchestra/gn-cloud-ogc-api-records-service docker image workflow located ?

**Comment by fvanderbiest** [comment]
candidate ? 
https://github.com/georchestra/geonetwork-microservices/blob/geor-main/.github/workflows/ci.yaml

**Comment by f-necas** [comment]
https://hub.docker.com/r/georchestra/gn-cloud-ogc-api-records-service
