### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3873]
To facilitate (meta)data discovery by bots, robots.txt should include a link to the sitemap.
See https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap?hl=fr#addsitemap

This should be included in https://github.com/georchestra/htdocs/blob/master/robots.txt:
```
Sitemap: /geonetwork/srv/api/sitemap
```

In the mean time, a call to https://www.google.com/ping?sitemap=https://www.geo2france.fr/geonetwork/srv/api/sitemap may help.

**Comment by jeanmi151** [comment]
This might help a bit but I think the main problem is that almost all the website is dynamically printed with JS, the bot don't have JS execution and just discover static content.

**Comment by fvanderbiest** [comment]
But view-source:https://www.geo2france.fr/geonetwork/srv/api/records/znieff.superf_znieff2?language=all  provides at least the following:
```html
<meta name="description" content="Découpage : commune 2022, Commune 2019, EPCI 2022, EPCI 2020, Canton, arrondissement, Bassin de vie, Zone d'emploi 2020, Zone d'emploi 2010, Unité urbaine, Aire urbaine, Bassin emploi-formation, SCOT approuvé, SCOT en cours, Parc naturel régional, PCAET, espace de dialogue, Département, Ancienne région, Région" />
<meta property="og:title" content="Superficie du territoire couvert par une ou plusieurs znieff de type 2 (km²)" />
<meta property="og:description" content="Découpage : commune 2022, Commune 2019, EPCI 2022, EPCI 2020, Canton, arrondissement, Bassin de vie, Zone d'emploi 2020, Zone d'emploi 2010, Unité urbaine, Aire urbaine, Bassin emploi-formation, SCOT approuvé, SCOT en cours, Parc naturel régional, PCAET, espace de dialogue, Département, Ancienne région, Région" />
<meta property="og:site_name" content="Géo2France" />
<meta property="og:image" content="https://geoterritoires.hautsdefrance.fr/GC_make_map.php?width=800&amp;lang=fr&amp;indics=znieff.superf_znieff2&amp;format=png&amp;" />
 ```

**Comment by fxprunayre** [comment]
The important part of the landing page is 
![image](https://user-images.githubusercontent.com/1701393/210979145-b1e89c29-ca0f-4dae-b14a-292fdd9f41c3.png)
which is used by search engine to categorize the page as a Dataset

See https://github.com/geonetwork/core-geonetwork/pull/3714

**Comment by fvanderbiest** [comment]
https://github.com/georchestra/htdocs/pull/1
