### ISSUE TITLE
datafeeder - support non-geo file types

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3879]
CSV being the first one to consider

**Comment by jeanpommier** [comment]
We could make it rely on OGR to data input: that would enable the support of so many formats in one go.

Combining it with VRT format, this would be a way to take any kind of format and expose to the rest of the process only one same data interface (the VRT).

**Comment by jahow** [comment]
Would GeoTools offer a similar set of formats to read from (esp. non-spatial)? I feel like we're already using GeoTools in several geOrchestra-related projects, and it might be beneficial to build things using the same foundations.

**Comment by jeanpommier** [comment]
I would tend to disagree. I don't think geotools provides such a unified access to data formats. And I don't see the necessity to converge here: this is mostly about getting info from the data then pushing them to a database, so for me  it is quite separate from the other workflows.

I know there is a strong adherence to java in geOrchestra ecosystem, but at least in this case, I believe that trying to rely on geotools is making things complicated.

**Comment by jahow** [comment]
Good points, thanks!

**Comment by landryb** [comment]
> And taking your argument the other way round, I'd say that OGR is very present upstream of the data chain, in QGIS mainly. That would make sens to support for the ingestion all datasets supported by QGIS.

+1, also this could pave the way for a QGIS plugin that would talk to the datafeeder API ;) (*right click on layer*->*publish in georchestra*)

**Comment by f-necas** [comment]
https://github.com/georchestra/georchestra/pull/4137
