### ISSUE TITLE
geOrchestra gateway as security-proxy replacement

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3881]
https://github.com/georchestra/georchestra-gateway should replace the security proxy for the most common use cases.
Questioning the use of the sp-trust-sp feature.

**Comment by landryb** [comment]
I think that'd be a good candidate for a georip ..

**Comment by fvanderbiest** [comment]
Following discussions with the team here + GIP:

- gateway will coexist with security proxy for georchestra 24
- standard deployments will continue using security proxy by default
- georchestra/docker will feature the gateway on branches 24 and master
- the ansible recipe was updated to optionally use the gateway
