### ISSUE TITLE
geoserver extensions - remove community

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3883]
colormap, mbtiles, s3-geotiff, ogcapi, flatgeobuf should be removed from https://github.com/georchestra/georchestra/blob/b96c5b4895043350a06d433c7e57e1e117b9106a/Makefile#L3

* ogcapi breaks WFS 1/2 geojson output
* flatgeobuf badly breaks shp stores

They should not be deployed in a production environnement as such.

**Comment by fvanderbiest** [comment]
Sharing here the French explanation for the flatgeobuf issue:

Quand geoserver va instancier ses datastores, il va chercher quelles classes de geotools peut gérer le datastore en question:
https://github.com/georchestra/geoserver/blob/2.20.4-georchestra/src/main/src/main/java/org/vfny/geoserver/util/DataStoreUtils.java#L95

 flatgeobuff répond présent (alors qu'il ne sait pas gérer les shapefiles), car on a bien un répertoire dans les paramêtres en entrée:
https://github.com/geotools/geotools/blob/main/modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatGeobufDataStoreFactory.java#L96

Et donc on se retrouve avec un FlatGeobufDataStore au lieu d'un ShapefileDatastore. Pourquoi cela fonctionne parfois et pas tout le temps ? car la méthode getAvailableDataStoreFactories() ne garantie pas l'ordre de la collection qui est retournée:
https://github.com/georchestra/geoserver/blob/2.20.4-georchestra/src/main/src/main/java/org/vfny/geoserver/util/DataStoreUtils.java#L92


Si on a de la chance, on va avoir un ShapefileDatastoreFactory, sinon on aura un FlatGeobufDataStoreFactory, qui au final ne saura pas trop quoi faire avec un répertoire de shapefiles ...

**Comment by pmauduit** [comment]
GS issue reported upstream: https://osgeo-org.atlassian.net/browse/GEOS-10824

**Comment by landryb** [comment]
is there a geoserver issue filed for the ogcapi issue with WFS & geojson ? it's a pity this is still a community module...

**Comment by pmauduit** [comment]
> is there a geoserver issue filed for the ogcapi issue with WFS & geojson ? it's a pity this is still a community module... 

Not as far as I am aware of, but during some GS talks at FOSS4G, I can recall that Andrea told it was still in a WIP state, and not really ready for production.
