### ISSUE TITLE
geonetwork - inconsistent behaviour when searching a MD title

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3890]
![image](https://user-images.githubusercontent.com/265319/216332712-5ea4b1a2-b3d6-4665-ae23-bd0d0a2603cc.png)

I've seen in this field the following:

- ```any:(${any}) resourceTitleObject.\*:(${any})^2```
- ```any:(${any}) resourceTitleObject.default:(${any})^2```
- ```any.langfre:(${any}) resourceTitleObject.\*:(${any})^2```

The doc which is linked is not very helpful for newcomers: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html

What would be a sensible default for geOrchestra ?
I've seen a new instance not taking into account metadata keywords, and this query structure had to be tweaked...

**Comment by fvanderbiest** [comment]
https://github.com/georchestra/geonetwork/blob/dc43e9814b0bdcbfef1f4ed172d5018fd25d5508/web-ui/src/main/resources/catalog/js/CatController.js#L179-L200 should be used in https://github.com/georchestra/geonetwork/blob/9b7752a6757a2dbd3b8c0d554ba9d5246daadf87/web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql#L769 according to @jahow

**Comment by fgravin** [comment]
Because of this issue https://github.com/georchestra/georchestra/issues/3918
The index directory is wrong, so I wonder what version of `records.json` do you have, it might also be a reason why the search is not working as expected.
I will wait to have all the correct paths set up correctly before digging in.

**Comment by pmauduit** [comment]
Testing today, it seems working (but still requires to remove / recreate a UI configuration in the admin panel), creating 2 MDD:

Blank search:
![image](https://user-images.githubusercontent.com/594335/233322367-c9b290c9-e9ed-4586-8087-8aab366bfe3a.png)

Exact title search:
![image](https://user-images.githubusercontent.com/594335/233322439-80be95e4-200a-4cd6-9726-d054295caf36.png)

Other search:
![image](https://user-images.githubusercontent.com/594335/233322529-75ba8924-e864-4f34-9d70-01dc35a11095.png)

Partial title search:
![image](https://user-images.githubusercontent.com/594335/233322597-a79804cc-9620-4a8f-abfe-9209e974afa0.png)

**Comment by pmauduit** [comment]
The query string being issued by the UI is different before & after having reinitialized it:

Before refreshing the ui config (returns no result):

```
         "query" : {
            "bool" : {
               "must" : [
                  {
                     "query_string" : {
                        "default_operator" : "AND",
                        "query" : "(any:(street cabinets in metropolitan France) resourceTitleObject.default:(street cabinets in metropolitan France)^2)"
                     }
                  },
                  {
                     "terms" : {
                        "isTemplate" : [
                           "n"
                        ]
                     }
                  }
               ]
            }
         },
```

vs after having regenerated the UI:

```
         "query" : {
            "bool" : {
               "must" : [
                  {
                     "query_string" : {
                        "default_operator" : "AND",
                        "query" : "(any.\\*:(street cabinets in metropolitan France) OR any.common:(street cabinets in metropolitan France) OR resourceTitleObject.\\*:(street cabinets in metropolitan France)^2 OR resourceTitleObject.\\*:\"street cabinets in metropolitan France\"^6)"
                     }
                  },
                  {
                     "terms" : {
                        "isTemplate" : [
                           "n"
                        ]
                     }
                  }
               ]
            }
         },
```

**Comment by pmauduit** [comment]
checking with tcpdump, the JSON payload being received by ES is quite similar to what is constructed by the UI in both cases.

**Comment by fvanderbiest** [comment]
Ok, there's definitely something fishy here...
What would you suggest @jahow @fgravin ? We need something working out of the box ...
Thanks !

**Comment by landryb** [comment]
> I don't get it: if I remove the ui configuration from the admin ui and then I recreate a new one, the settings_ui table is empty afterwards, but the search is then working fine.

in that case that's the default (for the ui config) that applies, and iirc its somewhere in the code ?

**Comment by pmauduit** [comment]
> its somewhere in the code ?

probably, but maybe we should be able to patch the one which is provided by the sql scripts:
https://github.com/georchestra/geonetwork/blob/georchestra-gn4.2.x/web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql#L769

so that we can begin with a working one ?

**Comment by jeanmi151** [comment]
@pmauduit can we close this ?

**Comment by pmauduit** [comment]
> @pmauduit can we close this ?

No not yet, config has to be rewritten to disambiguate which one comes along with which mapstore version

**Comment by jahow** [comment]
@pmauduit I tried to pick this up, to me it looks like the migration notes for 22  > master is addressing the mapstore template issue: https://github.com/georchestra/georchestra/tree/master/migrations/master#link-to-mapstore

Anything else you had in mind?

**Comment by fvanderbiest** [comment]
This is wrong: https://github.com/georchestra/georchestra/commit/e220a864386ae9a336dc7ccc9fccdc433ca71b34
I originally thought the issue came from geonetwork, but nothing changed in GN regarding these parameters.
The change is related to mapstore.
We have to disambiguate which mapstore version supports which query string.
If you could take care of it, that would be awesome :-)

**Comment by pmauduit** [comment]
the doc is wrong right now: it's not about the GN version, but the mapstore version. first pattern is ok with versions issued from the 2021.02.xx, new pattern is ok from mapstore issued from master/ 2022.??? branch (not sure which one).

**Comment by fvanderbiest** [comment]
cc @landryb for hints too. Thanks !

**Comment by landryb** [comment]
there's not much different between https://docs.mapstore.geosolutionsgroup.com/en/latest/developer-guide/map-query-parameters/#add-layers & https://docs.mapstore.geosolutionsgroup.com/en/v2021.02.02/developer-guide/map-query-parameters/#add-layers

**Comment by fvanderbiest** [comment]
> there's not much different between

indeed.

**Comment by jahow** [comment]
Closing this issue as the original topic is not relevant any more; the issue at hand is tracked here: https://github.com/georchestra/georchestra/issues/3958
