### ISSUE TITLE
ldap container warns about password policy

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3900]
Report from https://github.com/georchestra/docker/issues/131:
LDAP container warns about `slap_global_control: unrecognized control: 1.3.6.1.4.1.42.2.27.8.5.1`
see https://www.openldap.org/lists/openldap-software/200606/msg00021.html

**Comment by landryb** [comment]
one needs the ppolicy schema (in addition to the overlay), which is bundled by default iirc

**Comment by landryb** [comment]
mmm maybe the schema needs to be imported in `cn=config` too, since i don't have it under `/etc/ldap/slapd.d/cn=config/cn=schema`. Will recheck, but that's probably an easy fix.

**Comment by landryb** [comment]
i mean, i didnt have to import the ppolicy schema to have that warning go away, only loading the ppolicy module was enough.

**Comment by landryb** [comment]
maybe related to https://github.com/georchestra/georchestra/commit/2d74e3bc4f054ca73a69157159a8d21ec23a63c2#diff-73466bbf3fccee4532560db6fe0f6b704f18d0b1189ea0441ce7ec732bd296f2 ?

**Comment by pmauduit** [comment]
should be fixed by the commit above.
