### ISSUE TITLE
geonetwork latest - No template exists named build-thesaurus-fields

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3918]
On a fresh geonetwork 4.2 instance, when creating the index:
```
geonetwork_1                         | Error at xsl:call-template on line 601 column 62 of index.xsl:
geonetwork_1                         |   XTSE0650: No template exists named build-thesaurus-fields
geonetwork_1                         | 2023-03-28T14:26:25,103 ERROR [geonetwork.index] - Indexing stylesheet contains errors: Failed to compile stylesheet. 1 error detected.
geonetwork_1                         |   Marking the metadata as _indexingError=1 in index
```

**Comment by pmauduit** [comment]
reverting back to a former docker image (e.g. `georchestra/geonetwork:22.0.x`), it works, so it's likely caused by the last merge. It was also working with vagrant-master around 1PM: https://www.georchestra.org/datadir/reports-vagrant/master/GeonetworkSpec/002-001-Being_onto_the__geonetwork__catalogue__I_can_trigger_a_search-GnSearchResults.png

**Comment by pmauduit** [comment]
something is wrong in the way the different parts of the datadirs are calculated:
![image](https://user-images.githubusercontent.com/594335/228305326-e9b250cc-05c6-47aa-939d-280d720ec4be.png)

this is incoherent with the configuration provided by the georchestra datadir (which in case of docker sets the schema_plugin directory to point onto the webapp's subdirectory).

**Comment by pmauduit** [comment]
erasing the /mnt/geonetwork_datadir/config/schema_plugins content with the one from the webapp makes it, but I'd like to understand what we missed here.

**Comment by fgravin** [comment]
I have this error too.

yes the path to the schema_plugin should be to the webapp and not the datadir.

**Comment by pmauduit** [comment]
> And it uses a recent gn4.2.x image

geo2france's geonetwork is running a custom private geonetwork image based on the 4.2.x georchestra version, but older than the merge (the docker image has been built on the 2nd of february).

**Comment by pmauduit** [comment]
I also think that we are bootstrapping a wrong version of the georchestra/geonetwork_minimal_datadir (still in v4.0.6 instead of 4.2.2):

https://github.com/georchestra/geonetwork_minimal_datadir/blob/gn4.0.6/config/schema_plugins/iso19139/index-fields/index.xsl#L578-L584

**Comment by fvanderbiest** [comment]
Good catch Pierre - thanks https://github.com/georchestra/geonetwork/commit/9d735a6f677484b2d569f06fa3a7ba0a698cdc95

**Comment by fvanderbiest** [comment]
tested working
