### ISSUE TITLE
LDAP - missing datafeeder-application user

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3921]
https://github.com/georchestra/datadir/blob/e4f51b7e1748c84d2711e8f68aa73ce7a249f78c/datafeeder/datafeeder.properties#L49 requires a `datafeeder-application` LDAP user.

To be added to https://github.com/georchestra/georchestra/blob/master/ldap/docker-root/georchestra.ldif so that it works out of the box.

**Comment by fvanderbiest** [comment]
Maybe we should reuse geoserver_privileged_user instead, and uncomment https://github.com/georchestra/datadir/blob/e4f51b7e1748c84d2711e8f68aa73ce7a249f78c/datafeeder/datafeeder.properties#L43-L45 instead

**Comment by jeanmi151** [comment]
I guess i can do easily the second option ?

**Comment by fvanderbiest** [comment]
We should definitely give it a try, spin a docker compo and check it works out of the box.
Thanks !

**Comment by jeanmi151** [comment]
created the PR : https://github.com/georchestra/datadir/pull/283

**Comment by jeanmi151** [comment]
done
