### ISSUE TITLE
add user in the ldap for datafeeder

### ISSUE THREAD

**Issue by jeanmi151** [georchestra/georchestra#3952]
now datafeeder is using "testadmin" account but it is a temporary user (should be erase)
so it is needed to add another user only datafeeder application

**Comment by jeanmi151** [comment]
https://github.com/georchestra/datadir/pull/297
https://github.com/georchestra/georchestra/pull/3953

**Comment by fvanderbiest** [comment]
Also required https://github.com/georchestra/geonetwork/pull/236 and https://github.com/georchestra/geonetwork/pull/237
