### ISSUE TITLE
header shows me logged as testadmin (but I'm not)

### ISSUE THREAD

**Issue by jeanpommier** [georchestra/georchestra#3954]
When I start georchestra using the docker compo, I'm shown as logged in as `testadmin`. And the admin links are displayed. But I'm actually not logged in. And I'm getting 404/500 depending on the admin links I click.

![image](https://user-images.githubusercontent.com/4491521/235431094-c797c7d5-5a1e-430b-bed0-99eed3a69bb1.png)

Also happens if I click on log-out and use the link displayed on the logout page.

Clicking on the Import link (non-admin menu) redirects me, as last, to the login page

**Expected behaviour:**

- Shown as not logged in at startup
- clicking on login button opens the login page
- admin menu is not shown as long as I'm not logged in
- admin menu links resolve successfully when I'm logged in

**Reproduce it**
`docker-compose up`, open in the browser.

**Comment by fvanderbiest** [comment]
For the 23.0 release I suggest we patch https://github.com/georchestra/htdocs/blob/master/index.html in order to use the older header in an iframe, as we do [elsewhere](https://github.com/georchestra/georchestra/blob/d9948b9e06fa2b6d059970627a2f891bbbd48000/analytics/src/main/webapp/WEB-INF/jsp/header.jsp#L5-L7)

**Comment by fvanderbiest** [comment]
https://github.com/georchestra/header still needs some work + it should replace /header in every app.
Let's target 23.1 for the new geOrchestra header integration.

**Comment by fvanderbiest** [comment]
See https://github.com/georchestra/htdocs/pull/2 and https://github.com/georchestra/docker/pull/199

**Comment by jahow** [comment]
Note that https://github.com/georchestra/header in its current state now supports fetching the actual user profile; the pain is still fresh but it should work!
