### ISSUE TITLE
[geonetwork] add to map is not working for WFS layer (when configured with Mapstore viewer)

### ISSUE THREAD

**Issue by jeanpommier** [georchestra/georchestra#3957]
When I'm on the metadata record view and I click on the Add to map button for a WFS layer, on the redirection to Mapstore, the layer name is not passed in the URL, I'm seeing something like https://georchestra-127-0-1-1.traefik.me/mapstore/#/?actions=[{"type":"CATALOG:ADD_LAYERS_FROM_CATALOGS","layers":[""],"sources":[{"type":"wfs","url":"https://www.geoportalksk.sk/geoserver/ows"}]}] in the URL.

Which, as should be, is not loading any layer.

According to the Mapstore doc, I would rather espect https://georchestra-127-0-1-1.traefik.me/mapstore/#/?actions=[{"type":"CATALOG:ADD_LAYERS_FROM_CATALOGS","layers":["ksk_gis:okresy_ksk"],"sources":[{"type":"wfs","url":"https://www.geoportalksk.sk/geoserver/ows"}]}] (with the layer name)

Which seems to work fine

**Comment by jahow** [comment]
Maybe related to #3958, could you try reproducing this with `?view=default` in the url? thanks!

**Comment by jeanpommier** [comment]
I will. But I'm pretty sure I did test it using the locally deployed georchestra, that doesn't use the `georchestra` view

**Comment by jeanpommier** [comment]
I confirm: doesn't change a thing, the layers list is still empty in the URL

**Comment by jeanpommier** [comment]
I believe this is related to a snippet in the georchestra view : https://github.com/georchestra/geonetwork/blob/83a493242fb8bde91d9e45c9e4e5e56a4be258c1/web-ui/src/main/resources/catalog/components/common/map/externalviewer.js#L133-L137

**Comment by jeanpommier** [comment]
Oh. Apparently not. But it's not happening when clicking on a WFS link.
And definitely happening when clicking on a WMS link. Weird

**Comment by jeanpommier** [comment]
The [corresponding PR](https://github.com/geonetwork/core-geonetwork/pull/7181) on GN mainstream has been merged today (June 30th), it will be shipped with GN 4.2.5 then

**Comment by fvanderbiest** [comment]
Awesome. Thanks !
We still have not migrated to 4.2.4 on master, to my knowledge.
Might make sense to backport this at the same time.

**Comment by landryb** [comment]
> Awesome. Thanks ! We still have not migrated to 4.2.4 on master, to my knowledge. Might make sense to backport this at the same time.

feel free to start from https://github.com/landryb/geonetwork/tree/georchestra-gn4.2.x **poke** **nudge** **poke** ;)

**Comment by f-necas** [comment]
Implemented in last geor/gn version
