### ISSUE TITLE
Missing migrations notes

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3969]
This directory https://github.com/georchestra/georchestra/tree/master/migrations/master should be renamed into 23.0 both in the `23.0.x` branch and `master`.
And release notes should be updated accordingly.

**Comment by landryb** [comment]
I've updated the relnotes for https://github.com/georchestra/georchestra/releases/tag/23.0.0 to add major highlights & link to upgrade notes

**Comment by jeanmi151** [comment]
Thanks @landryb  
I guess we could recreate an empty README into georchestra/migrations/master for later migration in master branch

**Comment by fvanderbiest** [comment]
> Thanks @landryb I guess we could recreate an empty README into georchestra/migrations/master for later migration in master branch

:+1:

**Comment by jeanmi151** [comment]
I created a new PR : https://github.com/georchestra/georchestra/pull/3970
