### ISSUE TITLE
[geonetwork] GN does not build on master

### ISSUE THREAD

**Issue by jeanpommier** [georchestra/georchestra#3980]
Looking at the GH actions, or when starting a build on a freshly installed computer, the build fails for geonetwork
![image](https://github.com/georchestra/georchestra/assets/4491521/94b1d6f1-264e-4ba8-a4d1-40bf507c9dc9)

I suspect it would work fine on a computer that previously has built geOrchestra with tag 23.0.SNAPSHOT

This is due to the geonetwork [pom file](https://github.com/georchestra/geonetwork/blob/georchestra-gn4.2.x/georchestra-integration/pom.xml#L15) that references `<georchestra.version>23.0-SNAPSHOT</georchestra.version>` when 23.1-SNAPSHOT would be expected

**Comment by fvanderbiest** [comment]
Thanks for your gardening time :-)
