### ISSUE TITLE
[github actions] Do not run image building for pull requests

### ISSUE THREAD

**Issue by edevosc2c** [georchestra/georchestra#3981]
Currently every GitHub actions workflow will try to build a docker image for a pull request: https://github.com/georchestra/georchestra/blob/master/.github/workflows/analytics.yml#L48

This is wrong as a pull request environment do not have access to the github secrets like `secrets.DOCKER_HUB_USERNAME` and it doesn't make sense to build and push a new docker image for a pull request to docker hub.

We should modify the workflows so that building and pushing a new docker image is skipped for pull requests.

Shameless plug, but I like the way this case is handled in geonetwork-ui workflow: https://github.com/geonetwork/geonetwork-ui/blob/main/.github/workflows/artifacts.yml#L26

**Comment by fvanderbiest** [comment]
agreed !
