### ISSUE TITLE
data feeder advertises -0mb as max size

### ISSUE THREAD

**Issue by danduk82** [georchestra/georchestra#4015]
tested on v.23.0 on the docker official composition
![image](https://github.com/georchestra/georchestra/assets/2493436/36b51d2e-7eaa-4b60-99fb-8f3a0497de8f)

**Comment by edevosc2c** [comment]
but works in master branch

**Comment by f-necas** [comment]
[This commit](https://github.com/georchestra/georchestra/commit/479bbbec213c92777fbd2c8f4b4c6e80c3f26e2c) hasn't been added in 23. No file size so we cannot upload a file.

**Comment by fvanderbiest** [comment]
> [This commit](https://github.com/georchestra/georchestra/commit/479bbbec213c92777fbd2c8f4b4c6e80c3f26e2c) hasn't been added in 23. No file size so we cannot upload a file.

So we just need a cherry-pick on 23.0 + new minor relase If I understand correctly ?
Awesome, thanks for the investigation Florian.
