### ISSUE TITLE
Add ability to launch custom scripts before the start of the app

### ISSUE THREAD

**Issue by edevosc2c** [georchestra/georchestra#4030]
# Why

It is becoming a major thing that a lot of clients will ask us to have small modifications over the existing georchestra components.

For instance, Datagrandest mostly have only customized images for their needs.

The downside of maintaining custom images is that it adds maintenance cost, (sometimes confusion) and a big lag with the upstream/official image.

Creating a whole new docker image is not always needed, especially for small modifications.

# Proposed solution

At the geonetwork-ui project, they introduced the ability to execute custom scripts: https://github.com/geonetwork/geonetwork-ui/pull/507

So I propose to have a similar system in place for every docker image that we manage. I'm not entirely sure how to do it, but the ability to specify the directory where all the custom scripts will be executed is a good idea.
This would allow specifying these scripts inside the datadir for example.

Having this functionality will avoid doing "hacky" stuff, especially in the helm chart of georchestra for customizing the container, example:
- https://github.com/georchestra/helm-georchestra/pull/53
- https://github.com/georchestra/helm-georchestra/blob/main/templates/cas/cas-deployment.yaml#L30
- https://github.com/georchestra/helm-georchestra/blob/7bf2c518b64791f44bd9e22bde8848e843081b4c/templates/geonetwork/geonetwork-deployment.yaml#L41
- https://github.com/georchestra/helm-georchestra/blob/7bf2c518b64791f44bd9e22bde8848e843081b4c/templates/geoserver/geoserver-deployment.yaml#L44

# Additional comment

geoserver docker image seems to already support this "script" thing: https://github.com/georchestra/georchestra/tree/master/geoserver/webapp/src/docker/docker-entrypoint.d

On top of that this would fit the need explained by @jeanpommier here: https://github.com/georchestra/helm-georchestra/issues/46#issuecomment-1695733879

--------------

Ping @jeanmi151 @jeanpommier @pmauduit @fvanderbiest

**Comment by jeanmi151** [comment]
Okay after discussion with @edevosc2c , We think something like it is done for geonetwork-ui (datahub) would be a great thing : 
https://github.com/geonetwork/geonetwork-ui/pull/507/files#diff-964be1ec80820060f908f3aec54f46def8145c723a5b8a5bb44b9ec69c76d0c9

Whats we are thinking is : 
1. have a script with a env var (link to a path) that would activate (copy or sylmbolic link) customize webapp  before running the service
2. have a script with a env var (link to a path) that would execute all insider script contained in it
3. we could store this customization script and webressources in the /etc/georchestra/[application_name]/webappp_ressources/ and /etc/georchestra/[application_name]/init_scripts/

Would it be okay with you @jeanpommier  ?

**Comment by jeanpommier** [comment]
Can't it all be covered by the init scripts ? An init script can very well copy the webapp_resources to the right place, can't it ?

**Comment by edevosc2c** [comment]
I have been thinking of backporting these changes to previous georchestra docker images.

As it won't affect the usability/functionalities of the actual components of georchestra.

**Comment by jeanpommier** [comment]
Yup, seems reasonable.

**Comment by jeanpommier** [comment]
About the entrypoint implementation, it might be too soon for that but for the records, I'm pointing to a discussion I had some time ago about the pros and cons of `runparts` vs sourcing the sh scripts, which now might have my preference: https://github.com/dalibo/ldap2pg/pull/381

**Comment by jeanmi151** [comment]
notes of functionnality wanted, in kubernetes deployment the following geoserver files : https://github.com/georchestra/geoserver_minimal_datadir/blob/master/security/usergroup/my_ldap/config.xml#L5
https://github.com/georchestra/geoserver_minimal_datadir/blob/master/security/role/my_ldap/config.xml#L5

They are in bad configuration and we need to modify it by hand, I would be great to have an init script that overwrite this values.

**Comment by fvanderbiest** [comment]
> They are in bad configuration and we need to modify it by hand, I would be great to have an init script that overwrite this values.

Please note the image's entrypoint already tries to do some magic wrt these file:
https://github.com/georchestra/georchestra/blob/b480219326cd4544989aef883d59677419b932ab/geoserver/webapp/src/docker/docker-entrypoint.d/00-geoserver-bootstrap#L13-L15

**Comment by jeanmi151** [comment]
We discussed with @edevosc2c ,  we will create autoscript run for personalization for the following apps:
- security proxy for need for overwrite 404.jsp
- geoserver (for web.xml, and maybe plugings)
- cas (add pluging)
- console (customization of error messages translations)
- header (customization of the style for the header)

if you see others customizations for app I didn't put here please let me know

**Comment by f-necas** [comment]
- [x] security proxy for need for overwrite 404.jsp
- [x] geoserver (already 
- [ ] geonetwork
- [ ] cas (add pluging)
- [x] console (customization of error messages translations)
- [x] header (customization of the style for the header)

**Comment by edevosc2c** [comment]
Additional containers to do in medium priority:
- [ ] smtp
- [ ] database
- [ ] analytics
- [ ] mapstore
- [ ] import
- [ ] datafeeder
- [ ] ogc-api-records

**Comment by edevosc2c** [comment]
merged in master, backport PRs:
- https://github.com/georchestra/georchestra/pull/4106
- https://github.com/georchestra/georchestra-cas-server/pull/19
- datafeeder ui-frontend, no idea??
- https://github.com/georchestra/mapstore2-georchestra/pull/676
- https://github.com/georchestra/mapstore2-georchestra/pull/675
- docker-exim - smtp, no idea???
- ogc-api-records, no idea???

**Comment by edevosc2c** [comment]
Still missing custom scripts on georchestra gateway

**Comment by edevosc2c** [comment]
I'm closing this issue in favor of a separate one in https://github.com/georchestra/georchestra-gateway/issues/127
