### ISSUE TITLE
geonetwork 502 - Server Error

### ISSUE THREAD

**Issue by chocaete** [georchestra/georchestra#4063]
Dear all,

I'm a new user of the Geonetwork, and I recently installed my own data through my server. It was working properly until this week I got this issue:

```
502 - Web server received an invalid response while acting as a gateway or proxy server.
There is a problem with the page you are looking for, and it cannot be displayed.
When the Web server (while acting as a gateway or proxy) contacted the upstream content server, 
it received an invalid response from the content server.
```
Kindly, if someone can help to fix this issue.

Regards,

**Comment by pmauduit** [comment]
The error message you provided does not look like a message coming from a software being used by geOrchestra nor geonetwork. I suspect that you are getting it from your browser, configured to use a proxy.

Don't you have access to raw logs from your geonetwork (e.g. from your servlet container - tomcat, jetty - depending on your setup) ? Is it a geonetwork running from a geOrchestra instance ?
