### ISSUE TITLE
datafeeder - generated metadata displays warning about "keyword not found in thesaurus"

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#4086]
As seen in https://github.com/georchestra/datadir/pull/351 a warning pops up when the resulting metadata is viewed:
![image](https://github.com/georchestra/datadir/assets/265319/c03a8988-7534-4738-abff-1deae14e0e66)

**Comment by f-necas** [comment]
The gemet thesaurus is now embedded (imported) in default geOrchestr'a GN. No more warning.
