### ISSUE TITLE
datafeeder-ui: removal of the folder at georchestra/georchestra

### ISSUE THREAD

**Issue by edevosc2c** [georchestra/georchestra#4105]
It appears that the real component datafeeder ui/frontend is not hosted https://github.com/georchestra/georchestra/tree/master/datafeeder-ui anymore.

But hosted here: https://github.com/georchestra/geonetwork-ui/tree/georchestra-datafeeder under the branch `georchestra-datafeeder`.

I propose to remove the folder https://github.com/georchestra/georchestra/tree/master/datafeeder-ui for avoiding any confusion due to the old version of the component being still there.

**Comment by fvanderbiest** [comment]
Agreed. Go ahead.
Thanks !

**Comment by edevosc2c** [comment]
After discussion with @pmauduit this folder is actually needed for compiling datafeeder import/ui as per explained here: https://github.com/georchestra/georchestra/commit/60c38e8185f92fa70f2655be43bedba499b32dc8

Basically this folder is for compiling the docker image in the repo georchestra/georchestra from the source code located at https://github.com/georchestra/geonetwork-ui/tree/georchestra-datafeeder

So there is no need to compile datafeeder at the repository georchestra/geonetwork-ui like here: https://github.com/georchestra/geonetwork-ui/tree/georchestra-datafeeder/.github/workflows

I'll close this issue as the mystery has been solved.
