### ISSUE TITLE
console - remove orgType

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#4129]
This was introduced long ago, for the pigma project, but there's no use keeping it anymore.

https://github.com/georchestra/datadir/blob/42329afb68ed3b1326f8e696772cf4784a6ba43f/console/console.properties#L147-L149 could be removed as well.

**Comment by landryb** [comment]
well, we use it for various purposes :)

**Comment by fvanderbiest** [comment]
Oh ... could you describe ?

I find this feature very clumsy currently. 
Having to manage a static list of types in a config file does not sound very 2024-proof.

In addition, it's used nowhere else in geOrchestra.

**Comment by landryb** [comment]
in the automaton that distributes data to orgs in nextcloud, some 'products' are meant to be given only to some orgs so i have such kind of contraints:
```
  constraints:
    not_type_org: ["Etablissement d'enseignement et de recherche", "SA sous contrôle d'Etat à but non lucratif"]
    roles: ["DONNEES_MAJIC"]
```
it's also used to have some stats & do some reporting on the repartition/distribution of orgtypes across our 1150 orgs, via the csv export & excel...

**Comment by fvanderbiest** [comment]
Interesting. 
At least someone is making use of it :-)

Mixed feelings about this one...
It clutters everyone's view, but proves useful to one instance.

Ideally, it should be improved so that org types are not in a config file, but manageable through a web ui.

**Comment by fvanderbiest** [comment]
won't do, community uses it.
Sorry for the noise.
