### ISSUE TITLE
geonetwork - group sync mode documentation is outdated

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#4161]
The documentation on GeoNetwork groups synchronisation (either with geOrchestra roles or geOrchestra orgs) which is located in https://github.com/georchestra/georchestra/blob/master/docs/geonetwork-synchronization.md is outdated, since we now have a dedicated setting to this end:
https://github.com/georchestra/datadir/blob/a7b903b152891c56c0db5f1b5f9166492dffdf10/geonetwork/geonetwork.properties#L25-L37

**Comment by f-necas** [comment]
Updated here : https://github.com/georchestra/georchestra/blob/24.0/docs/geonetwork-synchronization.md

See PR : https://github.com/georchestra/georchestra/pull/4188
