### ISSUE TITLE
geonetwork - issues with tomcat7

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#418]
See this thread for more details https://groups.google.com/forum/#!topic/georchestra-dev/a1lz1sWFBSU

**Comment by pmauduit** [comment]
Mainly caused by the calls to ServletContext.getRealPath(".") that return null on tomcat7,8. I did not encounter other issue from my georchestra debian packages-powered vm, from what I remember.

**Comment by fvanderbiest** [comment]
We'd like to finish this one for the 15.06 release.
@pmauduit, can you tell us if it is already fixed on master, or what has to be done ? Thanks.

**Comment by pmauduit** [comment]
No idea of the current status, it will require some time to test it out

**Comment by fvanderbiest** [comment]
Should be fixed now, since we tested sucessfully MD creation and editing in a vm with debian 8.
