### ISSUE TITLE
non-gateway header shows undefined undefined instead of givenname/firstname

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#4210]
seen on demo.georchestra.org which uses the s-p and not the gateway, the s-p returns this for `/whoami`:
```
{
  "GeorchestraUser": {
    "roles":
       "ROLE_SUPERUSER",
       "ROLE_MAPSTORE_ADMIN",
       "ROLE_USER",
       "ROLE_ADMINISTRATOR",
       "ROLE_GN_ADMIN",
       "ROLE_EMAILPROXY"
    ],
    "username":"testadmin"
  }
}
```
this comes from https://github.com/georchestra/georchestra/blob/master/security-proxy/src/main/java/org/georchestra/security/Proxy.java#L371 and doesn't contain firstname/lastname which are consumed by the new webcomponent header

the gateway apparently returns much more things for `whoami`:
https://github.com/georchestra/georchestra-gateway/blob/master/gateway/src/main/java/org/georchestra/gateway/app/GeorchestraGatewayApplication.java#L81

there's no such thing as userMapper in the s-p/georchestra code ?

**Comment by landryb** [comment]
![image](https://github.com/georchestra/georchestra/assets/3421760/b0882740-53f8-4fc9-8914-8fb828751c41)

is the user experience

**Comment by pmauduit** [comment]
Here is the layout of a /whoami response from a gateway:

```
GeorchestraUser: {
  username: "pmauduit",
  roles: [
    "ROLE_SUPERUSER",
    "ROLE_GN_ADMIN",
    "ROLE_USER",
    "ROLE_ADMINISTRATOR"
  ],
  organization: "C2C",
  id: "d5f1491a-f5f8-4998-ae51-76cff38d500a",
  lastUpdated: "7c81fd7e1d81b233fc6ce3550f908a82cddc02dc6a725b6aa1e6c533f93b5c3d",
  firstName: "Pierre",
  lastName: "Mauduit",
  email: "pierre.mauduit@xxx",
  postalAddress: null,
  telephoneNumber: "+336123456",
  title: null,
  notes: null,
  ldapWarn: false,
  ldapRemainingDays: null,
  oauth2Provider: null,
  oauth2Uid: null
}
```
