### ISSUE TITLE
LDAP - remove l field in georchestra.ldif  

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#4226]
testuser still features an "l" field with an EWKT, was previously used with geofence - but I think this is not relevant anymore.
  
https://github.com/georchestra/georchestra/blob/b166236d8808ff8ed8ab3778f56bf510a11e9c30/ldap/docker-root/georchestra.ldif#L25

**Comment by pmauduit** [comment]
> (with an extra caution about #4222)

the json fixtures being used in the tests (https://github.com/georchestra/georchestra/blob/master/ldap-account-management/src/test/resources/defaultUsers.json#L2-L18) do not contain the 'l' attribute, so I think we are pretty safe.
