### ISSUE TITLE
accentuated chars from shared.maven.filters are not correctly displayed once replaced

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#479]
To reproduce: `shared.instance.name=GéoPicardie` in build_support/shared.maven.filters (UTF-8 file)

In mapfishapp, the page title source is displayed as:

```
<title lang="fr" dir="ltr">Visualiseur - GÃÂ©oPicardie</title>
```

The JSP: https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/filtered-resources/WEB-INF/jsp/index.jsp#L75

The maven filter:
https://github.com/georchestra/georchestra/blob/master/config/defaults/mapfishapp/maven.filter#L3

**Comment by pmauduit** [comment]
About this issue:
http://openjdk.java.net/jeps/226

(proposed for JDK9 anyway ... and obsoleted by my GeorchestraConfiguration class in my own branch, which already considers property files that it loads as UTF-8 text documents)

**Comment by fvanderbiest** [comment]
Shared maven filters will soon be removed.
Closing.
