### ISSUE TITLE
geOrchestra - validate on Apache Tomcat 7.x

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#504]
Existing issues:
 * geonetwork #418 
 * sec-proxy
 * ldapadmin #913 

From http://tomcat.apache.org/whichversion.html ...

Apache Tomcat 7.x builds upon the improvements made in Tomcat 6.0.x and implements the Servlet 3.0, JSP 2.2, EL 2.2 and Web Socket 1.0 specifications. 

In addition to that, it includes the following improvements:
* Web application memory leak detection and prevention
* Improved security for the Manager and Host Manager applications
* Generic CSRF protection
* Support for including external content directly in a web application
* Refactoring (connectors, lifecycle) and lots of internal code clean-up

**Comment by fvanderbiest** [comment]
LDAPadmin is also having issues with tomcat7, see https://github.com/georchestra/georchestra/pull/913

**Comment by fvanderbiest** [comment]
This becomes an important issue since tomcat6 has been removed from Debian Jessie: https://packages.debian.org/jessie/tomcat6

**Comment by pmauduit** [comment]
it seems that in order to have the security-proxy working in tomcat 7, just remove the servlet-mapping for `default` server-name:

https://github.com/georchestra/georchestra/blob/14.12/security-proxy/src/main/webapp/WEB-INF/web.xml#L106

To be tested more thoroughly though ... (tbh, I can't explain why yet, and I'd like to ...)

**Comment by pmauduit** [comment]
This commit fixes the issue with security-proxy (tested into a puppetized vm): https://github.com/pmauduit/georchestra/commit/a251a99cdfbfcc2d4341429843ccb60246783b75

**Comment by fvanderbiest** [comment]
This is huge, thanks Pierre !

Unfortunately, your [commit](https://github.com/pmauduit/georchestra/commit/a251a99cdfbfcc2d4341429843ccb60246783b75) is hard to read due to formatting. Can you split it into 2 commits and push this to master ? Thanks !

**Comment by pmauduit** [comment]
https://github.com/georchestra/georchestra/pull/962

**Comment by fvanderbiest** [comment]
All issues linked to the current one being fixed, closing.
