### ISSUE TITLE
mapfishapp - show generated styles in the styles list 

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#505]
Currently, the style list does not show the styles which have been generated by mapfishapp and applied to the layer.

![capture du 2013-12-01 14 12 30](https://f.cloud.github.com/assets/265319/1650420/73a6d8a2-5a8a-11e3-9879-1a9c69cbd4ab.png)

Would be nice to have each generated style referenced, next to the "official" server-side styles.

**Comment by MaelREBOUX** [comment]
+1 not clear for the users, actually.

**Comment by lecault** [comment]
In 16.12 (and before I think) by default mapfishapp says that is not style to a layer (cf screenshot).

![no_styling](https://user-images.githubusercontent.com/5269430/30382379-3e73c22e-989f-11e7-8cdd-b5b2d1f69f98.PNG)
