### ISSUE TITLE
mapfishapp: don't show 'download data' in actions menu if not using extractorapp

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#549]
For some reason one might not use extractorapp - in that case, it'd be nice to avoid adding the 'download data' (via a GEOR.config.extractorapp boolean ?) item in the layer context menu (in GEOR_managelayers.js, createMenuItems()) - or allow submitData() callback to have something configurable, instead of hardcoding a POST to /extractorapp/. I know i can still rewrite that in my reverse proxy to whatever i want, but still..

**Comment by fvanderbiest** [comment]
With 6552aa5ee114906aec7b8a0f888a61da102caf81 the "download data" action is not shown unless the extractor addon is available and loaded
