### ISSUE TITLE
analytics - improve performance on big logs

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#556]
When the ogc-statistics database gets huge, analytics takes too much time to display the stats.

**Comment by fvanderbiest** [comment]
@Vampouille is the "Hero of the Day", see http://www.postgresql.org/docs/9.1/static/ddl-partitioning.html

**Comment by Vampouille** [comment]
I saw several indexes on log table, maybe we can speed up insertion by removing those indexes (for example : layer, service)

**Comment by fvanderbiest** [comment]
+1, thanks

**Comment by Vampouille** [comment]
I just finish some tests with 6M records on my desktop. Query duration change from 2500ms to 80ms with following modifications :
  * create a hierarchy of tables (inherited postgres tables) on date field (partitions)
  * remove execution of prepared statements and replace with native query : executeQuery()
  * I also remove all indexes
I think I will commit those changes in the beginning of next week.

**Comment by fvanderbiest** [comment]
Mostly done with https://github.com/georchestra/georchestra/commit/ad0ba48455d03f561336b8fd9688ff33e0fc86cf but not yet merged into master.
