### ISSUE TITLE
Use the preferred language, as advertised by the browser

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#589]
Currently, geOrchestra has a shared maven filter to set the platform-wide default UI lang (see for instance https://github.com/georchestra/template/blob/master/build_support/shared.maven.filters#L42, overriding https://github.com/georchestra/georchestra/blob/master/config/shared.maven.filters#L10)

In some apps, the user may choose to override this setting by adding ?lang=xx in the URL.

The CAS, ldapadmin and geoserver webapps do not comply to this rule. 
Instead, they detect the user-preferred  lang, as advertised by the browser.

IMO, geOrchestra should apply the same strategy as ldapadmin & geoserver across all the webapps, ie: detect the user-preferred lang, and use it as the default UI lang.

`shared.language` could persist as a default language to use if we cannot offer UI strings translations in any of the user preferred languages.

Opinions ?

**Comment by fvanderbiest** [comment]
In a first approach, we'd like our webapps to automatically display localized strings according to the user's prefered lang (as set in his browser), defaulting to english if lang is not available. Letting the user change the UI lang is out of this issue's scope.

This applies to the following apps:
 * analytics
 * console
 * extractorapp
 * geonetwork 3.4
 * header
 * mapfishapp
 * security-proxy

**Comment by fvanderbiest** [comment]
Server-side detection:
 * header
 * security-proxy

Client-side detection:
 * analytics
 * extractorapp
 * mapfishapp
 * console

Unknown:
 * geonetwork 3.4

**Comment by fvanderbiest** [comment]
Example logic ...
![2017-12-19 15 58 02](https://user-images.githubusercontent.com/265319/34163074-06e855c6-e4d6-11e7-85c7-70e0963c0186.jpg)

A basic implementation with 211779bee28da6be832b4b8a6ba89137c5050a68

**Comment by Vampouille** [comment]
Security proxy already use browser 'Accept Language' configuration to select language of error pages like 'Resource not found'.

**Comment by fvanderbiest** [comment]
Relies on having GN 3.4 #1611 in geOrchestra 17.12
