### ISSUE TITLE
styler - missing SLD_VERSION

### ISSUE THREAD

**Issue by fphg** [georchestra/georchestra#636]
According to the SLD 1.1.0 spec, a DescribeLayer request shall use the mandatory sld_version parameter (sld_version=1.1.0). See p.11 table 1.

**Comment by landryb** [comment]
Fwiw - this hardcoded "/mapfishapp/" in the url, which is bad :)

**Comment by fvanderbiest** [comment]
> Fwiw - this hardcoded "/mapfishapp/" in the url, which is bad :)

yes, we'll have to deal with this at some time ... see https://github.com/georchestra/georchestra/issues/227
