### ISSUE TITLE
analytics - log4j config issue

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#731]
Seems like analytics.log is not historized ...

https://github.com/georchestra/georchestra/blob/master/config/defaults/analytics/WEB-INF/classes/log4j.properties looks OK, but the pom might have issues with log4j-extras version, see https://github.com/georchestra/georchestra/blob/master/analytics/pom.xml#L30-L57

**Comment by pmauduit** [comment]
https://github.com/georchestra/georchestra/pull/863 to sync with other webapps
