### ISSUE TITLE
run all tests on travis 

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#733]

**Comment by fvanderbiest** [comment]
Pierre is shy, so he won't tell everyone, but he succeeded this week-end: https://travis-ci.org/pmauduit/georchestra/builds/49084067

**Comment by pmauduit** [comment]
I'm not shy, it requires some "live running" tests because of huge maven pom.

**Comment by fvanderbiest** [comment]
Just kidding ;-)

**Comment by pmauduit** [comment]
And I want to finish with maven, to have a suitable generated site (coverage, test results, javadoc, ...)
