### ISSUE TITLE
proxy - check referer matches shared.server.name

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#755]
Currently: http://sdi.georchestra.org/proxy/?url=http://www.lemonde.fr

Expected: only the SDI applications should be able to use the OGC proxy.

**Comment by Vampouille** [comment]
We cannot make better filtering in security proxy code. So I think it's better to keep filtering in webserver configuration.

**Comment by fvanderbiest** [comment]
OK, thanks Julien !
Closing it then.
