### ISSUE TITLE
console - delegated administrators

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#786]
Currently, users belonging to the MOD_LDAPADMIN group have all rights on the LDAP.

Would be nice to have delegated administrators, ie people which have the right to manage users from the organisation(s) they belong to.

Example implementation: users belonging to special group MOD_LDAPADMIN_EL would be able to manage users from the EL_\* groups they belong to.

**Comment by fvanderbiest** [comment]
Here's a new proposal, probably easier to grasp, and probably to implement too (considering our current proxy ACLs): "Every user with the `MOD_LDAPADMIN_DELEGATED` role is granted access to the ldapadmin webapp, where he's able to manage users from his own org, including those which are currently `PENDING`".

Of course, this implies that users having this role are not able to change their own org. Only someone with the `MOD_LDAPADMIN` role is able to do so. 

I was told that people from one Org have to manage not only their own users, but also those from other Orgs (eg: local admin from `CD67` has to manage users from `CO_67123` + `CO_67456` + ...). In which case, we could have Orgs depending on a parent Org. 

An admin of Org `CD67` would thus be granted the ability to manage users from children Orgs such as `CO_67123` + `CO_67456`.

**Comment by fvanderbiest** [comment]
> In which case, we could have Orgs depending on a parent Org.

To be technically validated, considering our current LDAP architecture.

**Comment by fvanderbiest** [comment]
> To be technically validated, considering our current LDAP architecture.

Orgs are currently implemented with a `groupOfMembers` instance referring to an `organization` instance via the `seeAlso` attribute: https://github.com/georchestra/georchestra/blob/16.12/ldap/georchestra.ldif#L204-L221

We should be able to extend the membership to children roles with eg:
```ldif
dn: cn=parent,ou=orgs,dc=georchestra,dc=org
objectClass: groupOfMembers
objectClass: top
cn: parent
businessCategory: REGISTERED
description: 4184,684,9849,7987,797898,5797,579,97,49,797,97
member: uid=testadmin,ou=users,dc=georchestra,dc=org
member: uid=testuser,ou=users,dc=georchestra,dc=org
member: cn=child,ou=orgs,dc=georchestra,dc=org
o: Project Steering Committee
ou: parent
seeAlso: o=parent,ou=orgs,dc=georchestra,dc=org
```

**Comment by Vampouille** [comment]
> We should be able to extend the membership to children Orgs with eg:

We can also use hierarchical definition in LDAP. example of child DN : 
`dn: cn=child,cn=parent,ou=orgs,dc=georchestra,dc=org`

**Comment by fvanderbiest** [comment]
New proposals on https://groups.google.com/forum/#!topic/georchestra/OxFZk3ri3n0

**Comment by fvanderbiest** [comment]
GrandEst chose the following one : "Users with an `ORGADMIN` role are allowed the use of the console, where they can manage a collection of roles in a collection of orgs. Both of these collections are managed by a `SUPERUSER` at the user level."

This is the one we're now implementing.

**Comment by fvanderbiest** [comment]
This is mostly implemented with these PRs https://github.com/georchestra/georchestra/pulls?utf8=%E2%9C%93&q=is%3Apr+console+milestone%3A18.06+

![capture du 2018-04-17 09-34-45](https://user-images.githubusercontent.com/265319/38855016-95e9326e-4222-11e8-8bd2-2ab0bc700e22.png)

Closing
