### ISSUE TITLE
mapfishapp - support REST WMTS

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#841]
eg for http://wmts.geo.admin.ch/1.0.0/WMTSCapabilities.xml?REQUEST=GetCapabilities&SERVICE=WMTS&VERSION=1.0.0

We currently only support KVP, eg http://tile.geobretagne.fr/gwc02/service/wmts?REQUEST=GetCapabilities&SERVICE=WMTS&VERSION=1.0.0

**Comment by pmauduit** [comment]
:+1:
