### ISSUE TITLE
extractorapp - Protected layers extraction fails

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#850]
Even if the credentials for the geoserver_privileged_user are passed to the HTTPClient used to get the featuretypes, these are somehow discarded by GeoTools while creating the datastore.

**Comment by fvanderbiest** [comment]
Jesse, did you make any progress on this ?

**Comment by fvanderbiest** [comment]
Related discussion http://jira.codehaus.org/browse/GEOS-3967?focusedCommentId=280275&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-280275

**Comment by fvanderbiest** [comment]
@fphg Pierre thinks that this quick patch fixes the issue. 
https://github.com/pmauduit/georchestra/commit/d3e5d8d56b8d258b58fafdfc0e1231ce34ad7e56
Would you be able to test it ?

**Comment by pmauduit** [comment]
@fphg FYI I already deployed a patched version on sdi (and tested it with a protected layer in pmauduit_test workspace)

**Comment by fvanderbiest** [comment]
Closed on 14.12 as a result of https://github.com/georchestra/georchestra/pull/915
