### ISSUE TITLE
geonetwork_minimal_datadir - resolve conflicts 

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#853]
Several files have been edited on both sides (https://github.com/georchestra/geonetwork/tree/georchestra-14.12/web/src/main/webapp/WEB-INF/data and https://github.com/georchestra/geonetwork_minimal_datadir)

Meld is a great tool in order to spot the differences...
See https://github.com/georchestra/geonetwork_minimal_datadir/blob/master/README.md for a short explanation.

I think that files which were edited on both sides need to be merged.

**Comment by pmauduit** [comment]
After some local manual tests on my dev instance, I think it is ready to go.

**Comment by fvanderbiest** [comment]
Thanks a lot Pierre.

@fphg , would you be able to make a review of the new https://github.com/georchestra/geonetwork_minimal_datadir/ repository changes ?

When everyone agrees on it, we'll be able to remove https://github.com/georchestra/geonetwork/tree/georchestra-14.12/web/src/main/webapp/WEB-INF/data and make it submodule to geonetwork_minimal_datadir

**Comment by fvanderbiest** [comment]
No feedback from @fphg and others means we can remove https://github.com/georchestra/geonetwork/tree/georchestra-14.12/web/src/main/webapp/WEB-INF/data for the release ?
