### ISSUE TITLE
mapfishapp - javax.servlet:servlet-api:jar:2.3 related warning

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#862]
When running mapfishapp master with jetty:

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Mapfishapp Webapp 14.12-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> maven-jetty-plugin:6.1.26:run (default-cli) @ mapfishapp >>>
[WARNING] The POM for javax.servlet:servlet-api:jar:2.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
```

Our pom currently references v2.4
```
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>servlet-api</artifactId>
      <version>2.4</version>
      <scope>provided</scope>
    </dependency>
```
see https://github.com/georchestra/georchestra/blob/master/mapfishapp/pom.xml#L76-L81

**Comment by pmauduit** [comment]
I cannot find the warning on my instance:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Mapfishapp Webapp 14.12-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> maven-jetty-plugin:6.1.26:run (default-cli) @ mapfishapp >>>
Downloading: https://oss.sonatype.org/content/groups/jetty/org/mapfish/print/print-lib/2.0-SNAPSHOT/maven-metadata.xml
Downloading: http://scala-tools.org/repo-releases/org/mapfish/print/print-lib/2.0-SNAPSHOT/maven-metadata.xml
Downloading: http://sdi.georchestra.org/maven/repository/org/mapfish/print/print-lib/2.0-SNAPSHOT/maven-metadata.xml
Downloading: http://dev.mapfish.org/maven/repository/org/mapfish/print/print-lib/2.0-SNAPSHOT/maven-metadata.xml
Downloading: http://sdi.georchestra.org/maven/repository/org/georchestra/epsg-extension/14.12-SNAPSHOT/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/groups/jetty/org/georchestra/epsg-extension/14.12-SNAPSHOT/maven-metadata.xml
Downloading: http://dev.mapfish.org/maven/repository/org/georchestra/epsg-extension/14.12-SNAPSHOT/maven-metadata.xml
Downloading: http://scala-tools.org/repo-releases/org/georchestra/epsg-extension/14.12-SNAPSHOT/maven-metadata.xml
Downloading: http://sdi.georchestra.org/maven/repository/org/georchestra/root/14.12-SNAPSHOT/maven-metadata.xml
Downloading: http://dev.mapfish.org/maven/repository/org/georchestra/root/14.12-SNAPSHOT/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/groups/jetty/org/georchestra/root/14.12-SNAPSHOT/maven-metadata.xml
Downloading: http://scala-tools.org/repo-releases/org/georchestra/root/14.12-SNAPSHOT/maven-metadata.xml
[INFO] 
[INFO] --- git-commit-id-plugin:2.1.10:revision (default) @ mapfishapp ---
[INFO] 


```

**Comment by fvanderbiest** [comment]
Indeed there was rubbish in my ~/.m2/repository/javax/servlet/servlet-api/2.3 folder
I deleted it, and build again:

[INFO] >>> maven-jetty-plugin:6.1.26:run (default-cli) @ mapfishapp >>>
Downloading: http://sdi.georchestra.org/maven/repository/javax/servlet/servlet-api/2.3/servlet-api-2.3.pom
Downloading: http://dev.mapfish.org/maven/repository/javax/servlet/servlet-api/2.3/servlet-api-2.3.pom
[WARNING] Checksum validation failed, expected 5a7b9bcc0517b8fc785f306518b66616d9339548 but is eedbd26c2c25be8a2f2268cdaa03248fc05df4d9 for http://dev.mapfish.org/maven/repository/javax/servlet/servlet-api/2.3/servlet-api-2.3.pom
[WARNING] Checksum validation failed, expected 5a7b9bcc0517b8fc785f306518b66616d9339548 but is eedbd26c2c25be8a2f2268cdaa03248fc05df4d9 for http://dev.mapfish.org/maven/repository/javax/servlet/servlet-api/2.3/servlet-api-2.3.pom
Downloaded: http://dev.mapfish.org/maven/repository/javax/servlet/servlet-api/2.3/servlet-api-2.3.pom (2 KB at 5.0 KB/sec)
[WARNING] The POM for javax.servlet:servlet-api:jar:2.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details


Looks like http://dev.mapfish.org/maven/repository/javax/servlet/servlet-api/2.3 is invalid ...

**Comment by pmauduit** [comment]
Anyway, the warning could be from my PoV ignored, because servlet-api is ("has to be", more exactly) provided by the application server (jetty | tomcat), it is only used here at a compilation level, but excluded from the generated war.

**Comment by fvanderbiest** [comment]
This is indeed a minor issue, but it would be cleaner to fix it.

**Comment by pmauduit** [comment]
I don't have the behaviour at home either

**Comment by fvanderbiest** [comment]
I have uploaded the pom from http://mvnrepository.com/artifact/javax.servlet/servlet-api/2.3 to http://sdi.georchestra.org/maven/repository/javax/servlet/servlet-api/2.3/servlet-api-2.3.pom

Now the build has no warning, but http://dev.mapfish.org/maven/repository/javax/servlet/servlet-api/2.3/servlet-api-2.3.pom should be fixed.
