### ISSUE TITLE
downloadform: integrate into extractorapp ?

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#868]
The question is open, since GeoNetwork now has its own (better) download service (`file.disclaimer`), with dynamic licence agreement.

eg:
![capture du 2015-01-09 11 05 11](https://cloud.githubusercontent.com/assets/265319/5678130/681ed2e8-97ef-11e4-9fd3-9e8aa8b2ee2b.png)

**Comment by pmauduit** [comment]
+:1 downloadform involves its specific webapp with its own connections to the db, where it could be actually shared into existing the webapps (to be checked but extractorapp has already access to the georchestra postgresql db ?)

**Comment by fvanderbiest** [comment]
not relevant anymore
