### ISSUE TITLE
analytics: truncated layername when using QGIS as client (and LAYERS is the last WMS parameter)

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#877]
With current git HEAD, if i enable ogcstatistics, it seems the layername is mangled when a hit is registered:

this request:
```
statistics [INFO] anonymousUser|2015/01/14|http://localhost:8280/geoserver/wmsproxy/ows?BBOX=690065.87968665186781436%2C6458312.91811999119818211%2C723727.49425997096113861%2C6484785.49440503865480423&CRS=EPSG%3A2154&MAP_RESOLUTION=96&SERVICE=WMS&HEIGHT=939&REQUEST=GetMap&STYLES=&DPI=96&WIDTH=1194&TRANSPARENT=TRUE&VERSION=1.3.0&FORMAT=image%2Fpng&FORMAT_OPTIONS=dpi%3A96&LAYERS=ortho_2013|
```

results in the DB:
```
 anonymousUser | 2015-01-14 | WMS     | ortho_201 |  1 | getmap  |

```

ortho_2013 is only registered as ortho_201. That seems to be because LAYERS is the last param of the query... this is with qgis as wms client. If i use mapfishapp as wms client, the layername is correctly registered:
```
 statistics [INFO] testadmin|2015/01/14|http://localhost:8280/geoserver/wmsproxy/ows?CRS=EPSG%3A3857&BBOX=-2529148.3891107%2C3732572.9680109%2C-1227884.4195838%2C5033836.9375379&SERVICE=WMS&HEIGHT=532&REQUEST=GetMap&STYLES=&WIDTH=532&EXCEPTIONS=XML&TRANSPARENT=TRUE&VERSION=1.3.0&FORMAT=image%2Fpng&LAYERS=ortho_2013&SLD_VERSION=1.1.0|geOrchestra
```
results in
```
...
 testadmin     | 2015-01-14 | WMS     | ortho_2013              | 11 | getmap          | geOrchestra
 testadmin     | 2015-01-14 | WMS     | ortho_2013              | 12 | describelayer   | geOrchestra
 testadmin     | 2015-01-14 | WMS     | ortho_2013              | 13 | getmap          | geOrchestra
...
```

**Comment by fvanderbiest** [comment]
Never seen that before ! Thanks for the report.

**Comment by landryb** [comment]
Probably just a parsing issue or a buffer sized too short somewhere..

**Comment by landryb** [comment]
Wild guess, somewhere around here https://github.com/georchestra/georchestra/blob/master/ogc-server-statistics/src/main/java/org/georchestra/ogcservstatistics/log4j/OGCServiceParser.java#L254

**Comment by pmauduit** [comment]
Wondering why not rewriting the code to use a URL lib to parse the request uri. Trying to do it manually is error-prone.

**Comment by fvanderbiest** [comment]
To my knowledge, this was coded in a hurry ... so: refactoring welcome.

**Comment by fvanderbiest** [comment]
Bumping to 16.06 since we had no time to dedicate to this one.
PR's welcome.

**Comment by landryb** [comment]
If someday i manage to deploy analytics, i'll probably try to fix this one too..

**Comment by fvanderbiest** [comment]
Witnessing the same behavior today on master... (layer `opendata:ortho_2012_rgb` or simply `ortho_2012_rgb` if server from /geoserver/opendata/ows)

![screenshot from 2016-10-11 03-43-18](https://cloud.githubusercontent.com/assets/265319/19256220/0a24eef6-8f65-11e6-9e19-d333e8cebff6.png)
