### ISSUE TITLE
ldap - indexes

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#881]
Every 30 seconds, geonetwork fetches groups and users from the LDAP:

```
ldap_1         | 54b79cfb conn=1003 op=25 SRCH base="ou=users,dc=georchestra,dc=org" scope=1 deref=3 filter="(&(objectClass=*)(mail=*@*)(givenName=*))"
ldap_1         | 54b79cfb <= mdb_substring_candidates: (mail) not indexed
ldap_1         | 54b79cfb conn=1003 op=25 SEARCH RESULT tag=101 err=0 nentries=4 text=
ldap_1         | 54b79cfc conn=1003 op=26 SRCH base="ou=groups,dc=georchestra,dc=org" scope=1 deref=3 filter="(&(objectClass=groupOfNames)(cn=el_*))"
ldap_1         | 54b79cfc <= mdb_substring_candidates: (cn) not indexed
ldap_1         | 54b79cfc conn=1003 op=26 SEARCH RESULT tag=101 err=0 nentries=0 text=
```

The above message makes me think that several fields should be indexed by default, to speed up queries.

**Comment by fvanderbiest** [comment]
Quoting http://linux.die.net/man/8/slapindex:
Your slapd(8) should not be running (at least, not in read-write mode) when you do this to ensure consistency of the database.
This command provides ample opportunity for the user to obtain and drink their favorite beverage.

**Comment by fvanderbiest** [comment]
Should be fixed with https://github.com/georchestra/LDAP/pull/7

**Comment by fvanderbiest** [comment]
I'm not sure this fixes "mdb_equality_candidates: (member) not indexed"

**Comment by landryb** [comment]
Hmm i have to admit i didnt see this one in my logs. Any idea what ldap query triggers it ?

**Comment by fvanderbiest** [comment]
This is the query performed by CAS during login, as reported by the docker stack (currently being repaired / migrated to debian packages + "data dir")

**Comment by landryb** [comment]
Oops, of course i dont see it since i already have an index on member/memberUid..

```
olcDbIndex: objectClass eq
olcDbIndex: uid eq
olcDbIndex: mail eq,sub
olcDbIndex: cn eq,sub,subfinal
olcDbIndex: uidNumber,gidNumber eq
olcDbIndex: member,memberUid eq
olcDbIndex: entryUUID,entryCSN eq
```
For georchestra maybe only member is needed, not uidNumber/gidNumber/memberUid

**Comment by fvanderbiest** [comment]
Fixed
