### ISSUE TITLE
geoserver - cannot save layergroup when geofence is activated

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#885]
I can indeed reproduce the bug Florent witnessed while investigating #748 ...

geoserver_1    | 16 Jan 09:08:10 WARN [geoserver.web] - Error adding/modifying layer group.
geoserver_1    | java.lang.NullPointerException
geoserver_1    |        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1124)
geoserver_1    |        at org.geoserver.catalog.impl.ModificationProxyCloner.getDeepestCatalogInfoInterface(ModificationProxyCloner.java:162)
geoserver_1    |        at org.geoserver.catalog.impl.ModificationProxyCloner.clone(ModificationProxyCloner.java:77)
geoserver_1    |        at org.geoserver.catalog.impl.ModificationProxyCloner.cloneCollection(ModificationProxyCloner.java:189)
geoserver_1    |        at org.geoserver.catalog.impl.ModificationProxy.invoke(ModificationProxy.java:110)
geoserver_1    |        at com.sun.proxy.$Proxy66.getLayers(Unknown Source)
geoserver_1    |        at org.geoserver.security.SecureCatalogImpl.checkAccess(SecureCatalogImpl.java:629)
geoserver_1    |        at org.geoserver.security.SecureCatalogImpl.getLayerGroup(SecureCatalogImpl.java:294)
geoserver_1    |        at org.geoserver.catalog.impl.AbstractFilteredCatalog.getLayerGroup(AbstractFilteredCatalog.java:232)
geoserver_1    |        at org.geoserver.catalog.impl.AbstractCatalogDecorator.getLayerGroup(AbstractCatalogDecorator.java:469)
geoserver_1    |        at org.geoserver.catalog.impl.LocalWorkspaceCatalog.getLayerGroup(LocalWorkspaceCatalog.java:156)
geoserver_1    |        at org.geoserver.web.data.layergroup.LayerGroupNewPage.onSubmit(LayerGroupNewPage.java:48)
geoserver_1    |        at org.geoserver.web.data.layergroup.AbstractLayerGroupPage.save(AbstractLayerGroupPage.java:264)
geoserver_1    |        at org.geoserver.web.data.layergroup.AbstractLayerGroupPage.access$500(AbstractLayerGroupPage.java:53)
geoserver_1    |        at org.geoserver.web.data.layergroup.AbstractLayerGroupPage$6.onSubmit(AbstractLayerGroupPage.java:252)

**Comment by pmauduit** [comment]
I've a fix ready, but
  - [ ] Need to test without geofence first
  - [ ] Need to investigate a bit more to be sure it won't have any side-effects

**Comment by pmauduit** [comment]
Without geofence, without my modifications: It does not execute the same java code (no idea why), and the modification of a layer group does not throw any exceptions.

**Comment by pmauduit** [comment]
With geofence, with my modifications, without geofence activated in my datadir: works but #748

**Comment by fvanderbiest** [comment]
> With geofence, with my modifications, without geofence activated in my datadir:

If geoserver is built with geofence, you should update your data dir too.

**Comment by pmauduit** [comment]
> If geoserver is built with geofence, you should update your data dir too.

It was intentional ;-)

**Comment by pmauduit** [comment]
I strongly suspect classpath issues: It seems that different versions of the same classes are defined when GeoServer is activated:

```
$ for i in *.jar ; do echo $i && jar tf $i | grep SecuredFeature ; done 
[...]
gs-main-2.5.4.jar
org/geoserver/security/decorators/SecuredFeatureTypeInfo.class
org/geoserver/security/decorators/SecuredFeatureLocking.class
org/geoserver/security/decorators/SecuredFeatureCollection.class
org/geoserver/security/decorators/SecuredFeatureSource.class
org/geoserver/security/decorators/SecuredFeatureIterator.class
org/geoserver/security/decorators/SecuredFeatureStore.class
gs-ows-2.5.4.jar
gs-platform-2.5.4.jar
[...]
main-2.3.2.jar
org/geoserver/security/decorators/SecuredFeatureTypeInfo.class
org/geoserver/security/decorators/SecuredFeatureLocking.class
org/geoserver/security/decorators/SecuredFeatureCollection.class
org/geoserver/security/decorators/SecuredFeatureSource.class
org/geoserver/security/decorators/SecuredFeatureIterator.class
org/geoserver/security/decorators/SecuredFeatureStore.class
metrics-core-3.0.2.jar
net.opengis.fes-11.4.jar
```

**Comment by pmauduit** [comment]
I think my previous comment is a good guess: without geofence, the packaged geoserver webapp is clean.

**Comment by fgravin** [comment]
Interesting !! I had some issues with different versions of jars in geoserver WEB-INF/lib for both gs-* and gt*.
I fixed that by being sure all versions are updated at any place of georchestra and geofence project.

Geofence geoserver version is set here
https://github.com/georchestra/geofence/blob/81da5a386758176659dcbb953be4c997847af960/src/geoserver/pom.xml#L39

georchestra geoserver & geotools version for /geoserver directory of georchestra are set here:
https://github.com/georchestra/georchestra/blob/master/geoserver/pom.xml#L15

Check if somehow the 2.3.2 is not remaining in any pom.

**Comment by pmauduit** [comment]
> Check if somehow the 2.3.2 is not remaining in any pom.

It is

**Comment by pmauduit** [comment]
Weird, geoserver-template.war from the CI does not contain the 2.3.2 version, it might come from my profile.

**Comment by pmauduit** [comment]
Tested onto sdi.g.o, seems fixed

**Comment by esmailzadeh** [comment]
I used geoserver 2.6.2 with active geofence, please let me know how you fixed this problem
http://stackoverflow.com/questions/31365806/geoserve-crashing-after-adding-geofence-jar-libraries

**Comment by pmauduit** [comment]
@esmailzadeh are you trying to use the "vanilla" version of geofence ? We are using a fork for geOrchestra's needs ; if so, you might consider asking to the geofence team for support.

Anyway, for geOrchestra's needs, here is the PR we had to apply on geofence code to fix our issue:

https://github.com/georchestra/geofence/pull/1

Hope that helps

**Comment by esmailzadeh** [comment]
@pmauduit  
Tanx for your answer
