### ISSUE TITLE
geoserver - check config/defaults files are in line with 2.5.4

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#886]
The files from https://github.com/georchestra/georchestra/tree/master/config/defaults/geoserver-webapp override those from the geoserver webapp. 

They have not been touched since geoserver upgrade => there's probably an issue here ...

**Comment by fvanderbiest** [comment]
I've merged GeoServerBasePage.html with 297c343

But ```georchestra_master_root/config/defaults/geoserver-webapp/WEB-INF/classes/applicationSecurityProxyContext.xml``` and ```geoserver_2.5.4_root/src/main/src/main/java/applicationSecurityContext.xml``` do not have a lot in common.

I need someone to have a look at this.

I'm not sure we need https://github.com/georchestra/georchestra/blob/master/config/defaults/geoserver-webapp/WEB-INF/classes/applicationSecurityContextJDBC.xml anymore.

**Comment by pmauduit** [comment]
> I'm not sure we need https://github.com/georchestra/georchestra/blob/master/config/defaults/geoserver-webapp/WEB-INF/classes/applicationSecurityContextJDBC.xml anymore.

it seems that it can be removed with no harm (tested at runtime, but it isn't source anywhere in the WEB-INF).

**Comment by pmauduit** [comment]
> But georchestra_master_root/config/defaults/geoserver-webapp/WEB-INF/classes/applicationSecurityProxyContext.xml and geoserver_2.5.4_root/src/main/src/main/java/applicationSecurityContext.xml do not have a lot in common.

I think that spring internals automatically sources every files in `WEB-INF/classes/`, and both files are different and do not configure spring security internal classes the same way, hence the differences between them. I cannot find in the conf to be sure of that though.

**Comment by pmauduit** [comment]
In fact, even the file in `WEB-INF/classes/applicationSecurityProxyContext.xml` seems unused now. I tried to remove it and relaunched geoserver, I'm still able to be authenticated.

**Comment by pmauduit** [comment]
I think we can sweep off the default configuration & removing the useless files, and we should be good to go. This won't fix our problems on GS, but that would definitely be a good start.

**Comment by pmauduit** [comment]
files have been removed (see https://github.com/georchestra/georchestra/commit/ad8271b3b6ee4b0cc344c9749330b4a8c8b3b922)
