### ISSUE TITLE
ldapadmin - error removing a group with a space

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#892]
DELETE https://my.sdi.org/ldapadmin/private/groups/XX%20YY

{"error_message":"[LDAP: error code 32 - No Such Object]; nested exception is javax.naming.NameNotFoundException: [LDAP: error code 32 - No Such Object]; remaining name 'cn=XX%20YY,ou=groups'","success":false}

**Comment by fvanderbiest** [comment]
"404 not found" when trying to edit it ...

**Comment by fvanderbiest** [comment]
same as https://github.com/georchestra/georchestra/issues/608

**Comment by f-necas** [comment]
Not applicable anymore, closing
