### ISSUE TITLE
mapfishapp: check if ogc server supports describelayer before querying it

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#898]
Some OGC servers dont support nor advertise the DescribeLayer capability in their getcapabilities. mapfishapp shouldnt force-query describelayer in this case, producing a nasty error popup.

mapserver 6.4 and gwc apparently advertise it (see http://wms.craig.fr/ortho? or http://osm.geobretagne.fr/service/wms?), mapproxy and geoserver doesnt (or should be configured specifically to advertise it - see https://jira.codehaus.org/browse/GEOS-6327 ?) - see http://sdi.georchestra.org/geoserver/ows? or tiles.craig.fr/ortho/service?

**Comment by fvanderbiest** [comment]
With https://github.com/georchestra/georchestra/issues/899 this would be problematic for us.

Better a silent fail for every DescribeLayer request...
