### ISSUE TITLE
Improve the poms

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#900]
In order to have a clean autogenerated site page:
http://sdi.georchestra.org/maven.georchestra.org/staging/index.html

eg:
- Project Information
- Dependencies
- Project Team
- Mailing Lists
- Continuous Integration
- Issue Tracking
- Project License
- Source Repository
- About

**Comment by pmauduit** [comment]
My current working branch: 
https://github.com/pmauduit/georchestra/tree/maven-site-goal

Side effect: it fixes travis-ci ( https://travis-ci.org/pmauduit/georchestra/builds/49210183 )
