### ISSUE TITLE
extjs - prevent browser warning about flash plugin

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#902]
![45e64906-ac92-11e4-87cd-8802fe22917e](https://cloud.githubusercontent.com/assets/265319/6058577/da348226-ad28-11e4-9248-4e2ff24b3fdd.png)

**Comment by fvanderbiest** [comment]
Now I know where this comes from !

https://github.com/probonogeek/extjs/blob/731adf6cdb350f4233ce1645582d4928d6e50af5/src/widgets/chart/swfobject.js#L213-L217

**Comment by fvanderbiest** [comment]
Problem is, except building a custom Ext-all.js file, there does not seem a way to disable this behavior.

**Comment by landryb** [comment]
That's just pure insanity... but also probably related to the fact that we use an oldish extjs ?
Maybe we could benefit from a lighter stripped-down extjs....

**Comment by fvanderbiest** [comment]
> Maybe we could benefit from a lighter stripped-down extjs....

yep, +1

**Comment by AMathews** [comment]
@fvanderbiest Sorry to drop into this old ticket but I wanted to express my appreciation. I am dealing with this exact ExtJS 3 problem in the legacy product I am working on/in. You saved me a ton of time tracking this down. Cheers.

**Comment by fvanderbiest** [comment]
Forking into https://github.com/georchestra/extjs to apply [patch](https://github.com/georchestra/extjs/commit/74d59e25d6cbf868db24bd472fa8604268f7db2a)

**Comment by fvanderbiest** [comment]
Fixed from 16.12 on with the above PR.
@MaelREBOUX is gonna be happy, and he's probably not the only one here ;-)

**Comment by MaelREBOUX** [comment]
Can't wait to test !!
Our customers will be very happy. Some bads feedbacks because of this behaviour.
