### ISSUE TITLE
Bug Geoserver - Emprises natives

### ISSUE THREAD

**Issue by jusabatier** [georchestra/georchestra#903]
J'ai remarqué lors de l’édition de mes couches GS que les emprises natives étaient mal sauvegardées :

Les valeurs Minimum/Maximum en X/Y sont tronquées au premier espace rencontré dans la valeur.

Par exemple si la valeur correcte est "1 749 024,875", lors de la sauvegarde, GS va garder "1" comme valeur.

Il me faut donc a chaque fois cliquer sur "Basées sur les données" pour recharger les emprises natives et supprimer les espaces : "1 749 024,875" devient "1749024,875".

**Comment by fvanderbiest** [comment]
Non constaté sur sdi.georchestra.org

![capture du 2015-02-05 11 27 07](https://cloud.githubusercontent.com/assets/265319/6058696/fbdb0750-ad29-11e4-98f8-07179564fa53.png)

Un pb de locales ?

**Comment by jusabatier** [comment]
Je vois que pour vous les espaces sont remplacés par des virgules...

**Comment by pmauduit** [comment]
Cela ressemble à des préférences régionales au niveau du navigateur (formattage des nombres, ...) probablement lié aux locales. Quel navigateur est utilisé ?

**Comment by jusabatier** [comment]
Google Chrome

**Comment by jusabatier** [comment]
Solution trouvée.

Le problème est situé dans le fichier WEB-INF/web.xml du war GS :

```xml
<!-- 
      THIS FILTER MUST BE THE FIRST ONE, otherwise we end up with ruined chars in the input from the GUI
      See the "Note" in the Tomcat character encoding guide:
      http://wiki.apache.org/tomcat/FAQ/CharacterEncoding
    -->
    <filter-mapping>
      <filter-name>Set Character Encoding</filter-name>
      <url-pattern>/*</url-pattern>
    </filter-mapping>
```

Ce <filter-mapping> doit être le premier de la liste comme stipulé dans le commentaire.

Ce bug a été signalé et corrigé depuis la version 2.4.2 de GS, ce qui est étrange c'est que le fichier georchestra/geoserver/geoserver-submodule/src/web/app/src/main/webapp/WEB-INF/web.xml est bien dans la bonne version mais il doit être remplacé par un autre lors de la compilation maven.

Cf. http://jira.codehaus.org/browse/GEOS-6083

**Comment by fvanderbiest** [comment]
Fixed with https://github.com/georchestra/geofence/issues/2 - closing

**Comment by fvanderbiest** [comment]
Thanks again @jusabatier for the testing and PR :-)
