### ISSUE TITLE
cas - default lang

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#914]
The default lang should be the one chosen via the ```shared.language``` maven filter.
By default, /cas/login has english strings.

http://jasig.github.io/cas/4.0.x/installation/User-Interface-Customization.html#localization indicates that a ```locale``` parameter can be added, eg for French:

https://sdi.georchestra.org/cas/login?locale=fr&service=https%3A%2F%2Fsdi.georchestra.org%3A443%2Fj_spring_cas_security_check

**Comment by pmauduit** [comment]
fix proposal on its way, but with a different behaviour as the one described. We can make use of the Accept-Language HTTP header instead of using the one in shared.language.

**Comment by fvanderbiest** [comment]
Indeed much better this way :-)
Thanks Pierre

**Comment by fvanderbiest** [comment]
Hmm, side effect : https://sdi.georchestra.org/cas/login?locale=nl when your browser prefered lang is fr shows "CAS est indisponible".

Maybe we should just remove the possibility to switch lang ...

**Comment by pmauduit** [comment]
You mean removing the language switch in the interface ?

**Comment by fvanderbiest** [comment]
Yes

**Comment by fvanderbiest** [comment]
Well in fact the file is overriden in the profile, so: https://github.com/georchestra/template/blob/14.06/cas-server-webapp/WEB-INF/view/jsp/default/ui/casLoginView.jsp

**Comment by fvanderbiest** [comment]
Fixed from 14.06 on with https://github.com/georchestra/template/commit/a7ece266bbe3619ad3af5e8076baa8b638ba5fc8

SDI admins will have to merge upstream changes from the template config (using the appropriate branch matching their geOrchestra version) to get these changes.
