### ISSUE TITLE
GeoServer - delegated admin on workspace fails

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#927]
GeoServer has the following rule in "data security":

```
wrk.*.a = ROLE_EL_TEST
```

Testing with a user which is a member of groups EL_TEST and SV_USER, there are two issues.

First, when this user goes to /geoserver/web/?wicket:bookmarkablePage=:org.geoserver.web.data.workspace.WorkspacePage a stack trace appears:

```
org.apache.wicket.WicketRuntimeException: Can't instantiate page using constructor public org.geoserver.web.data.workspace.WorkspacePage()
```

Expected: a list of workspaces for which this user has admin rights.

Also, this user should be able to add new stores inside the `wrk` workspace, but doing so results in an error. On page /geoserver/web/?wicket:bookmarkablePage=:org.geoserver.web.data.store.NewDataPage

```
org.apache.wicket.WicketRuntimeException: Can't instantiate page using constructor public org.geoserver.web.data.store.NewDataPage()
    at org.apache.wicket.session.DefaultPageFactory.createPage(DefaultPageFactory.java:212)
    at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:57)
```

**Comment by fvanderbiest** [comment]
Tested with geOrchestra GeoServer 2.3.2 and 2.5.4, exact same issues.

**Comment by fphg** [comment]
2.6.2 as well

**Comment by fvanderbiest** [comment]
> Also, this user should be able to add new stores inside the wrk workspace

This is not what is written in the official geoserver documentation: http://docs.geoserver.org/stable/en/user/security/layer.html#access-modes

**"Admin mode only refers to the configuration of the layer"**

**Comment by fvanderbiest** [comment]
> "Admin mode only refers to the configuration of the layer"

=> closing the issue (but GeoServer should hide admin pages that delegated admin should not have access to instead of displaying stacktraces)
