### ISSUE TITLE
mapfishapp - navigateur firefox 31.4: 

### ISSUE THREAD

**Issue by vbesand** [georchestra/georchestra#932]
Les tests ont été réalisés sur chrome (version 39) et sur firefox (version 31.4.0)
Le service: http://geobretagne.fr/geoserver/ddtm29/wms? ne délivre aucune donnée depuis le naviguateur firefox et ce à partir de geobretagne ou de sdi.
Par contre le service http://geobretagne.fr/geoserver/ddtm29/wms? est correctement ouvert depuis le navigateur chrome et ce à partir de sdi et de geobretagne
![firefox_serviceddtm29](https://cloud.githubusercontent.com/assets/8100983/6488663/3fd86856-c299-11e4-9d24-50254dc7da32.jpg)

**Comment by fvanderbiest** [comment]
Le document capabilities est incorrect
http://geobretagne.fr/geoserver/ddtm29/wms?service=wms&request=getcapabilities

```xml
<Layer queryable="1" opaque="0">
        <Name>doc_urba</Name>
        <Title>Documents d'urbanisme en téléchargement du Finistère</Title>
        <Abstract>Les documents d'urbanisme (PLU, POS, cartes communales) numérisés par la DDTM29 ou pour lesquels elle a eu l'autorisation de les publier ici sont proposés au téléchargement</Abstract>
        <KeywordList>
          <Keyword>features</Keyword>
          <Keyword>doc_urba</Keyword>
          <Keyword vocabulary="Inspire">Zones de gestion, de restriction ou de réglementation et unités de déclaration</Keyword>
          <Keyword vocabulary="ISO">Carte de référence de la couverture terrestre</Keyword>
        </KeywordList>
        <CRS>EPSG:2154</CRS>
        <CRS>CRS:84</CRS>
        <EX_GeographicBoundingBox>
          <westBoundLongitude>-5.170604730670202</westBoundLongitude>
          <eastBoundLongitude>-3.433565079578919</eastBoundLongitude>
          <southBoundLatitude><?xml version="1.0" encoding="UTF-8"?><ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ogc http://geobretagne.fr/geoserver/schemas/wms/1.3.0/exceptions_1_3_0.xsd">   <ServiceException>
      javax.xml.transform.TransformerException: java.lang.reflect.UndeclaredThrowableException
java.lang.reflect.UndeclaredThrowableException
</ServiceException></ServiceExceptionReport>
```

Du coup c'est plutôt un problème GeoServer !

**Comment by vbesand** [comment]
Bonjour François,
    
    Merci pour ton retour, il y avait bien une erreur dans une des
    couches du namespace ddtm29.
    Après avoir corrigé le fichier doc_urba, le problème était toujours
    là.
    J'ai donc procédé à la vérification de toutes les couches de ce
    namespace pour arriver à une couche qui n'avait plus de style !
    Il a été nécessaire de rentrer dans le layer.xml pour remettre un id
    correct pour le style.
    A présent cela fonctionne.
    
    Encore merci
    
    Le 05/03/2015 08:37, "> François Van
      Der Biest (par Internet, dépôt noreply@github.com)" a écrit :
    
    
      Le document capabilities est incorrect
        http://geobretagne.fr/geoserver/ddtm29/wms?service=wms&request=getcapabilities
      
        <Layer queryable="1" opaque="0">
        <Name>doc_urba</Name>
        <Title>Documents d'urbanisme en téléchargement du Finistère</Title>
        <Abstract>Les documents d'urbanisme (PLU, POS, cartes communales) numérisés par la DDTM29 ou pour lesquels elle a eu l'autorisation de les publier ici sont proposés au téléchargement</Abstract>
        <KeywordList>
          <Keyword>features</Keyword>
          <Keyword>doc_urba</Keyword>
          <Keyword vocabulary="Inspire">Zones de gestion, de restriction ou de réglementation et unités de déclaration</Keyword>
          <Keyword vocabulary="ISO">Carte de référence de la couverture terrestre</Keyword>
        </KeywordList>
        <CRS>EPSG:2154</CRS>
        <CRS>CRS:84</CRS>
        <EX_GeographicBoundingBox>
          <westBoundLongitude>-5.170604730670202</westBoundLongitude>
          <eastBoundLongitude>-3.433565079578919</eastBoundLongitude>
          <southBoundLatitude><?xml version="1.0" encoding="UTF-8"?><ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSch
ema-instance" xsi:schemaLocation="http://www.opengis.net/ogc http://geobretagne.fr/geoserver/schemas/wms/1.3.0/exceptions_1_3_0.xsd">   <ServiceException>
      javax.xml.transform.TransformerException: java.lang.reflect.UndeclaredThrowableException
java.lang.reflect.UndeclaredThrowableException
</ServiceException></ServiceExceptionReport>
      
      Du coup c'est plutôt un problème GeoServer !
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by fvanderbiest** [comment]
cool

**Comment by vbesand** [comment]
Par contre serait-il possible en cas de capacité incorecte sur mapfishapp d'avoir un message d'erreur?

**Comment by fvanderbiest** [comment]
Possible, c'est à étudier ...
