### ISSUE TITLE
GeoServer 2.5.4, WFS, POST request, authentification

### ISSUE THREAD

**Issue by lecault** [georchestra/georchestra#933]
When we do a POST request on WFS on a layer where his namespace contains protect layers, we have request error. It's a problem for the request tool on mapfishapp, edit a layer or our signalement application. Examples below. I don't know if it's linked with issue 912.
 ------------------------------------------------------------------------------------------------------
Il apparaît lorsque l'on fait une requête POST sur un flux WFS dans un namespace qui contient au moins une couche protégée : l'action n'est pas possible pour les autres couches aussi. Cela est problématique notamment pour le requêtage mapfishapp, l'édition ou notre application Signalement. Je ne sais pas si c'est lié à l'issue 912.
 
Exemple de requête POST sur GeoBretagne :
 
http://geobretagne.fr/geoserver/ign/wfs

```xml
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" service="WFS" version="1.1.0" outputFormat="json" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/WFS-transaction.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <wfs:Query typeName="ign:bdtopo_commune" srsName="EPSG:3857" xmlns:feature="http://geobretagne.fr/ns/ign">
        <PropertyName>code_insee</PropertyName>
        <PropertyName>nom</PropertyName>
        <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
            <ogc:Contains>
                <ogc:PropertyName>the_geom</ogc:PropertyName>
                <gml:MultiPoint srsName="http://www.opengis.net/gml/srs/epsg.xml#3857" xmlns:gml="http://www.opengis.net/gml">
                    <gml:pointMember>
                        <gml:Point>
                            <gml:coordinates decimal="." cs="," ts=" ">-323661.37514577,6162047.4713801</gml:coordinates>
                        </gml:Point>
                    </gml:pointMember>
                </gml:MultiPoint>
            </ogc:Contains>
        </ogc:Filter>
    </wfs:Query>
</wfs:GetFeature>
```

Exemple sur sdi :
 
sdi.georchestra.org/geoserver/geor/wfs

```xml
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" service="WFS" version="1.1.0" outputFormat="json" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/WFS-transaction.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <wfs:Query typeName="geor:menhir" srsName="EPSG:3857"></wfs:Query>
</wfs:GetFeature>
```

Alors que si on fait des requêtes équivalentes en mode GET aucun soucis.
http://geobretagne.fr/geoserver/ign/wfs?request=GetFeature&typename=ign:bdtopo_commune&count=3
http://sdi.georchestra.org/geoserver/geor/wfs?request=GetFeature&typename=geor:menhir&count=3

**Comment by lecault** [comment]
It's ok. We change the catalog mode of GeoServer to Cached (before it's mixed).

**Comment by fvanderbiest** [comment]
Thanks for the feedback on this one.
May we close it ?

**Comment by lecault** [comment]
Yep you could close it :-).Loïc ECAULTAdministrateur des bases de données géolocaliséesPôle Observatoire et Information géographique (POLOI)Service Connaissance, Observation, Prospective, Stratégies (SCOPS)Direction de l'aménagement et de la solidarité (DIRAM) - Région Bretagne Tél : 02 90 09 16 28www.geobretagne.fr -----François Van Der Biest <notifications@github.com> a écrit : ----- 
A : georchestra/georchestra <georchestra@noreply.github.com>De : François Van Der Biest <notifications@github.com>Date : 12/03/2015 17:18Cc: lecault <loic.ecault@region-bretagne.fr>Objet : Re: [georchestra] GeoServer 2.5.4, WFS, POST request, authentification (#933)Thanks for the feedback on this one.May we close it ?—Reply to this email directly or view it on GitHub.
