### ISSUE TITLE
geoserver 2.5.4 - settings of the WFS page do not persist

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#947]
After submitting the form with the "save" button, the same page is shown again, and values have not been saved to ```wfs.xml```

**Comment by fphg** [comment]
please retry and make sure all fields are filled

**Comment by fvanderbiest** [comment]
nope, does not work...

**Comment by fphg** [comment]
We had the same issue until spatial dataset identifier, metadata, keywords & vocabulary got filled

**Comment by fvanderbiest** [comment]
Correct !

Setting the spatial dataset identifier was enough on sdi.georchestra.org/geoserver:
```xml
<inspire_dls:SpatialDataSetIdentifier>
  <inspire_common:Code>georchestra</inspire_common:Code>
  <inspire_common:Namespace>http://www.georchestra.org/</inspire_common:Namespace>
</inspire_dls:SpatialDataSetIdentifier>
```

Thanks a lot Fabrice.
