### ISSUE TITLE
[Mapfishapp] Namespace : ask layer problem

### ISSUE THREAD

**Issue by jusabatier** [georchestra/georchestra#950]
When I ask a layer by clicking on features,

If the layer was loaded with namespace in the URL : geoserver/namespace/wms

I've two pans opened in the bottom of the window, One with the layer name which is empty and another one with the namespace:layer_name which contains the clicked entities.

If I load the layer without namespace (geoserver/wms), this bug is no more present.

**Comment by fvanderbiest** [comment]
The error happens when querying (getFeatureInfo) a layer server by /geoserver/ns/wms rather than /geoserver/wms.
The resulting features reference a layer whose name differs from the expected one by the namespace.

**Comment by jusabatier** [comment]
Found an alternative to filter layers by namespace with the "/geoserver/wms" url syntax : 

```
/geoserver/wms?namespace=<namespace>
```

By this way, we can load the layer and correct the double results tabs bug on asking layer.

**Comment by fvanderbiest** [comment]
This has been fixed from 16.12 on.
