### ISSUE TITLE
mapfishapp - load layers from GWC

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#954]
Currently, adding layers from a tiled service such as http://ids.pigma.org/geoserver/gwc/service/wms fails because mapfishapp queries the WMS with 532 x 532 px tiles, which do not conform to the grid it advertises.

Would be a nice improvement to add the ability to read and use the advertised tilesets.

**Comment by fphg** [comment]
sure, but imho FullWMS shall be activated on the GWC WMS interface. Tile aware clients use WMTS or TMS. WMS's good for dynamic SLD with limited TTL; http headers are sufficient.

**Comment by jusabatier** [comment]
It's not difficult to create a custom gridset with 532*532 px tiles.

But with good tiles size, I still get an error which seems to be related to Mapfish : 

https://groups.google.com/forum/#!topic/georchestra/9xaznNgHFwU

When I searched for a solution I found that it could be related with the mapfish tileorigin wich is not good.
