### ISSUE TITLE
proxy - BasicAuthChallengeByUserAgent config should target GeoFence and Extractorapp-specific user agents

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#960]
In https://github.com/georchestra/georchestra/blob/14.12/security-proxy/src/main/webapp/WEB-INF/applicationContext-security.xml#L57-L58 we require clients presenting the ``` .*Jakarta.*``` and ```.*Apache-HttpClient.*``` user agents to provide a basic auth.

This was made with GeoFence and Extractorapp in mind.
But it has several drawbacks, since these user agents are not specific enough.

Eg: when the French GeoCatalogue tries to harvest our CSW service, it uses a UA matching the above conditions, and thus requires a dedicated user belonging to the SV_USER group.

**Comment by pmauduit** [comment]
I propose `georchestra-internals v[georchestra-version]` for internal specific geOrchestra needs

**Comment by fvanderbiest** [comment]
True.

=> we need to patch Extractorapp and GeoFence to provide this specific user agent.

**Comment by pmauduit** [comment]
I wonder if there are no other case where a http client is used in geOrchestra

**Comment by fvanderbiest** [comment]
There is another use case which fails due to this issue.
Extracting layers originating from a remote geOrchestra SDI is broken too, since the remote SP will expect the extractorapp to provide credentials (which it does not do).

I'm raising the priority level.

**Comment by fvanderbiest** [comment]
As discussed on IRC today, this is getting really critical, even for simple features such as https://github.com/georchestra/georchestra/issues/1016 where XHRs to other geOrchestra instances are not successful.

**Comment by fvanderbiest** [comment]
As a result, target is now 15.12 / 16.02

**Comment by pmauduit** [comment]
> As discussed on IRC today, this is getting really critical, even for simple features such as #1016 where XHRs to other geOrchestra instances are not successful.

After digging, the User-Agent sent to the remote geOr instance in the case of #1016 is correct. We hit a 401 because of something else. But I can confirm that my browser U-A was correctly set when requesting the remote MD.

**Comment by fvanderbiest** [comment]
IMO, we cannot go on requiring preemptive basic auth for clients with user agents as generic as:
```
     <value>.*Jakarta.*</value> <!-- GeoFence UA for GeoServer REST -->
     <value>.*Apache-HttpClient.*</value> <!-- Extractorapp client -->
```

**Comment by Vampouille** [comment]
PR for datadir :
https://github.com/georchestra/datadir/pull/8

**Comment by Vampouille** [comment]
PR for georchestra
https://github.com/georchestra/georchestra/pull/1182

**Comment by Vampouille** [comment]
I push a new version here : bfa6f58bcf2283ed73132164cc3a5553c8d73c55

**Comment by fvanderbiest** [comment]
To my knowledge, the extractorapp UA was modified, (except for the WFS store query, which results in regression #1192) but not GoeFence's UA. To be double checked.
