### ISSUE TITLE
security-proxy - bad HTTP response in case of downstream "connection refused"

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#961]
The security-proxy currently returns a "200 - OK" status with a blank content in case of unavailable downstream tomcats.

I think a "502 - Bad gateway" or a "503 - Service unavailable" should be more relevant.

Step to "reproduce":

- Launch the proxycas tomcat
- shut down the georchestra tomcat
- attempt to connect onto `http[s]://host/mapfishapp/`

**Comment by fvanderbiest** [comment]
+1, this would maximize the benefit of having the ErrorDocument setup as per https://github.com/georchestra/georchestra/blob/14.12/doc/setup/apache.md#configuration 

These error documents are currently shown (only) when the tomcat-proxycas is unavailable.
