### ISSUE TITLE
mapfishapp - annotation addon - remove dependency to ext/examples

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#965]
This would allow us to exclude ext/doc and ext/examples from the resulting WARs
This would result in a size decreased by more than 50%.

```
app/addons/annotation/manifest.json:        "../../../lib/externals/ext/examples/ux/Spinner.js",
app/addons/annotation/manifest.json:        "../../../lib/externals/ext/examples/ux/SpinnerField.js"
```

**Comment by pmauduit** [comment]
it is no big deal to exclude files from the generated webapp: https://github.com/pmauduit/georchestra/commit/f7f7606a66304f77e74ce93a3295f052f862d79c

**Comment by fvanderbiest** [comment]
Done with https://github.com/georchestra/georchestra/commit/a86e947002a3a3201f6ee473b88049d5e5fdf2c9, see https://github.com/georchestra/georchestra/issues/966 for the rest ...
