### ISSUE TITLE
WARs : exclude useless ext/doc and ext/examples

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#966]
eg with https://github.com/pmauduit/georchestra/commit/f7f7606a66304f77e74ce93a3295f052f862d79c

**Comment by pmauduit** [comment]
This one also (on MFapp):
https://github.com/pmauduit/georchestra/commit/7aec8b274e5ce35a9931fd6d9fa87b8802714d09

**Comment by pmauduit** [comment]
Warning: same for extractorapp (downloadform seems to need `ext/examples/ux/css/MultiSelect.css`).

**Comment by fvanderbiest** [comment]
pmauduit: do you think it's safe to bump maven-war-plugin version from 2.1.1 to 2.6 for mapfishapp, as you did for extractorapp ?

**Comment by pmauduit** [comment]
Yes
