### ISSUE TITLE
geofence - basic auth should not be required for getfeatureinfo on public layers

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#973]
Using QGis with a public WMS layer from sdi.georchestra.org, a dialog box is shown asking for auth.

![capture du 2015-05-08 07 30 06](https://cloud.githubusercontent.com/assets/265319/7531059/2b47bf48-f554-11e4-9030-64c6ed1e5379.png)

In the apache logs, one can see that the UA is "Mozilla/5.0":
[08/May/2015:07:27:56 +0200] "GET /geoserver/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetFeatureInfo&BBOX=1.79414860307594348,42.81381185373032139,4.09432349263746431,44.31196497873032314&SRS=EPSG:4326&WIDTH=1173&HEIGHT=764&LAYERS=geor:menhir&STYLES=&FORMAT=image/png&QUERY_LAYERS=geor:menhir&INFO_FORMAT=application/vnd.ogc.gml/3.1.1&X=282&Y=479&FEATURE_COUNT=10 HTTP/1.1" 401 928 "-" "Mozilla/5.0"

**Comment by fvanderbiest** [comment]
This seems specific to using INFO_FORMAT=application/vnd.ogc.gml/3.1.1 because using INFO_FORMAT=text/html does not trigger basic auth => probably a geofence issue

**Comment by fvanderbiest** [comment]
Our current set of rules should not trigger this
![capture du 2015-05-08 07 44 54](https://cloud.githubusercontent.com/assets/265319/7531193/2920ddd8-f556-11e4-8bd4-1017c5b5b14d.png)

**Comment by pmauduit** [comment]
The problem with the basic-auth filter in the security-proxy is that it does not consider if the underlying resource needs to be protected or not: it sends a 401 irregardless of the user's privileges, even if the resource is public, eg:

```
curl -i https://sig.agglo-rennesmetropole.fr/header/
HTTP/1.1 200 OK
[...]

curl -i -H 'User-Agent: Apache-HttpClient' https://sig.agglo-rennesmetropole.fr/header/
HTTP/1.1 401 Unauthorized
```

**Comment by fvanderbiest** [comment]
> The problem with the basic-auth filter in the security-proxy is that it does not consider if the underlying resource needs to be protected or not: it sends a 401 irregardless of the user's privileges, even if the resource is public

True, but in the current case, I suspect geofence rather than our security proxy.
See why on https://github.com/georchestra/georchestra/issues/973#issuecomment-100107313

**Comment by fvanderbiest** [comment]
Witnessed with an older version of geofence.
Closing.
