### ISSUE TITLE
Error Clone Georchestra Eclipse

### ISSUE THREAD

**Issue by debard** [georchestra/georchestra#979]
Bonjour à tous,
je prend en main Georchestra depuis peu et dès la mise en place d'un clone Git dans Eclipse une erreur m'indique qu'un fichier n'est pas valide pour etre enregistrer sur le systeme de fichier windows.
En effet l'erreur indique que l'extension est invalide. nomfichier:name.html. Le separator ":" bloque la creation du clone. Avez vous une solution ou alors la compilation du code source  avec le système windows n'est pas compatible avec georchestra.

Error:
Invalid path (contains separator ':'): ldapadmin/src/main/webapp/privateui/lib/angular/docs/partials/api/ng.directive:a.html

thank

**Comment by fvanderbiest** [comment]
Bonjour,
geOrchestra est principalement compilé et déployé, donc testé, sur des plateformes linux.
A un moment, le système de build a dû fonctionner sous Windows, mais nous n'avons pas focalisé nos efforts sur le support de cet OS et donc il est possible que l'introduction de la webapp ldapadmin ait cassé ce support.
Avez vous la possibilité de réaliser le clone depuis une vm linux ?

Notez que nous focalisons nos efforts actuellement sur la production de WARs génériques, ne nécessitant donc pas de compilation. Nous espérons que ceci sera disponible pour la prochaine version.
