### ISSUE TITLE
mapfishapp: fullscreen addon

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#981]
See http://geofao.org.bo/mapfishapp/app/addons/fullscreen/manifest.json or (mirror) https://gist.github.com/fvanderbiest/b004818d8bd3f77cce02

Would be good to see it more widely deployed => review + integration in geOrchestra sources

**Comment by MaelREBOUX** [comment]
Would be great to add it to the 15.12 milestone.

**Comment by fvanderbiest** [comment]
IIRC CIGALsace is very interested by this one too for 15.12

**Comment by fvanderbiest** [comment]
Expected compatibility with IE >= 10

**Comment by fvanderbiest** [comment]
http://caniuse.com/#feat=fullscreen says the API is supported by IE >= 11
As a result, the addon will work in a degraded fashion with IE10: sidebars will be collapsed.

**Comment by fvanderbiest** [comment]
http://sdi.georchestra.org/mapfishapp/

Tiles are not always loading at the edges, when fullscreened ... I'm wondering if the map div has the correct size...

Please report other potential issues.

**Comment by fvanderbiest** [comment]
All done, with documentation: https://github.com/georchestra/georchestra/blob/15.06/mapfishapp/src/main/webapp/app/addons/fullscreen/README.md
