### ISSUE TITLE
[tomcat6 to tomcat7,8] mapfishprint & geonetwork compatibility

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#983]
`servlet.getRealPath()` in recent versions of tomcat returns null, see:

https://github.com/georchestra/geonetwork/blob/georchestra-14.12/web/src/main/java/org/fao/geonet/resources/ResourceFilter.java#L100

We need to find an appropriate way to determine where the webapp is actually deployed.

It has been tested by hardcoding the paths successfully, but the actual fix would need a little bit work.

**Comment by fvanderbiest** [comment]
See also https://github.com/georchestra/georchestra/issues/418

**Comment by fvanderbiest** [comment]
IIRC, @pmauduit, you fixed the mapfish print issue, right ?

**Comment by pmauduit** [comment]
Yes, it only needs a mfprint version bump, which has been addressed with https://github.com/georchestra/georchestra/commit/d419d99963705d3914a09c954d16ed8c406af913
