### ISSUE TITLE
mapfishapp: CSS issue in context dataview

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#988]
See screenshot:

![issue-mfapp](https://cloud.githubusercontent.com/assets/594335/7795764/24276024-02d8-11e5-8cad-4f0bbd870fbf.png)

**Comment by fvanderbiest** [comment]
ellipsing overflowing text

![capture du 2015-07-07 17 25 32](https://cloud.githubusercontent.com/assets/265319/8549820/31b62c2c-24cd-11e5-94be-f6a002ce7f85.png)
