### ISSUE TITLE
ldapadmin - SMTP servers refusing ICMP protocols makes the deploy fail

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#991]
this has been (sort of) reported on IRC, see:

https://github.com/georchestra/georchestra/blob/14.12/ldapadmin/src/main/java/org/georchestra/ldapadmin/mailservice/AbstractEmailFactory.java#L48

We should not throw an exception in this case, but leave a trace in the logs to tell that it could lead to issues when sending emails.

**Comment by pmauduit** [comment]
Lots of users encounter unexpected behaviour using the InetAddress.isReachable() call, I'm confident that we should avoid it (http://stackoverflow.com/questions/9922543/why-does-inetaddress-isreachable-return-false-when-i-can-ping-the-ip-address).

In addition, it can be a sysadmin's policy to drop / reject ICMP ping on their SMTP server.

**Comment by landryb** [comment]
In fact, anything but localhost probably doesnt work.....

**Comment by pmauduit** [comment]
Fixed with https://github.com/georchestra/georchestra/pull/1061
